### PR TITLE
Fix crop aligning for "Original image"

### LINKED ISSUE #19919: crop of version 5.2.1 changes to square crop after altering with 5.3.0
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

Trying to alter cropped parts of an image that was edited using version 5.2.1 leads to square crops when editing with version 5.3.0.

### Steps to reproduce

- in darkroom open an image that was edited with version 5.2.1 and that contains a rectangle crop, e.g. 3:2.

Image

- open the crop module
 
Image

- change the existing crop e.g. by shifting it, leaving the crop ratio untouched

Image

 
- close the crop module
- the image has now a square (1:1) crop ratio with the width of the original crop

Image

### Expected behavior

The shifted crop format should be 3:2 not 1:1

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

darktable-5.3.0+997.g09b8299fa6-win64

### What OS are you using?

Windows

### What is the version of your OS?

Win 10 Pro

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1060 6GB

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
We must avoid aligning if cropping to original image aspect as we would re-calculate width&height with wrong data thus resulting in square-sized crops. This problem was only evident
- with elder edits (likely before c0a8430e647a40f2325c2c6d8ec37b0b875f81b1)
- and using "original image" ratio

We now check for valid aligning calculations so making sure.

Fixes #19919

@TurboGit @pass712 would you check?

### CODE REVIEW

**Comment by TurboGit** [comment]
Doesn't work for me. When I load the XMP (I have edited it to disable the liquify module) the thumbnail is square:

image

When I go to darkroom it is square:

image

When I expand the crop tool, the crop ratio is now ok: 

image

And if I collapse the crop module all ok:

image

**Comment by pass712** [comment]
Will check soon

**Comment by pass712** [comment]
Doesn't work for me too. Same behaviour as described.

**Comment by TurboGit** [comment]
@jenshannoschwalm : My scenario (wrong crop in thumb after loading XMP) seems to indicate that some wrong parameters are recorded. So maybe we need to bump crop module version and fix this wrong params? So a change in `legacy_params()` instead (or also) of `commit_params()`. Now I have no idea how a wrong params could have been committed.

**Comment by jenshannoschwalm** [comment]
Does this mean, you only observe the quadratic effect for thumbs?

**Comment by pass712** [comment]
No, it concerns the export as well.

**Comment by TurboGit** [comment]
I have tested on 5.2.1 and I fear that the problem is quite more complex :(

When I load the XMP, the thumb is (not as with this PR):

Capture d’écran du 2025-12-16 18-05-36

When I go to darkroom I have (not as with this PR):

Capture d’écran du 2025-12-16 18-05-50

When I just expand and collapse crop module (nothing else) I get:

Capture d’écran du 2025-12-16 18-06-06

And as you can see the final result on darkroom is the same than on 5.3 (or with this PR) as reported above.

What to do with all that???? No idea at the moment...

Is that something that helps you @jenshannoschwalm ?

**Comment by TurboGit** [comment]
On thing sure, 5.2.1 is broken as much as 5.3.0 as just expanding/collapsing the crop module changes the crop area.

**Comment by jenshannoschwalm** [comment]
@TurboGit indeed a bad and somewhat complex mess.

"Fortunately" i can spot any described issue **only** with ratio as "original image" ending in a squared crop with current master. In the latest commit you will find a commented line reporting the aligners and this output if i load your sidecar.
```
   257,3214 crop aligners d=1 n=0
   257,3214 modified roi OUT              [thumbnail]      crop                   2900       (0/0)  3713x5575 sc=1,000 -->       (0/0)  2996x2996 sc=1,000; 
   257,3215 pipe starting             CPU [thumbnail]                                        (0/0)  1200x1200 sc=0,401; 'img_18.cr2' ID=358
 ```
showing that there were bad crop parameters written, that happened with late master when commiting the box with bad alignment.

I'm deeply sorry about this but i don't see a good way to fix this mess.

Some questions when using this PR:
1. Do you see any issue with expanding/collapsing (or anything else) with any other crop ratio preset? I do not.
2. Do you see any issue **after** changing the crop on a bad  "square original image edit" expanding/collapsing? I do not.

If 1+2 are both safe i would be possible to do a migration algo testing for "original image" and reset cropping accordingly. Not an easy one.

**Comment by TurboGit** [comment]
For 1: I cannot answer I do crop with image aspect ratio 99% of the time and otherwise square.
For 2: No I do not see issue after changing the crop aspect ratio and collapsing/expanding crop. But I see an issue if I only move the crop area.

**Comment by jenshannoschwalm** [comment]
@TurboGit i may have found a way to somewhat revert the original->quadratic problem by some hack, see the second commit and comments there.

Maybe have a talk about this mess tonight, would be fine at 9pm?

**Comment by TurboGit** [comment]
@jenshannoschwalm : I see, the hack is frightening so close of the release.

Ok to talk at 9pm. What is your timezone and DST (daylight saving time)? At the time I wrote this message is was 18:24 on my side.

**Comment by TurboGit** [comment]
I have tested this PR and the thumbs is like this:

image

It is not as in 5.2.1 and not as in current master. I'm not sure now which crop is correct.

When I enter darkroom I do have the same crop area (which is good).

When I expand/collapse the crop module I have the crop area changed, and back to lighttable the thumb corresponds to what I had in darkroom (which is good):

image

**Comment by TurboGit** [comment]
Reading the code the change in `modify_roi_out()` is frightening and I'm not sure this is good for the release. We really need to discuss that.

**Comment by jenshannoschwalm** [comment]
No it's not for release, it:'s the closest hack i could think of.

Its now 8 past 9 now, signal or elements?

**Comment by TurboGit** [comment]
Signal or Element. Whatever is easier for you.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Not sure you have my id on both. Maybe jitsi meet ?

Just click: https://meet.jit.si/dt

**Comment by TurboGit** [comment]
@jenshannoschwalm : The link to the archive: https://drive.google.com/file/d/1p1Bv5c-rMTVokVrIVPJIhN6PyxTJDEB7/view?usp=sharing

It also contains screen shot of the rendering of the thumbs in 5.2.1, in master and after edit (only expand/collapse crop).

My observations, I'm pretty sure the cx & cy are ok as the cropped area when loaded into darkroom (master) was correct. So the solution discussed should possibly save us here :)

Let me know if you need something else to help you.

**Comment by jenshannoschwalm** [comment]
Mmh, first try with fixes in `legacy_paramas` force-pushed. The old portrait example unfortunately has cx/cy at zero :-(

**Comment by TurboGit** [comment]
> The old portrait example unfortunately has cx/cy at zero :-(

How is that possible? I mean when I open the picture on 5.2.1 my crop area is properly kept and the top/left corner is on the right position and not on 0x0. Given that, my expectation what that only the width/height were somehow broken otherwise it would not be possible for the crop to work at all. So I'm lost now.

**Comment by TurboGit** [comment]
This is what I have on 5.2.1 when hovering on crop in history:

crop-data-5 2 1

No zero there.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Maybe you're looking at the master .xmp? The ones in the `xmp-5.2.1` directory don't have zero and those are the ones to migrate properly.

**Comment by TurboGit** [comment]
@jenshannoschwalm : What about this which seems to be working on the 2 samples I sent:

```
  else if(old_version == 2)
  {
    const dt_iop_crop_params_t *o = (dt_iop_crop_params_t *)old_params;
    dt_iop_crop_params_t *n = malloc(sizeof(dt_iop_crop_params_t));
    memcpy(n, o, sizeof(dt_iop_crop_params_t));

    // Let's check for bad square crops because of bad edits with original image ratio
    if(abs(n->ratio_d) == 1 && n->ratio_n == 0)
    {
      // It seems that cw is always good on the legacy parameters
      // Since we have a original aspect ratio, we want the crop
      // width and height to be identical in percent. That is, we
      // keep the aspect ratio.
      n->ch = n->cw;
    }

    *new_params = n;
    *new_params_size = sizeof(dt_iop_crop_params_t);
    *new_version = 3;
    return 0;
  }
```

**Comment by jenshannoschwalm** [comment]
That for sure breaks fresh edits from master. It seems to be fine for 5.2.1 edits...

**Comment by TurboGit** [comment]
But maybe we cannot do better for master edit. Users using master are prepared for that. 

@jenshannoschwalm : Or do you have an idea to fix master edit?

**Comment by jenshannoschwalm** [comment]
Some comments
1. @TurboGit suggested above simple code; the relative width/height of the selected crop area for me is not defined via the cw/ch parameters but by the difference (cw-cx) / (ch-cy) - no? (Or am i just confused right now? See modify_roi_out(). Would we want to rename ch/cw as we did for rawprepare a while ago?)
2. After committing the last version (some additional checks) and testing with various master crop-edits checks it became clear to me, we have also non-square but still wrongly sized areas with current master so we have to test for crop-area-ratio matches sensor-ratio.
3. I still couldn't find any 5.2.1 edit that has the cropping area not matching the sensor ratio which seems to be good.
4. Also i couldn't yet find any edits with current master that don't match.
5. Current correcting version 2 tests for "crop-area-ratio matches sensor-ratio" if if bad does the "correcting code".

Pascal, the corrections for "original-5.2-but-master-edits" seem to be mostly good, i didn't fully test portraits and landscapes with the "original image" crop ratio toggled - so a portrait becomes a landscape.

**Comment by TurboGit** [comment]
> 1. @TurboGit suggested above simple code; the relative width/height of the selected crop area for me is not defined via the cw/ch parameters but by the difference (cw-cx) / (ch-cy) - no? (Or am i just confused right now? See modify_roi_out(). Would we want to rename ch/cw as we did for rawprepare a while ago?)

I think you're confused. The cw and ch are **width** and **height** in percent of the original image size. In `modify_roi_out()` you want the margin top/left/bottom/right (odx is the margin on the right, no?) I think. Or am I the one to be confused :) ?

**Comment by pass712** [comment]
Hi @TurboGit and @jenshannoschwalm ,

there are issues too with an image that was cropped **freehand** under 5.2.1. It also converts to a 1:1 crop under 5.3.0 by only opening and closing the crop module. Hope you also solve this with your solution. 

If you need the DNG and XMP please let me know.

1. Opened image in darkroom

capture_001_18122025_171211_crop




2. Opened the crop module (the shown crop rectangle is correct)

capture_002_18122025_171225_crop




3. closed the crop module -> square crop

capture_003_18122025_171234_crop






4. Will export with 2999 : 3000

capture_004_18122025_171301_crop

**Comment by TurboGit** [comment]
@jenshannoschwalm : So at this stage what do you think? Is my simple patch ok for 5.4 and we tell that any edit with master will be possibly broken? Or do you see a possible way to avoid this?

**Comment by TurboGit** [comment]
> there are issues too with an image that was cropped **freehand** under 5.2.1.

So we are doomed :(

EDIT: And for freehand crop we don't have a way to recover since we know nothing about aspect ratio.

**Comment by jenshannoschwalm** [comment]
The roi_out->width/height are not margins but in fact width&height.

**Comment by jenshannoschwalm** [comment]
> If you need the DNG and XMP please let me know.

Yes please.

**Comment by pass712** [comment]
Here you go.... https://magentacloud.de/s/KsBcJLGm5tbqroX

**Comment by TurboGit** [comment]
> The roi_out->width/height are not margins but in fact width&height.

So I don't see how this works... black magic?

In fact no, some computation are just temporary, in order we have:

```
  float odx = (float)roi_in->width * (d->cw - d->cx);
...
  roi_out->width = MAX(4, (int)odx);
...
  odx = floorf(odx);
...
  float width = odx;
  // so lets possibly enforce the ratio using the larger side as reference
  if(keep_aspect)
  {
    if(odx > ody) height = floorf(landscape ? odx / aspect : odx * aspect);
    else          width  = floorf(landscape ? ody * aspect : ody / aspect);
  }

  int align_w = roi_out->width >= roi_out->height ? d->ratio_d : d->ratio_n;
  const gboolean exact = _reduce_aligners(&align_w, &align_h);
  const int dw = exact ? (roi_out->width  % align_w) : 0;
...
  roi_out->width = MAX(4, roi_out->width - dw);

```

So at the end `roi_out->width` do not use `odx` at all.

The width/height above are only for printing on screen.

**Comment by jenshannoschwalm** [comment]
> > The roi_out->width/height are not margins but in fact width&height.
> 
> So I don't see how this works... black magic?
> 
> In fact no, some computation are just temporary, in order we have:
> 
> ```
>   float odx = (float)roi_in->width * (d->cw - d->cx);
> ...
>   roi_out->width = MAX(4, (int)odx);
> ...
>   odx = floorf(odx);
> ...
>   float width = odx;
>   // so lets possibly enforce the ratio using the larger side as reference
>   if(keep_aspect)
>   {
>     if(odx > ody) height = floorf(landscape ? odx / aspect : odx * aspect);
>     else          width  = floorf(landscape ? ody * aspect : ody / aspect);
>   }
> 
>   int align_w = roi_out->width >= roi_out->height ? d->ratio_d : d->ratio_n;
>   const gboolean exact = _reduce_aligners(&align_w, &align_h);
>   const int dw = exact ? (roi_out->width  % align_w) : 0;
> ...
>   roi_out->width = MAX(4, roi_out->width - dw);
> ```
> 
> So at the end `roi_out->width` do not use `odx` at all.
> 
> The width/height above are only for printing on screen.

oops, i think you missed
```  roi_out->x = MAX(0, (int)px);
  roi_out->y = MAX(0, (int)py);
  roi_out->width = MAX(4, (int)odx);
  roi_out->height = MAX(4, (int)ody);

  const gboolean exporting = piece->pipe->type & (DT_DEV_PIXELPIPE_EXPORT | DT_DEV_PIXELPIPE_THUMBNAIL);
  const gboolean aligned = d->ratio_d != 0 && d->ratio_n != 0;
  if(!exporting || !aligned) return;
```
the the early return here. The code after this is indeed only pixel exact width and height correction to match exactly a 3:2 ratio or whatever you chose to use.

**Comment by TurboGit** [comment]
> oops, i think you missed

Indeed missed that, I'll refrain from saying stupid things then :)

**Comment by jenshannoschwalm** [comment]
> Here you go

Thanks. Indeed, it's the same underlying issue - the bad master code inserted the aligning flag which "badly corrected" to the square and we didn't see in that bad code. After switching to freestyle there is absolutely no chance to "repair"

**Comment by jenshannoschwalm** [comment]
@TurboGit another short discussion right now?

**Comment by TurboGit** [comment]
Yes, I call.

**Comment by jenshannoschwalm** [comment]
1. squashed all to be in one commit
2. added some logs for -d params if things are ok
3. log-always all *repair* activity
4. some formatting for less reading errors
5. it's close to impossible to construct all or severe bad crop history steps but from my tests chances are not so bad to get something close or even exact.

For all testers:
1. Any reports about similar issues with crop mode other than related to use of "original image" in 5.2.1 and later edited in master would be highly appreciated (although leading to instant depression). Please provide raw and xmp ...
2. You could test without any debug flags as "repairing" will always be logged always.
3. Please remember, if you test you should test landscape and portrait images with "original image" and "flipped original image".

**Comment by TurboGit** [comment]
@jenshannoschwalm : Congrats and thanks for the hard work! I have tested this with many images. The 2 I sent, they are rendered ok with the XMP from 5.2.1 and master. I have also tested with more than 50 images from my collections some edited on 5.2 some before and some with master. All of them have a correct crop and editing the crop works as expected.

This is wonderful and well above my expectation. Seems like we have recovered from this issue. Thanks a lot!

I'll merge that in some hours if we don't have more issue reported as I think with this we can release.

**Comment by pass712** [comment]
Thanks @jenshannoschwalm and @TurboGit for your persistence in finding this nasty bug and your late night work! I keep my fingers crossed all works well and will give it an intense test.

**Comment by jenshannoschwalm** [comment]
@TurboGit
Just an information - latest force-pushed code did **not** change any code, just some commit message improves.

Are you sure we don't want any (even untranslated) control log message in the "repair" section? like "problematic crop module setting, please check"

**Comment by TurboGit** [comment]
@jenshannoschwalm : No because if the crawler (auto thumb updater) is ON the user will potentially get lot of messages.

File: src/iop/crop.c [hunk 1]
```diff
@@ -176,28 +174,118 @@ int legacy_params(dt_iop_module_t *self,
...
+    const dt_iop_crop_params_v2_t *o = (dt_iop_crop_params_v2_t *)old_params;
+    dt_iop_crop_params_t *n = malloc(sizeof(dt_iop_crop_params_t));
+    memcpy(n, o, sizeof(dt_iop_crop_params_t));
+
+    // Let's check for bad square crops because of bad edits with original image ratio
+    if(abs(n->ratio_d) == 1 && n->ratio_n == 0)
+    {
+      const float pwd = self->dev->image_storage.p_width;
+      const float pht = self->dev->image_storage.p_height;
+      const gboolean safe = pwd > 4.0f && pht > 4.0f;
```
Comment (zisoft) [inline src/iop/crop.c:222]: This line fires a GitGuardian incident "Generic Password".
Of couse a false positive due to the variable name `pwd`...

**Comment by pass712** [comment]
Checked 5.5.0 nightly today with a bunch of older edits including files with different orientation and rotated ones. All works fine. Great work @jenshannoschwalm and @TurboGit!  Many thanks again.
