### PR TITLE
datetime fix: long int is not gint64 equivalent on windows (WIN32)

### LINKED ISSUE #11582: Collections with times or dates not working?
Trying the new way to select a couple of dates. Date taken does not show any photos. Not any interval as I can see.
I would prefer Time category to work the same way as folders but with the added possibility to select a group of folder either with ctrl click or shift click as normal in most applications.

filter_module

Platform
darktable version : 3.9.0+1244~gfe1008608-dirty
OS : Win10 19042.1288
Memory : 32 GB
Graphics card : Gigabyte GeForce RTX 2070 SUPER OC 3X
Graphics driver : 30.0.14.9613
OpenCL installed : yes
OpenCL activated : yes

### PR DESCRIPTION
**Pull request by phweyland**
attempt to fix #11582

Not tested on windows

### CODE REVIEW

File: src/common/collection.c [hunk 1]
```diff
@@ -1830,14 +1830,14 @@ static gchar *get_query_string(const dt_collection_properties_t property, const
       if(strcmp(operator, "[]") == 0)
       {
         if(number1 && number2)
-          query = g_strdup_printf("((%s >= %ld) AND (%s <= %ld))", colname, (long int)nb1, colname, (long int)nb2);
+          query = g_strdup_printf("((%s >= %ld) AND (%s <= %ld))", colname, (GTimeSpan)nb1, colname, (GTimeSpan)nb2);
```
Comment (AlicVB) [inline src/common/collection.c:1833]: not sure it's needed to cast `nb1` and `nb2` as they are already defined as GTimeSpan
(same above)

Comment (phweyland) [reply src/common/collection.c:1833]: That seems logic ! :)
I do it.

File: src/common/collection.c [hunk 2]
```diff
@@ -1830,14 +1830,14 @@ static gchar *get_query_string(const dt_collection_properties_t property, const
       if(strcmp(operator, "[]") == 0)
       {
         if(number1 && number2)
-          query = g_strdup_printf("((%s >= %ld) AND (%s <= %ld))", colname, (long int)nb1, colname, (long int)nb2);
```
Comment (parafin) [inline src/common/collection.c:1833]: You have to change the format too, %ld is wrong. I think you have to use G_GUINT64_FORMAT

Comment (parafin) [reply src/common/collection.c:1833]: Or rather G_GINT64_FORMAT

Comment (kmilos) [reply src/common/collection.c:1833]: Or, as alternative to GLib types and macros, use inttypes.h standard/portable width integer types and macros.

Comment (parafin) [reply src/common/collection.c:1833]: I would agree, but we already stuck with glib, since nb1 type is GTimeSpan, which is defined as gint64: https://developer-old.gnome.org/glib/stable/glib-GDateTime.html#GTimeSpan

So it's better to match formatting macros to the actual type, even if it's all the same underneath.

Comment (phweyland) [reply src/common/collection.c:1833]: I had a doubt about %ld indeed. Thanks for your suggestions. Done.

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!
