### PR TITLE
darktable: Call dt_iop_set_darktable_iop_table when iop list is set.

### LINKED ISSUE #18093: Collections module : searching for a specific module not working any more
### Describe the bug

See title

### Steps to reproduce

- Goto _collections_ module
- Select _darktable - module_
- no module shown for selection

collections-module-bug

### Expected behavior

show list of modules to select from

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

5.1.0+9~g71233fe6c4

### What OS are you using?

Linux

### What is the version of your OS?

Ubunt 24.04

### Describe your system?

OS : Linux 6.8.0-51-generic / Ubuntu 24.04.1 LTS
Memory : MemTotal:       65759320 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 550.120
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu3
Desktop : LXQt
GTK+ : 3.24.41
Glib : ldd (Ubuntu GLIBC 2.39-0ubuntu8.3) 2.39
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
CMAKE_BUILD_TYPE : release

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by TurboGit**
This is important as the list of all iop must be known to populate the memory.darktable_iop_names table for the 'module' collection filter.

Add assert to catch this case and comments to avoid another regression when reordering the darktable start routines.

Fixes #18093.

### CODE REVIEW

File: src/common/darktable.c [hunk 1]
```diff
@@ -1799,6 +1796,10 @@ int dt_init(int argc, char *argv[], const gboolean init_gui, const gboolean load
     return 1;
   }
 
+  // set up memory.darktable_iop_names table
+  // must happen after dt_iop_load_modules_so() above
+  dt_iop_set_darktable_iop_table();
```
Comment (dterrahe) [inline src/common/darktable.c:1801]: Why not just move this inside `dt_iop_load_modules_so` then (and make it a local function to `imageop.c`)?
