### PR TITLE
fix several minor issues with dialog boxes

### LINKED ISSUE #14787: Activate the 'save' button with 'enter' key in src/libs/tagging.c
In Darktable GTK on Linux, some pop up windows like the 'edit tag' window do not activate the 'Yes/OK/Save' button by default. As a consequence, it is not possible to use the 'enter / return' key to activate/press the button and the mouse must be used to click on it.

A very simple solution would be to activate the default 'confirm/OK/save' button.

src/libs/tagging.c
 _pop_menu_dictionary_edit_tag(GtkWidget *menuitem, dt_lib_module_t *self)
[...]

  // Set 'Enter' key to activate the default button and make 'OK' button the default button
  gtk_dialog_set_activatable(dialog, TRUE);
  GtkWidget *ok_button = gtk_dialog_get_widget_for_response(dialog, Gtk.ResponseType.OK);
  gtk_button_set_can_default(ok_button, TRUE);
  gtk_button_grab_default(ok_button);

When editing lots of tags, it saves precious time.
What do you think ?

### PR DESCRIPTION
**Pull request by dterrahe**
closes #14787

This adds `gtk_dialog_set_default_response` to a few dialog boxes (and fixes it for presets where it no longer linked to the correct code after changes were made there). Some dialogs were already using a key handler to active the response on Enter/KP_Enter, but this would not give a hint to gtk which button should be marked as the default. (It also makes it less clear which button got pressed because the dialog closes immediately rather than with a small delay during which the button lights up).

@Nilvus as discussed in #14787, could you have a look at the CSS to style `.default` buttons distinctively? While you are looking; I'm noticing some strange behavior in the tagging module; when I right click on a tag and select "edit..." the dialog comes up looking normal. When I then press Del (which deletes the whole tag name and therefore disables the "save" button, that button moves down a little bit, leaving two superimposed buttons. Probably a gtk bug but maybe workaroundable in CSS?

Actually, that disabling the "save" button when the name is empty is new in this PR and also added for styles.

The presets and modulegroups edit dialog boxes are made wider if their title is long. Normally gtk ellipsizes a windows title and there's no way (as far as I know) to make the window scale with its title. This change is instead resizing the Entry _within_ the window, but of course that won't work perfectly if the fonts sizes are different.

The export metadata dialogs can now be resized and this will correctly resize the treeviews within them.

When the add to library/import dialog opened, I got a lot of "GFileInfo created without standard::is-hidden" messages on the command line. I believe this is now fixed. I have not tested if hidden files are now correctly filtered out (or whether the comment in the source that "g_file_info_get_is_hidden() always returns 0 on macOS" was possibly related to this).

In the metadata_view ("image information") preferences dialog the second column ("visible") is now focused. This has the advantage that you can use the up/down arrow keys to go to a different row and then press the space bar to toggle the option. Previously you had to know that you had to press the _right_ arrow key first too. Same in metadata.

EDIT: until @Nilvus provides updated CSS you might temporarily test with something silly like
```
.default
{
  background-color: transparent;
}
```
to be able to distinguish the default button in dialogs.

### CODE REVIEW

**Comment by dterrahe** [comment]
Didn't realise @TurboGit already fixed the import log spamming bug; removed during rebase.

**Comment by Nilvus** [comment]
> When I then press Del (which deletes the whole tag name and therefore disables the "save" button, that button moves down a little bit, leaving two superimposed buttons. Probably a gtk bug but maybe workaroundable in CSS?

I can't reproduce that on my side. The button doesn't move. As it could indeed be a Gtk bug, I use Debian Sid with Gtk 3.24.38

About default CSS, I see on many apps that what is used is same color as selected items, for example print box on Firefox:
image

We could find that way on many other apps.

So for darktable to match usual behavior, we should use same color as selected items on treeview for example. I test and it's not obvious that this is the default button.

That means that if we want to have a more usual behavior, we need to update actual colors for buttons. Is that worth the case though?

For that PR and waiting to see if it could be good to make a more important move on that part, I propose that CSS:

```
diff --git a/data/themes/darktable-elegant-dark.css b/data/themes/darktable-elegant-dark.css
index 8635809674..134640851f 100644
--- a/data/themes/darktable-elegant-dark.css
+++ b/data/themes/darktable-elegant-dark.css
@@ -50,6 +50,8 @@
 @define-color button_bg @grey_40;
 @define-color button_hover_bg @grey_65;
 @define-color button_hover_fg @grey_25;
+@define-color button_selected_bg @grey_55;
+@define-color button_selected_fg @grey_90;
 
 /* text fields */
 @define-color field_bg @grey_30;
diff --git a/data/themes/darktable-elegant-grey.css b/data/themes/darktable-elegant-grey.css
index 9ab463f027..356c42f45a 100644
--- a/data/themes/darktable-elegant-grey.css
+++ b/data/themes/darktable-elegant-grey.css
@@ -54,6 +54,8 @@
 @define-color button_bg @grey_55;
 @define-color button_hover_bg @grey_70;
 @define-color button_hover_fg @grey_30;
+@define-color button_selected_bg @grey_65;
+@define-color button_selected_fg @grey_95;
 
 /* text fields */
 @define-color field_bg @grey_45;
diff --git a/data/themes/darktable.css b/data/themes/darktable.css
index f175edb44d..185fdad688 100644
--- a/data/themes/darktable.css
+++ b/data/themes/darktable.css
@@ -156,6 +156,8 @@ Why that? Just because it's a developer choice and most classes use underscore i
 @define-color button_border shade(@button_bg, 1.04);
 @define-color button_hover_bg @grey_50;
 @define-color button_hover_fg @grey_15;
+@define-color button_selected_bg @grey_45;
+@define-color button_selected_fg @grey_90;
 
 /* text fields */
 @define-color field_bg @grey_15;
@@ -1668,6 +1670,13 @@ progressbar progress
   - Pseudo-classes : need to be defined last to not be overwritten -
   ------------------------------------------------------------------*/
 /*** All states options are designed below, active, hover, selected, disabled and check states ***/
+/* Default selected button for dialog boxes */
+.default
+{
+  color: @button_selected_fg;
+  background-color: @button_selected_bg;
+}
+
 /* Main states */
 .dt_history_items:active,
 .dt_history_items:checked,
```

**Review by Nilvus — APPROVED** [review]

**Comment by TurboGit** [comment]
@Nilvus : Should I merge now and the CSS part will be done on another PR?

**Comment by Nilvus** [comment]
I didn't tought to do a PR (that's why I put the diff). And is the result ok?

**Comment by dterrahe** [comment]
I can merge it into this PR if that's what you want?

**Comment by TurboGit** [comment]
> I can merge it into this PR if that's what you want?

Given @Nilvus, yes please :)

**Comment by dterrahe** [comment]
@Nilvus just one doubt:
there is a line
`messagedialog .default,  /* this show that a button in confirmation action pop-up has the focus (no by default) */`
that  gives "messagedialogs" slightly different colours than the dialogs in this PR.

Do you want to keep it that way or align them? (i.e. just remove that line so they all use the `.default` colours you specified above?

**Comment by Nilvus** [comment]
Good catch the line messagedialog, I missed that one. So my CSS code was a bad one.

Just use that for all dialog. Better to move .default at first and this would need to slightly change button background color on grey theme to improve contrast between both state.

So this would need to revert your last commit with my CSS and replace it by that diff:

```
diff --git a/data/themes/darktable-elegant-grey.css b/data/themes/darktable-elegant-grey.css
index 9ab463f027..fd782494f2 100644
--- a/data/themes/darktable-elegant-grey.css
+++ b/data/themes/darktable-elegant-grey.css
@@ -51,7 +51,7 @@
 @define-color bauhaus_fg_insensitive alpha(@bauhaus_fg, 0.5);
 
 /* GTK Buttons and tabs */
-@define-color button_bg @grey_55;
+@define-color button_bg shade(@grey_55,0.95);
 @define-color button_hover_bg @grey_70;
 @define-color button_hover_fg @grey_30;
 
diff --git a/data/themes/darktable.css b/data/themes/darktable.css
index f175edb44d..8c7e306449 100644
--- a/data/themes/darktable.css
+++ b/data/themes/darktable.css
@@ -1669,6 +1669,7 @@ progressbar progress
   ------------------------------------------------------------------*/
 /*** All states options are designed below, active, hover, selected, disabled and check states ***/
 /* Main states */
+.default,
 .dt_history_items:active,
 .dt_history_items:checked,
 button:active,
@@ -1682,7 +1683,6 @@ entry:checked,
 filechooser *:selected,
 menuitem:active,
 menuitem:selected,
-messagedialog .default,  /* this show that a button in confirmation action pop-up has the focus (no by default) */
 treeview *:selected:not(check),
 treeview *:checked:not(check),
 #main-histogram .dt_module_btn:checked:not(.rgb_toggle)
```

Shorter code and better result. Sorry for my mistake and thanks for your work.

**Comment by dterrahe** [comment]
Done. Thanks!

File: src/libs/export_metadata.c [hunk 1]
```diff
@@ -104,27 +104,9 @@ static void _add_selected_metadata(GtkTreeView *view, dt_lib_export_metadata_t *
 }
 
 // choice of a metadata tag
-static gboolean _click_on_metadata_list(GtkWidget *view, GdkEventButton *event, dt_lib_export_metadata_t *d)
+static void _metadata_activated(GtkTreeView *tree_view, GtkTreePath *path, GtkTreeViewColumn *column, dt_lib_export_metadata_t *d)
```
Comment (TurboGit) [inline src/libs/export_metadata.c:107]: please let's try to convert when possible to one parameter per line.

**Comment by dterrahe** [comment]
Add mnemonics to dialog buttons.

**Comment by dterrahe** [comment]
Release note:
- Added mnemonics to dialog box buttons and marked default buttons so pressing Enter will trigger them and close the dialog.

**Review by TurboGit — APPROVED** [review]
Thanks!
