### PR TITLE
colorbalancergb gamut mapping : better fix for #9095

### LINKED ISSUE #9095: color balance rgb gamut clipping
Hi

I am not sure if this is a bug, or if I am just too stupid to get my head around the color science. For some learning exercise I've loaded some artificial test images and played with the color balance rgb module.
According to the manual:

> At its output, color balance RGB checks that the graded colors fit inside the pipeline RGB color space (Rec 2020 by default) and applies a soft chroma clipping at constant luminance and hue. This prevents the out-of-gamut colors that can quickly be produced when increasing chroma and saturation.

But to me, the color changes are rather surprising. @aurelienpierre I hope you don't mind to elaborate what's happening and whether this is the intended behaviour.

I've downloaded one of the graphs from https://eng.aurelienpierre.com/2021/04/the-srgb-book-of-color/ and pushed chroma respectively saturation (beyond reason, I know). 
What surprises me, is that blue (hue 243) turns cyan (hue 185) before it eventually turns black when pushing chroma. Isn't that contrary to what's written in the manual?
Pushing saturation skips the cyan conversion and just goes black.

Activating filmic with default settings mitigates the cyan issue, since everything high luminance is desaturrated.

I am not sure if my approach was doomed from the start due to testing with a png, but I can also reproduce with a tif file.

EDIT: There are actually two things I am wondering:
1. Why is there a hue shift to cyan? This doesn't botter me really, since it seems to not happen when filmic is switched on
2. Shouldn't increased chroma clipping result in white instead of black? Looking at the 2nd image, right corner, this would avoid the harsh transition.

darktable 3.5.0 98ba99f784736c7c261e5f28209e33588142db48 (recent master)
Linux, OpenCL active - but can reproduce without.

 **Screenshots** 
chroma pushed - filmic off
ColorBalanceRGB-ChromaClipping-filmic-off
chroma pushed - filmic on
ColorBalanceRGB-ChromaClipping-filmic-on
saturation pushed - filmic off (filmic on does not change the clipping)
ColorBalanceRGB-SaturationClipping

**Test Images**
[test-images.zip](https://github.com/darktable-org/darktable/files/6563763/test-images.zip)

### PR DESCRIPTION
**Pull request by aurelienpierre**
Fix #9095 

Before this, with global chroma = +100% :
sRGB-primary-blue-continuous_03

After this patch:
sRGB-primary-blue-continuous_01

Before this, with saturation = +50% :
sRGB-primary-blue-continuous_04

After this patch:
sRGB-primary-blue-continuous_02

I have also changed the way the gamut LUT is used : previously, it used a nearest neighbour approach, now it does a linear interpolation, leading to better smoothness for quickly varying hues.

Notice the hue shift toward red in the yellow section. It shouldn't be there. I'm still trying to figure out where it comes from.

### CODE REVIEW

**Comment by TurboGit** [comment]
Despite the red shift I suppose this is good to go? The code looks sane. The math is yours and I trust it to be correct.

**Comment by aurelienpierre** [comment]
@TurboGit That part is good to go, yes. There is still something going on with the red shift, but I spent the past 2 days trying to figure it out, with no luck so far, so no reason to wait for it.

**Comment by johnny-bit** [comment]
the error caught by CI on windows debug build is:

```
src/iop/colorbalancergb.c:714: undefined reference to `lookup_gamut'
```

see https://github.com/darktable-org/darktable/pull/9227/checks?check_run_id=2810278966#step:5:908

**Comment by aurelienpierre** [comment]
> the error caught by CI on windows debug build is:

WTF ? How can all the other builds pass while this one fails ? The symbol is definitely there.

**Comment by johnny-bit** [comment]
> How can all the other builds pass while this one fails

That's why we have the CI, no? :P

static function helped :)

**Comment by flannelhead** [comment]
@aurelienpierre I debugged the red shift issue briefly – it would seem to me that the S' of the L'M'S' space gets a negative value [here](https://github.com/darktable-org/darktable/blob/b3a4335e57b1cab86375f8c8fe65113148a19c04/src/common/colorspaces_inline_conversions.h#L899) and is then clamped to zero -> red area. Something to take in account in the gamut mapping in JzAzBz before going back to XYZ?

**Comment by aurelienpierre** [comment]
@flannelhead thanks a lot ! So the good news, then, is that the color spaces transform are right, which was my concern. I will think about something.

**Comment by aurelienpierre** [comment]
With latest commit, saturation +50% :
sRGB-primary-blue-continuous_05
This fixes the negatives L'M'S'. There is still a hint of red, which probably comes from a wrong gamut LUT (the one computed from the working RGB space).

**Comment by aurelienpierre** [comment]
Bingo, I just found the remaining bastard !
sRGB-primary-blue-continuous_06

File: src/iop/colorbalancergb.c [hunk 1]
```diff
@@ -41,8 +41,8 @@
 
 //#include <gtk/gtk.h>
 #include <stdlib.h>
-#define LUT_ELEM 360 // gamut LUT number of elements: resolution of 1°
-#define STEPS 72     // so we test 72×72×72 combinations of RGB in [0; 1] to build the gamut LUT
+#define LUT_ELEM 360     // gamut LUT number of elements: resolution of 1°
+#define STEPS 92         // so we test 72×72×72 combinations of RGB in [0; 1] to build the gamut LUT
```
Comment (johnny-bit) [inline src/iop/colorbalancergb.c:45]: pedantic comment - wouldn't that make the test 92x92x92 instead of mentioned in comment 72x72x72?

Comment (aurelienpierre) [reply src/iop/colorbalancergb.c:45]: yeah, right.

**Comment by aurelienpierre** [comment]
@TurboGit this is now complete and all issues have been fixed. On a larger picture, it could be relevant to turn the gradients from https://eng.aurelienpierre.com/2021/04/the-srgb-book-of-color/ into a test bench, these have proven useful here and might be in many other places too.

File: src/iop/colorbalancergb.c [hunk 2]
```diff
@@ -1097,14 +1097,27 @@ void commit_params(struct dt_iop_module_t *self, dt_iop_params_t *p1, dt_dev_pix
           Jch[1] = hypotf(Jab[2], Jab[1]);
           Jch[2] = atan2f(Jab[2], Jab[1]);
 
-          const size_t index = (LUT_ELEM - 1) * (Jch[2] + M_PI_F) / (2.f * M_PI_F);
+          const size_t index = roundf((LUT_ELEM - 1) * (Jch[2] + M_PI_F) / (2.f * M_PI_F));
           // The 6.f factor is an ugly hack to prevent false-positives in gamut detection.
           // we shouldn't need it, which means there is a well-hidden bug somewhere.
           // for the time being, this will prevent gamut clipping of valid colors
```
Comment (flannelhead) [inline src/iop/colorbalancergb.c]: This comment becomes obsolete with the below change.

**Comment by flannelhead** [comment]
(Hope you don't mind a slightly off-topic shout-out :D)

Thank you @aurelienpierre for this module! It's already my favourite in Darktable by far and the bulk of the creative process happens right there. It also nicely pairs with Filmic – while some have issues with Filmic leaving highlights too desaturated, this module can be used to address that quite nicely. Especially the saturation controls offer a nice creative tool to e.g. create richer greens in pictures of plants.

While doing debugging of this issue, I also found the code to be clearly laid out and easy enough to follow. With the changes here, the gamut mapping part is also pretty fancy and will hopefully prevent nasty surprises when doing edits.

**Comment by TurboGit** [comment]
Very nice work! I let you remove the OBE comments as  described by @flannelhead.

File: src/iop/colorbalancergb.c (hunk 2 above)
Comment (aurelienpierre) [reply src/iop/colorbalancergb.c]: right, I forgot

**Review by TurboGit — APPROVED** [review]
Thanks ! Works for me.
