### PR TITLE
Fix clang build of masks/gradient.c

### LINKED ISSUE #20272: Macos Homebrew fatal error: label followed by a declaration is a C23 extension
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

release-5.5.0-149-gb6d2433ab9

...
...darktable/src/develop/masks/gradient.c:1489:7: fatal error: label followed by a declaration is a C23 extension [-Wc23-extensions]
 1489 |       float curvature = gradient
      |       ^
1 error generated.

### Steps to reproduce

on MacOs Tahoe and master:

1) cd darktable/packaging/macosx

2) ./1_install_hb_dependencies.sh
3) ./2_build_hb_darktable_default.sh

### Expected behavior

compile w/o error

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

release-5.5.0-149-gb6d2433ab9

### What OS are you using?

Mac

### What is the version of your OS?

Tahoe 26.2

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Linux build OK

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #20272

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
@TurboGit @kmilos in fact the culprit was the `;` removals in f0c74da882653b1f0a3b6d1a9674a0144f408cb7 so the 5.4.1 build worked/works fine with clang. So for master only :-)

File: src/develop/masks/gradient.c [hunk 1]
```diff
@@ -1485,7 +1485,7 @@ static void _gradient_modify_property(dt_masks_form_t *const form,
 
   switch(prop)
   {
-    case DT_MASKS_PROPERTY_CURVATURE:
+    case DT_MASKS_PROPERTY_CURVATURE:;  // the `;` is required for clang builds!
```
Comment (TurboGit) [inline src/develop/masks/gradient.c]: Well what about a clean fix adding `{` `}` for the whole code in the case statement?

```
case ...:
   {
       ...
   }
   break;
```

Would that work?

**Comment by TurboGit** [comment]
> @TurboGit @kmilos in fact the culprit was the `;` removals in [f0c74da](https://github.com/darktable-org/darktable/commit/f0c74da882653b1f0a3b6d1a9674a0144f408cb7) so the 5.4.1 build worked/works fine with clang. So for master only :-)

Yes, but this is a hack to workaround a compiler check. I still think we should do better and use a block `{` `}`. I can do it, let me know.
