### PR TITLE
Fix a race condition forced by `dt_history_delete_on_image_ext()`

### LINKED ISSUE #20151: Background job "Discard history" does not work properly
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

When i start the "discard history" background job these issues can be observed here.
1. The whole dt window sort of freezes, can be resized or alike ...
2. There is no visible progress at the progress bar
3. the cancel button does not change when hovered and a click is not received
4. gnome responds with this

Image

### Steps to reproduce

Select many images in lighttable (it should take some seconds to be tested ...) and "discard history"

### Expected behavior

Should be working as "compress history ..." according to source they both should be "blocking" with an available cancel button.

### Logfile | Screenshot | Screencast

Nothing worthwhile to me in the logs. 
For me "somehow" the backjob makes gtk non-responding? Checked `backgroundjobs.c` and `control_jobs.c` already (when running the job  `_lib_backgroundjobs_updated()` is done)                                    

### Commit

unknown

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

master

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 43, 16core AMD system, OpenCL active or not doesn't matter

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RustiCL, Radeon™ 8060S

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Raising `DT_SIGNAL_TAG_CHANGED` in `dt_history_delete_on_image_ext()` possibly leads to a race condition in the `_control_work_res()` dispatcher, both fight for the imgid lock possibly leading to a standstill on fast systems.
If we want the signal we have the explicit `dt_history_delete_on_image()` doing that.

Raising `DT_SIGNAL_DEVELOP_MIPMAP_UPDATED` is done after unlocking imgid.

While being here:
1. `dt_history_hash_write_from_history()` is also done while the imgid is locked for history changes.
2. Functions presented via `history.h` check for a valid imgid for safety
3. `dt_history_item_as_string()` is only used here so static and removed from `history.h`
4. `dt_history_end_attop()` is static so it has been renamed according to standard.
5. Readabilty for `_control_generic_images_job_create()` 
6. Tested for all functions called by any `g_main_context_invoke()` variant and modified the return value for maintenance.

Release note: Fixed a possibly standstill while discarding history on fast systems

Fixes #20151

### CODE REVIEW

File: src/common/history.c [hunk 1]
```diff
@@ -164,14 +166,20 @@ void dt_history_delete_on_image_ext(const dt_imgid_t imgid,
 
 void dt_history_delete_on_image(const dt_imgid_t imgid)
 {
-  dt_history_delete_on_image_ext(imgid, TRUE, TRUE);
-  DT_CONTROL_SIGNAL_RAISE(DT_SIGNAL_TAG_CHANGED);
+  if(!dt_is_valid_imgid(imgid))
```
Comment (TurboGit) [inline src/common/history.c]: I think this should be `if(dt_is_valid_imgid(...`.

Comment (jenshannoschwalm) [reply src/common/history.c]: Of course!

**Comment by jenshannoschwalm** [comment]
Thanks for fetching the wrong check. I just again cross checked that we signal the tag change whereever we wanted it to do so. Nothing found.
