### PR TITLE
Bugfix: guides exposing

### LINKED ISSUE #15984: Guide lines / grid do not appear when module 'rotate and perspective' is activated
### Describe the bug

If you first activate the 'rotate and perspective' module for an image, the guides or the grid do not appear, although the grid display is configured in the module ('show guides' selected).
To make the grid visible, you have to close the module and then open it again by clicking on the module name. This is not a disaster, but a bit annoying. ;-)
It would be ideal if the grid appeared automatically as soon as the module is activated, at least if this behavior is configured in the module ('show guides' selected).
After the grid has been successfully displayed once, everything works as expected, i.e. the grid disappears when the module is deactivated and it is immediately displayed again when it is reactivated.

I have already observed this behavior in darktable versions older than 4.6.0.

### Steps to reproduce

1. Open an image in darkroom on which the module 'rotate and perspective' has not yet been applied.
2. Fold out / open module 'rotate and perspective' by clicking on the module name.
3. Activate module 'rotate and perspective' 
grafik

Expectation: The grid/guide is displayed.
Instead, to make the grid visible: Close the module again and open / unfold it again by clicking on the module name

### Expected behavior

It would be ideal if the grid appeared automatically as soon as the module is activated, at least if this behavior is configured in the module ('show guides' selected).

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

OBS

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

kubuntu desktop, nothing special

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
The global guide drawing via darkroom expose has to check for an active gui_module with `IOP_FLAGS_GUIDES_SPECIAL_DRAW`, in such a case it should not do that globally but rely on the module's exposure hook.

While being here simplified the ashift hash calculation.

Fixes #15984

@TurboGit might be worth to concider the second commit for 4.6.1 too

### CODE REVIEW

File: src/views/darkroom.c [hunk 1]
```diff
@@ -590,8 +590,11 @@ void expose(
                            darktable.lib->proxy.colorpicker.live_samples, FALSE);
   }
 
-  // draw guide lines if needed
-  if(!dev->gui_module || !(dev->gui_module->flags() & IOP_FLAGS_GUIDES_SPECIAL_DRAW))
+  const gboolean special_draw = dev->gui_module
+                             && dev->gui_module->flags() & IOP_FLAGS_GUIDES_SPECIAL_DRAW
+                             && dev->gui_module->enabled;
+  // draw guide lines if there is no active gui_module doing it via post_expose
+  if(!special_draw)
```
Comment (TurboGit) [inline src/views/darkroom.c:597]: So we do not call special draw if module is enabled now. Where it is called then now? Since this PR seems to work I'm missing something to understand how it works.

**Comment by TurboGit** [comment]
You put this in Draft, so you have found something broken I suppose?

File: src/views/darkroom.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/views/darkroom.c:596]: Indeed. That would sometimes lead to grid drawing twice. :-)

Current code for all those modules have that flag assumes they do something whatever the enabled status is. So we have to make sure ashift paints the default.

**Review by TurboGit — APPROVED** [review]
Works for me, Thanks!

**Comment by TurboGit** [comment]
Merged in master, 2nd commit also in 4.6.x branch.
