### PR TITLE
export metadata: remove history from xmp if max size exceeded

### LINKED ISSUE #4355: Unreadable jpeg metadata fields when including develop history
When exporting an image to jpeg, the 'Title' metadata field cannot be read by exiftool (command-line), libxmp (python) or flickr. When de-selecting 'develop history' in the 'edit metadata exportation' window (in the 'export selected' module), the issue disappears.

The Title field appears to be present in the file (since Geeqie displays it) but something is preventing other tools from reading it properly.

I've only been able to reproduce this issue on a single image so far and with exiftool/libxmp (possibly due to the fact that the image in question had a large history stack) but another user has also experienced this with flickr (see https://discuss.pixls.us/t/darktable-3-1-does-not-export-title-of-file/16589/3). 

Darktable version: 3.1.0+449~gc5f14d958-dirty
OS: ArchLinux
OpenCL: Issue occurs both with and without OpenCL

XMP attached

[2017-07-23-18.56.15.0_01.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/4242474/2017-07-23-18.56.15.0_01.cr2.xmp.txt)

### PR DESCRIPTION
**Pull request by phweyland**
fixes #4355

### CODE REVIEW

**Comment by TurboGit** [comment]
How to reproduce the issue on #4355 ? I tried the XMP posted there. I have added metadata and when I export I have them in the jpeg. Maybe I'm missing something ?

File: src/common/exif.cc [hunk 1]
```diff
@@ -3988,8 +4005,31 @@ int dt_exif_xmp_attach_export(const int imgid, const char *filename, void *metad
...
-    std::cerr << "[dt_exif_xmp_attach_export] " << filename << ": caught exiv2 exception '" << e << "'\n";
-    return -1;
+    std::string s(e.what());
+    if(s == "Size of XMP JPEG segment is larger than 65535 bytes")
+    {
+      Exiv2::XmpData &xmpData = img->xmpData();
+      _remove_xmp_keys(xmpData, "Xmp.darktable.history");
+      _remove_xmp_keys(xmpData, "Xmp.darktable.masks_history");
+      _remove_xmp_keys(xmpData, "Xmp.darktable.auto_presets_applied");
+      _remove_xmp_keys(xmpData, "Xmp.darktable.iop_order");
```
Comment (TurboGit) [inline src/common/exif.cc:4015]: finally you did not removed iop_order_list, is that expected ?

Comment (TurboGit) [reply src/common/exif.cc:4015]: > How to reproduce the issue on #4355 ? I tried the XMP posted there. I have added metadata and when I export I have them in the jpeg. Maybe I'm missing something ?

Ok found, I had not the history exported :)

**Comment by TurboGit** [comment]
>    How to reproduce the issue on #4355 ? I tried the XMP posted there. I have added metadata and when I export I have them in the jpeg. Maybe I'm missing something ?

Ok found, I had not the history exported :)

File: src/common/exif.cc (hunk 1 above)
Comment (phweyland) [reply src/common/exif.cc:4015]: In fact, in the four strings above represents the needles => more 1800 records in case of the test file, and iop_order_list is included.

**Comment by phweyland** [comment]
> Ok found, I had not the history exported :)

Yes, would have been better with a bit of explanation.
The bug: when xmp size > 65k all xmp info were lost.
The fix: when size > 65k remove the history records. Then other xmp are not lost anymore.

File: src/common/exif.cc [hunk 2]
```diff
@@ -3988,8 +4005,31 @@ int dt_exif_xmp_attach_export(const int imgid, const char *filename, void *metad
   }
   catch(Exiv2::AnyError &e)
   {
-    std::cerr << "[dt_exif_xmp_attach_export] " << filename << ": caught exiv2 exception '" << e << "'\n";
-    return -1;
+    std::string s(e.what());
+    if(s == "Size of XMP JPEG segment is larger than 65535 bytes")
```
Comment (parafin) [inline src/common/exif.cc:4009]: That's not how you detect type of exception, especially since the message might be translated. Instead you should check e.code() == Exiv2::kerTooLargeJpegSegment.

File: src/common/exif.cc [hunk 3]
```diff
@@ -3988,8 +4005,31 @@ int dt_exif_xmp_attach_export(const int imgid, const char *filename, void *metad
...
+    {
+      Exiv2::XmpData &xmpData = img->xmpData();
+      _remove_xmp_keys(xmpData, "Xmp.darktable.history");
+      _remove_xmp_keys(xmpData, "Xmp.darktable.masks_history");
+      _remove_xmp_keys(xmpData, "Xmp.darktable.auto_presets_applied");
+      _remove_xmp_keys(xmpData, "Xmp.darktable.iop_order");
+
+      try
+      {
+        img->writeMetadata();
```
Comment (parafin) [inline src/common/exif.cc:4019]: So you're assuming the exception was thrown by img->writeMetadata() above. Then add try-catch block around that call, check if error code is what you want and try to handle it. Re-throw (just plain throw) otherwise. This way you don't have to move img outside of try block or re-getting xmpData.

**Review by parafin — CHANGES_REQUESTED** [review]
Re-factoring is needed.

File: src/common/exif.cc (hunk 3 above)
Comment (phweyland) [reply src/common/exif.cc:4019]: > So you're assuming the exception was thrown by img->writeMetadata() above.

I've checked this. The oversize exception is generated there.

File: src/common/exif.cc (hunk 2 above)
Comment (phweyland) [reply src/common/exif.cc:4009]: Excellent. I'll do.

File: src/common/exif.cc (hunk 3 above)
Comment (phweyland) [reply src/common/exif.cc:4019]: >  Then add try-catch block around that call, check if error code is what you want and try to handle it.

Sounds great. I'll make a try.

**Comment by phweyland** [comment]
@parafin changes done.
2 cases checked:
- history giving size exception => no history but other tags
- normal history => history + other tags

Not able to test the throw path. Deserves your control.

File: src/common/exif.cc [hunk 4]
```diff
@@ -3983,7 +3999,32 @@ int dt_exif_xmp_attach_export(const int imgid, const char *filename, void *metad
...
+      if(e.code() == Exiv2::kerTooLargeJpegSegment)
+      {
+        _remove_xmp_keys(xmpData, "Xmp.darktable.history");
+        _remove_xmp_keys(xmpData, "Xmp.darktable.masks_history");
+        _remove_xmp_keys(xmpData, "Xmp.darktable.auto_presets_applied");
+        _remove_xmp_keys(xmpData, "Xmp.darktable.iop_order");
+        try
+        {
+          img->writeMetadata();
+          return 0;
```
Comment (parafin) [inline src/common/exif.cc:4017]: return should be removed here, because it already exists after catch() and some code might be added in-between in the future.

File: src/common/exif.cc [hunk 5]
```diff
@@ -3693,8 +3693,6 @@ static void _exif_xmp_read_data_export(Exiv2::XmpData &xmpData, const int imgid,
     g_list_free_full(hierarchical, g_free);
   }
 
-  /* TODO: Add tags to IPTC namespace as well */
```
Comment (parafin) [inline src/common/exif.cc:3696]: Is this intended change?

File: src/common/exif.cc [hunk 6]
```diff
@@ -3793,6 +3791,24 @@ static void dt_remove_xmp_key(Exiv2::XmpData &xmp, const char *key)
...
+    const std::string needle = key;
+    for(Exiv2::XmpData::iterator i = xmpData.begin(); i != xmpData.end();)
+    {
+      if(i->key().compare(0, needle.length(), needle) == 0)
+        i = xmpData.erase(i);
+      else
+        ++i;
+    }
+  }
+  catch(Exiv2::AnyError &e)
```
Comment (parafin) [inline src/common/exif.cc:3807]: Do some exceptions happen in this function? I mean if errors are not expected here, then try-catch can be removed, since the way code is written right now exceptions will be handled outside this function by printing a error and returning a failure. Or what is the reasoning here?

**Review by parafin — CHANGES_REQUESTED** [review]
Much better, but see my notes.

**Comment by phweyland** [comment]
@parafin, thanks for your comments. Fixed the return issue.
Let me know if you see other points to be fixed.

**Comment by parafin** [comment]
There were also 2 questions - about _remove_xmp_keys and about removed comment. If both of those points were intended, then current version looks fine. I mean it's now OK to be merged as is.

**Review by phweyland — COMMENTED** [review]
> There were also 2 questions - about _remove_xmp_keys and about removed comment.

I'm sorry. I've answered those points, but I must have used the wrong button. I still see some pending points and a submit review button... I'll kick it.

**Comment by parafin** [comment]
All good then.

**Review by parafin — APPROVED** [review]

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !

**Comment by RawConvert** [comment]
I just mentioned this issue in #7455 in case there is a loose end.
