### PR TITLE
crop dimensions string visibility fixes

### LINKED ISSUE #3624: clipping: crop dimensions label is sometimes rendered off-screen
When cropping while zoomed in, the default placement of the crop dimensions string (e.g. "1920x1080") at the center of the crop window can result in the dimensions string being rendered partially or completely off-screen.

Example:

screenshot-clip-label-offscreen

### LINKED ISSUE #3625: clipping: crop dimensions label can be hard to see over some images
The crop dimensions string (e.g. "1920x1080") can be difficult to see when rendered over an image area with pixels similar to the text color.

Example:

screenshot-clip-label-bad-vis

### PR DESCRIPTION
**Pull request by kamalmostafa**
Fixes #3624; Fixes #3625.

### CODE REVIEW

File: src/iop/clipping.c [hunk 1]
```diff
@@ -2324,9 +2324,24 @@ void gui_post_expose(struct dt_iop_module_t *self, cairo_t *cr, int32_t width, i
     snprintf(dimensions, sizeof(dimensions), "%.0fx%.0f", (float)procw * g->clip_w, (float)proch * g->clip_h);
```
Comment (TurboGit) [inline src/iop/clipping.c]: As we are at it, can you add spaces around x :  "%.0f x %.0f"

This will be even more readable I think. Thanks.

**Comment by TurboGit** [comment]
If you can do that soon I'll even consider this for 3.0 instead of 3.0.1. Given that 3.0 is a full rework of the GUI it will be nice to have this enhancement for the final release.

File: src/iop/clipping.c (hunk 1 above)
Comment (kamalmostafa) [reply src/iop/clipping.c]: Sure.  And while we're at that, what about using a Unicode "Multiplication X" character instead of the regular lower-case x?  So:  **1920 ✕ 1080**

https://www.fileformat.info/info/unicode/char/2715/index.htm

I think that would look even nicer, and the center of the X would mark the exact center of the crop window if we're careful to use e.g. "%5.0f ✕ %-5.0f".

Any objection to using that Unicode "Multiplication X"?

Comment (TurboGit) [reply src/iop/clipping.c]: Yes, sadly last time I have introduced an Unicode character in dt it was an issue for Windows. So I would prefer a plan x for now until this is fixed (maybe need another font) on Windows.

Comment (kamalmostafa) [reply src/iop/clipping.c]: Yep, I had that concern too.  Fwiw though, iop/clipping.c does already use a unicode character...
`pango_layout_set_text(layout, "ꝏ", -1); `
... though I do not know whether it renders correctly in Windows.  ;-)

The commit I'm adding to this pull req just sticks with the plain old lower-case "x".

**Comment by TurboGit** [comment]
Ok, I'll merge now. Note that there is many variables that can be made consts. Will do that, but please remember for your next PR. Thanks.

File: src/iop/clipping.c (hunk 1 above)
Comment (parafin) [reply src/iop/clipping.c]: FYI, these symbols aren't rendered for me on Linux, at least in a web browser. So please don't use such characters, it's not just about Windows.
