### PR TITLE
channelmixerrgb: change the CAT check in warning

### LINKED ISSUE #7271: 'double CAT applied' warning on pristine image
**Describe the bug**
"double CAT applied" warning is shown for freshly opened image

**To Reproduce**
1. Open raw image (I tried with Nikon D7000 NEF and Panasonic LX7 RW2) in darkroom (clear history before, if needed)
2. Check the module list (screenshot is heavily cropped). Note that 'colour calibration' displays a warning.
image
3. Open 'colour calibration' to check warning:
image
4. Check 'white balance' to ensure it's set to 'camera reference'
image
5. Compress the history from item 4 (white balance, before 'colour calibration'
image
6. Observe that colour calibration is re-added, with no 'double CAT' warning:
image

**Expected behavior**
No 'double CAT' warning when image is opened

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+2075~gc06b55abd
 - OS: Ubuntu 20.10

### LINKED ISSUE #7286: Color calibration module gives hint "double CAT applied" but there is only one module instance
**Describe the bug**
Migrated today to latest darktable master 3.3.0~git2079.19b17c9cc. When I open any of my already imported CR2 raws from Darktable 3.2, I get the "double CAT applied" hint.

**To Reproduce**
1. Change chromatic adaption defaults to **modern**
2. Restart darktable
3. Choose a unprocessed CR2 file in lighttable and open it with double click in darkroom.
4. Color calibration shows the "double CAT applied" hint, even if no other instance is active
5. Switch back to lighttable and reopen image again
6. The warning disappears.

You could instead after step 4 create a duplicate or original duplicate and switch between the two, the warning also disappears.

**Expected behavior**
No warning at all after first open.

**Screenshots**
Screenshot from 2020-12-12 16-17-06

Platform (please complete the following information):

    Darktable Version: 3.3.0~git2079.19b17c9cc.
    OS: Debian Bullseye
    OpenCL: yes
    PNY Nvidia Quadro 450.80.02-1

Binary package was obtained from https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

### PR DESCRIPTION
**Pull request by aurelienpierre**
prevent false positives

fix #7286
fix #7271

### CODE REVIEW

File: src/iop/channelmixerrgb.c [hunk 1]
```diff
@@ -2036,11 +2036,7 @@ void gui_changed(dt_iop_module_t *self, GtkWidget *w, void *previous)
   if(self->enabled && !(p->illuminant == DT_ILLUMINANT_PIPE || p->adaptation == DT_ADAPTATION_RGB))
   {
     // this module instance is doing chromatic adaptation
-    dt_iop_order_entry_t *CAT_instance = self->dev->proxy.chroma_adaptation;
-    dt_iop_order_entry_t *current_instance
-        = dt_ioppr_get_iop_order_entry(self->dev->iop_order_list, "channelmixerrgb", self->multi_priority);
-
-    if(CAT_instance && CAT_instance->o.iop_order != current_instance->o.iop_order)
+    if(!is_module_cat_on_pipe(self))
```
Comment (TurboGit) [inline src/iop/channelmixerrgb.c:2039]: I'm not sure to understand this one.

You check if self is not on the PIPE already... And you say in this path "another channelmixerrgb instance is doing CAT earlier in the pipe" ? Can you clarify ?

Comment (aurelienpierre) [reply src/iop/channelmixerrgb.c:2039]: `declare_cat_on_pipe(struct dt_iop_module_t *self, gboolean preset)` registers instances of color calibration doing CAT with a conflict resolution (in case of conflict : first one in pipe order gets the seat). So, anytime, we only need to check if the current instance is the one registered on the pipe. If not and the instance performs CAT, then we have a problem.

Comment (TurboGit) [reply src/iop/channelmixerrgb.c:2039]: I see, thanks.
