### PR TITLE
Proper fix for highlights reconstruction ROI problems

### LINKED ISSUE #12667: Seg fault trying to open RAW file in lighttable; JPG opens fine
Manjaro Ryzen 3900+ 32 gig RAM Nvidia proprietary

- Removed all traces of previous dt (/opt/darktable as well as .config/.cache).
- Fetched dt source from GitHub onto a new folder.
- Changed option(DONT_USE_INTERNAL_LUA "Never fall back to the intree copy of lua" OFF) in DefineOptions.cmake
- Created a new build directory, then cmake/make/make install as usual. No errors.
- Performed darktable-cmstest and darktable-cltest. No errors.
- Removed all old .xmp in Picture folder.
- Started darktable in terminal. No errors.
- Opened darktable. No errors.
- Imported Picture folder (contaning a few .RAF and .JPG). No errors.
- In lighttable, doubleclicked a JPG. No errors.
- Closed darktable. No errors.
- Opened darktable in terminal again.
- In lighttable, doubleclicked a RAF. Text: _Loading xxxx.RAF_. L-o-n-g wait. **Seg fault**.

Same RAF opened just fine yesterday (in darktable version compiled yesterday).

_Darktable version:_
[ver.txt](https://github.com/darktable-org/darktable/files/9808828/ver.txt)

_Terminal output:_
[urk.txt](https://github.com/darktable-org/darktable/files/9809001/urk.txt)

_**--- Addendum ---**_
I repeated all steps above, but this time I did _not_ change anything in DefineOptions.cmake.
Still segfault when I doubleclicked a RAF. 

_Darktable version:_
[ver2.txt](https://github.com/darktable-org/darktable/files/9809935/ver2.txt)

_Terminal output:_
[urk2.txt](https://github.com/darktable-org/darktable/files/9809937/urk2.txt)

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As reported in #12667 there were crashes in opposed or segmentation based code.

There has been a previous pr #12670, that one has become a mess but is a valuable resource to understand the problems.

In short; the mentioned algorithms require all image data for a stable calculation of chromacity correction (opposed) and the segmentation analysis and recovery code.

Thus we have to change the roi_in to "take it all". But - and that has been the problem of current code - the roi_out can be extended (for example by demosaic rounding for xtrans sensors). This results in a situation where the roi_out area is not fully inside roi_in.

This can't be properly fixed in the modify code, we have to check for the proper output range in the algorithms.

Fixes #12667

Replaces #12670

### CODE REVIEW

File: src/iop/highlights.c [hunk 1]
```diff
@@ -2036,7 +2032,7 @@ void modify_roi_in(dt_iop_module_t *self, dt_dev_pixelpipe_iop_t *piece, const d
   if(visualizing || (d->mode != DT_IOP_HIGHLIGHTS_OPPOSED && d->mode != DT_IOP_HIGHLIGHTS_SEGMENTS))
     return;
 
-  *roi_in = *roi_out;
+  // we always take the full date provided by rawspeed
```
Comment (TurboGit) [inline src/iop/highlights.c:2035]: minor typo : full data

Comment (jenshannoschwalm) [reply src/iop/highlights.c]: done plus two mor `for_each_channel`

**Review by TurboGit — APPROVED** [review]
This looks good to me. Better merging sooner than later to have proper field testing. Thanks a lot for the difficult work on this one.

**Comment by ClaesGitHub** [comment]
Thank you/Danke vielmals/Merci!
