### PR TITLE
Fix rated image undo of previously rejected image

### LINKED ISSUE #19749: A reject-rating from undo is not found by filter
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

When a "**reject**" is set back with "**ctrl+z**" it is not grabbed by the filter.

### Steps to reproduce

Mode **Lighttable**:

Open a folder and found there a rejected picture.
Give it a 1-star-rating.
Oh sorry, take this step back with "Ctrl+z" (undo).
The picture now is **rejected** again.
Use rating-filter "rejected only".
The picture is not visible.
Stop darktable and start again.
The picture is still **not found by the filter** although it is marked as rejected.

Press "1" and press "r" while the picture is selected.
Now the filter finds the rejected picture.

### Expected behavior

Filter "rejected only" should show pictures that are marked as rejected

### Logfile | Screenshot | Screencast

May be same as issue #18719 ?

### Commit

_No response_

### Where did you obtain darktable from?

OBS build

### darktable version

5.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04.3 LTS

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by wpferguson**
Test for new rating of DT_VIEW_REJECT(6), which  is not valid and change it to DT_RATINGS_REJECT(-3) so that the correct rating flags are changed.  This problem only appears when taking a previously rejected image then applying a rating, then using CTRL-Z to undo.

Fixes #19749

### CODE REVIEW

File: src/common/ratings.c [hunk 1]
```diff
@@ -63,6 +63,8 @@ static void _ratings_apply_to_image(const dt_imgid_t imgid, const int rating)
   if(image)
   {
     // apply or remove rejection
+    if(new_rating == DT_VIEW_REJECT) // handle undo
+      new_rating = DT_RATINGS_REJECT;
```
Comment (TurboGit) [inline src/common/ratings.c]: As this imply that the next conditional will be taken, maybe clearer, just below:

```
if(new_rating == DT_RATINGS_REJECT 
   || new_rating == DT_VIEW_REJECT)
```

Comment (TurboGit) [reply src/common/ratings.c]: And as we are at it we can remove `new_rating` and use `rating` directly. The variable `new_rating` was not changed anyway.

Comment (wpferguson) [reply src/common/ratings.c]: I'll change new_rating to rating.

Comment (wpferguson) [reply src/common/ratings.c]: > As this imply that the next conditional will be taken, maybe clearer, just below:

Okay, I shouldn't try coding before I've had at least one (2?)  cup of coffee.  I finally understand your proposed change.  I'll clean it all up now that I'm awake.

Comment (wpferguson) [reply src/common/ratings.c]: Next time I'm being dense (or stupid), tell me to go drink some coffee.  Sorry for all the noise and thanks for putting up with me.
