### PR TITLE
Handle corrupted images gracefully

### LINKED ISSUE #5039: Darkroom freezes when loading some CR2 image files
**Describe the bug**

Certain CR2 images cause Darktable to freeze in darkroom mode when they are selected. Darkroom shows "loading image xxx" and hangs. Other images in darkroom mode can be clicked but that will be ignored. Changing back to lighttable allows me to continue using Darktable but the error will re-occur next time. Most files work though. Not related to a certain lens AFAIK. Only appears in a certain photo set but might be accidental and not all photos in that set are causing problems.

Console output when opening a problematic image for darkroom from lighttable:

```
[rawspeed] (IMG_4469.CR2) rawspeed::RawImage rawspeed::RawDecoder::decodeRaw(), line 282: const uint8_t* rawspeed::BitStream<Tag, Cache>::getInput() [with Tag = rawspeed::JPEGBitPumpTag; Cache = rawspeed::BitStreamCacheRightInLeftOut; uint8_t = unsigned char], line 139: Buffer overflow read in BitStream
[rawspeed] (IMG_4456.CR2) virtual std::unique_ptr<rawspeed::RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData*), line 91: No decoder found. Sorry.
[rawspeed] (IMG_4458.CR2) rawspeed::RawImage rawspeed::RawDecoder::decodeRaw(), line 282: const uint8_t* rawspeed::BitStream<Tag, Cache>::getInput() [with Tag = rawspeed::JPEGBitPumpTag; Cache = rawspeed::BitStreamCacheRightInLeftOut; uint8_t = unsigned char], line 139: Buffer overflow read in BitStream
allocation failed???
allocation failed???

```

**To Reproduce**
1. Put problematic file in folder
2. Import folder
3. Doubleclick file in lighttable mode
4. Darkroom mode will open, show blank image area and "Loading image xxx..." and hang as described above

**Expected behavior**
Image opens so I can edit it in darkroom.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2 from the repos
 - OS: Manjaro Gnome
 - no OpenCL
 - Radeon RX570 with video-linux 2018.05.04

**Other**
The xmp file gets created when I try to open a problematic image. I can open the image in XnView MP without problems. An example file causing the issue is attached.

[IMG_4469.zip](https://github.com/darktable-org/darktable/files/4628704/IMG_4469.zip)

**References**
I found https://github.com/darktable-org/darktable/issues/4730 but my issue is less severe, not causing Darktable to crash completely.

The issue is not new, I already commented here (I am "Christian G" over there): https://redmine.darktable.org/issues/10548#note-6

There's also several issues linked on Redmine which are all closed but apparently did not help for my specific problem.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
If an image could not be opened we have the 'image loading' message
forever until the user decides to switch back to lighttable mode.

This pr introduces `image_invalid` in `dt_develop_t`. If we find an error
while loading the mipmap cache this is switched on.

In darkroom expose we show a more meaningful message in this case and after
a while switch back to lighttable automatically.

fixes #5039

### CODE REVIEW

File: src/develop/develop.c [hunk 1]
```diff
@@ -70,7 +70,7 @@ void dt_dev_init(dt_develop_t *dev, int32_t gui_attached)
 
   dt_image_init(&dev->image_storage);
   dev->image_status = dev->preview_status = dev->preview2_status = DT_DEV_PIXELPIPE_DIRTY;
-  dev->image_loading = dev->preview_loading = dev->preview2_loading = dev->history_updating = 0;
+  dev->image_loading = dev->preview_loading = dev->preview2_loading = dev->history_updating = dev->image_invalid = 0;
```
Comment (TurboGit) [inline src/develop/develop.c:73]: I'm never happy with using int instead of boolean. At least when you see gboolean in the code you know it is a bi-state switch. Can you change all the int above to be boolean ? At least image_invalid which is clearly a boolean but I bet all others are also bi-sate variables.

Comment (jenshannoschwalm) [reply src/develop/develop.c:73]: Ok, i'll take care of this. Although - image_invalid is probably the only one **not** being a boolean :-)

**Comment by jenshannoschwalm** [comment]
done

**Comment by TurboGit** [comment]
Looks good now, thanks for fixing all those booleans!
