### PR TITLE
[AI] Fix AI object mask groups losing holes after vectorisation

### LINKED ISSUE #20870: Wrong sequence of ai objects in ai mask groups
### Is there an existing issue for this?

- [ ] I checked and did not find my issue in the already reported ones

### Describe the bug

If the raster mask that is generated from the newly implemented AI Mask option has a "hole" inside, the hole will be missing from the final vectorized mask. The out-most ai object appears at the top of the mask group as shown in the Mask Manager. It should be placed at the bottom of the group as the first ai object, so that the remaining ai objects (the inner holes) can be "deducted" from the out-most mask successfully to get the final correct mask.

### Steps to reproduce

1. The issue is found only for masks with a "hole" or "holes" inside. Activate AI Mask creation > click on the image to get the desired mask. The masked area shown here is correct, with "holes" inside.
Image
2. I used shift+right-click to commit the mask generation action, so that a raster mask is saved for reference purpose. A mask preview for the module shows that the inner holes are now gone.
Image
3. The raster mask that is saved previously is good with "holes" inside, as shown in the External Raster Masks module.
Image
4. As shown in the Mask Manager, the out-most ai object, which is ai object 9, is at the top of the group which I suppose is the last in the group. 
Image
5. If I keep Move Down ai object 9 in the Mask Manager until it is at the bottom; the mask now becomes good.
Image

### Expected behavior

The out-most ai object should be placed as the first object in the mask group, but not the last.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

online forum

### darktable version

5.5.0+995~gc3afa02829

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD i-gpu Vega 11, driver: 31.0.12027.9001

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by andriiryzhkov**
Fixes #20870

When an AI object mask produces a shape with holes (e.g. a donut-shaped selection), the final mask was coming out as a solid outer region – the holes were silently missing. @shumconstedit tracked this down in the issue report with very clear screenshots and a reliable manual workaround (moving the outermost path to the bottom of the group in the Mask Manager).

## Root cause

`ras2forms` returns vectorised paths in reverse potrace order (innermost hole first, outer last) because of an internal `g_list_prepend` step. When the AI object mask's group builder iterated that list forward and appended each path to the group, the outer ended up at the last position.

The render consequence:

- Position 0: innermost hole with `DIFFERENCE` mode → subtracts from an empty buffer → no-op.
- Position 1: next hole → still no-op.
- Position N-1: outer with default `UNION` mode → drawn over the empty buffer, filling the whole region as a solid shape.

Net result: holes invisible in the rendered mask.

## Fix

Reverse the forms and signs lists in `_register_vectorized_forms` before building the group, so outer lands at position 0 (rendered first as the base) and holes follow after with `DIFFERENCE` (correctly subtracting from the base).

Naming convention is unchanged: outer gets `#1`, inner holes increment upward. In the Mask Manager this displays as `#N` at the top, `#1` at the bottom – matching the "newest-at-top" convention used for all other mask types in darktable.

## Scope

- Only touches `_register_vectorized_forms` in `src/develop/masks/object.c`.
- `ras2forms` itself is unchanged – the External Raster Masks module doesn't build a group from its output (registers each form independently), so it isn't affected.
- No XML/config/translation changes.

### CODE REVIEW

File: src/develop/masks/object.c [hunk 1]
```diff
@@ -1020,6 +1020,10 @@ _register_vectorized_forms(dt_iop_module_t *module,
   }
   grp_nb++;
   path_nb++;
+  // reverse so outer comes before its holes: outer lands at position 0
```
Comment (TurboGit) [inline src/develop/masks/object.c]: What about reversing the two lists created in `ras2forms()`? This will be more generic and will match the actual rasterization done in potrace.

Comment (andriiryzhkov) [reply src/develop/masks/object.c]: Moved it to `ras2forms`. Tested on external raster mask module too - sequence is correct there now.

**Review by TurboGit — APPROVED** [review]
Thanks!
