### PR TITLE
colorzones: fix "edit by area"-min-max indicators

### LINKED ISSUE #5585: Wrong "edit by area"-min-max indicators in the colorzones module
**Describe the bug**
The "edit by area"-min-max indicators in the colorzones module are drawn incorrectly when color is selected by hue as shown is this example (see the non-monotonous behavior of the gray shaded area),

**To Reproduce**
Go to the colorzones module, select option "edit by area" and channel "hue" and hover over all nodes.

**Expected behavior**
No highly non-monotonous behavior of the area indicator.

**Screenshots**
color_zones_edit_by_area

**Platform (please complete the following information):**
 - Darktable Version: git master

**Additional context**
I opened a PR to fix this issue.

### PR DESCRIPTION
**Pull request by rabauke**
When introducing the new spline algorithms for the color zones module, the code for the "edit by area"-min-max indicators was not adjusted correctly in b17d74fe09d7fe79df65437a4d334580f1166fd9. This pr is to fix this UI issue.

This fixes #5585.

### CODE REVIEW

File: src/iop/colorzones.c [hunk 1]
```diff
@@ -2136,8 +2149,7 @@ static void _channel_tabs_switch_callback(GtkNotebook *notebook, GtkWidget *page
 
 static void _color_picker_callback(GtkToggleButton *togglebutton, dt_iop_module_t *module)
 {
-  if(gtk_toggle_button_get_active(togglebutton))
-    dt_iop_color_picker_set_cst(module, iop_cs_LCh);
+  if(gtk_toggle_button_get_active(togglebutton)) dt_iop_color_picker_set_cst(module, iop_cs_LCh);
```
Comment (rabauke) [inline src/iop/colorzones.c:2152]: Ooops. Some automatic code re-formating by clang-format slipped in. This and all changes below will be reverted,

**Comment by TurboGit** [comment]
Indeed, nice to see this fixed just in time for the release. Thanks!
