### PR TITLE
Fix for - Drag and drop into lighttable fails if it's empty #8914 - feedback needed

### LINKED ISSUE #8914: Drag and drop into lighttable fails if it's empty
Ubuntu 18.04    dt 3.5.0+1966~g12d7a9967-dirty
If I already have one image in lighttable, I can drag some other raw file, or a folder of raws, into lighttable, and it works ok.  This is using the desktop's own file manager, "Files".
But if lighttable is empty, it doesn't work, lighttable remains empty.

### PR DESCRIPTION
**Pull request by domosbg**
Fixes #8914

This should fix the problem mentioned in the title.

But I need some feedback about the implementation: I copied the complete function static void _event_dnd_received(...) from thumbtable.c to lighttable.c. So same function in 2 files. I think that is not a good solution because redundancy of code should nomally be avoided. So, where is the right place to put this function or is it ok to have it 2 times?

### CODE REVIEW

**Comment by TurboGit** [comment]
> So same function in 2 files. I think that is not a good solution because redundancy of code should nomally be avoided. So, where is the right place to put this function or is it ok to have it 2 times?

You could probably make this routine "public" by adding the spec into thumbtable.h (with a different name, more generic like `dt_thumbtable_dnd_received` ?) and then call it in thumbtable in `static void _event_dnd_received(...)` and in lighttable?

I did not looked at the code, so double check this is fine. For sure it cannot be exported from lighttable.c which is a views and no public spec (fully self sufficient module).

**Comment by TurboGit** [comment]
Last but not least, please do not merge master into your topic branch, you need to rebase and fix potential conflicts. TIA.

**Comment by domosbg** [comment]
Thanks for your help. I changed it how you suggested.

Sorry for the wrong using of github. I thought there was something wrong, but i wasn't sure how to do it. But now I take a look again and I think I understood now how to rebase. Next time I will make it right (hopefully).

File: src/views/lighttable.c [hunk 1]
```diff
@@ -1284,6 +1291,10 @@ void gui_init(dt_view_t *self)
   gtk_overlay_reorder_overlay(GTK_OVERLAY(dt_ui_center_base(darktable.gui->ui)),
                               gtk_widget_get_parent(dt_ui_toast_msg(darktable.gui->ui)), -1);
 
+  // enable drag & drop
+  gtk_drag_dest_set(dt_ui_center_base(darktable.gui->ui), GTK_DEST_DEFAULT_ALL, target_list_all, n_targets_all, GDK_ACTION_MOVE);
+  g_signal_connect(G_OBJECT(dt_ui_center_base(darktable.gui->ui)), "drag-data-received", G_CALLBACK(_event_dnd_received), NULL);
```
Comment (TurboGit) [inline src/views/lighttable.c:1296]: since you have 100% the same spec & code for _event_dnd_received maybe just:
`G_CALLBACK(dt_thumbtable_event_dnd_received)`

And you can remove `_event_dnd_received` completely.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Can be simplified further I think.

**Comment by domosbg** [comment]
I simplified it as requested. Sorry that it takes a few days, unfortunately I actually have problems with my internet connection at home.

**Review by TurboGit — APPROVED** [review]
Looks good now, and works for me, thanks !
