### PR TITLE
exif: fix DNG Daylight illuminant parsing

### LINKED ISSUE #10848: Darktable 3.8.0 no longer recognizes embedded color matrix for DNGs produced by CHDK firmware for Canon Powershot ELPH 180
**Describe the bug/issue**

Version 3.8.0 of darktable no longer recognizes the embedded color matrix for the DNGs produced by my Kolari Pocket (Canon Powershot ELPH 180) running the CHDK firmware. Prior versions of darktable did not have this issue. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Download an example raw file here https://filebin.net/77ss7rf4pka42fqi  (If the file is no longer available let me know).  This is the original DNG straight from the SD card as produced by CHDK
2. Open in darktable 3.8.0

**Screenshots**

In version 3.6.0 the matrix is read by darktable just fine.
image

Running 3.8.0, when importing the DNGs, the following message appears. 
image

And the embedded matrix isn't present. It's not in the drop down menu for input color profile after opening either. 
image

**Platform**
* darktable version : e.g. 3.8.0
* OS                :  Windows 10 

**Additional context**
I have also tried running the DNGs through the Adobe DNG Converter to ensure that the CHDK dngs are "up to spec", but that did not resolve the issue.

### PR DESCRIPTION
**Pull request by kmilos**
Minimally fixes #10848

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Ok for 3.8.1?

**Comment by kmilos** [comment]
Should be, after it is confirmed ;)

**Comment by kmilos** [comment]
Works for me.

However, might wat to wait for merge/issue closing as there are some more open comments/requests over there.

**Comment by kmilos** [comment]
@jenshannoschwalm Please review

I have also added the adaptation matrix for 3200K ISO studio tungsten source for completeness.

This does not include the handling of the "unknown" light source.

**Comment by jenshannoschwalm** [comment]
Code looks good and safe for me.

Can't test on those images though 😁

**Comment by jenshannoschwalm** [comment]
https://github.com/darktable-org/darktable/blob/a9273c4ad66b8c55c2fe057e2f5b6cb43a7a059c/src/common/exif.cc#L1274

I think here we can be sure there is no valid matrix so an "unknown situation".

Wouldn't it be safe to
1. default to D65 and also
2. set img->camera_missing_sample to true triggering the warning?

**Comment by kmilos** [comment]
I'd prefer to have this merged as is to fix the linked issue in particular, and handle the unknown case separately.

File: src/common/exif.cc [hunk 1]
```diff
@@ -1237,10 +1240,13 @@ static bool _exif_decode_exif_data(dt_image_t *img, Exiv2::ExifData &exifData)
             mat3mul(img->d65_color_matrix, correctmat[0], colmatrix[sel_illu]);
             break;
           case DT_LS_D55:
+          case DT_LS_Daylight:
+          case DT_LS_FineWeather:
```
Comment (parafin) [inline src/common/exif.cc:1244]: Do we just assume that FineWeather is the same as Daylight (then why it was introduced at all?) or is there some reference? I couldn't find it.

File: src/common/exif.cc [hunk 2]
```diff
@@ -1254,9 +1260,14 @@ static bool _exif_decode_exif_data(dt_image_t *img, Exiv2::ExifData &exifData)
             mat3mul(img->d65_color_matrix, correctmat[5], colmatrix[sel_illu]);
             break;
           case DT_LS_CoolWhiteFluorescent:
+          case DT_LS_Fluorescent:
```
Comment (parafin) [inline src/common/exif.cc:1263]: CoolWhiteFluorescent is assumed to be F2 illuminant (judging by the matrix and actual description of F2 matches) and it has temperature of 4230 K. Fluorescent is cited to have temperature of 3800 K by Lumariver manual. It's not really close to each other...

File: src/common/exif.cc [hunk 3]
```diff
@@ -1170,7 +1171,9 @@ static bool _exif_decode_exif_data(dt_image_t *img, Exiv2::ExifData &exifData)
         { 0.9904476, -0.0071683, -0.0116156, -0.0123712, 1.0155950, -0.0029282, -0.0035635, 0.0067697,
           0.9181569 }, //  Standard light C
         { 0.9212269, -0.0449128, 0.1211620, -0.0553723, 1.0277243, 0.0403563, 0.0235086, -0.0391019,
-          1.6390644 }  // CoolWhiteFluorescent
+          1.6390644 }, // CoolWhiteFluorescent
+        { 0.8662704, -0.0913307, 0.2772741, -0.1090739, 1.0747007, 0.0914149, 0.0551057, -0.0924980,
+          2.5124774 }  // ISO Studio Tungsten
```
Comment (parafin) [inline src/common/exif.cc:1176]: Where does this come from? Which temperature is ISOStudioTungsten? What is the reference for that?

**Review by parafin — COMMENTED** [review]
Some questions about this PR. I'm not nitpicking, I'm just also interested in this subject.

File: src/common/exif.cc (hunk 3 above)
Comment (kmilos) [reply src/common/exif.cc:1176]: ISO Studio Tungsten is 3200K, as defined in the DNG SDK. The xy (and therefore XYZ) is calculated using the logic in the DNG SDK, and then adaptation using Bradford matrix just like other examples on http://www.brucelindbloom.com/Eqn_ChromAdapt.html

File: src/common/exif.cc (hunk 2 above)
Comment (kmilos) [reply src/common/exif.cc:1263]: Again, DNG SDK.

File: src/common/exif.cc (hunk 1 above)
Comment (kmilos) [reply src/common/exif.cc:1244]: This comes from the DNG SDK.

Comment (parafin) [reply src/common/exif.cc:1244]: Do you happen to have a link where exactly in the sources it is defined?

File: src/common/exif.cc (hunk 3 above)
Comment (parafin) [reply src/common/exif.cc:1176]: OK, maybe worth adding a comment about that, because above it is stated that all matrices come directly from http://www.brucelindbloom.com website.

**Comment by kmilos** [comment]
Btw, this is not ideal either, because Adobe define Daylight as 5500K **w/ tint 10**, so the XYZ and the adaptation matrix are not really identical to D55 (tint 0).

I could fix this, but then we'd better fix a few other ones where tint is not 0...

In any case, this might be "good enough" for now and better than having no (or unadapted) matrix ;)

File: src/common/exif.cc (hunk 1 above)
Comment (parafin) [reply src/common/exif.cc:1244]: Found it, nevermind, thanx.

Comment (parafin) [reply src/common/exif.cc:1244]: The problem with DNG SDK as a reference is that they also define StandardLightB as D55, which is quite off actually (4874). But I think we're indeed good with thinking that FineWeather means Daylight.

File: src/common/exif.cc (hunk 2 above)
Comment (parafin) [reply src/common/exif.cc:1263]: DNG SDK is somewhat weird in this sense (e.g. why CoolWhiteFluorescent and not WhiteFluorescent), but OK, makes sense. BTW, we're missing other fluorescent illuminants (WarmWhite, etc.).

File: src/common/exif.cc (hunk 3 above)
Comment (kmilos) [reply src/common/exif.cc:1176]: Done

File: src/common/exif.cc (hunk 2 above)
Comment (kmilos) [reply src/common/exif.cc:1264]: Actually, they define CoolWhiteFluorescent as F9 and Fluorescent as F2, so they should indeed not be aliased here...

Comment (kmilos) [reply src/common/exif.cc:1264]: As for the others, I could calculate and add them the same way as I did for 3200K - even easier as xy coords are defined already...

Comment (parafin) [reply src/common/exif.cc:1264]: I think maybe we're looking at different parts of DNG SDK after all, here's what I found: https://github.com/aizvorski/dng_sdk/blob/master/source/dng_camera_profile.cpp#L135

Comment (kmilos) [reply src/common/exif.cc:1264]: Yes, but also take a look at `dng_xy_coord.cpp` of a more recent package, that one is too old.

Comment (parafin) [reply src/common/exif.cc:1264]: Indeed, thanx for that. IMHO it's logical to use then that as a reference.

Comment (kmilos) [reply src/common/exif.cc:1266]: Updated now against that more up-to-date reference.

Comment (kmilos) [reply src/common/exif.cc:1266]: Still missing the adaptation for the few remaining fluorescents though...

**Review by parafin — APPROVED** [review]

**Comment by TurboGit** [comment]
Merged into master and darktable-3.8.x branch.
