### PR TITLE
Bugfix: pixelpipe cache versus raster mask 

### LINKED ISSUE #14271: DT 4.3.0 Hierarchically higher modules ignore/disable rastermask if created with detail treshold mask.
### Describe the bug

If you have created _detail threshold mask_ in one module (let's say for example exposure module) and reuse it in _hierarchically higher module as raster mask_ (for example in contrast equalizer) in next hierarchically higher module (for example color balance rgb) _it will be ignored/disabled._

If you then _switch off the raster mask_ in the module where the raster mask was used (in this case contrast equalizer) and _switch it on again_, it will _also be taken into account_ by the higher module (color balance rgb). 

### Steps to reproduce

1. Create a mask with the help of _detail threshold_ slider and apply it (exposure module here):

grafik
grafik

2. Make a change in hierarchically higher module (contrast equalizer) and apply the _raster mask_ based on detail threshold mask made by exposure module :

grafik
grafik

3. Go to a hierarchically higher module (color balance rgb) and make a change there. The raster mask applied to the hierarchically lower module is _ignored/disabled_. 

grafik

4. Go back to the module that used the raster mask (contrast equalizer) . Although it is _shown as applied_ in the menu, _it is not active_:

grafik

5. Deactivate it and activate it again. Now it is applied again. 

grafik

6.  This time it will be active also in hierarchically higher module:

grafik

7. It can be - but this is not always the case - if you then make another change in this module (color balance rgb), that again the raster mask is switched off. Then you have to repeat steps 4 to 6. In the following video that was the case:

https://user-images.githubusercontent.com/38165484/233368904-3291e672-eece-4739-a722-3b53e6c9c505.mp4

Here is also the output of the terminal with "darktable -d all" when this video was made:

[darktable_raster_mask.txt](https://github.com/darktable-org/darktable/files/11286278/darktable_raster_mask.txt)

Important note:

This behavior _does not always happen_. However, I could not determine under what circumstances this happened. 

Raw file I used for the demonstration is from this post
https://discuss.pixls.us/t/gamut-issues-should-i-be-worried/36719/1

### Expected behavior

When raster mask is used by one module, it should not be affected by other modules that are used after it.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+1872~gd2c7145fd

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-70-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070/PCIe/SSE2

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
We have #14271 indicating a problems with details masks.

The whole details-mask thing got some love leading to easier understanding what's going on there.
There is now only `gboolean want_detail_mask` in `struct dt_dev_pixelpipe_t` that is set to `TRUE` if we use a dual-demosaicing mode or the "details threshold" if refining a mask. If this is set, either `demosaic` (for raws) or `rawprepare` for sraws writes the scharr-mask. Simpler interface, nothing changed in color maths ...

But- this didn't solve the issue, in fact there was nothing wrong there, just not understandable what happens.

The issue reported could also be triggered by other raster mask dependencies, so what happened? The content of the source raster mask is not reflected in cache hashes later in the pipe, so we could take non-valid cachelines.
What is done here, whenever we update a raster mask, all later cachelines are invalidated.

Another old bug fixed, was just very difficult to trigger with 5 cachelines so got un-noticed.

Fixes #14271 @s7habo

### CODE REVIEW

**Comment by TurboGit** [comment]
> Another old bug fixed, was just very difficult to trigger with 5 cachelines so got un-noticed.

Congrats, again !

File: src/develop/pixelpipe_cache.c [hunk 1]
```diff
@@ -130,17 +130,20 @@ uint64_t dt_dev_pixelpipe_cache_basichash(
...
+  const uint32_t hashing_pipemode[3] = {(uint32_t)imgid,
+                                        (uint32_t)pipe->type,
+                                        (uint32_t)pipe->want_detail_mask };
 
   char *pstr = (char *)hashing_pipemode;
   for(size_t ip = 0; ip < sizeof(hashing_pipemode); ip++)
     hash = ((hash << 5) + hash) ^ pstr[ip];
 
-  // also use the details mask roi
+/*
```
Comment (TurboGit) [inline src/develop/pixelpipe_cache.c:141]: Maybe just remove this or add a comment about why it is commented out?

**Review by TurboGit — CHANGES_REQUESTED** [review]
Minor comment.

File: src/develop/pixelpipe_cache.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/develop/pixelpipe_cache.c:141]: I fully agree. Maybe merge now, I think it might be very good to explain exactly there why we take what parameters to calculate the hash and how we validate the integrity .
Will add this the next days.

**Review by TurboGit — APPROVED** [review]
Thanks!
