### PR TITLE
fix tag categories recursively not exported

### LINKED ISSUE #20368: Problem to export non-private tag categories under the "new" recursive tagging system
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

This is partly related to the transition to recursively private tags: https://github.com/darktable-org/darktable/pull/20160

After trying to understand the new system, setting all parent categories to non-private still won't allow me to export non-private tags.
It seems that the criterion to exclude tags is not just everything following a private category, but anything following a category in general. I.e. both "private" and "category" have the same effect.

### Steps to reproduce

1. Create a completely new first-order tag (non-private, not a category): It gets exported.
2. Use this tag as a parent directory (non-private, still not a category) and attach a sub-tag (non-private): Both get exported.
3. Try to exclude the parent directory via "Export preferences > omit hierarchy": Both echelons are still exported.
4. Set the parent directory as a category (but not even as private): None of both tags get exported.

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

GitHub nightly

### darktable version

5.5.0+325~g35a0cbe5dd

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by zisoft**
Wrongly handled flag comparison causes tag categories being recursively not exported, regardless of the private setting.

fixes #20368

No additional release notes entry required.

### CODE REVIEW

File: src/common/tags.c [hunk 1]
```diff
@@ -1032,7 +1032,7 @@ static gboolean _check_private_recursive(dt_tag_t *t)
       if(tagid != 0)
       {
         gint flags = dt_tag_get_flags(tagid);
```
Comment (TurboGit) [inline src/common/tags.c]: As we are at it, could be const. TIA.

Comment (zisoft) [reply src/common/tags.c]: Done
