### PR TITLE
Windows: remove incorrect Atom detection & revised performance configuration

### LINKED ISSUE #11981: missing translation option in range selection
eve the term "now" is translated in the po file it's not translated in the GUI:
image

translation properly used in date selection dialog:
image

**Platform**
* darktable version : darktable-3.9.0+1690~g04eabd0e9
* OS                : OSx

### PR DESCRIPTION
**Pull request by peterbud**
This PR contains two changes:
* Windows: remove incorrect Atom detection - Fixes #11981
* Add more robust performance configuration 
So far performance configuration run only once on a naive machine, running darktable for the very first time. This change enables running performance configurations again when we see necessary by bumping DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION. Also different performance configurations are better documented, and more structured.

Please help reviewing whether performance configuration is well balanced (ie we don't limit powerful machines/configurations with sub-optimal settings), and also whether additional settings might be needed to be added to performance config.

### CODE REVIEW

File: src/common/darktable.c [hunk 1]
```diff
@@ -1161,37 +1165,78 @@ void dt_show_times(const dt_times_t *start, const char *prefix, const char *suff
...
-    dt_conf_set_int("host_memory_limit", mem >> 11);
+
+    if(dt_conf_get_int("worker_threads") < 8) dt_conf_set_int("worker_threads", 8);
+
+    // if machine has at least 8GB RAM, use half of the total memory size
+    if(dt_conf_get_int("host_memory_limit") < (mem >> 11)) dt_conf_set_int("host_memory_limit", mem >> 11);
+
+    if(dt_conf_get_int("singlebuffer_limit") < 16) dt_conf_set_int("singlebuffer_limit", 16);
+
+    if(!strcmp(dt_conf_get_string("plugins/darkroom/demosaic/quality"), "always bilinear (fast)"))
```
Comment (houz) [inline src/common/darktable.c]: The result of `dt_conf_get_string()` needs to be `g_free()`ed.

File: src/common/darktable.c [hunk 2]
```diff
@@ -1161,37 +1165,78 @@ void dt_show_times(const dt_times_t *start, const char *prefix, const char *suff
...
     fprintf(stderr, "[defaults] setting high quality defaults\n");
-    dt_conf_set_int("worker_threads", 8);
+
+    if(dt_conf_get_int("worker_threads") < 8) dt_conf_set_int("worker_threads", 8);
+
+    if(dt_conf_get_int("host_memory_limit") < 1500) dt_conf_set_int("host_memory_limit", 1500);
+
+    if(dt_conf_get_int("singlebuffer_limit") < 16) dt_conf_set_int("singlebuffer_limit", 16);
+
+    if(!strcmp(dt_conf_get_string("plugins/darkroom/demosaic/quality"), "always bilinear (fast)"))
```
Comment (houz) [inline src/common/darktable.c]: See above, you are leaking.

Comment (peterbud) [reply src/common/darktable.c]: Rookie mistake, sorry

File: src/common/darktable.c [hunk 3]
```diff
@@ -1161,37 +1165,81 @@ void dt_show_times(const dt_times_t *start, const char *prefix, const char *suff
...
+    // But respect if user has set higher values manually earlier
     fprintf(stderr, "[defaults] setting very high quality defaults\n");
-    dt_conf_set_int("worker_threads", 8);
-    // if no less than 8Gb, half the total size
-    dt_conf_set_int("host_memory_limit", mem >> 11);
+
+    if(dt_conf_get_int("worker_threads") < 8) dt_conf_set_int("worker_threads", 8);
+
+    // if machine has at least 8GB RAM, use half of the total memory size
+    if(dt_conf_get_int("host_memory_limit") < (mem >> 11)) dt_conf_set_int("host_memory_limit", mem >> 11);
```
[the remark this answers is not in the document]
Comment (peterbud) [reply src/common/darktable.c]: OK, thank you!

**Comment by peterbud** [comment]
According to IRC, I have made additional changes: mainly enabling the user to decide whether he/she would like to run this performance tuning or not. Also added the suggestions fro @LebedevRI .

What bothers me is that at the very first run after a new install we should not present this dialog (but simply silently configure as before), but currently this check will prevent showing the dialog even for existing installs, as I cannot decide whether it is really the very first run after a new install, or just a new version installed over an existing one where this code is being introduced. Maybe I could use `dt_conf_init()` to figure out and return whether there was no darktablerc at all (meaning really a new install) and act accordingly?

File: src/control/conf.h [hunk 4]
```diff
@@ -250,7 +250,6 @@ static inline void dt_conf_init(dt_conf_t *cf, const char *filename, GSList *ove
     }
     fclose(f);
   }
-  if(defaults) dt_configure_defaults();
```
Comment (houz) [inline src/control/conf.h]: If you leave this in you shouldn't have the problem of figuring out if it's a new configuration or an old one lacking the setting.

Comment (peterbud) [reply src/control/conf.h]: OK, makes sense. Let me restructure

File: src/common/darktable.c [hunk 5]
```diff
@@ -770,6 +770,30 @@ int dt_init(int argc, char *argv[], const gboolean init_gui, const gboolean load
     gtk_init(&argc, &argv);
   }
 
+  // execute a performance check and configuration if needed
+  int last_configure_version = dt_conf_get_int("performance_configuration_version_completed");
+  if(last_configure_version < DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION)
+  {
+    // if this is the very first time -> run this configuration unconditionally
```
Comment (houz) [inline src/common/darktable.c]: The comment is no longer true. And you don't need to initialize the variable either. scan-build will complain about that.

File: src/common/darktable.c [hunk 6]
```diff
@@ -770,6 +770,30 @@ int dt_init(int argc, char *argv[], const gboolean init_gui, const gboolean load
...
+    bool run_configure = TRUE;
+
+    // ask the user whether he/she would like
+    // dt to make changes in the settings
+    char *label_text = g_markup_printf_escaped(
+        _("We have an updated performance configuration logic - executing that might improve the "
```
Comment (houz) [inline src/common/darktable.c]: Some typos in that string. Fixed version:

> We have an updated performance configuration logic - executing that might improve the performance of darktable.\nThis will potentially overwrite some of your existing settings - especially in case you have manually modified them to custom values.\nWould you like to execute this update of the performance configuration?\n

File: src/common/darktable.c [hunk 7]
```diff
@@ -770,6 +770,30 @@ int dt_init(int argc, char *argv[], const gboolean init_gui, const gboolean load
...
+  // execute a performance check and configuration if needed
+  int last_configure_version = dt_conf_get_int("performance_configuration_version_completed");
+  if(last_configure_version < DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION)
+  {
+    // if this is the very first time -> run this configuration unconditionally
+    bool run_configure = TRUE;
+
+    // ask the user whether he/she would like
+    // dt to make changes in the settings
+    char *label_text = g_markup_printf_escaped(
```
Comment (houz) [inline src/common/darktable.c]: No need for `g_markup_printf_escaped`, you don't use markup in the string. Just pass `_("...")` to `dt_gui_show_standalone_yes_no_dialog()` instead of `label_text`.
