### PR TITLE
metadata: proper search on double list

### LINKED ISSUE #7780: Segfault on importing image
I see there's a couple of these "crash on import" bug reports, but couldn't find one with this backtrace. #6660 might be related, but it's closed and the last comment says it's most likely fixed in 3.4.0, which it isn't if this is the same bug.

**Describe the bug**

Importing a bunch of old images, edited with older versions (possibly dev) cause darktable to crash.

**To Reproduce**

I've narrowed it down to one problematic image which when you import it via Import/Image will *always* crash darktable. The stacktrace indicates that the xmp exif parsing is at fault, so I'm attaching the xmp file:

[DSC_1932_10.NEF.xmp.tar.gz](https://github.com/darktable-org/darktable/files/5792863/DSC_1932_10.NEF.xmp.tar.gz)

**Expected behavior**

Don't crash.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0 (package version 3.4.0-13.2 installed from the OBS tumbleweed repo)
 - OS: opensuse tumbleweed
- OpenCL: disabled/not available
 - Graphics: AMD R9 290, open source amdgpu

I can upload the coredump if that helps.

Backtrace:
```
#0  _metadata_remove_metadata_from_list (metadata=0x555556b10980 = {...}, list=0x555555dc1fa0) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/metadata.c:511
#1  _metadata_execute(GList const*, GList const*, GList**, gboolean, gint) (imgs=imgs@entry=0x555556b69140 = {...}, metadata=metadata@entry=0x555556b10980 = {...}, undo=undo@entry=0x7fffffff9d00, undo_on=undo_on@entry=0, action=action@entry=2)
    at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/metadata.c:547
#2  0x00007ffff7c8e876 in dt_metadata_clear(GList const*, gboolean) (imgs=0x555556b69140 = {...}, undo_on=0) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/metadata.c:708
#3  0x00007ffff7c324e5 in _exif_decode_xmp_data(dt_image_t*, Exiv2::XmpData&, int, bool) (img=0x5555579d7880, xmpData=..., version=4, exif_read=<optimized out>) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/exif.cc:437
#4  0x00007ffff7c3e449 in dt_exif_xmp_read(dt_image_t*, char const*, int) (img=0x5555579d7880, filename=0x55555837b870 "/tmp/test/DSC_1932_10.NEF.xmp", history_only=0) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/exif.cc:2758
#5  0x00007ffff7c67016 in _image_read_duplicates(uint32_t, char const*) (id=4548, filename=filename@entry=0x555557c94450 "/tmp/test/DSC_1932.NEF") at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/image.c:1261
#6  0x00007ffff7c68173 in _image_import_internal(int32_t, char const*, gboolean, gboolean)
    (film_id=film_id@entry=57, filename=filename@entry=0x555555610670 "/tmp/test/DSC_1932.NEF", override_ignore_jpegs=override_ignore_jpegs@entry=1, lua_locking=lua_locking@entry=1) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/image.c:1338
#7  0x00007ffff7c6882a in dt_image_import(int32_t, char const*, gboolean) (film_id=film_id@entry=57, filename=filename@entry=0x555555610670 "/tmp/test/DSC_1932.NEF", override_ignore_jpegs=override_ignore_jpegs@entry=1)
    at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/common/image.c:1566
#8  0x00007fff7dd79a16 in _lib_import_single_image_callback (widget=<optimized out>, d=0x555557cdcf30) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/libs/import.c:630
#9  0x00007ffff6a102de in  () at /usr/lib64/libgobject-2.0.so.0
#10 0x00007ffff6a28a99 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff6a2900f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff703a4c0 in  () at /usr/lib64/libgtk-3.so.0
#13 0x00007ffff6a10092 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#14 0x00007ffff6a2246a in  () at /usr/lib64/libgobject-2.0.so.0
#15 0x00007ffff6a28ea9 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#16 0x00007ffff6a2900f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#17 0x00007ffff703a050 in  () at /usr/lib64/libgtk-3.so.0
#18 0x00007ffff72ece2b in  () at /usr/lib64/libgtk-3.so.0
#19 0x00007ffff6a102de in  () at /usr/lib64/libgobject-2.0.so.0
#20 0x00007ffff6a28a99 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#21 0x00007ffff6a2900f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#22 0x00007ffff7103bb4 in  () at /usr/lib64/libgtk-3.so.0
#23 0x00007ffff6a13390 in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib64/libgobject-2.0.so.0
#24 0x00007ffff6a102de in  () at /usr/lib64/libgobject-2.0.so.0
#25 0x00007ffff6a28a99 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#26 0x00007ffff6a2900f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#27 0x00007ffff70fd007 in  () at /usr/lib64/libgtk-3.so.0
#28 0x00007ffff71051ab in  () at /usr/lib64/libgtk-3.so.0
#29 0x00007ffff7105b1f in  () at /usr/lib64/libgtk-3.so.0
#30 0x00007ffff70c362c in gtk_event_controller_handle_event () at /usr/lib64/libgtk-3.so.0
#31 0x00007ffff729bf4d in  () at /usr/lib64/libgtk-3.so.0
#32 0x00007ffff72e3068 in  () at /usr/lib64/libgtk-3.so.0
#33 0x00007ffff6a102de in  () at /usr/lib64/libgobject-2.0.so.0
#34 0x00007ffff6a2820b in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#35 0x00007ffff6a2900f in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#36 0x00007ffff72aa414 in  () at /usr/lib64/libgtk-3.so.0
#37 0x00007ffff714e710 in  () at /usr/lib64/libgtk-3.so.0
#38 0x00007ffff714f9cb in gtk_main_do_event () at /usr/lib64/libgtk-3.so.0
#39 0x00007ffff6e32013 in  () at /usr/lib64/libgdk-3.so.0
#40 0x00007ffff6e68e02 in  () at /usr/lib64/libgdk-3.so.0
#41 0x00007ffff76f4e57 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#42 0x00007ffff76f51d8 in  () at /usr/lib64/libglib-2.0.so.0
#43 0x00007ffff76f54cb in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#44 0x00007ffff714cbfd in gtk_main () at /usr/lib64/libgtk-3.so.0
#45 0x00007ffff7de5bbd in dt_gui_gtk_run(dt_gui_gtk_t*) (gui=<optimized out>) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/gui/gtk.c:1549
#46 0x00005555555550a2 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/darktable-3.4.0-13.2.x86_64/src/main.c:93
```

### PR DESCRIPTION
**Pull request by phweyland**
fixes #7780

metadata values equal to metadata keys (1, 2, 3,...) could make confusion on double list searches... fixed.

### CODE REVIEW

File: src/common/metadata.c [hunk 1]
```diff
@@ -191,9 +191,15 @@ typedef struct dt_undo_metadata_t
   GList *after;       // list of key/value after
 } dt_undo_metadata_t;
 
-static gboolean _compare_metadata(gconstpointer a, gconstpointer b)
+static GList *_list_find_custom(GList *list, gpointer data)
```
Comment (TurboGit) [inline src/common/metadata.c:194]: isn't the simple fix to only change:
`return g_strcmp0(a, b);`
to
`return a && b ? g_strcmp0(a, b) : FALSE;`

Maybe not, but reading the patch it seems that the proposed change is exactly equivalent exception for the check for null inside the loop below:

`   if(i->data ...)`

Comment (TurboGit) [reply src/common/metadata.c:194]: I'm my thinking is wrong, please explain and add a comment otherwise someone reading the code will certainly convert back this part as it was before.

Comment (phweyland) [reply src/common/metadata.c:194]: this is a double list: for each metadata there the id and then the value.
As long as the metadata value is not equal to one of the metadata id that works fine.
But if somebody (like for the related issue) set the title value to 1, g_list_ find finds the key instead of the value. The the list pointer is wrong...
So in the _list_find_custom loop there is 2 g_list_next to pull the key record in the comparison.

Comment (phweyland) [reply src/common/metadata.c:194]: if(i->data ...
I've added this test on the pointer because g_strcmp0 is able to return 0 if the 2 pointers are NULL.

Comment (TurboGit) [reply src/common/metadata.c:194]: Oh I see, by "double list" I understood doubly linked list but this is a list with 2 entries for each metadata and we need to skip one every two values. Now I see the double g_list_next()! Sorry, I was confused.

**Review by TurboGit — APPROVED** [review]
So good to go. Thanks.
