### PR TITLE
opencl: handle fast pipe on GPU

### LINKED ISSUE #10538: crop / rotate and perspective don't prioritise GPU
I've recently noticed a slowdown using both the _crop_ and the _rotate and perspective_ modules and it seems that these modules are processing the full and preview pixelpipes with the wrong priority.

I have my OpenCL setting set to "very fast GPU" so I would expect both pipes to be processed on the GPU and for neither to use my CPU. However, I often (not always) see the following instead, and note an asociated slowdown in processing

```
13.526286 [pixelpipe_process] [preview/fast] using device 0
13.526317 [pixelpipe_process] [full] using device -1
[lens correction] camera/lens not found
14.531432 [pixelpipe_process] [preview/fast] using device 0
14.531497 [pixelpipe_process] [full] using device -1
```

Once I close the offending module it appears to go back to using device 0 for both pipes again. Shouldn't these modules either use device 0 for both pipes or prioritise 0 for the full pipe?

### PR DESCRIPTION
**Pull request by elstoc**
Applies the correct opencl priority to fast pipe based on the pipe type (preview/2, thumbnail, full, export).

Resolves #10538

### CODE REVIEW

File: src/common/opencl.c [hunk 1]
```diff
@@ -1399,33 +1399,37 @@ int dt_opencl_lock_device(const int pipetype)
   int *priority = (int *)malloc(prio_size);
   int mandatory;
 
-  switch(pipetype)
-  {
-    case DT_DEV_PIXELPIPE_FULL:
+    if((pipetype & DT_DEV_PIXELPIPE_FULL) == DT_DEV_PIXELPIPE_FULL)
```
Comment (dterrahe) [inline src/common/opencl.c:1402]: These types of bitbucket checks are usually be simplified to just
`if(pipetype & DT_DEV_PIXELPIPE_FULL)`
same with others below.

Unless I'm mistaken? I see this pattern repeated everywhere in the code now (at least 93 times for just DT_DEV_PIXELPIPE according to grep). Is there a reason for this somehow in this case? Or just a copy/paste bonanza. Maybe a nice cleanup post release?

Anyway, good catch/bug hunt!

Comment (elstoc) [reply src/common/opencl.c:1402]: Copy paste from other code doing the same thing. I'm happy to change it if you think it's better

Comment (ralfbrown) [reply src/common/opencl.c:1402]: It looks like you could have just masked off the FAST bit in the switch:
`switch(pipetype & ~DT_DEV_PIXELPIPE_FAST)`

Comment (elstoc) [reply src/common/opencl.c:1402]: too... many... options... ;) 

@TurboGit what would you like me to do here

Comment (TurboGit) [reply src/common/opencl.c:1402]: I suppose I would go for : `switch(pipe_type & DT_DEV_PIXELPIPE_ANY) `

This will require less modifications after and will make the code easier to read.

Comment (elstoc) [reply src/common/opencl.c:1402]: ok will do

Comment (elstoc) [reply src/common/opencl.c]: done

**Review by TurboGit — APPROVED** [review]
Looks cleaner and simpler. Thanks!
