### PR TITLE
Color calibration: disable Yxy <-> XYZ roundtrip if no gamut compression is requested

### LINKED ISSUE #9076: Color Calibration Channel Mixer produces black patch
**Describe the bug/issue**
Here is a gradient created and embedded with linear rec 2020 color space, saved as 16 bit tiff.

[gradient chart l rec 2020.tif.txt](https://github.com/darktable-org/darktable/files/6554086/gradient.chart.l.rec.2020.tif.txt)

I attempt to invert colours using the channel mixer part of color calibration module, with the following settings:
CAT: 
adaptation: none (byass)
gamut compression: 0
Clip negative RGB from gamut: unticked
R: r-1, g1, b1
G: r1, g-1, b1
B: r1, g1, b-1

As we can see below, the region that was green, and becomes magenta with these color calibration settings, now has a big black patch, instead of smooth gradients.

gradient chart l rec 2020 col cal
[gradient chart l rec 2020.tif.xmp.txt](https://github.com/darktable-org/darktable/files/6554117/gradient.chart.l.rec.2020.tif.xmp.txt)

Comparably, the same settings used in the old depreciated channel mixer produce smooth gradients with no black patches, as expected:

gradient chart l rec 2020 ch mix
[gradient chart l rec 2020_01.tif .xmp.txt](https://github.com/darktable-org/darktable/files/6554135/gradient.chart.l.rec.2020_01.tif.xmp.txt)

Working profile for both is linear rec 2020, output profile is srgb. Perhaps of interest is that changing working profile does alter the shape of the black patch, but doesn't make it disappear. 

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.4.1
* OS                : MacOS 10.12.6
* Memory            : 4 GB 1600 MHz DDR3
* Graphics card     : Intel HD Graphics 4000 1536 MB & NVIDIA GeForce GT 650M
* Graphics driver   : 
* OpenCL installed  : Y
* OpenCL activated  : Y

 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 I also tried these settings on a RAW file with lots of green, and black patches became noticeable there too. Here is the RAW:
 https://discuss.pixls.us/t/sapajus-nigritus-helping-me-in-my-first-color-grading-steps/25022
 
 Some screenshots. Pay close attention to the leaf in top left corner.
 First, with everything in pipe turned off except white balance default:
col cal off

Second, with color calibration on, above settings:
col cal on

Third, with channel mixer on, above settings:
col cal off, ch mix on

### PR DESCRIPTION
**Pull request by aurelienpierre**
The conversion to Yxy will produce division by zero and all sorts of oddities if colors are out of gamut, even when no clipping and no gamut compression are required. In that case, we entirely remove the roundtrip, leaving only the channel mixing.

Notice it will fix the black pixels but will still result in RGB clipping at some point, meaning wrong colors anyway.

fix #9076

### CODE REVIEW

File: src/iop/channelmixerrgb.c [hunk 1]
```diff
@@ -747,7 +749,10 @@ static inline void loop_switch(const float *const restrict in, float *const rest
     /* FROM HERE WE ARE MANDATORILY IN XYZ - DATA IS IN temp_one */
 
     // Gamut mapping happens in XYZ space no matter what
-    gamut_mapping(temp_one, gamut, clip, temp_two);
+    if(do_gamut_mapping)
+      gamut_mapping(temp_one, gamut, clip, temp_two);
+    else
+      for(size_t c = 0; c < 3; ++c) temp_two[c] = temp_one[c];
```
Comment (ralfbrown) [inline src/iop/channelmixerrgb.c:755]: Why not use `for_each_channel`, or even more succinctly, `copy_pixel(temp_two,temp_one)`?  Copying three elements won't vectorize.

Comment (aurelienpierre) [reply src/iop/channelmixerrgb.c:755]: because we are already in a SIMD loop, and one of the compilers will fail on nesting SIMD loops inside SIMD loops.

Comment (ralfbrown) [reply src/iop/channelmixerrgb.c:755]: Gotcha.  In that case, I would recommend using DT_PIXEL_SIMD_CHANNELS instead of 3, which is what `for_each_channel` uses internally.

Comment (aurelienpierre) [reply src/iop/channelmixerrgb.c]: Done

**Review by TurboGit — APPROVED** [review]
Works for me, thanks !
