### PR TITLE
geotagging: improve timezone entry

### LINKED ISSUE #9702: no way to define timezone for gpx file anymore
**Describe the bug/issue**
geotaggging using a gpx file does not work anymore, because I can't define the correct timezone.

- current timezone: Europe/Vienna (UTC+1:00) + daylight saving time -> 2 hours difference between UTC and local time
- in earlier versions of dt I could define the timezone of the gpx-file in the file-dialog-window
- the field 'camera time zone' seems to only affect the section to apply the offset, but has no effect on the 'gpx file' section

**To Reproduce**
1. open map view
2. open geotagging module
3. add gpx file
4. no matching image
5. mouseover shows no difference between localtime and UTC
(see screenshot in red)

**Screenshot**
image

**Expected behavior**
- possibility to define time zone of the gpx file

**Platform**

* darktable version : 3.6.0
* OS                : Linux
* Linux - Distro    : Manjaro
* Desktop           : gnome

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with latest master**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

### PR DESCRIPTION
**Pull request by quovadit**
fix #9702

- show indicator * as long as input field 'camera time zone' is not saved
- allow saving with tab-key and focus-out (in addition to return-key)
- show entry_completion before entering the first key (delete 'UTC')

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Looks good to me, I'll wait for @phweyland feedback who is the main maintainer of this part of dt.

File: src/libs/geotagging.c [hunk 1]
```diff
@@ -1563,9 +1564,8 @@ static gboolean _datetime_key_pressed(GtkWidget *entry, GdkEventKey *event, dt_l
   }
 }
 
-static void _timezone_save(dt_lib_module_t *self)
+static void _timezone_save(dt_lib_module_t *self, dt_lib_geotagging_t *d)
```
Comment (phweyland) [inline src/libs/geotagging.c:1567]: This change is not necessary.

File: src/libs/geotagging.c [hunk 2]
```diff
@@ -1563,9 +1564,8 @@ static gboolean _datetime_key_pressed(GtkWidget *entry, GdkEventKey *event, dt_l
...
 {
-  dt_lib_geotagging_t *d = (dt_lib_geotagging_t *)self->data;
```
Comment (phweyland) [inline src/libs/geotagging.c:1568]: idem

File: src/libs/geotagging.c [hunk 3]
```diff
@@ -1579,33 +1579,43 @@ static void _timezone_save(dt_lib_module_t *self)
...
+    case GDK_KEY_Tab:
+      _timezone_save(self, d);
       return TRUE;
     case GDK_KEY_Escape:
       gtk_window_set_focus(GTK_WINDOW(dt_ui_main_window(darktable.gui->ui)), NULL);
       return TRUE;
-    case GDK_KEY_Tab:
-      return TRUE;
     default:
+      gtk_label_set_text(GTK_LABEL (d->timezone_changed), "* ");
```
Comment (phweyland) [inline src/libs/geotagging.c:1606]: Why the extra space ?
Alignment should be treated in CSS.

**Review by phweyland — CHANGES_REQUESTED** [review]
Taking in account the Tab key is welcome. :+1: 

I would prefer to have the "\*" close to the entry field.
There is also some flicker on the alignment with the above lines when the "\*" appears or disappears. Have you tried to put it after the entry ? And maybe with a constant width.

**Comment by phweyland** [comment]
Would be also great to update the "timezone" tooltip to describe the new behavior ("\*" and necessity to hit enter).

File: src/libs/geotagging.c (hunk 1 above)
Comment (quovadit) [reply src/libs/geotagging.c]: done

File: src/libs/geotagging.c (hunk 2 above)
Comment (quovadit) [reply src/libs/geotagging.c]: done

File: src/libs/geotagging.c (hunk 3 above)
Comment (quovadit) [reply src/libs/geotagging.c]: I tried css, but then there is also a space if no * is shown, so I kept the space

**Comment by quovadit** [comment]
I fixed the coding issues, added a tooltip, moved the asterisk after the entry, and removed the flickering.

**Comment by phweyland** [comment]
I get a compilation error (the same as travis one):
```
/home/philippe/git/dt/src/libs/geotagging.c: In function ‘_timezone_key_pressed’:
/home/philippe/git/dt/src/libs/geotagging.c:1601:7: error: a label can only be part of a statement and a declaration is not a statement
 1601 |       dt_lib_geotagging_t *d = (dt_lib_geotagging_t *)self->data;
      |       ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

**Comment by quovadit** [comment]
sorry, a label is not allowed to appear immediately before a declaration (for whatever reason...)
Hopefully this commit fixes it, it's just an empty statement after the label

**Comment by phweyland** [comment]
> a label is not allowed to appear immediately before a declaration (for whatever reason...)
> Hopefully this commit fixes it, it's just an empty statement after the label

A bit strange, yes.
Another way to solve this is to use brackets {}.

That works for me. Thanks.

**Review by phweyland — APPROVED** [review]

File: src/libs/geotagging.c [hunk 4]
```diff
@@ -1583,25 +1591,26 @@ static gboolean _timezone_key_pressed(GtkWidget *entry, GdkEventKey *event, dt_l
...
       return TRUE;
     case GDK_KEY_Escape:
       gtk_window_set_focus(GTK_WINDOW(dt_ui_main_window(darktable.gui->ui)), NULL);
       return TRUE;
-    case GDK_KEY_Tab:
-      return TRUE;
-    default:
+    default: ;
+      dt_lib_geotagging_t *d = (dt_lib_geotagging_t *)self->data;
+      gtk_label_set_text(GTK_LABEL (d->timezone_changed), " *");
```
Comment (johnny-bit) [inline src/libs/geotagging.c:1602]:
```suggestion
    default:
      {
        dt_lib_geotagging_t *d = (dt_lib_geotagging_t *)self->data;
        gtk_label_set_text(GTK_LABEL (d->timezone_changed), " *");
      }
```

would imo look better than lone `;` but that's my 2c ;)

**Comment by TurboGit** [comment]
Something strange... When I start dt I have (see on the right the what looks like HTTP headers:

image

On anly after selecting the entry "`europe/paris`" and selecting a picture the display is reset properly.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Some weird output!

**Comment by quovadit** [comment]
fixed weird output with languages other than english.

File: src/libs/geotagging.c (hunk 4 above)
Comment (phweyland) [reply src/libs/geotagging.c:1602]: This is cleaner indeed !
Please do the change if you don't mind.

**Review by TurboGit — APPROVED** [review]
Looks good to me now, thanks !
