### PR TITLE
Again work on pixelpipe cache ( #14291)

### LINKED ISSUE #14291: color calibration auto-detect WB bad interaction with pixpipe cache
### Describe the bug

If selecting one of the "AI" auto-detect choices in the "illuminant" dropdown for color calibration, the module needs to run on the "full" pipe to compute the new white balance.  But with pixelpipe caching, it doesn't actually do so in many cases, so it either has no effect or produces a black image as in #12382.

### Steps to reproduce

For a black image:
1. open an image in darkroom and choose one of the "AI" auto-detect options in color calibration.
2. reset the module
3. switch to lighttable view and back to darkroom
4. choose the same auto-detect option again

### Expected behavior

The auto-detect code should be run and produce a valid white balance.

### Logfile | Screenshot | Screencast

_No response_

### Commit

This has probably been around since color calibration was first added, but the better caching now makes it more obvious.

### Where did you install darktable from?

self compiled

### darktable version

current master - 4.3.0+1909

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 8.1, GCC 10.4

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Invalidating the pixelpipe cache should fix this.  A faster (for the user) approach would be to have the auto-detect code run standalone, but that would require not just getting the module input from the cache but also running the pixelpipe up to that point in case of a miss.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #14291 

Another of those issues related to pixelpipe cache.
Here we change some module params (this new data is not reflected by a modified hash for the following modules in the pipe) but output of later modules in the pipe "seem" to be valid still.

In this pr

1. Some function parameter changes
2. Adding iop_order to the cache struct so we
3. A new function invalidating all cachelines with a higher iop_order. This might be very useful in other modules doing some clever stuff ...
4. Issue in channelmixer rgb auto modes should be fixed by using the new function

### CODE REVIEW

File: src/develop/pixelpipe_cache.c [hunk 1]
```diff
@@ -49,6 +49,7 @@ gboolean dt_dev_pixelpipe_cache_init(
   cache->hash = (uint64_t *)calloc(entries, sizeof(uint64_t));
   cache->used = (int32_t *)calloc(entries, sizeof(int32_t));
   cache->modname = (char **)calloc(entries, sizeof(char *));
+  cache->ioporder = (int32_t *)calloc(entries, sizeof(int32_t));
```
Comment (dterrahe) [inline src/develop/pixelpipe_cache.c:52]: Looks like it could be an array of structs, no? Not a biggie, of course.

**Comment by ralfbrown** [comment]
Spent about ten minutes fiddling with illuminant settings in color calibration, resetting the module, and switching back and forth between lighttable and darkroom views.  No more black images, but the autodetect still occasionally fails to run or appears to run but not update the color temperature.

To get a failure, which will be apparent by the on-screen message about starting the detection which isn't immediately overwritten by the message that the detection completed, the most reliable way seems to be switching back and forth between the two auto-detect setttings.  Once both fail, resetting the module or selecting a non-auto illuminant other than daylight, planckian, or custom (which keeps the current illuminant color) will usually get at least one of the two auto-detects working again for one or two iterations.

On our standard test image mire1.cr2,"by surfaces" normally sets 5002K and "by edges" normally sets 5274K.

**Review by ralfbrown — APPROVED** [review]

File: src/develop/pixelpipe_cache.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/develop/pixelpipe_cache.c:54]: yes. maybe later :-)

**Comment by jenshannoschwalm** [comment]
> but the autodetect still occasionally fails to run or appears to run but not update the color temperature

Could reproduce, we should invalidate current module iop-order too :-)

**Comment by jenshannoschwalm** [comment]
From my side
1. ready to go.
2. Tested the late report of @ralfbrown, recalculation now always works - we had to invalidate also current module's output.
3. While still being here, some unused struct declarations have been removed, they were simply misleading. All related to raster masks.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
@jenshannoschwalm : Good for me as-is.
