### PR TITLE
Ensure valid thumb->zoom_100

### LINKED ISSUE #15775: Zoom in culling mode fails
### Describe the bug

In culling layout (fixed mode) zooming and switching to the next image fails.

### Steps to reproduce

In **lighttable** select some images

capture_001_29112023_100325

Activate **culling layout (fixed mode)**

capture_003_29112023_100411

Zoom in one ore more steps (**CTRL scroll up**)

capture_004_29112023_100414

Switch to next image in selection (**Cursor-Right**)

screen now either becomes grey, shows blotches or unpredictable pixeled boxes. 

capture_005_29112023_100435

capture_006_29112023_100438

Repeated switches lead to "working..." message and heavy CPU workload

capture_007_29112023_100504

capture_008_29112023_100533

Pressing [ESC] returns to lighttable safely

### Expected behavior

show the next image in selection zoomed 

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/13498959/darktable-log.txt)

### Commit

_No response_

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.5.0+1328~g0b2d4ade8e

### What OS are you using?

Windows

### What is the version of your OS?

Microsoft Windows 10 Pro, Version	10.0.19045 Build 19045

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Occurs with or without using OpenCL / GPU, logfile is without OpenCL

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
In a few cornercases the calculation of thumb->zoom_100 fails. We can assume this to be valid only if we have valid thumb->img_width > 0. (same fore height)

As we keep a thumbs zoom_100 for it's lifetime we don't write it so it will be updated if valid data are present.

Fixes #15775 

and see for a reproducer.

### CODE REVIEW

File: src/dtgtk/thumbnail.c [hunk 1]
```diff
@@ -695,8 +695,14 @@ static gboolean _event_image_draw(GtkWidget *widget,
       cairo_surface_t *img_surf = NULL;
       if(thumb->zoomable)
       {
-        if(thumb->zoom > 1.0f)
-          thumb->zoom = MIN(thumb->zoom, dt_thumbnail_get_zoom100(thumb));
+        const float zoom100 = dt_thumbnail_get_zoom100(thumb);
+        // Any zoom100 > 1 is ensured to be correct
+
+//        dt_print(DT_DEBUG_LIGHTTABLE, "zoomable event draw zoom=%f, zoom100=%f, image %ix%i\n",
```
Comment (TurboGit) [inline src/dtgtk/thumbnail.c:701]: Probable to be removed, no? Or uncomment as it is under a debug swicth?

**Comment by jenshannoschwalm** [comment]
Force-pushed squashed commit
