### PR TITLE
Ensure supported OpenCL device version

### LINKED ISSUE #14731: Darktable crash at startup windows 11
### Describe the bug

I have installed darktable on windows 11 but when I try to run it it crash at startup.

it seems an issue with opencl becasue the program correctly run when i run directly the darktable.exe file from the cmd with the option --disable-opencl.

The output of the darktable-cltest.exe is the belowe one:

can you please help me in understand how to solve my issue?
Thanks in advance

```
C:\Program Files\darktable\bin>darktable-cltest.exe
[dt_get_sysresource_level] switched to 1 as `default'
  total mem:       32614MB
  mipmap cache:    4076MB
  available mem:   16307MB
  singlebuff:      254MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: OFF
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
[opencl_init] found 3 platforms
[opencl_init] found 5 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'NVIDIA GeForce GTX 1660 Ti'
   CANONICAL NAME:           nvidiageforcegtx1660ti
   PLATFORM NAME & VENDOR:   NVIDIA CUDA, NVIDIA Corporation
   DRIVER VERSION:           535.98
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          6144 MB
   MAX MEM ALLOC:            1536 MB
   MAX IMAGE SIZE:           32768 x 32768
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         C:\Program Files\darktable\share\darktable\kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   KERNEL LOADING TIME:       0.0438 sec

[dt_opencl_device_init]
   DEVICE:                   1: 'Intel(R) UHD Graphics 630', NEW
   CANONICAL NAME:           intelruhdgraphics630
   PLATFORM NAME & VENDOR:   Intel(R) OpenCL HD Graphics, Intel(R) Corporation
   DRIVER VERSION:           31.0.101.2111
   DEVICE VERSION:           OpenCL 3.0 NEO
   DEVICE_TYPE:              GPU
   *** new device is blacklisted ***

[dt_opencl_device_init]
   DEVICE:                   2: 'Intel(R) UHD Graphics 630'
   CANONICAL NAME:           intelruhdgraphics630
   PLATFORM NAME & VENDOR:   OpenCLOn12, Microsoft
   DRIVER VERSION:           1.1.0
   DEVICE VERSION:           OpenCL 1.2 D3D12 Implementation
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          16307 MB
   MAX MEM ALLOC:            1024 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   *** marked as disabled ***

[dt_opencl_device_init]
   DEVICE:                   3: 'NVIDIA GeForce GTX 1660 Ti'
   CANONICAL NAME:           nvidiageforcegtx1660ti
   PLATFORM NAME & VENDOR:   OpenCLOn12, Microsoft
   DRIVER VERSION:           1.1.0
   DEVICE VERSION:           OpenCL 1.2 D3D12 Implementation
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          5979 MB
   MAX MEM ALLOC:            1024 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         C:\Program Files\darktable\share\darktable\kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
3.369635 [opencl_fopen_stat] could not open file `C:\Users\della\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_NVIDIAGeForceGTX1660Ti_110\blendop.cl.bin.2b7e5266aa3a85724bf666e26fd07e41'!
3.370027 [opencl_load_program] could not load cached binary program, trying to compile source

```

### Steps to reproduce

the issue happens every time I run darktable in my pc with windows 11

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/11793552/darktable-log.txt)

### Commit

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
We didn't check for unsupported device versions 1.0 and 1.1, (wasn't even aware that versions still might be around)

Devices with 1.0 or 1.1 OpenCL version must be rejected.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Would be for 4.4.1 & 4.6

File: src/common/opencl.c [hunk 1]
```diff
@@ -735,6 +735,25 @@ static gboolean _opencl_device_init(dt_opencl_t *cl,
...
+  if(strlen(deviceversion) < 9)
+  {
+     dt_print_nts(DT_DEBUG_OPENCL,
+                 "   *** no proper device version ***\n");
+    res = TRUE;
+    goto end;
+  }
+  else
+  {
+    if((strncmp(deviceversion+7, "1.0", 3) == 0)
```
Comment (TurboGit) [inline src/common/opencl.c:747]: Are we safe trying to skip OpenCL prefix here (+7)? It seems very fragile and will break as soon as some new format is used. Aslo isn't the deviceversion here "OpenCL 3.0 CUDA" and not the OpenCL C API version, clinfo gives me:
```

  Device Version                                  OpenCL 3.0 CUDA
  Device OpenCL C Version                         OpenCL C 1.2 
```

Comment (jenshannoschwalm) [reply src/common/opencl.c:747]: We are safe as the OpenCL docs define the first 7 chars to be constant. Also safe for introducing new version as we only check for <1.2

As this is definitely a corner case I have no problem with not merging at all.

Comment (TurboGit) [reply src/common/opencl.c:747]: Thanks for clarifying the offset of 7 chars. My last question was not answered, is `deviceversion` the **"Device Version**" or the "**Device OpenCL C Version**"?

Comment (jenshannoschwalm) [reply src/common/opencl.c:747]: The spec defines the returned string to be "OpenCL" followed by one of the version id's "1.0, 1.1, 1.2, 2.0..." followed by space followed by some vendor specific stuff.

It's neither the api version nor some device-hardware version but reflects the supported opencl version.

So if we would bump the api to 2.0 we would have to exclude "1.2" too.

**Comment by jenshannoschwalm** [comment]
Release note: Make sure OpenCL devices report at least v1. 2 support

**Comment by TurboGit** [comment]
Thanks!
