### PR TITLE
Bugfix and refactor xmp writing tests

### LINKED ISSUE #13870: copy and import wrongly creates XMPs for JPGs, disregarding the config setting to create XMPs only 'after edits'
**Did you buy darktable from an application store ?**
No. On Debian 11 I built dt myself from Master. On intel iMac, I'm using 4.2.1 from the Apple binary.

**Describe the bug/issue**
I use Fuji cameras, and shoot RAW+JPG. I’ve not previously used dt’s ‘copy and import’ to import files. I've just been trying it on both my systems to import direct from SD with directory and file naming patterns set. I was surprised to see that dt always creates an XMP for the JPGs (but not the RAWs), disregarding the config setting create XMPs only ‘after edits’.

**To Reproduce**

1. Set Settings>Storage>XMP to 'after edits'.
2. Adjust Settings>Import naming patterns as required
3. Mount SD card from camera, and run 'copy and import' 
4. Open destination directory where pictures have been stored.
5. See RAW files without XMPs, but XMPs created for all JPEGs.

**Expected behavior**
No XMP files created for any picture files.

**Platform**

1. Current stable dt release for intel macOS. Intel Core i5 Mac running Ventura 13.12.1. 16Gb RAM. Radeon Pro 555 2 GB graphics card.

2. Current dt Master built as per the instructions for Debian install on GitHub, using the script provided. Dell Inspiron 3521  (Intel Pentium) with 8Gb RAM, running Debian 11 (Gnome Desktop). No graphics card. No OpenCL.

**Additional context**
 
Exactly the same behaviour on both systems, regardless of camera model.

 - Do you use lua scripts?
 No

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #13870

Investigated above issue, an easier way to reproduce (also a more common use case):

1. Select "after edit" in UI's "write sidecar for each image"
2. Import some raws and jpegs
3. close dt and check for possibly written sidecars (there should be none)
4. open dt and remove those images from the database
5. close dt and check for written sidecars again
6. You will find written sidecars for non-raws which is wrong.

Central fix is in `gboolean dt_image_write_sidecar_file(const int32_t imgid)`

- now returns a gboolean, TRUE if no sidecar was written
- it properly checks if xmp writing mode is DT_WRITE_XMP_NEVER OR writing mode is DT_WRITE_XMP_LAZY **and** image is un-altered
- in both cases xmp files are **not** written

Add DT_HISTORY_HASH_NONE to dt_history_hash_t
image ids should always be int32_t

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Release note:
Avoid xmp writing if not requested and image was not altered

File: src/views/darkroom.c [hunk 1]
```diff
@@ -947,18 +947,15 @@ static void _dev_change_image(dt_develop_t *dev, const int32_t imgid)
   // commit image ops to db
   dt_dev_write_history(dev);
 
+  const int32_t devid = dev->image_storage.id;
```
Comment (TurboGit) [inline src/views/darkroom.c:950]: as `devid` is used for OpenCL device I strongly suggest to use `devimgid` or something similar.

File: src/views/darkroom.c [hunk 2]
```diff
@@ -3239,6 +3236,8 @@ void leave(dt_view_t *self)
...
```
Comment (TurboGit) [inline src/views/darkroom.c:3239]: likewise

File: src/views/darkroom.c [hunk 3]
```diff
@@ -947,18 +947,15 @@ static void _dev_change_image(dt_develop_t *dev, const int32_t imgid)
...
-  if(!dt_history_hash_is_mipmap_synced(dev->image_storage.id))
+  if(!dt_history_hash_is_mipmap_synced(devid))
   {
-    const dt_history_hash_t hash_status = dt_history_hash_get_status(dev->image_storage.id);
-
-    dt_mipmap_cache_remove(darktable.mipmap_cache, dev->image_storage.id);
-    dt_image_update_final_size(dev->image_storage.id);
-    const gboolean fresh = (hash_status == DT_HISTORY_HASH_BASIC) || (hash_status == DT_HISTORY_HASH_AUTO);
-    const dt_imageio_write_xmp_t xmp_mode = dt_image_get_xmp_mode();
-    if((xmp_mode == DT_WRITE_XMP_ALWAYS) || ((xmp_mode == DT_WRITE_XMP_LAZY) && !fresh))
```
Comment (TurboGit) [inline src/views/darkroom.c:959]: I cannot see where this complex check using DT_WRITE_XMP_ALWAYS, DT_WRITE_XMP_LAZY, DT_HISTORY_HASH_BASIC & DT_HISTORY_HASH_AUTO is now done. Can you give me some hint for the review? TIA.

**Review by TurboGit — COMMENTED** [review]
First review on this tricky stuff.

File: src/views/darkroom.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/views/darkroom.c]: right and done

File: src/views/darkroom.c (hunk 2 above)
Comment (jenshannoschwalm) [reply src/views/darkroom.c]: right and done

File: src/views/darkroom.c (hunk 3 above)
Comment (jenshannoschwalm) [reply src/views/darkroom.c:959]: It's all in done in `dt_image_write_sidecar_file(const int32_t imgid)`

Basically we trust all image developing to set the `DT_HISTORY_HASH_CURRENT` bit flag so `dt_image_altered()` returns a TRUE. From my understanding of the codebase this is the intended functionality of that function (also my tests here did not show problems) so we can avoid the "complicated" tests.

**Review by TurboGit — APPROVED** [review]
Thanks!

File: src/common/image.c [hunk 4]
```diff
@@ -2699,68 +2699,79 @@ int dt_image_local_copy_reset(const int32_t imgid)
...
+
+    //  nothing to do, the original is not accessible and there is no local copy
+    if(!from_cache)
+      return TRUE;
+  }
+
+  dt_image_path_append_version(imgid, filename, sizeof(filename));
+  g_strlcat(filename, ".xmp", sizeof(filename));
+
+  if(!dt_exif_xmp_write(imgid, filename))
```
Comment (TurboGit) [inline src/common/image.c:2734]: This is introducing a regression, to reproduce:

- Ensure that you have "write sidecar file for each image" set to "after edit" & "look for updated XMP files on startup" activated.
- Take 2 images without XMP
- Import them
- Select one and go to darkroom, do an edit (change exposure)
- Quit darktable
- Restart it

And see that the DB timestamp has not been updated with the XMP timestamp.
image

Comment (TurboGit) [reply src/common/image.c:2734]: I'll open a separate issue.
