### PR TITLE
Collect : make tags tree work like folders

### LINKED ISSUE #10799: filmic graph on quick access panel
**Describe the bug/issue**
Using the quick access panel, as set up using https://discuss.pixls.us/uploads/short-url/1b9eEypF4OMeNW3qnNpTvYZBj0t.dtpreset (https://discuss.pixls.us/t/simple-modulegroup-presets/28645 -> _simple (modern).dtpreset_), filmic's _graph_ is not updated when the sliders are manipulated, or only with a large delay.

**To Reproduce**
1. Import the simple (modern) preset from the forum page.
2. Open an image
3. Switch to the quick access panel
4. Drag the sliders

**Expected behavior**
The _graph_ is updated just like when filmic is used normally.

**Screencast**
screencast

**Platform**
* darktable version : 3.9.0+25~gc4e00c2c2
* OS                : Linux - kernel 5.13.0
* Linux - Distro    : Kubuntu 21.10
* Memory            : 64 GB
* Graphics card     : Nvidia 1060/6GB
* Graphics driver   : 470.86
* OpenCL installed  : yes
* OpenCL activated  : yes/no (does not matter)
* Xorg              : 7.7
* Desktop           : KDE
* GTK+              : 3.24.30
* CMAKE_BUILD_TYPE  : Release

### PR DESCRIPTION
**Pull request by AlicVB**
- Fixes #10799 (tag tree expansion/selection after row activation)
- Don't redraw the tree 3 times (and launch 3 sql queries) at each row activation
- Only show relevant item in the tree when one type something in the entry box

### CODE REVIEW

File: src/libs/collect.c [hunk 1]
```diff
@@ -743,141 +797,142 @@ static void tags_view(dt_lib_collect_rule_t *dr)
...
-  gtk_widget_hide(GTK_WIDGET(d->scrolledwindow));
-  gtk_widget_hide(GTK_WIDGET(d->sw2));
 
-  set_properties(dr);
+  if(d->tags_new)
+  {
+    // tree creation/recreation
+    sqlite3_stmt *stmt;
+    GtkTreeIter uncategorized, temp;
+    memset(&uncategorized, 0, sizeof(GtkTreeIter));
```
Comment (LebedevRI) [inline src/libs/collect.c]: And this one
Do you even need to zero-initialize it?

**Comment by LebedevRI** [comment]
Seems ok
