### PR TITLE
import_session: for win32 don't lower the path

### LINKED ISSUE #11188: Import changes case of path which leads to duplicate directory entries in collection (Win 10)
**Describe the bug/issue**
I managed to get multiple entries for the same directory in the collection module by importing, copy&import and searching filmroll directory. It seems that (not 100% sure)
- search filmroll takes the upper/lower case from the file dialog
- copy & import converts the path to all lowercase

**To Reproduce**
Copy some file to a directory with a mixed case name
import them from that directory
search the filmroll in that directory
Copy & import a bunch of photos from an other location into that same directory

**Expected behavior**
In the collections module, set to "directory view" you have only one directory (preferable with the mixed case naming)

**Actual behaviour**
There are multiple entries with different case for one directory

**Screenshots**
grafik

For the copy&import I used the following pattern:
grafik

**Which commit introduced the error**
Noticed this behavior with the official 3.8.1 and could reproduce it with the 3.9.0 6d18168b1
At least the convert to lowercase came with 6f072ee

**Platform**

* darktable version : 3.9.0 6d18168b1
* OS                : Windows 10 21H1

**Additional context**
When I find some time I'll do more research about this problem. If someone has some hints where to look please let me know 😉

### PR DESCRIPTION
**Pull request by phweyland**
attempt to fix #11188

I don't see the necessity to lower the path case, even for windows. So I've removed this part.

Not tested on windows. That would be great if a windows user could test it. TIA.

### CODE REVIEW

**Comment by Mark-64** [comment]
Converting to lowercase was meant to fix #10244, so I am afraid this will cause regressions.
I will tests it in the coming days as soos as I have some time

**Comment by phweyland** [comment]
> Converting to lowercase was meant to fix #10244, so I am afraid this will cause regressions.

Thanks for the inputs.
You may be right, but this is not good neither, because everything is forced to be lower case.
I think the solution should be to follow the existing case if any, or the calculated one otherwise (not to create different version in the db).
I'll take in account this.

**Review by ChristianBirzer — APPROVED** [review]
The copy&import now takes the upper/lower case like it is on the file system.
Tested on Win10 with mixed case paths
.
The add to library, copy&import and search filmroll all behave the same now and there is no more mix up with paths converted to lowercase.

**Comment by phweyland** [comment]
The last commit should (not tested) recognize an existing windows folder even if the case is different.
That's not enough. I still have to use the existing path instead of the new one (for windows), to have in dt memory only the existing one (collect, ...).
@Mark-64 , do you think that, with the last point done, the different issues you mention should be covered ? Do I miss something ? Thanks

**Comment by phweyland** [comment]
Cannot test this on windows. Take this with a lot of salt.
But test and feedback are welcome.

File: src/common/film.c [hunk 1]
```diff
@@ -90,7 +90,11 @@ int32_t dt_film_get_id(const char *folder)
   int32_t filmroll_id = -1;
   sqlite3_stmt *stmt;
   DT_DEBUG_SQLITE3_PREPARE_V2(dt_database_get(darktable.db),
+#ifdef _WIN32
+                              "SELECT id FROM main.film_rolls WHERE folder LIKE ?1",
```
Comment (TurboGit) [inline src/common/film.c:94]: LIKE is case sensitive, so why it is needed as it seems equivalent to the "=" just below, no?

Comment (TurboGit) [reply src/common/film.c:94]: Oh, no LIKE is no case  sensitive. To avoid LIKE (maybe slower) we also could use:

`... WHERE folder = ?1 COLLATE NOCASE`

Comment (TurboGit) [reply src/common/film.c:94]: But then, we may also some similar fixes for `filename`? All in all I fear this is opening a can of worms :(

Comment (phweyland) [reply src/common/film.c:94]: I don't know what is faster. If there is a place where performance is critical it's in collection for example (a lot of LIKEs there) but film_roll recognition is not as critical (in import_session variables' pathname is even evaluated 3 times...).

> But then, we may also some similar fixes for filename?

I think filename works as it is because of the mechanism which tests if the file already exists and increments the index if necessary (here linix and windows answer differently but consistently).
With film_roll on the contrary we have to reuse it if already exists.

> All in all I fear this is opening a can of worms :(

Agreed, especially on collect side. See #11288 for example. But if we can afford some issues in collect, import is more critical as it can feed inconsistencies into the db.

**Comment by ChristianBirzer** [comment]
Hi, I'm currently doing some more tests.
What I did test so far looks good, with one small exception (But I'm not sure if it is worth to fix at all):

When you have two import session with different job names (resulting in different film rolls) and the case of the path to that film roll will differ, than there are also two different cases in the database.

Example:
Copy & import images using a base directory naming pattern in lowercase with a job name "Test 1":
grafik
Then copy&import to the same base directory but change its name to mixed case and change the job name to "Test 2":
grafik
This will lead to two film rolls (of course because two different job names) that are in the same directory but with different cases:
grafik
grafik

But I know this is a very ugly way to use this. I wouldn't expect this to be a problem in real world usage. Therefore personally, I wouldn't change it (I guess you would have to split the import filmroll name into peaces and match each with existing case insensitive....)

I will do more tests and report if I find something of more importance ;-)

BTW: Thank you very much for your work! It's great 👍

**Comment by phweyland** [comment]
Thanks for testing.
In your example above, the actual folder `bilder zum testen` is unique on your disk, right ?
If so, there may be a simple way to get it right: get the real path after creation of the folder. I'll check this.

**Comment by phweyland** [comment]
If travis stays happy, based on your last use case, I get the actual path of the folder before creating the film_roll.
I've also reverted the last commit which became useless.
Hoping the returned path is consistent with the one it replaces (// and all the stuff).
If that doesn't work I try to trace if there is any difference (other than case).

**Comment by ChristianBirzer** [comment]
Just did a very very quick test and noticed that I cannot import any photos using the copy&import function anymore.
Get the message "requested session path not available. device not mounted?" and "0 images imported".
Using commit 086f93aa
When debugging into your changes, I see that the _import_session_initialize_filmroll is called twice when importing one image.
The first call uses the current date for the placeholders ($EXIF.YEAR etc. is used in the import dialog). This folder does not exists and therefor path is 0x0 after the g_strdup(g_dir_read_name).
Then the function is called again with the date from the exif of the imported image.
This time, path seems to be correct in line 81 for ghe g_dir_open("F:\\temp\\bilder zum testen\\2020\\2021-05-01 Test 1") but after the g_strdup(g_dir_read_name(cdir)) path is "PK1_4908.DNG" which is a file that is already in the target path (not the selected source path).
I guess, the dir_read_name doesn't return the name of the directory but the next entry in that.?

**Comment by phweyland** [comment]
> I guess, the dir_read_name doesn't return the name of the directory but the next entry in that.?

I guess you are right. I've read the doc too fast ... I'll try again.

**Comment by phweyland** [comment]
Another attempt. Could work better.

> The first call uses the current date for the placeholders ($EXIF.YEAR etc. is used in the import dialog). This folder does not exists and therefor path is 0x0 after the g_strdup(g_dir_read_name).

I've seen there are several calls on the same init, but this sounds strange for me. Just before trying to get the actual path we hav e g_mkdir_with_parents() which should create if it doesn't exist, shouldn't it ?

**Comment by ChristianBirzer** [comment]
Hmmm. The import works again now. Thanks for that. But I'm sorry to say that the case issue is back again. This time a bit stranger.
When I import 1 image each with a base path pattern once in lower and once in mixed case, I get two rilmrolls (and two filders) in the collection with each 1 picture but when I select this folder or filmroll, both images are displayed:
grafik
grafik

Don't have the time to debug into it right now.

**Comment by phweyland** [comment]
Thanks again for testing. I'm very sorry. This attempt failed also. It seems that the returned path is the one used to create GFile and not the actual path on the disk.
So the best approach seems to be the one 2 commits before with the defect described [here](https://github.com/darktable-org/darktable/pull/11270#issuecomment-1062017678). Would you agree ?
Of course, if someone finds the way to get actual path we would consider it.

**Comment by ChristianBirzer** [comment]
> So the best approach seems to be the one 2 commits before with the defect described [here](https://github.com/darktable-org/darktable/pull/11270#issuecomment-1062017678). Would you agree ?

Yes, I think this is the best to get currently without a huge amount of work. I have to admit that changing the case in the import file pattern is nasty. Most important change is not to convert everything to lowercase but use the case that is entered. And that works fine with your changes.

If I find some time (which is rather unlikely...) I'll do some research about that.

**Comment by phweyland** [comment]
OK then. Here is what we can do for time being (hoping Ive mimicked properly 22d5764) .
Thanks so much for testing all this.

**Comment by phweyland** [comment]
@ChristianBirzer sorry to bother you again, but if you could verify that we are back to https://github.com/darktable-org/darktable/commit/22d5764c09ea66902b765229697d838249f24a2c (I haven't any windows system available at the moment), we could ask Pascal to merge this. TIA.

**Comment by ChristianBirzer** [comment]
Hi. Sorry, had this already on my todo list but was a bit out of time ☹

Just tested the latest commit and could not find any problem (except the one known but this should not happen in normal use; only when you really try hard to break it 😉)
So my opinion is: Everything is fine, import works like it should, can be merged.

I also took a look at #10244, #10232 and #10235 and could not reproduce the mentions problems with this version.
👍

**Review by TurboGit — APPROVED** [review]
Thanks for the hard work here!
