### PR TITLE
fix for build issue (#12720) with macOS sdk13

### LINKED ISSUE #12720: macOS13: build fails using macos sdk13
after upgrading macports to ventura13, upgrade to commandline tools 14.1 RC2  and completely rebuild the macports environment according to https://github.com/darktable-org/darktable/commits/master/packaging/macosx/BUILD.txt the build is done with macOS sdk13.0.

the build fails with error:
```
In file included from /Users/martinstraeten/src/darktable/src/osx/osx.mm:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:24:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:62:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/Headers/PrintCore.h:26:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/Headers/PDEPluginInterface.h:22:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/ppd.h:24:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/cups.h:27:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/ipp.h:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/http.h:39:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/netinet/ip.h:86:2: fatal error: unknown type name 'u_int'
        u_int   ip_hl:4,                /* header length */
        ^
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_heif.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_libraw.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_j2k.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/pwstorage/backend_libsecret.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/sqliteicu.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/cups_print.c.o
[ 53%] Building C object bin/CMakeFiles/lib_darktable.dir/common/printing.c.o
[ 53%] Building C object bin/CMakeFiles/lib_darktable.dir/common/printprof.c.o
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/osx/osx.mm.o] Error 1
```
found a solution for that at https://github.com/axel-download-accelerator/axel/issues/136 for an try and error approach:
adding 
```
#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)
#define _DARWIN_C_SOURCE
#endif
```
to src/osx/osx.mm fixes the build issue, so darktable can be built with macos sdk13

### PR DESCRIPTION
**Pull request by MStraeten**
error message: `/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/netinet/ip.h:86:2: fatal error: unknown type name 'u_int' `
solution hint found in https://github.com/axel-download-accelerator/axel/pull/196

fixes #12720

### CODE REVIEW

File: src/osx/osx.mm [hunk 1]
```diff
@@ -15,6 +15,11 @@
     along with darktable.  If not, see <http://www.gnu.org/licenses/>.
 */
 
+/* workaround to fix issue #12720 */
+#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)
```
Comment (parafin) [inline src/osx/osx.mm:19]: I suppose there’s no need for #if, just leave #define

**Review by TurboGit — APPROVED** [review]
Thanks!
