### PR TITLE
import: allows comma in file name

### LINKED ISSUE #11045: crash when selecting folder in "add to library"
**To Reproduce**
1 Click "add to library..."
2 Click an existing 'place'.
3 Click folder in the 2nd panel down.
4 See error.

**Expected behavior**
I expected it to expand the folder I clicked on. Or show files from it.
(Actually I'm not sure what I expected because I find the places/folders screen a bit confusing.)

**Screenshots**
image

**Platform**
* darktable version : 3.8.0
* OS                : Windows 10
* Memory            : 32GB
* Graphics card     : Radeon RX 5500 XT
* Graphics driver   : 22.1.1

**Additional context**
this is darktable 3.8.0 reporting an exception:

-------------------

Error occurred on Wednesday, February 2, 2022 at 18:34:02.

darktable.exe caused an Access Violation at location 00007FFB0B7C15FD in module libimport.dll Reading from location 0000000000000000.

AddrPC           Params
00007FFB0B7C15FD 0000000000000001 0000000000000022 00000128DA57C4F0  libimport.dll!0x7ffb000015fd
00007FFB0B7C5CDD 00000128DA2A4A10 0000000000000001 0000000000000000  libimport.dll!0x7ffb00005cdd
00007FFB0B7C61BE 0000000000000001 00007FFB68C973B3 0000000000000008  libimport.dll!0x7ffb000061be
00007FFB18162D16 0000000100000002 00007FFB68C9BB1D 00007FFB68CD8268  libgtk-3-0.dll!0x7ffb00002d16
00007FFB68C9719E 00000128CEAC4660 00000128D9F9E780 0000000000000002  libgobject-2.0-0.dll!g_closure_invoke
00007FFB68CA9208 00000128CEB7E480 0000012800000000 00000128DDCC10F0  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFB68CAEC19 00000128DDCC10F0 0000000000000000 0000012800000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB68CAF3A8 00000128DDCC10F0 00007FFB68CB6E46 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00007FFB18413655 0000012800000000 00007FFB1843BE7A 0000012800000000  libgtk-3-0.dll!gtk_requisition_copy
00007FFB182C178F FFFFFFFFFFFFFFFF 00007FFB7FE2E693 0000000000000027  libgtk-3-0.dll!gtk_lock_button_set_permission
00007FFB182C37B8 0000000000000000 00007FFB1B269240 00000128CEB72500  libgtk-3-0.dll!gtk_main_do_event
00007FFB1B22F59A 00000001CC9FDEB0 00000128CEB72500 00007FFB7FE2DFD0  libgdk-3-0.dll!gdk_event_free
00007FFB1B26927F 00000128CE2E9680 00007FFB4C32BB20 0000000000000000  libgdk-3-0.dll!gdk_win32_drag_context_get_type
00007FFB4C328E84 0000000000000578 00000001CC9FDFF8 00000128F70FEB80  libglib-2.0-0.dll!g_clear_list
00007FFB4C32BEDE 00000128CE2E9680 00007FFB4C32C252 0000000000000001  libglib-2.0-0.dll!g_main_context_check
00007FFB4C32C3FC 00000128F7420640 00000128F7420640 0000000000000001  libglib-2.0-0.dll!g_main_loop_run
00007FFB18220FE2 0000000000000000 00000128CEAE23A0 00000128CEAE23A0  libgtk-3-0.dll!gtk_dialog_run
00007FFB0B7C2BF9 0000000000000005 00007FFB8159B3C7 00000128CCA10000  libimport.dll!0x7ffb00002bf9
00007FFB0B7C55BA 00000128CEA61E60 00007FFB00000008 00000128CEAE52A0  libimport.dll!0x7ffb000055ba
00007FFB68C973B3 0000000000000020 00007FFB81591C4F 0000000000000002  libgobject-2.0-0.dll!g_closure_invoke
00007FFB68CAF251 00000128DDBF0A40 00007FFB181A8FD3 0000012800000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB68CAF3A8 00000128CE25BD40 00007FFB68CD8268 00000128CEAD9DF0  libgobject-2.0-0.dll!g_signal_emit
00007FFB181A9138 0000000000000001 00007FFB8159B3C7 0000000000000004  libgtk-3-0.dll!gtk_button_clicked
00007FFB68C973B3 0000000000000000 000000000000047B 00000128CEA02160  libgobject-2.0-0.dll!g_closure_invoke
00007FFB68CAF251 00000128DDBF0A40 00007FFB8159B3C7 0000012800000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB68CAF3A8 00000128CCC0E4D0 00007FFB4C387A96 0000000000000002  libgobject-2.0-0.dll!g_signal_emit
00007FFB181A7286 00000128CEAD9DF0 00007FFB68CAF111 00000128CE2E9680  libgtk-3-0.dll!gtk_builder_get_application
00007FFB68C973B3 00007FFB4C4274D8 00000001CC9FEBD0 00000128CE257270  libgobject-2.0-0.dll!g_closure_invoke
00007FFB68CAF251 00000128DDBF3840 00000128DE100DD0 00007FFB00000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB68CAF3A8 00000128F8EA9CC0 00000001CC9FEB30 00000128F8EA9CC0  libgobject-2.0-0.dll!g_signal_emit
00007FFB182765BD 0000000000000000 00005C94CCA10CF0 00000128CEAD9DF0  libgtk-3-0.dll!gtk_gesture_long_press_new
00007FFB68C99D4A 0000000000000008 00007FFB73D74DF3 00000001CC9FED08  libgobject-2.0-0.dll!g_cclosure_marshal_VOID__BOXEDv
00007FFB68C973B3 00000128DDBF0A40 00000128DDBF0A40 00000128CEB7B2D0  libgobject-2.0-0.dll!g_closure_invoke
00007FFB68CAF251 00000128DDBF3840 405A800000000012 0000000500000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB68CAF3A8 00000128CEAD9FD0 00000128DDBF37F0 0000000000000001  libgobject-2.0-0.dll!g_signal_emit
00007FFB182735B3 0000012800000000 0000000000000000 00000128CEAD9FD0  libgtk-3-0.dll!gtk_glade_catalog_init
00007FFB18274BCB 0000000000000002 00000128DDBF0950 00000128DDBF3840  libgtk-3-0.dll!gtk_gesture_handles_sequence
00007FFB18277DB4 0000000000000000 000000000000008B 00000128DA129D00  libgtk-3-0.dll!gtk_gesture_rotate_get_angle_delta
00007FFB1823CC3D 0000012800000000 00007FFB81595BA1 405B000000000000  libgtk-3-0.dll!gtk_event_controller_handle_event
00007FFB18411D3C 0000000000000000 00007FFB4C31970A 00000128CCA10000  libgtk-3-0.dll!gtk_requisition_free
00007FFB18162DC1 00000128DE0FFE90 00007FFB815947B1 0000000000000000  libgtk-3-0.dll!0x7ffb00002dc1
00007FFB68C973B3 00000128DA129C10 0000000000000000 00000128CEAE16C0  libgobject-2.0-0.dll!g_closure_invoke
00007FFB68CAE7E3 00000128DDBF0A40 0000000000000000 0000012800000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB68CAF3A8 00000128DDBF0A40 00007FFB68CB6E46 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00007FFB18413655 0000012800000000 00007FFB1843BE7A 00000128F70A0BB0  libgtk-3-0.dll!gtk_requisition_copy
00007FFB182C178F 0000000000000000 0000000000000000 0000000000000027  libgtk-3-0.dll!gtk_lock_button_set_permission
00007FFB182C37B8 0000000000000000 00007FFB1B269240 0000000000000000  libgtk-3-0.dll!gtk_main_do_event
00007FFB1B22F59A 00000001CC9FF3F0 00000128CEB72500 00007FFB7FE2DFD0  libgdk-3-0.dll!gdk_event_free
00007FFB1B26927F 00000128CE2E9680 00007FFB4C32BB20 0000000000000000  libgdk-3-0.dll!gdk_win32_drag_context_get_type
00007FFB4C328E84 00007FFB00000002 00000001CC9FF538 00000128CE2ADDC0  libglib-2.0-0.dll!g_clear_list
00007FFB4C32BEDE 00000001CC9FF690 00007FFB4C34BD06 0000000000000000  libglib-2.0-0.dll!g_main_context_check
00007FFB4C32C3FC 0000000000000000 0000000000000000 00007FFB18E0B0C0  libglib-2.0-0.dll!g_main_loop_run
00007FFB182C269D 0000000000000000 00007FF6E47C4030 00000128CE2603B0  libgtk-3-0.dll!gtk_main
00007FFB18AD064C 00007FFB00000001 00000128CE2ADDC0 00007FFB00000001  libdarktable.dll!dt_gui_gtk_run
00007FF6E47C2B47 00007FF6E47C1660 0000000000000010 0000000000000000  darktable.exe!0x7ff600002b47
00007FF6E47C15B5 000000000000005A 0000000000000000 00007FF6E47C7090  darktable.exe!0x7ff6000015b5
00007FF6E47C13D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff6000013d4
00007FF6E47C1506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff600001506
00007FFB7FD17034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFB815C2651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.8.0.0
ntdll.dll   	10.0.19041.1288
KERNEL32.DLL	10.0.19041.1348
KERNELBASE.dll	10.0.19041.1387
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
ADVAPI32.dll	10.0.19041.1052
sechost.dll 	10.0.19041.1415
RPCRT4.dll  	10.0.19041.1288
libglib-2.0-0.dll	2.70.2.0
libdarktable.dll
GDI32.dll   	10.0.19041.1202
win32u.dll  	10.0.19041.1387
ole32.dll   	10.0.19041.1202
gdi32full.dll	10.0.19041.1387
ucrtbase.dll	10.0.19041.789
msvcp_win.dll	10.0.19041.789
USER32.dll  	10.0.19041.1202
combase.dll 	10.0.19041.1348
PSAPI.DLL   	10.0.19041.546
SHELL32.dll 	10.0.19041.1387
WS2_32.dll  	10.0.19041.546
libiconv-2.dll	1.16.0.0
libwinpthread-1.dll	1.0.0.0
libgcc_s_seh-1.dll
libstdc++-6.dll
libpcre-1.dll
libcairo-2.dll
exchndl.dll 	0.9.3.0
libgdk_pixbuf-2.0-0.dll	2.42.6.0
libgdk-3-0.dll	3.24.30.0
IMM32.dll   	10.0.19041.546
SETUPAPI.dll	10.0.19041.1237
cfgmgr32.dll	10.0.19041.1151
bcrypt.dll  	10.0.19041.1023
libgio-2.0-0.dll	2.70.2.0
SHLWAPI.dll 	10.0.19041.1023
libgobject-2.0-0.dll	2.70.2.0
lua54.dll
libpango-1.0-0.dll	1.50.0.0
libpangocairo-1.0-0.dll	1.50.0.0
zlib1.dll
libgtk-3-0.dll	3.24.30.0
libgomp-1.dll
libavif.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.1320
WLDAP32.dll 	10.0.19041.546
comdlg32.dll	10.0.19041.906
shcore.dll  	10.0.19041.1387
libgmodule-2.0-0.dll	2.70.2.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libexiv2.dll
libheif.dll
libGraphicsMagick-3.dll
libicuin69.dll
libicuuc69.dll
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
libopenjp2-7.dll
libpng16-16.dll
libpugixml.dll	1.11.0.0
libsecret-1-0.dll
libsoup-2.4-1.dll
libtiff-5.dll
libsqlite3-0.dll
libxml2-2.dll
librsvg-2-2.dll
MSIMG32.dll 	10.0.19041.546
libfontconfig-1.dll
libfreetype-6.dll	2.11.1.0
libpixman-1-0.dll
VERSION.dll 	10.0.19041.546
mgwhelp.dll 	0.9.3.0
dwmapi.dll  	10.0.19041.746
HID.DLL     	10.0.19041.546
gdiplus.dll 	10.0.19041.1348
libcairo-gobject-2.dll
WINMM.dll   	10.0.19041.546
DNSAPI.dll  	10.0.19041.1320
libepoxy-0.dll
IPHLPAPI.DLL	10.0.19041.546
libfribidi-0.dll
libpangowin32-1.0-0.dll	1.50.0.0
libffi-7.dll
libthai-0.dll
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.50.0.0
libdav1d.dll	5.1.1.0
libaom.dll
rav1e.dll
COMCTL32.dll	6.10.19041.1110
libbrotlidec.dll
libcrypto-1_1-x64.dll	1.1.1.12
libnghttp2-14.dll
libidn2-0.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.12
libzstd.dll
libatk-1.0-0.dll	2.36.0.0
WINSPOOL.DRV	10.0.19041.1288
libexif-12.dll
libltdl-7.dll
libsystre-0.dll
libexpat-1.dll
libbz2-1.dll
libde265-0.dll
libx265.dll 	3.4.0.31
libHalf-2_5.dll
libIex-2_5.dll
libicudt69.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libgcrypt-20.dll	1.9.4.0
libjbig-0.dll
libdeflate.dll
libLerc.dll
liblzma-5.dll	5.2.5.0
USERENV.dll 	10.0.19041.572
libwebp-7.dll
dbghelp.dll 	10.0.19041.867
libdatrie-1.dll
USP10.dll   	10.0.19041.546
libgraphite2.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libtre-5.dll
libgpg-error-0.dll	1.43.0.0
dbgcore.DLL 	10.0.19041.789
CRYPTBASE.DLL	10.0.19041.546
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1415
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1387
Wldp.dll    	10.0.19041.1320
mswsock.dll 	10.0.19041.546
winhttp.dll 	10.0.19041.1320
uxtheme.dll 	10.0.19041.1266
DEVOBJ.dll  	10.0.19041.1151
MSCTF.dll   	10.0.19041.1387
OLEAUT32.dll	10.0.19041.985
WINTRUST.dll	10.0.19041.1266
MSASN1.dll  	10.0.19041.546
kernel.appcore.dll	10.0.19041.546
clbcatq.dll 	2001.12.10941.16384
OpenCL.dll  	2.2.6.0
amdocl64.dll	10.0.3354.13
OPENGL32.dll	10.0.19041.1081
GLU32.dll   	10.0.19041.1081
amd_comgr.dll
profapi.dll 	10.0.19041.844
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1151
AppXDeploymentClient.dll	10.0.19041.1288
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.964
propsys.dll 	7.0.19041.1023
mssprxy.dll 	7.0.19041.1387
mrmcorer.dll	10.0.19041.1266
iertutil.dll	11.0.19041.1266
windows.staterepositorycore.dll	10.0.19041.844
bcp47mrm.dll	10.0.19041.1266
Windows.UI.dll	10.0.19041.746
WindowManagementAPI.dll
TextInputFramework.dll	10.0.19041.1387
InputHost.dll	10.0.19041.906
wintypes.dll	10.0.19041.1348
CoreMessaging.dll	10.0.19041.746
CoreUIComponents.dll	10.0.19041.546
ntmarta.dll 	10.0.19041.546
libpixbufloader-png.dll
mscms.dll   	10.0.19041.746
ColorAdapterClient.dll	10.0.19041.546
icm32.dll   	10.0.19041.546
Oleacc.dll  	7.2.19041.746
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libavif.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libxcf.dll
libdisk.dll
libemail.dll
libgallery.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libblurs.dll
libborders.dll
libcacorrect.dll
libcacorrectrgb.dll
libcensorize.dll
libchannelmixer.dll
libchannelmixerrgb.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorbalancergb.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libcrop.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdiffuse.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libgmic.dll
libGraphicsMagick++-12.dll
libfftw3-3.dll
libopencv_videoio452.dll	4.5.2.0
libopencv_core452.dll	4.5.2.0
libopencv_imgcodecs452.dll	4.5.2.0
libopencv_imgproc452.dll	4.5.2.0
tbb.dll
libopenblas.dll
libgfortran-5.dll
libquadmath-0.dll
libmask_manager.dll
libmonochrome.dll
libnegadoctor.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgamepad.dll
SDL2.dll    	2.0.18.0
dinput8.dll 	10.0.19041.1
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
libioporder.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_locations.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmidi.dll
libportmidi.dll
winmmbase.dll	10.0.19041.1
MMDevAPI.DLL	10.0.19041.1023
wdmaud.drv  	10.0.19041.1
ksuser.dll  	10.0.19041.1
AVRT.dll    	10.0.19041.546
AUDIOSES.DLL	10.0.19041.1023
powrprof.dll	10.0.19041.546
UMPDC.dll
msacm32.drv 	10.0.19041.488
MSACM32.dll 	10.0.19041.1
midimap.dll 	10.0.19041.488
libmodulegroups.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
libpixbufloader-svg.dll
TextShaping.dll

Windows 10.0.19044
DrMingw 0.9.3

### LINKED ISSUE #11092: an unhandled exception when accessing a folder in an unremovable library place
**Did you buy darktable from an application store ?**
No.

**Describe the bug/issue**
The Darktable 3.8.0 crashes when I open a folder that I was not able to remove from import places. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. I right-click a place "2021-08-10 Hoštice s Verčou" to remove it
2. I get "you can't delete the selected place" error (but no reason why I can't) - see the screenshot: 
(BTW the folder still exists)

image

3. Then I click on the folder and that's when it crashes:

image

4. I am attaching the backtrace: [darktable_bt_XSSIH1.txt](https://github.com/darktable-org/darktable/files/8032201/darktable_bt_XSSIH1.txt)

**Platform**

* darktable version : 3.8.0
* OS                : Windows 10 64 bit 21H1
* Memory            :  16 GB
* Graphics card     :  AMD Radeon Vega 8 Graphics

### PR DESCRIPTION
**Pull request by phweyland**
- fixes #11045
- on opening selects the last place if any
- fixes a Gtk-CRITICAL on selection with iter not set
- some code cleaning
- EDIT should also fix #11092

### CODE REVIEW

**Comment by TurboGit** [comment]
I'll check and try to have this in 3.8.1, but that's very very close to the release.

File: src/libs/import.c [hunk 1]
```diff
@@ -1440,47 +1438,76 @@ static void _update_folders_list(dt_lib_module_t* self)
...
 }
 
-static void _add_custom_place(const gchar *folder, dt_lib_module_t* self)
+static void _escape_place_name_comma(char *name)
 {
-  dt_lib_import_t *d = (dt_lib_import_t *)self->data;
-  const char *current_folders = dt_conf_get_string_const("ui_last/import_custom_places");
-  GtkTreeIter iter;
+  for(int i = 0; name && i < strlen(name); i++)
+    if(name[i] == ',') name[i] = '\1';
```
Comment (TurboGit) [inline src/libs/import.c:1446]: Are we sure that \1 is not some kind of prefix in multi-bytes chars in UTF encoding?

File: src/libs/import.c [hunk 2]
```diff
@@ -1323,7 +1323,6 @@ static void _update_places_list(dt_lib_module_t* self)
     gchar *homedir = dt_loc_get_home_dir(NULL);
```
Comment (TurboGit) [inline src/libs/import.c:1323]: shouldn't we free this?

**Review by TurboGit — CHANGES_REQUESTED** [review]
Some changes, as I'm working this morning on creating 3.8.1 tarball I will postpone this for 4.0.

**Comment by TurboGit** [comment]
Haven't you missed a push here? The comments are marked as resolved but I see no changes.

**Comment by phweyland** [comment]
> The comments are marked as resolved but I see no changes.

I've answered the points but I haven't made any change as everything is correct (if I'm not mistaken :))

**Comment by TurboGit** [comment]
> I've answered the points but I haven't made any change as everything is correct (if I'm not mistaken :))

I really don't show the answers on my side :(

**Comment by phweyland** [comment]
> I really don't see the answers on my side :(

Sorry, my bad. I'd started a review (don't know how and why) and it was still pending.
Can you see them now ?

File: src/libs/import.c (hunk 1 above)
Comment (TurboGit) [reply src/libs/import.c:1446]: UTF-8 maybe but in the context of multi-bytes chars. Non-ascii characters are  encoded using 2-4 bytes. And byte inside a multi-byte chars may well be 1 I suppose. And here you read one char by one char so crossing multi-bytes encoding.

To avoid any issue why not use a character that cannot be used to create a filename?

Just checked and this is not easy to have cross-platform solutions :( So yes using `','` may be a good option... Let's see if we can find something that won't break current settings.

Comment (TurboGit) [reply src/libs/import.c:1446]: I see, not problem then. I don't know the code point encoding by memory :) Thanks to have checked.

**Review by TurboGit — APPROVED** [review]
Thanks! All good.
