### PR TITLE
don't trigger unnecessary workings on zoom bounds

### LINKED ISSUE #15688: New crop changes cause slight flickering
### Describe the bug

Crop changes introduced recently caused image flickering which was raised in #15549 and partly addressed in #15546 .

According to @piratenpanda : "much much better, only seeing jumps of a few pixels"

I would like to argue that this few pixel flickering is still annoying. I happens in "Rotate and perspective" module when I try to carefully align a manually drawn structure line to an image feature, the image is "running away" from my cursor. I also see it in color calibration when I correct white balance by selecting an area on the image. It is less annoying, but still there.

I must admit that I couldn't follow the entire pull request discussion, I believe there were multiple issues discussed and I couldn't separate and understand them, so please ignore this issue if it is currently being worked on.

### Steps to reproduce

1. Open image in darkroom
2. open rotate and perspective module, select manully draw structure lines
3. Press Alt+1 to zoom in
4. Draw a structure line
5. Click and drag one end of it. For me it will not cause flickering.
6. With the mouse scroll zoom out a little bit, and drag the end of a structure line again. Image starts jumping a few pixels as you drag even when you avoid dragging to the edges.

### Expected behavior

Image should stay where it was, and not jump. Not even a single pixel.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1245~gfaef4b3d62

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.1 Vera

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### LINKED ISSUE #15737: darkroom displays "working" when scrolling mouse even if fully zoomed in/out
Scroll to zoom out in the darkroom view. Even after the image is fully zoomed out, the "working" indicator still flashes over the image. Similarly when zooming in past the maximum zoom.

Does this mean it's trying to rerun the pipe? I suspect pipe caching means it doesn't do much but the "working" indicator suggests it's _trying_ to do something when it's not needed.

4.5.0+1294~g749a577100 on ArchLinux

### LINKED ISSUE #15747: weird panning, when zoomed and using eyedropper for colorcalibration
### Describe the bug

I zoomed into a pic (100% and 200%) and used the eyedropper of colorcalibration. When the mouse, the picture is moving (panning). 

I saw similar behaviour on rotate and perspective, when manually drawing lines for keystoneing. I initially thought it is a feature...

@dterrahe can it be, this is also related to commit 135d5a6 or its parrents? (just a smell of somebody who cannot do the coding :slightly_smiling_face:  )

### Steps to reproduce

1) Go to darkroom
2) middle click to zoom e.g. 100% or 200%
3) use eyedropper of colorcalibration
4) pick an area, drag the mouse around and see

### Expected behavior

there should be no movement of the picture

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/49004103/550313c0-7332-467b-a3d1-60ab88646178

### Commit

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0-1310-g368a506772

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

* darktable version : 4.5.0-1310-g368a506772
* OS                : Linux - kernel 6.6.2-gentoo
* Distro            : Gentoo Base System release 2.14
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-535.129.03
* OpenCL installed  : Yes (opencl-headers-2023.04.17)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.9
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.38
* gcc               : 13.2.1_p20230826
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

please see system description

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

not tried yet other versions of dt
only tried with RAW (ORF)
yes, it can be reproduced with discarded history
I didn't try with empty config yet

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #15737 (see https://github.com/darktable-org/darktable/issues/15737#issuecomment-1826470375)
fixes #15688
fixes #15747

As per the bug; when "fully" (depending on ctrl) zoomed in or out, zooming a little further still triggers a "working" message even though nothing changes. Same with moves. This PR checks if a move or zoom request leads to an actual change in the viewport and only then issues a redraw request.

@elstoc help with extensive testing appreciated.

### CODE REVIEW

File: src/develop/develop.c [hunk 1]
```diff
@@ -2681,6 +2688,13 @@ void dt_dev_zoom_move(dt_dev_viewport_t *port,
   dt_pthread_mutex_unlock(&dev->history_mutex);
   dt_pthread_mutex_unlock(&(darktable.control->global_mutex));
 
+  if( old_zoom == port->zoom
+      && old_closeup == port->closeup
+      && fabsf(old_zoom_x - port->zoom_x) < 1e-6
```
Comment (jenshannoschwalm) [inline src/develop/develop.c:2693]: I think the overall idea is **very** good and it avoids some pipe recalculations. Nevertheless i have some jitter-around while mouse-scroll zooming in.

As both zoom_x & zoom_y are coordinates it think the "eps" of 1e-6 is by far too small, i tested with 2.0f and everything is rock-stable

**Comment by elstoc** [comment]
> @elstoc help with extensive testing appreciated

Hard to know what else to test outside the original issue without knowing what might be impacted. But the original issue seems to be fixed.

File: src/develop/develop.c (hunk 1 above)
Comment (elstoc) [reply src/develop/develop.c:2693]: Not sure I notice much difference personally. I don't know what you mean by "jitter" but I have noticed that there now seems to be some sort of "progressive update" when zooming out, which wasn't there before -- if I zoom out two "clicks" of my zoom wheel then the display updates the roi of the first zoom click and then the second, where before it updated the whole image at once. It's a bit distracting but I'm not sure whether it's intentional or not.

Comment (jenshannoschwalm) [reply src/develop/develop.c:2693]: To reproduce the "jitter" use mouse scroll in darkroom being already at 100% and try to increase zoom. You will see - in master and with this pr - the darkroom image slightly moving around for a pixel or even two, this is likely due to some rounding and roi corrections.

As any dragging around for just one pixel - either by a mouse drag or caused by rounding - doesn't make sense to me we could avoid reprocessing/exposing in such a case. Maybe we can find a better threshold than 2.0 but i think the idea is really good as it avoids getting data via pixelpipe - even if that cost is close to zero because of caching.

About the drawing-whole-image-at-once, the new behaviour is intentional.

Comment (jenshannoschwalm) [reply src/develop/develop.c:2693]: See #15688, also solved via this pr for me.

Comment (dterrahe) [reply src/develop/develop.c]: > As both zoom_x & zoom_y are coordinates it think the "eps" of 1e-6 is by far too small

You are right of course!

> i tested with 2.0f and everything is rock-stable

The risk is that you may end up 1 pixel from the edge of the crop and not be able to move to the _real_ end. So you could end up with a whole row of contrasting pixels that you meant to crop out and _checked_ (by moving "all the way" to the edge _while zoomed in_) and it still showing up in your final image. So I think .5 pixel would be the maximum. But since distortions can stretch 1 pixel in the RAW to multiple pixels in the processed image, maybe 0.1? I'll submit that so we all can test.

> I don't know what you mean by "jitter"

Me neither. To me, jitter is repeated jumping back-and-forth between two states. Not meandering around or slowly creeping. But people seem to use it with slightly different meanings which doesn't help the clarity of reported issues.

> there now seems to be some sort of "progressive update" when zooming out, which wasn't there before

Is "before" 4.4.2 or before this PR? The progressive update was always there, but in 4.4.2 it was just not shown; multiple (many) recalcs could go on in the background, but the scaled up preview image continued to be shown until you stopped moving/zooming. Now you get to see the intermediate/partial results, so there is a quicker response.

I had not been able to reproduce #15688 (tbh I was not sure I understood it) or #15747 yet (which has a very helpful video and might be a duplicate of #15688), but I hopefully added a complete fix for both of those as well, so I'm optimistically going to mark this PR as "fixes" them both. @axelg-de would you please test if this PR solves your issue?

**Comment by dterrahe** [comment]
> Hard to know what else to test

ALL the things I did _not_ think of and therefore haven't tested :-)

More seriously, it would be good if you could go through all your usual use cases (I don't know if you've switched to master as your daily driver?) and pay close attention to screen updates possibly not happening (because that's what this PR does; it skips screen updates when it thinks they are not necessary; sometime it might get it wrong!). So if you've been moving/zooming/toggling states (masks/color assessment/whatever)/changing module focus and at some point an update doesn't happen (or you have to trigger it twice) or, for example, the image slightly jumps when you are just changing the exposure (which again might indicate a refresh was missed).

So I'm not really asking to do specific _testing_, just to pay extra close attention and _report_ any issues while I still have a chance to address them before release.

Your help as always greatly appreciated!

**Comment by elstoc** [comment]
> More seriously, it would be good if you could go through all your usual use cases (I don't know if you've switched to master as your daily driver?)

No, I might move to master as my daily driver soon but at the moment I'm only using it because I've been doing some work on the user manual and I wanted to get some screenshots / test new functionality. I'm not sure how much time I'll have to do more 'open ended' testing right now but I'll certainly keep an eye out for further issues.

**Comment by dterrahe** [comment]
@TurboGit I'm not sure if the _priority: low_ label is appropriate here, but also this is not a trivial low risk change. So I think it "should" still be considered for 4.6 if enough high quality testing feedback is received.

File: src/develop/develop.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/develop/develop.c]: > To me, jitter is repeated jumping back-and-forth between two states

At least in the real-time audio processing or timings jitter is also associated with "in phase" ...

What i meant was, that the image is not constantly at the same position while further zooming in at the same mouse position. Likely due to `dt_dev_distort_backtransform_locked()`.

Anyway, tested you latest commit and it all looks good to me now.

**Comment by elstoc** [comment]
> Is "before" 4.4.2 or before this PR? The progressive update was always there, but in 4.4.2 it was just not shown; multiple (many) recalcs could go on in the background, but the scaled up preview image continued to be shown until you stopped moving/zooming. Now you get to see the intermediate/partial results, so there is a quicker response.

I mean in 4.4.2 -- this is really the first time I've used master in this release cycle. I'm not sure whether I prefer the "quicker" update -- I find it kind of distracting and I think it might have been better when the whole image updated at the same time, even if it was slower.

File: src/develop/develop.c (hunk 1 above)
Comment (AxelG-DE) [reply src/develop/develop.c]: > @AxelG-DE would you please test if this PR solves your issue?

I did test and also documented in the [aforementioned issue 15747](https://github.com/darktable-org/darktable/issues/15747#issuecomment-1826826775). It does improve a lot, but still the image jumps upon release the left mouse button. Find video in the issue...

**Comment by dterrahe** [comment]
> I'm not sure whether I prefer the "quicker" update

Not unexpected.

The feedback elsewhere has been _mostly_ positive, but anyway, there are now _many_ other changes that are dependent on this one (and it was, besides a perrsonal preference of the developer, also a logical consequence of a whole bunch of simplifications/streamlinings/deduplications and bugfixes) so at this point in the cycle unfortunately feedback loses its ability to influence.

Apart from bugfixes!!

**Comment by AxelG-DE** [comment]
@dterrahe do you need me to test again, after the push at 7 p.m. my time (32mins ago)?

**Comment by dterrahe** [comment]
> @dterrahe do you need me to test again, after the push at 7 p.m. my time (32mins ago)?

@AxelG-DE Now please (pushed again after noticing I messed up).

**Comment by dterrahe** [comment]
> the picture stays rock solid now

Great! Thanks for testing!

**Comment by dterrahe** [comment]
> when initially clicking into the picture, a square will be drawn and only when moving the cursor, a new box is drawn with one corner at the initial click-space

I believe it's been like that since prehistoric times. And intentionally. Do you see a change relative to 4.4.2? If so, could be a scaling factor (maybe previously the initial box centered on the cursor was smaller). What dpi setting do you have?

If really a new issue, better to raise separately because has nothing to do with this pr.

**Comment by jenshannoschwalm** [comment]
Really a great improvement! Waiting to discuss what we can do with the iop cache for after 4.6

**Comment by dterrahe** [comment]
> Stable here too.

Ok, so the problem seems to have been solved.

Now we need to test if this introduces new regressions...

@turbogit it is not a _large_ PR so could still be reverted if it causes problems (that are larger than the one it fixes). So maybe more efficient to have more people test in master?

**Comment by dterrahe** [comment]
> Really a great improvement!

It is great that we now get some really serious testing of all the refactorings. And filed issues. It is impossible to make such deep changes without causing ripples, but is very satisfying to clean those up too. Thanks again @AxelG-DE and @elstoc; you have both made 4.6 better (or, in @elstoc's case, less worse than it otherwise would have been :wink:)

**Comment by dterrahe** [comment]
> I dream of two the same ones...

People with weird setups are the best testers. It is all about corner cases ;-)

**Comment by TurboGit** [comment]
> @TurboGit it is not a _large_ PR so could still be reverted if it causes problems (that are larger than the one it fixes). So maybe more efficient to have more people test in master?

Fully agreed, tested on my side and things are better with this PR.

**Review by TurboGit — APPROVED** [review]
Thanks!
