### PR TITLE
fix a crash in windows for dual demosaicers

### LINKED ISSUE #8025: dual demosaic crashes in Windows
Testing the new dual demosaicing feature, and we have the usual Windows-only issue related to parallelization.
With current git master DT crashes by selecting either RCD+VNG4 or Amaze+VNG4

Cattura

Backtrace attached
[darktable_bt_6YQZX0.txt](https://github.com/darktable-org/darktable/files/5892105/darktable_bt_6YQZX0.txt)

@jenshannoschwalm can you please have a look? Also @ralfbrown, you solved several similar issues recently

### PR DESCRIPTION
**Pull request by Mark-64**
This fixes a crash in windows with dual demosaic
fixes #8025 
replaces #8029

### CODE REVIEW

File: src/common/colorspaces_inline_conversions.h [hunk 1]
```diff
@@ -193,9 +193,11 @@ static inline float cbrta_halleyf(const float a, const float R)
   return b;
 }
 
+/* this produces a crash in Windows with gcc -Ofast #8025
```
Comment (TurboGit) [inline src/common/colorspaces_inline_conversions.h:196]: Just a question as I have not followed all the discussion. Why do we disable this on all platforms if it break Windows ? Or is the bug on all platforms but only visible/reproducible on Windows ?

Comment (Mark-64) [reply src/common/colorspaces_inline_conversions.h:196]: This  is a good question, I have the issue only with Windows / gcc, but it seems that performance penalization is small because the code vectorization was poor anyhow. I leave the last word to you   more expert devs. Eventually we can restrict this change to Windows only

Comment (Mark-64) [reply src/common/colorspaces_inline_conversions.h:196]: Coverted to draft because I noticed that lab_f() is called in many modules that do create any problem, so disabling simd there can't be right, even if restricted only to Windows.
I have to investigate a bit more

Comment (jenshannoschwalm) [reply src/common/colorspaces_inline_conversions.h:196]: Maybe the -Ofast option is the culprit although i don't what detail triggers the bug.

Comment (Mark-64) [reply src/common/colorspaces_inline_conversions.h:196]: most likely.
In many modules, `lab_f()` is called from `dt_XYZ_to_Lab()` so we have even deeper nesting and no problems.
Instead `#pragma GCC optimize ("-Ofast")` is only used in `rcd_demosaic.c` and `dual_demosaic.c`

Comment (TurboGit) [reply src/common/colorspaces_inline_conversions.h:196]: And this is not the first time we had issues with `-Ofast`. I would propose to remove this from this file. Maybe that's because such optimization is better to be used globally ? As we have a set of inline and not inline who knows what an optim in one file can do... So if ok please remove `-Ofast` and we will revisit this whole issue in another PR.

Comment (TurboGit) [reply src/common/colorspaces_inline_conversions.h:196]: Especially when one read:

```
-Ofast
    Disregard strict standards compliance.  ...
```

Let's keep away of this.

Comment (Mark-64) [reply src/common/colorspaces_inline_conversions.h]: Please see last commit.

- reverted change in lab_f()
- disabled gcc -Ofast only for the problematic function blend_images() in dual_demosaic.c and only for Windows.

This seems to me the fix with the smallest impact.
If other issues will come out with -Ofast in Windows, we will have to disable it completely

**Comment by TurboGit** [comment]
Sorry but I'm not ok to go this way. We don't have -Ofast in dt currently and I'd prefer to remove it completely from here too. As I said it has already proved to cause troubles, those issues are hard to reproduce and -Ofast seems a dangerous option to start with. So please remove it.

**Comment by Mark-64** [comment]
I didn't introduce -Ofast, it is in current master in  in `rcd_demosaic.c` and `dual_demosaic.c`.
I can remove those, no pb, that automatically solves the issue too
@jenshannoschwalm for you to know

**Comment by jenshannoschwalm** [comment]
Just to let you know, rcd demosaicer will be ~30% slower and there have been no issues related ,,,

**Comment by jenshannoschwalm** [comment]
There will be other options that can be used ...

**Comment by TurboGit** [comment]
30% that's a lot indeed, but again looking at the -Ofast description I don't think it is the way to go. As I said I remember in first version of Filmic we had tracked down some very strange issue and removing some optimization like -Ofast (was due to fast-math which is part of -Ofast) was the fix.

And if -Ofast is 30% faster then we should probably have been using it in all dt code already.

A better path is probably to optimize the code some other way as @ralfbrown has been doing since some time.

**Comment by TurboGit** [comment]
BTW, any hope to get an OpenCL code for RCD ? Maybe that will help a lot.

**Comment by jenshannoschwalm** [comment]
Pascal, after a few seconds thinking i have absolutely no objections about this pr :-) -Ofast breaks IEEE conformance and more, so it's good to not-have this as it is now.

As the rcd code has finite-maths only and all divides are ensured via eps we can use explicit options as done in filmicrgb.

About the work of @ralfbrown, that's great and improved many things a lot, congrats again. But on the rcd stuff, i don't really think there is much room via better vectorizing or aligning as that is already very good. And btw, rcd is - even with this pr - still faster than ppg and double as amaze, so ...

Hope for an OpenCL- RCD implementation? Yes, the algo is not that difficult and i will do it for sure (although that's something complety new for me), atm i am working on updating the raw ca correction module so thats priority.

**Comment by TurboGit** [comment]
Fix is ok to me. I'll merge this to un-break the Windows version. And we'll see if we can do better. Thanks to all for contributing on this.
