### PR TITLE
import exif: use comment() for correct reading of UserComment and disregard the "binary comment"

### LINKED ISSUE #7579: Importing RAWs add "binary comment" to description metadata
**Describe the bug**

When importing RAWs to darktable 3.4, a description metadata is added with the content "binary comment".
I'm importing NEF RAWs from a Nikon camera, I tried changing comments off and comments on with a blank field, issue persists.

**Expected behavior**

A clear description metadata

**Screenshots**

captura

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Ubuntu 20.10

**Additional context**
<!-- Add any other context about the problem here, for example:
Sample NEF:

[sample.zip](https://github.com/darktable-org/darktable/files/5757601/sample.zip)

### PR DESCRIPTION
**Pull request by phweyland**
Fixes #7579

This fixes two issues:
- charset=xxx is not part of the UserComment. The method comment() allows to get the text properly decoded. BTW, this charset=xxx was then written in xmp description and polluted it as well.
- special text "binary comment" return by exiv2 in case of invalid text.

### CODE REVIEW

File: src/common/exif.cc [hunk 1]
```diff
@@ -1065,7 +1065,10 @@ static bool _exif_decode_exif_data(dt_image_t *img, Exiv2::ExifData &exifData)
     if(FIND_EXIF_TAG("Exif.Photo.UserComment"))
     {
       std::string str = pos->print(&exifData);
-      dt_metadata_set_import(img->id, "Xmp.dc.description", str.c_str());
+      Exiv2::CommentValue value(str);
+      const char *comment = value.comment().c_str();
```
Comment (johnny-bit) [inline src/common/exif.cc:1069]: This line causes LLVM to warn:

`src/src/common/exif.cc:1069:29: fatal error: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]`

**Comment by phweyland** [comment]
Seems to be better for LLVM , but I don't really master this...

File: src/common/exif.cc [hunk 2]
```diff
@@ -1065,7 +1065,10 @@ static bool _exif_decode_exif_data(dt_image_t *img, Exiv2::ExifData &exifData)
     if(FIND_EXIF_TAG("Exif.Photo.UserComment"))
     {
       std::string str = pos->print(&exifData);
-      dt_metadata_set_import(img->id, "Xmp.dc.description", str.c_str());
+      Exiv2::CommentValue value(str);
+      std::string comment = value.comment();
```
Comment (johnny-bit) [inline src/common/exif.cc:1069]: additionally you can use string copy constructor which should be tad faster ;)

```cpp
std::string comment(value.comment());
```

Comment (phweyland) [reply src/common/exif.cc]: Well, no way, I have to learn to understand properly... (any advice for learning basics of C++ BTW ?...)
Thanks !

Comment (parafin) [reply src/common/exif.cc]: @johnny-bit, these 2 initialization methods both call copy constructor and are totally identical. I think assignment way to write it is more readable.

Comment (johnny-bit) [reply src/common/exif.cc]: don't sweat it ;) C++ is far more complex (imo) than C, has it's own advantages and disadvantages... I think best reading material is "Effective (Modern) C++" and "Effective STL" and maybe some others. Most of teh time knowledge of C is enough to write good enough C++ :)

Comment (phweyland) [reply src/common/exif.cc]: >  I think best reading material is "Effective (Modern) C++" and "Effective STL"

Thanks. I'll make a try on this (if the neurons that I have left support it) !

Comment (phweyland) [reply src/common/exif.cc]: As identical, I let the code as it is...

File: src/common/exif.cc [hunk 3]
```diff
@@ -1065,7 +1065,10 @@ static bool _exif_decode_exif_data(dt_image_t *img, Exiv2::ExifData &exifData)
     if(FIND_EXIF_TAG("Exif.Photo.UserComment"))
     {
       std::string str = pos->print(&exifData);
-      dt_metadata_set_import(img->id, "Xmp.dc.description", str.c_str());
+      Exiv2::CommentValue value(str);
+      std::string str2(value.comment());
+      if(g_strcmp0("binary comment", str2.c_str()))
```
Comment (parafin) [inline src/common/exif.cc:1070]: This can be re-written as `if(str2 != "binary comment")`. I think it's more readable than `if(g_strcmp0())`, since with strcmp it's confusing that 0 (false) return value means string match.

Comment (phweyland) [reply src/common/exif.cc:1070]: The way to learn a lot of stuff with 2 lines of code ! :smiley: 
Let's do it.

**Comment by phweyland** [comment]
@TurboGit I think this is ok for your review.

**Review by TurboGit — APPROVED** [review]
Thanks ! An easy one with all the review already received !

**Comment by TurboGit** [comment]
Merged in master and 3.4.1.
