### PR TITLE
BUGFIXES new iop cache issues

### LINKED ISSUE #12336: 'Unhandled exception' crash when making consecutive exposure adjustments
OK, my first ever issue..... tell me if something's missing

I've been trying out the latest weekly Windows build, (posted on discuss.pixls.us by wpferguson) but have got a consistent crash with an "Unhandled exception". See backtrace below.

To reproduce:
1. Close dt if running.
2. Start dt
3. Open image in darkroom
4. make 2 consecutive adjustments to the exposure slider inthe 'quick access' panel.
5. dt crashes.

If, however, I do a single exposure adjustment, then something else, like color balance rgb saturation, then come back to exposure it works properly. If I then open a new image, it still works properly, right from the start. But the problem returns if dt is restarted.
I did have two other versions of dt installed, but uninstalling them made no difference.
 
apostle338 on the discuss.pixls.us forum is able to reproduce it, but only with OpenCL set to off or standard. The crash does not occur when OpenCL is set to 'very fast GPU'.

Not sure if it's related, but I have just reinstalled dt4.0, and now the weekly build won't run. A blank window opens briefly then disappears. I had this problem the other way around after installing the weekly build the first time, 4.0 wouldn't run. It did after uninstalling the weekly build, which I then reinstalled and ran using --configdir to set a separate db, and all seemed fine. Make of this what you will... I have not a clue!

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.1.0+177~g8e7e79817
* OS                : Windows 11
* Linux - Distro    :
* Memory            :  16GB
* CPU Intel i5-2400 @3.10GHz
* Graphics card     : embedded
* Graphics driver   : unknown
* OpenCL installed  : no
* OpenCL activated  :  no
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : unknown

 - Can you reproduce with another darktable version(s)? --- no
 - Can you reproduce with a RAW or Jpeg or both? ---Raw not sure about jpg.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? --- yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? ----yes
 - Do you use lua scripts? --- no
Here's the backtrace:
[darktable_bt_6GPOQ1.txt](https://github.com/darktable-org/darktable/files/9358769/darktable_bt_6GPOQ1.txt)

### LINKED ISSUE #12364: OOM kills probably due to "Improving pixelpipe cache"
I recently started having out of memory kills, after editing a few images (in the order of 5-10). I began to pay attention to my system's memory usage, and noticed that darktable uses more and more memory after every edited image. I even tried to set the "darktable resources" setting to "small" from "default", but it had no effect.

I bisected the issue down to a few commit. I can continue the bisect, but I thought this might be enough to start a discussion.
```
tbilles@serpens ~/sources/darktable> git bisect visualize --graph --oneline
* bec92e554 (refs/bisect/bad) Add two important cache importance hints - highlights because of possibly heavy processing, could be changed to runtime hints - colorin because that's very likely to stay stable while doing later processing
* b0e209644 Make the iop cache aware if importance hints
* 332facc82 (HEAD) Prepare imageop for cache hints
* 650d78a1a RFC Improving pixelpipe cache
```

The commits are related to #12169 

My machine has 12 Gb RAM, baseline system usage is 3-3.5Gb, no swap. While bisecting this issue, good commits after 2-3 image edits result in ~5 Gb memory usage (entire system), bad commits are more like ~7-8 Gb. OOM kill starts to happen above 10 Gb (or at least that is what I see on my memory usage widget).

Is this cache improvement supposed to increase memory usage by this much? Could there be a leak somewhere? (Memory usage doesn't go down when I switch back to lighttable or open an other image in darkroom.) Or is it just the cache filling up?

**Platform**
* OS                : Linux - kernel 5.17.5
* Linux - Distro    : Ubuntu 20.04
* Memory            :  12 Gb
* Graphics card     :  Integrated HD Graphics 4600
* Graphics driver   : Intel
* OpenCL installed  : -
* OpenCL activated  : -
* gcc               : gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
* CMAKE_BUILD_TYPE  : RelWithDebInfo

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As mentioned in #12364 the used memory in the cache could grow substancially.
This was due to wrong arithmetics on size_t data.
One more problem related to cache memory was in `dt_get_iopcache_mem()`, it now takes the
limit to half of mipmap size.

`dt_dev_pixelpipe_init_cached()` and `dt_dev_pixelpipe_cache_init()` could have left not fully initialized
cache structs in cases of problems. Fixed now.

We now only have one function to get the cacheline, `dt_dev_pixelpipe_cache_get()`.
The new version takes an additional const gboolean argument `important`

The observed crashes in #12336 were very likely related to two problems:
  1. `_get_oldest_cacheline` could return a cacheline index of -1
  2. `_get_free_cacheline` could return a wrong cacheline because of bad testing while cleaning up memory
  3. Issue 2 was very unlikely to happen with CL enabled - only with "always syncing" or two consecutive syncing modules - so it was not observed.  

All `dt_dev_pixelpipe_init` variants return proper gbooleans.

Fixes #12364
Fixes #12336

I have tested here for some hours and could not get a single crash any more - with cl enabled or not.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Building fails due to
```
/libs/metadata_view.c
2022-08-28T10:19:34.5624905Z /home/runner/work/darktable/darktable/src/src/libs/metadata_view.c:748:40: fatal error: implicit conversion from 'unsigned int' to 'float' changes value from 4294967295 to 4294967296 [-Wimplicit-const-int-float-conversion]
2022-08-28T10:19:34.5625473Z         if(img->exif_focus_distance == UINT32_MAX)
2022-08-28T10:19:34.5625716Z                                     ~~ ^~~~~~~~~~
2022-08-28T10:19:34.5626094Z /usr/include/stdint.h:129:23: note: expanded from macro 'UINT32_MAX'
2022-08-28T10:19:34.5626392Z # define UINT32_MAX             (4294967295U)
2022-08-28T10:19:34.5626613Z                                  ^~~~~~~~~~~
2022-08-28T10:19:34.5626828Z 1 error generated.

```

**Comment by gi-man** [comment]
I built this on windows to test it. It solved the windows issues we were seeing. I'm able to do multiple exposure adjustments without any crash.

**Comment by jenshannoschwalm** [comment]
I will think if there is a fix for 4.0.1 too.

**Comment by jenshannoschwalm** [comment]
@gi-man thanks for testing!

**Comment by gi-man** [comment]
I did more stress test to see if I could make it crash. I set the resourced to small and tried to do a lot of exposure adjustments fairly fast with the keyboard adjustment. I could not get it crash. It is good to go in my opinion.

File: src/develop/pixelpipe_cache.c [hunk 1]
```diff
@@ -213,84 +212,83 @@ static int _get_oldest_cacheline(dt_dev_pixelpipe_cache_t *cache)
...
     cache->allmem -= cache->size[oldest];
- 
+    freed += cache->size[oldest];
     cache->size[oldest] = 0;
     cache->data[oldest] = NULL;
     cache->hash[oldest] = -1;
     cache->basichash[oldest] = -1;
-    cache->used[oldest] = 1;
-    oldest = _get_oldest_cacheline(cache);
+    cache->used[oldest] = 1000;
```
Comment (TurboGit) [inline src/develop/pixelpipe_cache.c:230]: We have 1000 used in 3 more places. IIUC this is an "old" age for the entry. Probably using a #define (a named number) for this would make the code easier to read.

File: src/develop/pixelpipe_cache.c [hunk 2]
```diff
@@ -182,26 +178,29 @@ gboolean dt_dev_pixelpipe_cache_available(dt_dev_pixelpipe_cache_t *cache, const
...
+    }
+  }
+  return id;
 }
 
-static int _get_oldest_cacheline(dt_dev_pixelpipe_cache_t *cache)
+static int _get_oldest_used_cacheline(dt_dev_pixelpipe_cache_t *cache)
 {
-  int weight = -1;
+  int weight = 16;
```
Comment (TurboGit) [inline src/develop/pixelpipe_cache.c:199]: Also 16 here... Could probably help to use a named number for add a comment.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Some minor changed proposed.

File: src/develop/pixelpipe_cache.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/develop/pixelpipe_cache.c:230]: good point

File: src/develop/pixelpipe_cache.c (hunk 2 above)
Comment (jenshannoschwalm) [reply src/develop/pixelpipe_cache.c:199]: did a comment here explaining why ...

**Comment by jenshannoschwalm** [comment]
> Some minor changed proposed.

done

**Comment by jenshannoschwalm** [comment]
@TurboGit i did two late changes (not changing functionality) just to improve debugging issues possibly related to iop cache correctness.
1. tabbed output of full cache data via dt_vprint
2. the reweight function should not change module information

Ready to go from my side

**Review by TurboGit — APPROVED** [review]
Looks ok to me now. Thanks!

**Comment by jenshannoschwalm** [comment]
@TurboGit i rechecked pixelpipe problems in 4.0 branch.

Indeed i could reproduce (rarely and only in darkroom) failures. I am not completely sure here - we don't have good ways to keep track of the cache - but it seems to be related to more than one darkroom module in expanded state. From my understanding this can happen as we might have more than 3 cachelines in important state so there might be not enough "old" buffers while processing the pixelpipe.
ATM i don't have a good idea how to fix this properly.

**Comment by paolodepetrillo** [comment]
This change seems to be causing a crash for me. I'm running on Arch Linux, Core i7-5820K, 16GB RAM, OpenCL enabled with a GTX 1080, very fast GPU scheduling profile.

The crash is consistently reproducible, usually on an image that has some slower modules (D&S, HL reconstruction with guided laplacians), almost always in the crop module when changing the aspect ratio or adjusting the crop.

The error message "munmap_chunk(): invalid pointer" is printed, and the crash occurs on a call to free() from _get_free_cacheline at pixelpipe_cache.c:225. Backtrace from gdb is attached.
[bt.txt](https://github.com/darktable-org/darktable/files/9483800/bt.txt)

The crash occurs with the latest master 5cca9d64 and with the commit where this was merged dc536632, but does not occur with the previous commit e3b1f3ae.
