### PR TITLE
don't show inactive picker under snapshot overlay

### LINKED ISSUE #15626: [DT 4.5.0] When snapshot is activated, canvas gets a selection area
### Describe the bug

If you have previously used color pickers in one of the modules, even if you are in another module, if you have created a snapshot and then activated it, the selection area remains active.

image

### Steps to reproduce

1. use a color picker in a module (e.g. exposure, color calibration)
2. then use another module
3. create snapshot
4. activate it
5. a selection area appears on the canvas
6. deactivate snapshot  
7. selection area disappears

To solve the problem:

1. activate snapshot again 
2. activate _color picker_ in the color _picker module_
3. selection area is switched off

### Expected behavior

Selection area should no longer be displayed after changing the module and after activating the snapshot.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1138~g8fa44f311

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-1028-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070/PCIe/SSE2, 535.129.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #15626

Also fixes https://github.com/darktable-org/darktable/pull/15546#issuecomment-1793453837;
when the retouch module was _focused_ but not _enabled_, the crop module would not show an outline of the crop area (like it did if liquify was focused). You had to enabled and then un+refocus retouch to see the crop outline.

@jenshannoschwalm I don't think we only want to see the outline when the "requester" is enabled, but rather always when crop is temporarily disabled. So I've simplified the logic a little bit. Let me know if I overlooked something.

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
I think your idea I good and what we have now is better than before. Can't test thoroughly though, deep in opencl stuff atm.

File: src/develop/imageop.h [hunk 1]
```diff
@@ -569,7 +569,7 @@ gboolean dt_iop_have_required_input_format(const int required_ch,
                                            const dt_iop_roi_t *const roi_in,
                                            const dt_iop_roi_t *const roi_out);
 
-
+gboolean dt_iop_canvas_not_sensitive(const struct dt_develop_t *dev);
```
Comment (TurboGit) [inline src/develop/imageop.h:572]: I'll add a little comment here.

**Review by TurboGit — CHANGES_REQUESTED** [review]
A minor comment, code ok to me and works fine.

File: src/develop/imageop.h (hunk 1 above)
Comment (TurboGit) [reply src/develop/imageop.h:572]: Reading my comment I see that it is not really clear... I meant that a comment is needed here and not that I'll add it myself :)

Comment (dterrahe) [reply src/develop/imageop.h:574]: I only read quickly and indeed misunderstood, but makes more sense this way ;-)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by jenshannoschwalm** [comment]
Nice to see the requester workaround fixed!
