### PR TITLE
wrap degrees around when entered or horizon drawn

### LINKED ISSUE #14008: rotate and perspective clips at 180 degrees rendering the horizontal line ineffective.
**Describe the bug/issue**
Darktable 4.2.1 (Windows), rotate and perspective

For example when scanning images you can end up having an image that is rotated wrong by around 180 degrees.
Lets assume the image is 182° wrongly rotated and you use the rotate and perspective > rotation slider and enter 180.
You will see that you are very close but want a bit more rotation (2° in this example).
Now what will not work:

1. Using the Bauhaus slider you cannot extend over the 180, as this is the limit. You cannot use the mouse for the remaining 2° nor can you enter 182 - its always clipped to 180.

2. Using  the mouse and right-click to draw the horizontal line: Even though 2° is correctly detected and written on the screen, it wont be applied. There is also no error message, so the user might have the impression that the operation was successful.

The workaround is to rotate the image to -180 instead in the first place. Then the Bauhaus Slider and the line will work, as -178 is not clipped.

--- 

My expectation is that the rotation is doing a roundtrip.
Check the book "3D Math Primer for Graphics and Game Development. Second Edition, page 241."
f(x)= x-360°*Floor((x+180°)/360°)

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #14008 and should also deal correctly with manually entered values.

Since this impacts _all_ degree and gradient sliders, it would be much appreciated if this got some testing (from @codingdave and others).

### CODE REVIEW

File: src/bauhaus/bauhaus.c [hunk 1]
```diff
@@ -2595,7 +2595,7 @@ static void _slider_add_step(GtkWidget *widget, float delta, guint state, gboole
   }
   else if(!strcmp(d->format,"°") && (d->max - d->min) * d->factor == 360.0f
           && fabsf(value + delta)/(d->max - d->min) < 2)
```
Comment (ralfbrown) [inline src/bauhaus/bauhaus.c:2597]: It might be worthwhile allowing a bit of fuzz on the comparison to 360, i.e.
`fabsf((d->max - d->min) * d->factor - 360.0f) < 0.0001f`
since the result after multiplying the difference may not be exact.

Comment (dterrahe) [reply src/bauhaus/bauhaus.c:2597]: This is meant to deal with 0-360, -180 - +180 and 0-1 * 360, so not scaled diffs between random close numbers. Seems to work fine on my Intel, but if there's a not-purely-theoretical chance it behaves differently on other architectures, it would be worth sacrificing some readability. Or even spell out those options. What do you think?

Comment (ralfbrown) [reply src/bauhaus/bauhaus.c:2597]: I brought up the issue because one of my recent speedups was adding the fuzz factor so that the default neutral setting would actually cause the processing code to be skipped as intended - after a double-click to reset the slider to 1.0, the actual value read from three different sliders was 0.9999999 or 1.0000001.

Comment (dterrahe) [reply src/bauhaus/bauhaus.c:2597]: Can you provide a link to the change please? Not sure if you are saying you introduced this small diff on purpose or found that it unintentionally appeared in bauhaus. If first, it "shouldn't" impact the min/max values, if the latter, then, well...

Comment (ralfbrown) [reply src/bauhaus/bauhaus.c:2597]: I introduced it on purpose in src/iop/colorbalance.c.
e.g. `const int run_saturation = fabsf(saturation - 1.0f) > 1e-6;`
instead of `const int run_saturation = (saturation != 1.0f);`

Comment (dterrahe) [reply src/bauhaus/bauhaus.c:2597]: Interesting...

Those are _slightly_ more complex cases in that they have
`dt_bauhaus_slider_set_soft_range(..., 0.5f, 1.5f);`, scaling factor of 100 (-100) and in one case an offset. There are even more fun ones where a whole non-linear transformation function is applied backwards and forwards so I would be more surprised if that _didn't_ introduce rounding errors.

I'll introduce a fuzz out of abundance of caution. Thanks!

**Comment by TurboGit** [comment]
Works ok for:
- Rotation in Rotation & perspective module
- Hue in Colorize module
- Hue Shift in Color Balance RGB module
- Rotation in Blurs module
- Rotation in Graduated density

So looks fine... I'll let some more times for others to test.

**Review by TurboGit — APPROVED** [review]

**Comment by jenshannoschwalm** [comment]
No issues here.

**Review by TurboGit — APPROVED** [review]
Let's move forward indeed. Thanks!

**Comment by dterrahe** [comment]
Release Note:
- In rotate & perspective, if the current rotation is close to +-180 degrees, adjusting it by drawing a horizon line with right-click+drag could lead to it being clipped at the end of the slider. It now correctly wraps around and a manually entered value outside the range, like 182, will be wrapped as well, to -178 degrees.

**Comment by TurboGit** [comment]
Thanks!

**Comment by codingdave** [comment]
Thanks guys, I now have been able to test that feature and it turns out a big improvement (small things matter:-)). This speeds up my workflow and gives very human numbers. Thanks!
