### PR TITLE
Avoid calling gnubin executables during macos build

### LINKED ISSUE #20613: Mac build fails if /opt/local/libexec/gnubin is in PATH
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

If `/opt/local/libexec/gnubin` (or `$(brew --prefix coreutils)/libexec/gnubin`) is early in PATH, the versions of `find` and `sed` invoked will be the GNU versions. The arguments differ from the Mac versions in incompatible ways. I fixed it by prepending "/usr/bin/" to these two commands. Other commands seem to work, but the future-compatible fix is to be sure we are never calling the gnu executables by removing "gnubin" from PATH or moving it to the end.

### Steps to reproduce

1. Install homebrew
2. `brew install findutils gnu-sed`
3. Add `$(brew --prefix coreutils)/libexec/gnubin`) to the beginning of PATH
4. Run the packaging/macos homebrew build scripts
5. The error output is:
```
sed: can't read s|{VERSION}|5.5.0|: No such file or directory
./3_make_hb_darktable_package.sh{}:209: Error: command `sed -i '' 's|{VERSION}|'$(git describe --tags --long --match '*[0-9.][0-9.][0-9]' | cut -d- -f2 | sed 's/^\([0-9]*\.[0-9]*\)$/\1.0/')'|' "$dtWorkingDir"/Contents/Info.plist` failed with exit code 2
```

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

236065061667623f2521f04b3918c1331598017f

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 15

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by lefth**
This fixes #20613.

### CODE REVIEW

**Comment by zisoft** [comment]
See my comment here: https://github.com/darktable-org/darktable/issues/20613#issuecomment-4102425761

The darktable build scripts don't require or install gnubin, so please fix your system setup.

**Comment by zisoft** [comment]
I am still not convinced about these changes.

These changes are necessary for YOU, because YOU have changed the standard behavior of YOUR system.

Sure, we can add `/usr/bin` to the tools to make sure the system tools are used, but then we should be complete here: `cut`, `grep`, ...

File: packaging/macosx/3_make_hb_darktable_package.sh [hunk 1]
```diff
@@ -33,11 +33,11 @@ function install_dependencies {
     absolutePath=$(dirname $(grealpath "$1"))
 
     # Get dependencies of current executable
-    oToolLDependencies=$(otool -L "$1" 2>/dev/null | grep compatibility | cut -d\( -f1 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' | uniq)
+    oToolLDependencies=$(otool -L "$1" 2>/dev/null | grep compatibility | cut -d\( -f1 | /usr/bin/sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' | uniq)
 
     # Handle library relative paths
-    oToolLDependencies=$(echo "$oToolLDependencies" | sed "s#@loader_path#${absolutePath}#")
-    oToolLDependencies=$(echo "$oToolLDependencies" | sed "s#@rpath#${absolutePath}#")
+    oToolLDependencies=$(echo "$oToolLDependencies" | /usr/bin/sed "s#@loader_path#${absolutePath}#")
```
Comment (TurboGit) [inline packaging/macosx/3_make_hb_darktable_package.sh]: That's wrong, you need to use PATH and never use full path in a script.

**Comment by lefth** [comment]
I'll see if I can tweak the calls to utility binaries to be cross platform. And yes, I know that's silly. It's Mac. It's not cross platform. Yet this is a homebrew installation accept, and homebrew sanctions putting the GNU utilities in PATH.

**Comment by zisoft** [comment]
> and homebrew sanctions putting the GNU utilities in PATH

No, homebew does not overwrite the standard system utilities, it installs the GNU utilities with the prefix "g":

```
All commands have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
PATH="$HOMEBREW_PREFIX/opt/findutils/libexec/gnubin:$PATH"
```

YOU have changed the PATH to overwrite the standard system utilities.

How should darktable take into account the personal preferences of countless users? The scripts are written to support the minimal standard system installation.

As I already wrote in your issue report, it would be an easy step to write a simple shell script which restores the system PATH and calls the darktable build scripts.

**Comment by lefth** [comment]
@zisoft Those directions you quoted are the directions I followed. I didn't do anything with the system configuration, nor install files in inappropriate places.

My impression is that lowering friction for newbies is important. How easy a project is to build influences whether new contributors join the project. Most of the time, when people fail to build a project, you don't hear about it--they just give up. I'd like to correct one of those small roadblocks. And no, it doesn't affect everybody. It probably affects everyone that shell scripts on both Mac and Linux, though pure Mac users won't have this setup. (That said, I know darktable has a very dedicated team and would not make technically bad compromises for the dubious benefit of some few people being able to compile more easily.)

I didn't understand what you said about assuming a minimal system to support the build agents. Is it important to not change this script?

Failing that, as I said on the issue page, there are other ways to prevent this problem: invoke the commands in a portable way, print a specific error, or add a sentence to the build instructions.

**Comment by zisoft** [comment]
@lefth : 
I agree with @TurboGit comment above, and my personal opinion is to not use absolute paths in install scripts.
But that does not mean that I am not open to suggestions.

So let's ask what a coding AI agent tells us in this modern times of software development. Let me quote the answer here:

> Based on the analysis of packaging/macosx/3_make_hb_darktable_package.sh, it is recommended to rely on the PATH rather than using absolute paths for system binary tools like sed, find, and grep.
> Here is the reasoning for this recommendation:
> 1.  Portability across macOS Environments:
>     *   While system tools usually live in /usr/bin or /bin, users (or CI environments) might use package managers like Homebrew or MacPorts that install tools in /usr/local/bin or /opt/homebrew/bin.
>     *   Relying on PATH allows the user to control which version of the tools is prioritized.
> 2.  Tool Specificity (BSD vs. GNU):
>     *   The script uses BSD-style syntax for sed (specifically sed -i '', seen on lines 209, 210, 285, etc.). This syntax is native to macOS's default sed.
>     *   If you hardcoded /usr/bin/sed, you would enforce the system version. However, if a user has configured their environment to use GNU tools (e.g., gnubin in path), this script might actually fail because GNU sed handles -i differently. Relying on PATH implies "use the tool configured for this environment," which is generally the expected behavior for build scripts.
> 3.  Readability and Maintenance:
>     *   The script is significantly cleaner without full paths cluttering the logic.
>     *   The script already relies on PATH for brew, git, otool, install_name_tool, and pkg-config. Being inconsistent by hardcoding only sed or grep would add confusion.
> Exception / nuance:
> The only strong argument for absolute paths is security (avoiding path hijacking), but for a build script intended to be run by a developer or a CI runner in a controlled environment, this risk is minimal compared to the loss of flexibility.
> Proposed Action:
> Keep the script as is regarding tool invocation. Do not change sed to /usr/bin/sed.

Based on this answer and since I am the maintainer of this script, I would really like to end the discussion here.

@TurboGit : I vote for closing this PR

**Comment by lefth** [comment]
I removed the absolute paths and added a check/error if `which sed` refers to the same file as `which gsed`.

Making the calls actually wasn't possible without making the script fairly ugly or requiring perl, so I didn't go that route.

I've also said all I have to say on the topic. Thanks for your consideration.

File: packaging/macosx/3_make_hb_darktable_package.sh [hunk 2]
```diff
@@ -11,6 +11,11 @@
 set -e -o pipefail
 trap 'echo "${BASH_SOURCE[0]}{${FUNCNAME[0]}}:${LINENO}: Error: command \`${BASH_COMMAND}\` failed with exit code $?"' ERR
 
+if [[ "$(realpath "$(which sed)")" == "$(realpath "$(which gsed)")" ]]; then
```
Comment (TurboGit) [inline packaging/macosx/3_make_hb_darktable_package.sh]: Either that (failing / exit 1) or a simple fallback:

```
SED=sed

if [[ "$(realpath "$(which sed)")" == "$(realpath "$(which gsed)")" ]]; then
   SED=/usr/bin/sed
fi
```

And use `$SED` instead of `sed` in the script.

@zisoft : Would that work or is having gnubin in the `PATH` possibly bringing more issues?

Comment (zisoft) [reply packaging/macosx/3_make_hb_darktable_package.sh]: @TurboGit : Having gnubin prepended to PATH is the root cause of the problems @lefth encountered and the reason for this PR. This replaces the system `sed` (and more) by the GNU version, which is not compatible with the script.

So we have 2 options here:

1. Since the coreutils (GNU version of the tools) is already a requirement of the macOS package build we can rewrite the script  to work with the GNU versions. 
2. Tell users which have gnubin prepended in their PATH that they are using a non system default installation (and this is exactly what homebrew tells the user during installation!) and error out the script (this is what this PR currently does).

> And use $SED instead of sed in the script.

This is possible too and needs further testing regarding the other tools which gnubin replaces.

To clarify: The GNU tools are installed with the `coreutils` package and homebrew gives a clear message about their usage:

```
All commands have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
PATH="$HOMEBREW_PREFIX/opt/findutils/libexec/gnubin:$PATH"
```

So this is NOT the default, it is a USER decision.

My proposal @lefth : 
Modify the script in a way that `sed` is replaced by `gsed` (don't use absolute paths!). If more tools are incompatible, (find, grep, cut, ...) do the same by using the appropriate `g...` versions.

...or let me know if I should takeover here to modify the script.

EDIT:
`gsed` is not a part of `coreutils`, so it seems you have even more tools installed which replace the standard system tools...

**Comment by zisoft** [comment]
Further analysis:

The GNU tools replace dozens of standard system tools like `cut`, `mkdir`, `sed`, `find`, ...

If we implement a solution just for `sed`, chances are high to run into the next problem with one of the other tools.

So I think the easiest way to solve this would be to simply add

```
# Ensure we use system tools (BSD sed, find, etc.) even if user has GNU tools in PATH
export PATH="/usr/bin:/bin:$PATH"
```

at the beginning of the script (just below the comment header).

I have tested this successfully.

@lefth , @TurboGit : What do you think?

If agreed, @lefth please update your PR.

**Comment by TurboGit** [comment]
Yes if there is dozen tools my solution is not good at all indeed.

I would agree that add PATH at the top is the solution for now.

In the long run maybe ensuring that GNU tools are installed and having the script migrated to use GNU tools would be best.

**Comment by lefth** [comment]
Thank you for the approval. I will also prepare another draft PR showing an implementation of what it would like to require and use the minimal amount of GNU utilities. I'm not a fan of adding extra utilities because it turns out most of them are in separate packages which darktable doesn't directly require.

**Comment by zisoft** [comment]
The scripts are for building and packaging, which works fine with basic system tools.
No need to install additional packages to do the same job.
