### PR TITLE
Ensure demosaic switched on/off depending on image type

### LINKED ISSUE #6992: Seg fault with darktable-generate-cache
darktable 3.3.0+1705~g2bdb83188
With 5K images and I constantly change between collections, the lighttable view was taking long to draw the images (5 in a row). It starts off fast but slows down over time.

Decided to build the cache and see if helped.

```
mchhil@xyz:~/darktable$ /opt/darktable/bin/darktable-generate-cache
creating complete lighttable thumbnail cache
creating cache directories
creating cache directory '/home/mchhil/.cache/darktable/mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d/0'
creating cache directory '/home/mchhil/.cache/darktable/mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d/1'
creating cache directory '/home/mchhil/.cache/darktable/mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d/2'
image 1/5078 (0.02%) (id:1)
image 2/5078 (0.04%) (id:2)
image 3/5078 (0.06%) (id:3)
image 4/5078 (0.08%) (id:4)
image 5/5078 (0.10%) (id:5)
image 6/5078 (0.12%) (id:6)
image 7/5078 (0.14%) (id:7)
image 8/5078 (0.16%) (id:8)
image 9/5078 (0.18%) (id:9)
image 10/5078 (0.20%) (id:10)
....
....
....
image 791/5078 (15.58%) (id:791)
image 792/5078 (15.60%) (id:792)
image 793/5078 (15.62%) (id:793)
**Segmentation fault (core dumped)**
```

This is what my cache directory structure looks like

\home\mchhil\.cache\darktable\mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d\5
\home\mchhil\.cache\darktable\mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d\3
\home\mchhil\.cache\darktable\mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d\0
\home\mchhil\.cache\darktable\mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d\1
\home\mchhil\.cache\darktable\mipmaps-aa9d315b7cd299e1db70d11c4a2ce8afc56563cb.d\2

Folders 3 and 5 were from before I ran generate cache based on timestamps.

No backtrace file available.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As reported in #6992 we might have a corrupt history with disabled demosaic module
for raw. The first attempt to fix this via #7015 was wrong.

As @TurboGit suggested we need a check for the image type, i tried to find a
generic solution but at least with the current code there seems to be no way.

This pr just ensures demosaic to set off for non-raws and to on for raws.
It also reports via the console and give a hint while in gui.

Should fix #6992

### CODE REVIEW

File: src/develop/pixelpipe_hb.c [hunk 1]
```diff
@@ -339,16 +339,44 @@ void dt_dev_pixelpipe_synch(dt_dev_pixelpipe_t *pipe, dt_develop_t *dev, GList *
...
+        }
+      }
+
+      piece->enabled = active;
       dt_iop_commit_params(hist->module, hist->params, hist->blend_params, pipe, piece);
     }
     nodes = g_list_next(nodes);
   }
+  if(hint)
+    dt_control_log(_("history problem detected\nplease report via the issue tracker\nincluding the xmp file"));
```
Comment (johnny-bit) [inline src/develop/pixelpipe_hb.c:379]: XMP and maybe image file itself if necessary?

**Comment by TurboGit** [comment]
I'm not fond of this but I cannot see a better solution and better than crashing. So let's merge. Thanks.
