### PR TITLE
A slightly more informative warning before database updating

### LINKED ISSUE #8887: Database upgrade takes a very long time with no visible progress
**Describe the bug/issue**

After backing up my configuration, I decided to try out darktable built from the master branch.

I ran darktable and a dialog popped up to upgrade data.db. The upgrade took a few moments.

Then a second dialog popped up to upgrade the library.db. This took almost 17 minutes. During this time, there was no feedback, either from the terminal or in the UI. It looked like darktable was hanging.

**To Reproduce**

1. Have a large library, like most users of darktable.
2. Upgrade darktable from one version to another.
3. Run darkable.
4. Wait for a very long time.

**Expected behavior**

I would have expected some sort of update process. There should be at least a UI spinner. Ideally, there would be a progress bar.

This has been an issue in previous updates. I've just been patient. I don't remember the whole update taking 17 minutes before, however.

**Platform**

* darktable version : 3.5.0~git2099.cf47c7e45f-5823.2
* OS                : Linux 5.11.17-300.fc34.x86_64
* Linux - Distro    : Fedora 34
* Memory            : 16 GB
* Graphics card     : Intel 620
* Graphics driver   : Intel NEO
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : Wayland
* Desktop           : GNOME 40
* GTK+              : gtk3-3.24.29-1.fc34.x86_64

```
this is darktable 3.5.0~git2099.cf47c7e45f-5823.2
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional context**

 - Can you reproduce with another darktable version(s)? Yes, this has happened on every upgrade with database changes. It seemed extra excessive this time around.
 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? No, because the delay scales with the library size, as darktable needs to upgrade the libraries.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #8887

We could do some more here but this should be of help anyway.

### CODE REVIEW

File: src/common/database.c [hunk 1]
```diff
@@ -2731,7 +2731,7 @@ void ask_for_upgrade(const gchar *dbname, const gboolean has_gui)
   char *label_text = g_markup_printf_escaped(_("the database schema has to be upgraded for\n"
                                                "\n"
                                                "<span style='italic'>%s</span>\n"
-                                               "\n"
+                                               "\nthis might take a very long time in case of a large database\n\n"
```
Comment (TurboGit) [inline src/common/database.c:2734]: I would remove the "very" as it is a bit frightening to me, saying it could takes hours or days. The upgrade is generally fast or done in "just" several minutes.

**Review by TurboGit — APPROVED** [review]
Thanks !
