### PR TITLE
Fix Lua API not reporting image rating correctly

### LINKED ISSUE #5475: Ratings of rejected images misreported in Lua API.
**Describe the bug**
The documentation for the Lua API states [(section 2.2.39)](https://www.darktable.org/lua-api/types_dt_lua_image_t.html#types_dt_lua_image_t_rating) that a rejected image's `rating` field is equal to -1.
However, in the current master revision, I am observing that rejected images have a `rating` field equal to 0, identical to that of unrated images.

**Platform (please complete the following information):**
 - Darktable Version: master revision 7c22327
 - OS: Fedora 32

### PR DESCRIPTION
**Pull request by wpferguson**
Changed image rating member to use dt_image_get_xmp_rating so that future rating flag changes only need to get changed in one place.

Fixes #5475

### CODE REVIEW

**Comment by wpferguson** [comment]
last commit message should say dt_image_set_xmp_rating rather than dt_set_xmp_rating.

File: src/lua/image.c [hunk 1]
```diff
@@ -182,9 +182,7 @@ static int rating_member(lua_State *L)
   if(lua_gettop(L) != 3)
   {
     const dt_image_t *my_image = checkreadimage(L, 1);
-    int score = my_image->flags & 0x7;
-    if(score > 6) score = 5;
-    if(score == 6) score = -1;
+    int score = dt_image_get_xmp_rating(my_image);
```
Comment (TurboGit) [inline src/lua/image.c:185]: const ?

Comment (wpferguson) [reply src/lua/image.c:185]: yes :)

**Comment by wpferguson** [comment]
@TurboGit  I should probably do a scan of the API and see if I can find any other hard coded values or duplicated logic.

File: src/lua/image.c (hunk 1 above)
Comment (wpferguson) [reply src/lua/image.c]: done

**Comment by TurboGit** [comment]
This looks good now. Thanks.

And yes, checking the Lua API is certainly important as we have made many changes for 3.2.
