### PR TITLE
[tiling] use size_t cast for operation in case we could have int overshoot in tile

### LINKED ISSUE #8510: Rotate segfaults in /home/darktable/rpmbuild/BUILD/darktable-3.4.1/src/develop/tiling.c:1143
Built darktable from rpm sourced designed for Fedora
[Mail@omen-gatworks ~]$ uname -a
Linux omen-gatworks 5.8.15-201.fc32.x86_64 #1 SMP Thu Oct 15 15:56:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Surprised it came together and worked.
Anyway, imported some 3k .jpgs as well as some NEF * nikon raw files"
Picked on one of them to play. During the rotate feature, darktable deceided to segfault.
Tried again, but used gdb to see where its issue is located:

On 3/18/21 10:12 AM, Postmaster wrote:
> param: 4, val: 0
> cl_get_gt_device(): error, unknown device: 0
> Cloning into '/home/darktable/.config/darktable/lua'...
> remote: Enumerating objects: 47, done.
> remote: Counting objects: 100% (47/47), done.
> remote: Compressing objects: 100% (32/32), done.
> remote: Total 3499 (delta 26), reused 31 (delta 15), pack-reused 3452
> Receiving objects: 100% (3499/3499), 939.66 KiB | 34.00 KiB/s, done.
> Resolving deltas: 100% (2283/2283), done.
> fatal: destination path '/home/darktable/.config/darktable/lua' already
> exists and is not an empty directory.
> fatal: destination path '/home/darktable/.config/darktable/lua' already
> exists and is not an empty directory.
> Segmentation fault (core dumped)
======================================================
> command name abbreviations are allowed if unambiguous.
> (gdb) bt
> #0  0x00007ffff7af1532 in __memmove_avx_unaligned_erms () at /lib64/libc.so.6
> #1  0x00007ffff7d9ba05 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string_fortified.h:34
> #2  _default_process_tiling_roi._omp_fn.1 () at /home/darktable/rpmbuild/BUILD/darktable-3.4.1/src/develop/tiling.c:1143
> #3  0x00007ffff77fcdce in gomp_thread_start () at /lib64/libgomp.so.1
> #4  0x00007ffff7973432 in start_thread () at /lib64/libpthread.so.0
> #5  0x00007ffff7a8d913 in clone () at /lib64/libc.so.6
> (gdb)

thats all i know.

### PR DESCRIPTION
**Pull request by johnny-bit**
fixes #8510

While i'm not 100% sure about it and i never managed to reproduce problem in 8510 but this is probably the least invasive way to "fix" this.

Also since we haven't heard from op on that it's probably best case scenario for that issue.

### CODE REVIEW

File: src/develop/tiling.c [hunk 1]
```diff
@@ -1777,8 +1777,8 @@ static int _default_process_tiling_cl_roi(struct dt_iop_module_t *self, struct d
       piece->pipe->tiling = 1;
 
       /* the output dimensions of the good part of this specific tile */
-      const size_t wd = (tx + 1) * tile_wd > roi_out->width ? roi_out->width - tx * tile_wd : tile_wd;
```
Comment (TurboGit) [inline src/develop/tiling.c:1780]: Why removing the `const` here ?

Maybe double check that above we can also add const ?

Comment (johnny-bit) [reply src/develop/tiling.c:1780]: copypasta got ahold of me here ;) will fix! thank!

**Review by TurboGit — APPROVED** [review]
Thanks !
