### PR TITLE
Fix integer overflows in size_t calculations

### LINKED ISSUE #3298: loading huge EXR image crashes
**Describe the bug**
`darktable 32000x18000.exr` → segmentation fault, and `darktable` can no longer be started from that directory without crashing

**To Reproduce**
1. Create an EXR file with very large image size (I tried 32000x18000 which crashes; 16000x9000 loads ok)
2. Try to load it in `darktable`
3. Crash

**Expected behavior**
Ideally, for the image to be loaded successfully.
Pragmatically, an error message saying that the dimensions are too big, without a crash.

**Platform (please complete the following information):**
 - OS: Debian Buster
 - Version: git master at `release-3.0.0rc0-22-gc03143cb9`

**Additional context**
My EXR files have R G B half channels.  They contain computer generated fractal imagery generated with https://mathr.co.uk/kf/kf.html whose output tiles were assembled into a large image using https://mathr.co.uk/exrtact

**Crash log**
[darktable_bt_72GVA0.txt](https://github.com/darktable-org/darktable/files/3811088/darktable_bt_72GVA0.txt)

### PR DESCRIPTION
**Pull request by johnny-bit**
This is 2-parter:

1. fixes incorrect assumption about data size, now forces calculation using platform dependent size_t

Fixes #3298

2. in many places in code we've had things like `malloc(3*width*height*sizeof(float))` which would turn whole operation into signed int based, causing wraparound effect for large enough width & height.

this changeset should allow for processing of gigantic images on 64-bit systems (over 135 MPix) where otherwise mem allocations could fail due to size calculation wrapping around.

for reference see #3298

There still might be places where allocations are wrongly calculated. This might be a suggestion for future reference ;)

//EDIT:

Might be linked to #2607 problems...

### CODE REVIEW

**Comment by ralfbrown** [comment]
I would have sworn  int\*int\*long promotes everything to `long` before multiplying, but I just checked the generated code and it does in fact do the first multiplication using `int` and then promotes for the second multiply, while long\*int\*int does both multiplications using longs.

May I suggest that anywhere you modify a call to `dt_alloc_align` which is allocating floats, you go right to calling `dt_alloc_align_float` instead?  For example
```
    float *const buf = dt_alloc_align(64, 4 * height * width * sizeof(float));
```
becomes
```
   float *const buf = dt_alloc_align_float((size_t)4 * height * width);
```
[without the `size_t` cast, we could still handle 500Mpix images in this example]

That wil reduce the number of instances of the magic constant 64 to be changed if there is ever a port to an architecture that requires stricter alignment.

**Comment by johnny-bit** [comment]
OK, working on it!

**Comment by johnny-bit** [comment]
Huh... what else would need to be changed.. all calls to `*alloc*()` need to be inspected... halp...

**Comment by ralfbrown** [comment]
> Huh... what else would need to be changed.. all calls to `*alloc*()` need to be inspected... halp...

True.  Also memcpy().  Probably every line containing "sizeof(float)" if you want to be thorough....  But at least this is something that can be done incrementally, not something where you have to handle every occurrence before you can merge.

File: src/common/box_filters.c [hunk 1]
```diff
@@ -493,7 +493,7 @@ static void dt_box_mean_1ch(float *const buf, const int height, const int width,
                             const int iterations)
 {
   const int size = MAX(width,height);
-  float *const restrict scanlines = dt_alloc_align(64, 4 * size * sizeof(float) * dt_get_num_threads());
+  float *const restrict scanlines = dt_alloc_align_float((size_t)4 * size * dt_get_num_threads());
```
Comment (dterrahe) [inline src/common/box_filters.c:496]: alternatively, you could redefine dt_get_num_threads as
`static inline size_t dt_get_num_threads()`
(and reorder the multiplication)

That would get rid of a fair number of the explicit `(size_t)` casts. And is arguably a more logical interface.

File: src/common/eaw.c [hunk 2]
```diff
@@ -603,7 +603,7 @@ void eaw_dn_decompose(float *const restrict out, const float *const restrict in,
   static const float filter[5] = { 1.0f / 16.0f, 4.0f / 16.0f, 6.0f / 16.0f, 4.0f / 16.0f, 1.0f / 16.0f };
   const int boundary = 2 * mult;
   const int nthreads = dt_get_num_threads();
```
Comment (dterrahe) [inline src/common/eaw.c:605]: This should then be `const size_t nthreads = dt_get_num_threads();` as well

File: src/common/imageio.c [hunk 3]
```diff
@@ -91,7 +91,7 @@ int dt_imageio_large_thumbnail(const char *filename, uint8_t **buffer, int32_t *
     // Decompress the JPG into our own memory format
     dt_imageio_jpeg_t jpg;
     if(dt_imageio_jpeg_decompress_header(buf, bufsize, &jpg)) goto error;
-    *buffer = (uint8_t *)dt_alloc_align(64, (size_t)sizeof(uint8_t) * jpg.width * jpg.height * 4);
+    *buffer = (uint8_t *)dt_alloc_align(64, (size_t)sizeof(uint8_t) * 4 * jpg.width * jpg.height);
```
Comment (dterrahe) [inline src/common/imageio.c:94]: the cast can be removed here?

File: src/common/iop_profile.c [hunk 4]
```diff
@@ -1407,7 +1407,7 @@ int dt_ioppr_transform_image_colorspace_cl(struct dt_iop_module_t *self, const i
   else
   {
     // no matrix, call lcms2
-    src_buffer = dt_alloc_align(64, width * height * ch * sizeof(float));
+    src_buffer = dt_alloc_align_float((size_t) ch * width * height);
```
Comment (dterrahe) [inline src/common/iop_profile.c:1410]: Or define ch as `const size_t ch = 4;` above?

File: src/common/nlmeans_core.c [hunk 5]
```diff
@@ -405,7 +405,7 @@ void nlmeans_denoise(const float *const inbuf, float *const outbuf,
 #endif /* CACHE_PIXDIFFS */
   const int padded_scratch_size = 16*((scratch_size+15)/16); // round up to a full cache line
   const int numthreads = dt_get_num_threads() ;
```
Comment (dterrahe) [inline src/common/nlmeans_core.c:407]: size_t

File: src/common/box_filters.c (hunk 1 above)
Comment (johnny-bit) [reply src/common/box_filters.c:496]: while I do agree, the `dt_get_num_threads` is basically a call to `omp_get_num_procs` which returns int :/ So I'm down to changing def to size_t if I get a buy-in... @TurboGit or @ralfbrown or others :)

Comment (ralfbrown) [reply src/common/box_filters.c:496]: I'm fine with casting the result from `omp_get_num_procs`.  If it ever returns a value < 1, lots of stuff in dt will blow up.  And it will be a *very* long time until there's a shared-memory machine with more than 2 billion CPUs....

File: src/common/nlmeans_core.c (hunk 5 above)
Comment (johnny-bit) [reply src/common/nlmeans_core.c:407]: sure... @ralfbrown - I need your recommendation on this, I think @dterrahe is right here.

Comment (ralfbrown) [reply src/common/nlmeans_core.c:407]: Sure `size_t numthreads`.  If you want to be thorough, `scratch_size` and `padded_scratch_size` could also be made `size_t`.  There's a second copy of that code for the SSE path near line 630.

Comment (johnny-bit) [reply src/common/nlmeans_core.c:407]: OK, I'll work on that tomorrow then! Thank you @dterrahe & @ralfbrown !

**Comment by TurboGit** [comment]
@johnny-bit : conflicts resolution is needed. TIA.

**Comment by dterrahe** [comment]
nice job!

**Comment by johnny-bit** [comment]
OK, this should be "done" - meaning: No actual change was made, all image ops return exact same results, just in extreme cases when int overflows might happen, this should be more resilent.

@TurboGit - I've set milestone to 3.4.1 since despite "large area" this should be miniscule change overal.

**Review by dterrahe — APPROVED** [review]
Looks good to me. A pity that c requires all this extra work as it seems it should be able to use a function's param type to immediately promote the first element of a multiplication, but they probably thought they had a very good reason not to standardize it that way.

Just to prove I did review (but of course not every line);
`double *As = calloc((size_t)wd * S, sizeof(double));`
could be
`double *As = calloc(sizeof(double) * wd * S, 1);`
;-)

From now on, it will be up to Pascal to check _every new commit_ for this kind of error. It is a pity that it is not obvious, when copying any copy snippets, that one as to be careful with reordering multiplications :-/

**Comment by johnny-bit** [comment]
Actually calloc should stay as is ;) after all it's `calloc(num_of_elems, size_of_elem)` :wink:

**Comment by dterrahe** [comment]
> Actually calloc should stay as is ;) after all it's `calloc(num_of_elems, size_of_elem)` 😉

Hm, so  `double *target_L = (double *)calloc(sizeof(double), (N + 4));` is the wrong way around??

;-)

size_of_elem = 1 is fine. Or num_of_elems = 1. That's being used quite a few times, even in lines you have adjusted. I wasn't implying you should change any of that. The changes you made look fine and unfortunately necesssary. Thanks again for the boring cleanup work!

**Comment by TurboGit** [comment]
Merging, I have queued this for 3.4.1 and will see if it can be merged there without conflicts.
