### PR TITLE
fallback from midi knob press to knob turn for reset

### LINKED ISSUE #9944: Collections combobox broken
Selectable items don't show up, only section headers. This was broken by #9929. Fix incoming.

### PR DESCRIPTION
**Pull request by dterrahe**
Implements the default behaviour for Loupedeck and others where pressing a rotor down resets it to default position. Only turning the rotor needs to be mapped to a slider; the rotor _press_ can be assigned to something else, but if it has not been mapped to anything explicitly, it will fall back to resetting the same slider (or combo) that _turning_ the rotor is assigned to.

Midi devices where the note and cc do not have the same number will need an explicit override. Currently this is only implemented for x-touch mini and Loupedeck doesn't need it; other devices might not work correctly.

Also fixes #9944

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Very curious, I have not followed the whole new input system at all.

Is dt now supporting the loupedeck+ ?

**Comment by dterrahe** [comment]
> Is dt now supporting the loupedeck+ ?

Yep.

Although nobody has reported back with success stories. It would also be useful if somebody provided a template mapping (using shortcut export).

**Comment by jenshannoschwalm** [comment]
Do you have access to such a device? If not, I would get one and would let it to you for some months...

**Comment by dterrahe** [comment]
I don't, but there was a user many months ago (I'd have to look up the name I'm afraid), while I had the prototype midi interface going, who provided me with detailed data from it. It is a standard midi device and the codes it sends are very convenient, so I'm quite confident it simply works. But of course it would come as a blank slate, so you'd have to map each key/rotor yourself (which is easy) or wait for someone else to provide a basic template.

The only additional features that would be useful for it are:
- using real key names (as printed on the device) instead of midi "note" names. This needs some additional configuration/lua interfacing.
- saving/preconfiguring relative rotor encoding settings. Midi supports a number of different relative codings (a "down" move can be either 127, 63, 65, 31 or 15). Currently, at startup you have to slowly turn left one of the knobs until this encoding is detected, but this isn't saved yet. And a list could be maintained that gives known encodings for known devices. To be implemented.

If you get one and _do_ unexpectedly have any issues I'd gladly help you resolve them "remotely" if you provide clear issue reports/debug iterations.

One thing I'm unclear about is whether the little lights next to the lum/sat/hue buttons can be switched on with note messages or whether a different mechanism is used. Worst case they might get out of sync with the selected colorzones tab (which is what you would map them to).

File: src/gui/accelerators.c [hunk 1]
```diff
@@ -445,32 +440,30 @@ static gchar *_shortcut_key_move_name(dt_input_device_t id, guint key_or_move, g
   else
   {
     GSList *driver = darktable.control->input_drivers;
-    while(driver)
+    while(driver && (id -= 10) > 10)
+      driver = driver->next;
+
+    if(!driver)
+      name = g_strdup(_("Unknown driver"));
```
Comment (TurboGit) [inline src/gui/accelerators.c:447]: no capital letter here.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Minor style fix, TIA.

**Review by TurboGit — APPROVED** [review]
Good to me, thanks !
