### PR TITLE
Fix cacorrect multithreading

### LINKED ISSUE #15600: Darktable hangs on activating raw cacorrect
### Describe the bug

Activating Raw Chromatic Aberattion module causes to Darktable rendering thread to freeze. 

### Steps to reproduce

1) Import raw from https://discuss.pixls.us/t/thundery-summer-sunset-and-a-question-poll/34696 forum thread and switch to dark room mode.
2) Activate Raw Chromatic Aberration
3) 'Working...' will be shown over the image and will stay stuck. DT may still stay responsive if there is another thread in the pool, but pressing 'D' (to go back to Lighttable) will freeze it.

Afterwards, kill -9 will be necessary.
On restart, thumbnail generation also hangs (with DT responsive) and you can salvage by Discard History on the thumbnail, followed by Alt-F4 and another kill -9.
Starting with empty ~/.config/darktable did NOT help.
I did not notice high CPU usage and I couldn't find the hung thread with gdb, unfortunately.
I've been seeing the problem on master for months - I have a large archive of old edits with Raw Chromatic Aberration module active and they were getting nuked as soon as I clicked on them - but due to the nature of the issue, I couldn't pinpoint the module that was causing it.

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

master, problem replicable for the last several months

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 20.04

### Describe your system?

Using x11, DT compiled with clang-12.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GTX 1080, nvidia-driver-520

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Make sure all internal buffers are aligned-64 to allow vectorisation avoiding overflow from one to the next buffer.
Ideas:
1. Assume the OpenMP is correct
2. Compiler does some vectorisation
3. Make sure all internal buffers are strictly aligned to 64

@sh1llo try to get into your issue (fearing it might not be a compiler but a design problem in the algo), could you try this

EDIT: will keep working on this until fine ...

Fixes #15600

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
force pushed some workup, code readability, rounding fixes and declaring some parameters shared

I looked up file history here and spotted #15056 and #15116, i think the fix by @MStraeten didn't fix an apple but a clang issue.

I would like
1. @sh1llo to test this pr as is and
2. @MStraeten or @zisoft to test this PR plus remove the test for apple in `#if defined(_OPENMP) && !defined(__APPLE__)` in line 379

**Comment by MStraeten** [comment]
unfortunately this PR dosen't fix #15116, so disabling that parallelization at least for Apple M1 can't be dropped ...

**Comment by jenshannoschwalm** [comment]
Thanks Martin. Could you test with that passage being

```
#if defined(_OPENMP)
#pragma omp parallel
#endif

```

**Comment by zisoft** [comment]
So here are my results (Intel Mac, AMD Radeon 5500):

**current master without this PR**
 apply raw chromatic abberation --> ok

uncomment `#if defined(_OPENMP) && !defined(__APPLE__)`
apply raw chromatic abberation --> dt hangs (working...)


**current master with this PR**
apply raw chromatic abberation --> ok

uncomment `#if defined(_OPENMP) && !defined(__APPLE__)`
apply raw chromatic abberation --> dt hangs (working...)

So unfortunately no change for Apple

**Comment by jenshannoschwalm** [comment]
Thanks a lot for testing. It seems we have to test for gcc & openmp here.

Unfortunately I have no idea why this is so. Do we hit some building issue? Is  this a clang problem? Does our code not follow openmp specs?

**Comment by jenshannoschwalm** [comment]
Latest commit reverted some OpenMP pragmas, this make gcc running system here ~5% slower but hopefully allows running with threads on clang builds.

@MStraeten and @zisoft

**Comment by zisoft** [comment]
Tim Cook will hire you :-)

Works!!
And as far I can tell it is much faster now.

**Comment by MStraeten** [comment]
fixes #15116 on arm64

**Comment by jenshannoschwalm** [comment]
> Tim Cook will hire you :-)

I don't care about **that** but i live very close in Hamm so i would accept a coffee afetr a bike ride and see how you do things in darktable on a mac :-)

**Comment by jenshannoschwalm** [comment]
> And as far I can tell it is much faster now.

It should be, it's using multiple threads now :-)

**Comment by jenshannoschwalm** [comment]
@TurboGit i think ready to get merged now.

**Comment by zisoft** [comment]
> i live very close in Hamm so i would accept a coffee afetr a bike ride and see how you do things in darktable on a mac :-)

very much appreciated!

**Comment by sh1llo** [comment]
Tested with this pr, fixes the issue for me. Just to make sure, I checked my older edits that were freezing, and they also correctly open now.
+1 from me, and thanks!

File: src/iop/cacorrect.c [hunk 1]
```diff
@@ -440,7 +443,7 @@ void process(
       for(int top = -border; top < height; top += ts - border2)
```
Comment (dterrahe) [inline src/iop/cacorrect.c:443]: {

Nothing to do with your changes, but I'm surprised Pascal didn't ask for it :-)

File: src/iop/cacorrect.c [hunk 2]
```diff
@@ -340,93 +343,93 @@ void process(
...
 
     // shift the beginning of all arrays but the first by 64 bytes to avoid cache miss conflicts on CPUs which
     // have <=4-way associative L1-Cache
 
     // rgb data in a tile
     float *rgb[3];
     rgb[0] = (float(*))data;
-    rgb[1] = (float(*))(data + 1 * sizeof(float) * ts * ts + 1 * 64);
-    rgb[2] = (float(*))(data + 2 * sizeof(float) * ts * ts + 2 * 64);
+    rgb[1] = (float(*))(data + tilebuf_size);
```
Comment (dterrahe) [inline src/iop/cacorrect.c:418]: You can get rid of the explicit casts and sets of parentheses now, which makes this piece of code a bit more readable.

File: src/iop/cacorrect.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/iop/cacorrect.c:443]: indeed, makes that huge loop better to review

File: src/iop/cacorrect.c (hunk 2 above)
Comment (jenshannoschwalm) [reply src/iop/cacorrect.c:418]: rigth again

**Comment by jenshannoschwalm** [comment]
force pushed squashed suggested modifications

**Comment by dterrahe** [comment]
Just for my understanding/education (and maybe a bit of documentation, in case someone in future tries to claw back those 5% performance lost and inadvertently reintroduces the bug!) removing the "default(none)" pragma and explicit sharing declarations reverts all variables to _shared_.

Presumably this doesn't impact any of the consts (?) so that leaves _darktable_ (which is read in infrequently executed `dt_print` only) and _processpasstwo_. The latter doesn't seem to be referenced in an inner loop, so is the 5% hit surprising?

File: src/iop/cacorrect.c (hunk 1 above)
Comment (TurboGit) [reply src/iop/cacorrect.c:443]: I hadn't reviews yet :)

**Comment by jenshannoschwalm** [comment]
Nope, I would say and I don't see a way atm with other pragmas. We might try with simd and aligning hints though.

My major lesson for now - and I should have spotted it earlier - if there is something wrong about apple, it could be clang.

Maybe we should also do integration tests with clang?

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by TurboGit** [comment]
I'll have to analyze the regression test:

```
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 43.13434
      Avg dE                   : 0.65424
      Std dE                   : 3.53237
      ----------------------------------
      Pixels below avg + 0 std : 93.87 %
      Pixels below avg + 1 std : 96.61 %
      Pixels below avg + 3 std : 97.71 %
      Pixels below avg + 6 std : 98.80 %
      Pixels below avg + 9 std : 99.94 %
      ----------------------------------
      Pixels above tolerance   : 4.03 %
 
  FAILS: image visually changed
         see diff.png for visual difference
         (308908 pixels changed)

```

**Comment by TurboGit** [comment]
Hum... the diff is very suspicious as the right border is very different:

image

But the right border is a uniform color, and well it is indeed broken, see the new output:

image

So after all not ready for integration.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Something broken...

**Comment by jenshannoschwalm** [comment]
Will check and look if there was a problem or if this is a new problem.

**Comment by MStraeten** [comment]
can't reproduce that right border issue on my mac but have reproduced it with a windows build

**Comment by TurboGit** [comment]
@jenshannoschwalm : For the record, the first commit (2c9117e58ef6bce0f85c59bc98afd6d3b5e7ae1a) is introducing this regression.

**Comment by zisoft** [comment]
Same here, not reproducible on my Mac, but on Windows.
The green border appears when _avoid colorshift_ is checked.

Another thing I have noted: On Mac there is absolutely no visible difference when activating/deactivating the module.
No change in waveform or vectorscope.

Tested with mire1.cr2

**Comment by jenshannoschwalm** [comment]
Thanks for the first-commit suggestion. I looked at it again and there is indeed a very stupid bug when calculating the number of tiles. Will fix asap

**Comment by jenshannoschwalm** [comment]
Could you all test again, i think i understand the things i did wrong. Made sure about aligning and fixed (also renamed vars for readbility) wrongdoing for number of tiles to be calculated resulting in the border issue.

@TurboGit could you please check the integration test on your side? If everything goes right and no more requests after reviewing i would propose to
1. squash in 1 commit so everything is in one place
2. correct the commit message

**Comment by TurboGit** [comment]
@jenshannoschwalm : The test pass and is 100% identical to the expected output:

```
Test 0084-cacorrect
      Image mire1.cr2
      CPU & GPU version differ by 18288 pixels
      CPU vs. GPU report :
      ----------------------------------
      Max dE                   : 1.61430
      Avg dE                   : 0.00296
      Std dE                   : 0.04009
      ----------------------------------
      Pixels below avg + 0 std : 99.34 %
      Pixels below avg + 1 std : 99.35 %
      Pixels below avg + 3 std : 99.37 %
      Pixels below avg + 6 std : 99.46 %
      Pixels below avg + 9 std : 99.55 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 0.00000
      Avg dE                   : 0.00000
      Std dE                   : 0.00000
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
  OK
```

**Comment by jenshannoschwalm** [comment]
Good. Will do the squashing later tonight.

**Comment by jenshannoschwalm** [comment]
Added another macro borderh for code readability, no algo stuff changed. Ready to go

**Review by TurboGit — APPROVED** [review]
All good now, thanks!

**Comment by jenshannoschwalm** [comment]
@ralfbrown could you have look too? Anything compiler specific, clang? Or some aligning stuff for osx?

**Comment by ralfbrown** [comment]
I'm not aware of any compiler-specific issues, but I also don't use clang.  Cacheline-alignment shouldn't have any impact other than performance (due to cachelines getting bounced between the two cores processing the pixels before/after the boundary a cacheline straddles).

I'll take a look, but it's a hefty chunk of code so I'll need to dedicate a block of time.  Probably over the weekend.

**Comment by jenshannoschwalm** [comment]
> I'll take a look, but it's a hefty chunk of code so I'll need to dedicate a block of time. Probably over the weekend.

:-) It really is hefty.
