### PR TITLE
[exif] add guard when accesssing fourth element of Exif.Olympus*.Gradation tags

### LINKED ISSUE #20011: darktable 5.4 can't open Olympus ORF files from E-410 and E-510 DSLRs
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

After updating to version 5.4, ORF files from Olympus E-410 and E-510 cameras can no longer be opened and edited in the darkroom, giving "File appears corrupt, switching to lighttable now".

Raw files work without any problem in the lighttable.

Same thing happened when I used appimage for darktable 5.4, creating a database from scratch.

The log when opening those files reads as "[rawspeed] (FILENAME.ORF) vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)".

Files in question are NOT corrupted - they've opened without any problem in previous versions of darktable, and they open in RawTherapee 5.9 now.

### Steps to reproduce

1. Open darktable
2. Import ORF files into lighttable.
3. Open any of the files

### Expected behavior

Open the file and allow editing

### Logfile | Screenshot | Screencast

./Darktable-5.4.0-x86_64.AppImage -d opencl
darktable 5.4.0
Copyright (C) 2012-2025 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Exiv2                  -> 0.28.7
  Lensfun                -> 0.3.2
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.6.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  OSMGpsMap              -> ENABLED  - map view is available
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  LibRaw                 -> ENABLED  - Version 0.22.0-PreRC1
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0026 [dt starting]
 /tmp/.mount_DarktahDhJdB/usr/bin/darktable -d opencl
Gtk-Message: 18:57:55.939: Failed to load module "xapp-gtk3-module"
     0.4849 [opencl_init] opencl disabled via darktable preferences
     0.4854 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL'
     0.4856 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL.so'
     0.4866 [opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded, preference 'default path'
     0.4866 [opencl_init] 0 platforms detected, error: Unknown OpenCL error
     0.4866 [opencl_init] FINALLY: opencl PREFERENCE=OFF is NOT AVAILABLE and NOT ENABLED.
     8.4711 [rawspeed] (P6290647.ORF) vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)
   213.6291 [rawspeed] (_0060065.ORF) vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)
   245.4274 [rawspeed] (_0060073.ORF) vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)

### Commit

_No response_

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint Debian Edition 6 Faye (based on Debian 12)

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by ralfbrown**
It turns out that Olympus' Gradation info can consist of either three or four integers.  Avoid crashing when there are only three....

Should fix #20011, though I haven't had a chance to test yet.

### CODE REVIEW

**Comment by TurboGit** [comment]
Still not working for me:

`    61,5104 [rawspeed] (Olympus - E-410 - 16bit (4_3).ORF) vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)`

**Comment by ralfbrown** [comment]
Turns out that size() returns bytes, not  number of elements in tag....

**Comment by TurboGit** [comment]
I can read the RAW now, but the colors seems off:

image

**Comment by ralfbrown** [comment]
With a default/fresh config, I see a picture which looks reasonable (mostly green, since it's a closeup of a plant).

**Comment by kmilos** [comment]
> Turns out that size() returns bytes, not number of elements in tag....

Try count()

**Comment by TurboGit** [comment]
@ralfbrown : Sorry for the noise, I had some auto-preset applied... I'm testing so many things that sometime it feels as if my Darktable instance is broken :)

File: src/common/exif.cc [hunk 1]
```diff
@@ -1212,11 +1212,11 @@ static void _check_highlight_preservation(Exiv2::ExifData &exifData,
        ||FIND_EXIF_TAG("Exif.OlympusRd2.Gradation"))
     {
       // first three values specify one of the possible settings: Normal(Off), Auto, Low Key, High Key
-      // fourth specifies 0=user-selected or 1=auto-override
+      // fourth (if present) specifies 0=user-selected or 1=auto-override
       const long state1 = pos->toLong(0);
       const long state2 = pos->toLong(1);
       const long state3 = pos->toLong(2);
-      const long state4 = pos->toLong(3);
+      const long state4 = pos->size() > (int)(3*sizeof(short)) ? pos->toLong(3) : 0;
```
Comment (kmilos) [inline src/common/exif.cc]: `sizeof(short)` could depend on platform. Try `count()` instead of calculating byte size. Otherwise the TIFF type SSHORT is defined as `int16_t` in exiv2, which is guaranteed to be exactly 2 bytes in all implementations.

**Comment by ralfbrown** [comment]
Release note:
- fix crash for certain Olympus models when parsing highlight-preservation Exif tag
