### PR TITLE
xmp update fix

### LINKED ISSUE #5486: Update database from selected xmp files not working for tags
**Describe the bug**
When I update tags within XMP sidecar files in another application (eg. Digikam), darktable does not appear to update its database even though I select "update datebase from selected xmp files" within the "updated xmp sidecar files found" dialog when starting darktable.

This is also reproducible without another application.  See steps below.

**To Reproduce**
A pre-requisite is that both Digikam and darktable have their own libraries generated from the images in the same folder.  I created the Digikam library first (no XMP files were created or existed).  I then created darktable's library on the same folder, which created XMP files for each image.  darktable is configured to look for updated XMP files on start.  Digikam is configured to read and write XMP sidecar files.  For tags in particular, Digikam is configured to read and write both Xmp.dc.subject and Xmp.lr.hierarchicalSubject.

1.  Ensure both Digikam and darktable are closed.
2.  In Digikam, select a photo and add two tags.
3.  Close Digikam.  At this time, I confirm the tags are in both sections of the XMP file noted above.
4.  Open darktable
5.  At the "updated xmp sidecar files found" dialog, select the row and click "update database from selected xmp files".
6.  darktable does the right thing and imports the two tags.
7.  Close darktable
8.  Open Digikam
9.  Select the same image
10.  Remove one of the tags and select Apply
11.  Close Digikam.  At this time, I confirm that both sections of the XMP file contain the one tag.
12.  Open darktable
13.  At the "updated xmp sidecar files found" dialog, select the row and click "update database from selected xmp files".
14.  darktable continues to show two tags.
15.  Close darktable
16.  The XMP sidecar file has both tags in both sections.

An alternative way to reproduce without another application:
1.  Open darktable
2.  Assign two tags to an image
3.  Close darktable
4.  Edit the XMP sidecar file (using vi or similar editor) and remove one of the tags from both Xmp.dc.subject and Xmp.lr.hierarchicalSubject sections
5.  Open darktable
6.  At the "updated xmp sidecar files found" dialog, select the row and click "update database from selected xmp files".
7.  darktable continues to show two tags
8.  Close darktable
9.  The XMP sidecar file has both tags in both sections.

It appears that darktable didn't update the database.  It certainly updated the XMP files when it shouldn't have.

**Expected behavior**
darktable should update the database with the new XMP sidecar file content.  In the case above, the darktable database should have been updated to reflect one tag and should not have written the 2nd tag back to the XMP file.

**Screenshots**
Let me know if needed

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS:  Manjaro Linux 
 - OpenCL activated
 - Asus GTX Strix 1660 Super.  Nvidia proprietary drivers.

**Additional context**
All packages have been installed from the Manjaro repo (nothing compiled by me).

Sample XMP:
```
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:MicrosoftPhoto="http://ns.microsoft.com/photo/1.0/"
    xmlns:acdsee="http://ns.acdsee.com/iptc/1.0/"
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:lr="http://ns.adobe.com/lightroom/1.0/"
    xmlns:darktable="http://darktable.sf.net/"
   MicrosoftPhoto:Rating="0"
   acdsee:rating="0"
   exif:ApertureValue="196608/65536"
   exif:ColorSpace="1"
   exif:CustomRendered="0"
   exif:DateTimeOriginal="2020:01:26 21:22:42"
   exif:ExifVersion="0230"
   exif:ExposureBiasValue="0/1"
   exif:ExposureMode="0"
   exif:ExposureProgram="3"
   exif:ExposureTime="1/160"
   exif:FNumber="28/10"
   exif:FlashpixVersion="0100"
   exif:FocalLength="50/1"
   exif:FocalPlaneResolutionUnit="2"
   exif:FocalPlaneXResolution="5184000/907"
   exif:FocalPlaneYResolution="3456000/595"
   exif:MeteringMode="5"
   exif:PixelXDimension="5184"
   exif:PixelYDimension="3456"
   exif:SceneCaptureType="0"
   exif:ShutterSpeedValue="483328/65536"
   exif:WhiteBalance="0"
   photoshop:DateCreated="2020-01-26T21:22:42.92"
   tiff:Compression="6"
   tiff:ImageLength="3456"
   tiff:ImageWidth="5184"
   tiff:Make="Canon"
   tiff:Model="Canon EOS 7D"
   tiff:Orientation="1"
   tiff:ResolutionUnit="2"
   tiff:XResolution="72/1"
   tiff:YResolution="72/1"
   xmp:CreateDate="2020-01-26T21:22:42.92"
   xmp:ModifyDate="2020-01-26T21:22:42.92"
   xmp:Rating="0"
   xmpMM:DerivedFrom="IMG_1229.CR2"
   darktable:xmp_version="3"
   darktable:raw_params="0"
   darktable:auto_presets_applied="0"
   darktable:history_end="0"
   darktable:iop_order_version="0">
   <exif:ComponentsConfiguration>
    <rdf:Seq>
     <rdf:li>1</rdf:li>
     <rdf:li>2</rdf:li>
     <rdf:li>3</rdf:li>
     <rdf:li>0</rdf:li>
    </rdf:Seq>
   </exif:ComponentsConfiguration>
   <exif:Flash
    exif:Fired="True"
    exif:Function="False"
    exif:Mode="1"
    exif:RedEyeMode="False"
    exif:Return="0"/>
   <exif:ISOSpeedRatings>
    <rdf:Seq>
     <rdf:li>1250</rdf:li>
    </rdf:Seq>
   </exif:ISOSpeedRatings>
   <tiff:BitsPerSample>
    <rdf:Seq>
     <rdf:li>8 8 8</rdf:li>
    </rdf:Seq>
   </tiff:BitsPerSample>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>tag1</rdf:li>
     <rdf:li>tag2</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <lr:hierarchicalSubject>
    <rdf:Bag>
     <rdf:li>tag1</rdf:li>
     <rdf:li>tag2</rdf:li>
    </rdf:Bag>
   </lr:hierarchicalSubject>
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq/>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
```

### PR DESCRIPTION
**Pull request by phweyland**
- clean up metadata and tags before updating from xmp (triggered by crawler)
- read dt colors if xmp.xmp.label (from external app) not present instead of overwriting them
- some signal raise moved from common to libs (dead locks in _exif_decode_xmp_data)
- ~~some memory leak fixes (g_list_free) in tagging.c~~ fix lists with grouped images instead

fixes #5486

### CODE REVIEW

**Comment by johnny-bit** [comment]
@alicvb recently changed way how list from get images to act on behaves. Your change might introduce double free... Needs check

**Comment by TurboGit** [comment]
> @AlicVB recently changed way how list from get images to act on behaves. Your change might introduce double free... Needs check

This was for the collection changed signal, I don't think there is an issue with this PR.

File: src/libs/tagging.c [hunk 1]
```diff
@@ -2936,10 +2936,10 @@ static gboolean _lib_tagging_tag_redo(GtkAccelGroup *accel_group, GObject *accel
     GList *imgs = dt_view_get_images_to_act_on(TRUE, TRUE);
     const gboolean res = dt_tag_attach_string_list(d->last_tag, imgs, TRUE);
     if(res) dt_image_synch_xmps(imgs);
-
+    g_list_free(imgs);
```
Comment (johnny-bit) [inline src/libs/tagging.c:2939]: please note that in  #5405 @AlicVB specifically removed all my calls to `g_list_free` and the `dt_view_get_images_to_act_on` actually returns `darktable.view_manager->act_on.images` so that free isn't needed

Comment (TurboGit) [reply src/libs/tagging.c:2939]: You may well be right for this one!

**Comment by johnny-bit** [comment]
I commented in code :) Pls note of https://github.com/darktable-org/darktable/blob/e567bdc207ce145eefc6b40cc98fd6b81ded7a47/src/views/view.c#L889 where as you can see regardless of "force" param the returned list is `darktable.view_manager->act_on.images` and all calls to `dt_view_get_images_to_act_on` properly free previous list if needed :)

File: src/libs/tagging.c (hunk 1 above)
Comment (phweyland) [reply src/libs/tagging.c:2939]: Guys, that's very dangerous to change the code this way !
All the previous code is based on the fact the caller owns the list and can change it as needed (add grouped image for example). See dt_image_set_location() for example.
And it remains g_list_free(imgs) in various places, even in tagging!

Comment (johnny-bit) [reply src/libs/tagging.c:2939]: I think @AlicVB removed all those that referenced list returned from `dt_view_get_images_to_act_on`. Not many calls were there tbh, and those which needed list ownership were changed to receive list copy.

I'd wait for @AlicVB to review & comment. as it stands now I don't think we have leak nor do I see double frees. sure there might be a lot of `g_list_free` but may not reffer to list returned from images to act on.

**Comment by phweyland** [comment]
> > @AlicVB recently changed way how list from get images to act on behaves. Your change might introduce double free... Needs check
> 
> This was for the collection changed signal, I don't think there is an issue with this PR.

This one had been another surprise, yes.
That's ok as soon as that is clearly documented / commented...

**Comment by phweyland** [comment]
Why not to change
`GList *dt_view_get_images_to_act_on(gboolean only_visible, gboolean force);`
to
`const GList *dt_view_get_images_to_act_on(gboolean only_visible, gboolean force);`
?

**Comment by johnny-bit** [comment]
Hmmm... sounds good IMO.

**Comment by TurboGit** [comment]
> Why not to change
> `GList *dt_view_get_images_to_act_on(gboolean only_visible, gboolean force);`
> to
> `const GList *dt_view_get_images_to_act_on(gboolean only_visible, gboolean force);`
> ?

Sound like a great "fix" as it will auto document that this GList cannot be modified/freed.

**Comment by phweyland** [comment]
I add it to that PR if doesn't create issue.

**Comment by TurboGit** [comment]
And as you expected this need a rebase !

**Comment by TurboGit** [comment]
Works on my side! Very good to see this fixed for the release, a nasty bug!

Thanks Philippe!

**Comment by craigtaranto** [comment]
Thank you all for quickly addressing this bug!  Looking forward to darktable 3.2 when released.
