### PR TITLE
Fix watermark filename size

### LINKED ISSUE #19895: Watermark filenames beyond a certain length silently fail to insert
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

I have some filenames that are on the longer side.  I couldn't for the life of me get them to show up as a watermark even though they were available in the `marker` dropdown menu.

Here's an example filename: `Plum Sketch-alamy2HT7K25-orderOY87853803-invoiceIY03977824-PrunusDomestic-darktable.svg`.  I also observed this behavior with pngs.

On a hunch, I tried renaming one of the files to a much shorter filename and then it suddenly started working.

### Steps to reproduce

1. create an SVG and save it to the watermark folder (on my system, it was `~/.var/app/org.darktable.Darktable/config/darktable/watermarks/`)
2. set the filename to something that's at least 60 characters long, plus `.svg` (for example, `123456789_123456789_123456789_123456789_123456789_123456789_.svg`)
3. refresh the `marker` dropdown then select the svg or png file
4. !! the image doesn't show up !!
5. rename the file to a name that is 59 characters or shorter, plus the extension (eg `123456789_123456789_123456789_123456789_123456789_123456789.svg`)
6. refresh the `marker` dropdown and pick the file
7. !! the file shows up !!

### Expected behavior

show the watermark image

### Logfile | Screenshot | Screencast

here's logs from loading a working image and a non-working image

```
darktable 5.2.1
Copyright (C) 2012-2025 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Exiv2                  -> 0.28.7
  Lensfun                -> 0.3.4
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.5.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  OSMGpsMap              -> ENABLED  - map view is available
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  LibRaw                 -> ENABLED  - Version 0.22.0-Devel202502
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

...

    17.1825 [commit color calibration]  temp=3024  xy=0.4357 0.4012 - XYZ=1.0860 1.0000 0.4065 - LMS=1.0650 0.9513 0.4342  DT_ILLUMINANT_LED
    17.1825 committed                     [preview]        channelmixerrgb        3400  enabled  piece hash=c8da901ef4add7cb
    17.1825 committed                     [preview]        crop                   2900  enabled  piece hash=c16a9925f2bbc530
    17.1825 committed                     [preview]        watermark              9000  enabled  piece hash=e987c4196fdc80d6
    17.1825 committed                     [preview]        watermark              9000  enabled  piece hash=e987c4196fdc80d6
    17.1825 synch all modules done        [preview]                                     defaults 0.0180s, history 0.0047s
    17.1825 get dimensions                [preview]                                          (0/0)   1251x900 sc=1.000; ID=2725
    17.1825 modified roi OUT              [preview]        rawprepare              100       (0/0)   1251x900 sc=1.000 -->       (0/0)   1197x900 sc=1.000;
    17.1825 modified roi OUT              [preview]        crop                   2900       (0/0)   1197x900 sc=1.000 -->     (6/140)   1184x666 sc=1.000;
    17.1826 pipe cache check              [preview]                                     12 lines (important=1, used=10). Freed: invalid 0MB used 0MB. Using 111MB, limit=0MB
    17.1826 pipe cache check              [full]                                        64 lines (important=2, used=12). Freed: invalid 0MB used 0MB. Using 226MB, limit=2944MB
    17.1826 pipe starting             CPU [preview]                                          (0/0)   1184x666 sc=1.000; ID=2725
    17.1826 pipe starting             CPU [full]                                             (0/0)    804x452 sc=0.174; ID=2725
    17.1826 cache HIT                     [preview]        colorout               8400  IOP_CS_RGB, hash=cb0786fde4cc17cb
    17.1826 pipe data: from cache         [preview]        colorout               8400       (0/0)   1184x666 sc=1.000;
    17.1826 modified roi IN               [full]           crop                   2900       (0/0)    804x452 sc=0.174 -->      (0/92)    804x452 sc=0.174; ID=2725
    17.1826 modified roi IN               [full]           demosaic                900      (0/92)    804x452 sc=0.174 -->     (0/526)  4608x2590 sc=1.000; ID=2725
    17.1826 modified roi IN               [full]           highlights              500     (0/526)  4608x2590 sc=1.000 -->       (0/0)  4610x3464 sc=1.000; ID=2725
    17.1826 cache HIT                     [full]           temperature             300  IOP_CS_RAW, hash=2cc8855aaafd748c
    17.1826 pipe data: from cache         [full]           temperature             300       (0/0)  4610x3464 sc=1.000;
    17.1829 process                   CPU [full]           highlights              500       (0/0)  4610x3464 sc=1.000 -->     (0/526)  4608x2590 sc=1.000; IOP_CS_RAW 160MB
    17.1829 process                   CPU [preview]        watermark              9000       (0/0)   1184x666 sc=1.000; IOP_CS_RGB 25MB
    17.1868 importance hints          CPU [preview]        watermark              9000       (0/0)   1184x666 sc=1.000; input_hint focus
    17.1868 process                   CPU [preview]        gamma                  9100       (0/0)   1184x666 sc=1.000; IOP_CS_RGB 25MB
    17.1882 process                   CPU [full]           demosaic                900     (0/526)  4608x2590 sc=1.000 -->      (0/92)    804x452 sc=0.174; IOP_CS_RAW -> IOP_CS_RGB 585MB
    17.1924 dt_ioppr_transform_image_colorspace_rgb `system display profile' -> `sRGB' [final histogram]
    17.2132 cache report                  [preview]                                     12 lines (important=1, used=10, invalid=0). Using 120MB, limit=0MB. Hits/run=0.50. Hits/test=0.071
    17.2133 pipe finished             CPU [preview]                                          (0/0)   1184x666 sc=1.000; ID=2725
    17.2572 process                   CPU [full]           exposure               2500      (0/92)    804x452 sc=0.174; IOP_CS_RGB 12MB
    17.2575 process                   CPU [full]           crop                   2900      (0/92)    804x452 sc=0.174 -->       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    17.2579 process                   CPU [full]           colorin                3300       (0/0)    804x452 sc=0.174; IOP_CS_RGB -> IOP_CS_LAB 12MB
    17.2579 matrix conversion         CPU [full]           colorin                3300       (0/0)    804x452 sc=0.174; `standard color matrix', corrected by: 1.870 1.000 0.528
    17.2587 transform colorspace      CPU [full]           channelmixerrgb        3400       (0/0)    804x452 sc=0.174; IOP_CS_LAB -> IOP_CS_RGB `linear Rec2020 RGB'
    17.2591 process                   CPU [full]           channelmixerrgb        3400       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    17.2617 process                   CPU [full]           sigmoid                5800       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    17.2647 transform colorspace      CPU [full]           colorout               8400       (0/0)    804x452 sc=0.174; IOP_CS_RGB -> IOP_CS_LAB `linear Rec2020 RGB'
    17.2651 process                   CPU [full]           colorout               8400       (0/0)    804x452 sc=0.174; IOP_CS_LAB -> IOP_CS_RGB 12MB
    17.2661 process                   CPU [full]           watermark              9000       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    17.2667 importance hints          CPU [full]           watermark              9000       (0/0)    804x452 sc=0.174; input_hint focus
    17.2667 process                   CPU [full]           gamma                  9100       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    17.2674 get dimensions                [full]                                             (0/0)  4816x3464 sc=1.000; ID=2725
    17.2675 modified roi OUT              [full]           rawprepare              100       (0/0)  4816x3464 sc=1.000 -->       (0/0)  4610x3464 sc=1.000;
    17.2675 modified roi OUT              [full]           crop                   2900       (0/0)  4610x3464 sc=1.000 -->     (1/528)  4608x2592 sc=1.000;
    17.2677 cache report                  [full]                                        64 lines (important=5, used=22, invalid=0). Using 321MB, limit=2944MB. Hits/run=0.50. Hits/test=0.042
    17.2677 pipe finished             CPU [full]                                             (0/0)    804x452 sc=0.174; ID=2725
    17.2690 chroma data                                    channelmixerrgb        3400  D65=YES.  NOW 1.531 1.000 2.762, D65 2.864 1.000 1.459, AS-SHOT 1.531 1.000 2.762 File `2025-11-27 16.04.24_0085.RW2' ID=2725
    28.2024 dev_pixelpipe_change          [preview]                                     top changed,
    28.2024 synch top history module      [preview]        watermark              9000
    28.2024 committed                     [preview]        watermark              9000  enabled  piece hash=af17fafde43ed000
    28.2025 get dimensions                [preview]                                          (0/0)   1251x900 sc=1.000; ID=2725
    28.2025 modified roi OUT              [preview]        rawprepare              100       (0/0)   1251x900 sc=1.000 -->       (0/0)   1197x900 sc=1.000;
    28.2025 modified roi OUT              [preview]        crop                   2900       (0/0)   1197x900 sc=1.000 -->     (6/140)   1184x666 sc=1.000;
    28.2025 pipe cache check              [preview]                                     12 lines (important=1, used=10). Freed: invalid 0MB used 0MB. Using 120MB, limit=0MB
    28.2025 pipe starting             CPU [preview]                                          (0/0)   1184x666 sc=1.000; ID=2725
    28.2025 cache HIT                     [preview]        watermark              9000  IOP_CS_RGB, hash=c9a6e7f9034831be
    28.2025 pipe data: from cache         [preview]        watermark              9000       (0/0)   1184x666 sc=1.000;
    28.2025 cache HIT                     [preview]        gamma                  9100  IOP_CS_RGB, hash=9ebe7bdb93fff632
    28.2025 process                   CPU [preview]        gamma                  9100       (0/0)   1184x666 sc=1.000; IOP_CS_RGB 25MB
    28.2042 dev_pixelpipe_change          [full]                                        top changed,
    28.2042 synch top history module      [full]           watermark              9000
    28.2043 committed                     [full]           watermark              9000  enabled  piece hash=af17fafde43ed000
    28.2043 get dimensions                [full]                                             (0/0)  4816x3464 sc=1.000; ID=2725
    28.2043 modified roi OUT              [full]           rawprepare              100       (0/0)  4816x3464 sc=1.000 -->       (0/0)  4610x3464 sc=1.000;
    28.2043 modified roi OUT              [full]           crop                   2900       (0/0)  4610x3464 sc=1.000 -->     (1/528)  4608x2592 sc=1.000;
    28.2043 pipe cache check              [full]                                        64 lines (important=5, used=22). Freed: invalid 0MB used 0MB. Using 321MB, limit=2944MB
    28.2043 pipe starting             CPU [full]                                             (0/0)    804x452 sc=0.174; ID=2725
    28.2061 cache HIT                     [full]           colorout               8400  IOP_CS_RGB, hash=e2acf7cc5fbbe301
    28.2061 pipe data: from cache         [full]           colorout               8400       (0/0)    804x452 sc=0.174;
    28.2061 process                   CPU [full]           watermark              9000       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    28.2147 dt_ioppr_transform_image_colorspace_rgb `system display profile' -> `sRGB' [final histogram]
    28.2192 cache report                  [preview]                                     12 lines (important=3, used=10, invalid=0). Using 120MB, limit=0MB. Hits/run=0.67. Hits/test=0.133
    28.2192 pipe finished             CPU [preview]                                          (0/0)   1184x666 sc=1.000; ID=2725
    28.2193 importance hints          CPU [full]           watermark              9000       (0/0)    804x452 sc=0.174; input_hint focus
    28.2194 process                   CPU [full]           gamma                  9100       (0/0)    804x452 sc=0.174; IOP_CS_RGB 12MB
    28.2203 get dimensions                [full]                                             (0/0)  4816x3464 sc=1.000; ID=2725
    28.2203 modified roi OUT              [full]           rawprepare              100       (0/0)  4816x3464 sc=1.000 -->       (0/0)  4610x3464 sc=1.000;
    28.2203 modified roi OUT              [full]           crop                   2900       (0/0)  4610x3464 sc=1.000 -->     (1/528)  4608x2592 sc=1.000;
    28.2204 cache report                  [full]                                        64 lines (important=6, used=24, invalid=0). Using 332MB, limit=2944MB. Hits/run=0.67. Hits/test=0.074
    28.2204 pipe finished             CPU [full]                                             (0/0)    804x452 sc=0.174; ID=2725
    28.2210 chroma data                                    channelmixerrgb        3400  D65=YES.  NOW 1.531 1.000 2.762, D65 2.864 1.000 1.459, AS-SHOT 1.531 1.000 2.762 File `2025-11-27 16.04.24_0085.RW2' ID=2725
    28.7803 exif_xmp_read_data: dt_exif_xmp_write. imgid=2725, hist=16, took 0.001s
```

### Commit

_No response_

### Where did you obtain darktable from?

Flatpak

### darktable version

v5.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Pop!_OS 24.04 LTS x86_64 (ubuntu-like)

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Instead of the fixed size of just 64 use the macro defined for this purpose.

Fixes #19895

Release note: Fix restriction for filename length in watermark module

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

File: src/iop/watermark.c [hunk 1]
```diff
@@ -400,6 +416,32 @@ int legacy_params(dt_iop_module_t *self,
...
+    dt_iop_watermark_params_v7_t *n = malloc(sizeof(dt_iop_watermark_params_v7_t));
+
+    n->opacity = o->opacity;
+    n->scale = o->scale;
+    n->xoffset = o->xoffset;
+    n->yoffset = o->yoffset;
+    n->alignment = o->alignment;
+    n->rotate = o->rotate;
+    n->scale_base = o->scale_base;
+    // let scale_img and scale_svg at the default values
```
Comment (ralfbrown) [inline src/iop/watermark.c:431]: Those fields should also be copied, since they existed in the previous version....  As is, they become uninitialized data, since the memory is allocated with malloc rather than calloc.

Comment (jenshannoschwalm) [reply src/iop/watermark.c:431]: Thanks for reviewing, absolutely right.
