### PR TITLE
fix mask indicator visibility

### LINKED ISSUE #9073: Mask indicator only works with some right-side button modes
The mask indicator that appears in processing module headers only appears to work when `preferences > darkroom > show right-side buttons in processing module headers` is set to "always", "active" or "dim".

In the other modes it will sometimes display, but usually this only seems to happen if you change mode while still in the darkroom view (presumably because it still "remembers" the state from a previous setting?)

darktable 3.5.0+2356~g8462ec043 on ArchLinux

### PR DESCRIPTION
**Pull request by Mark-64**
Fixes the mask indicator visibility in "dynamic modes" for header buttons, by placing the mask indicator to the right of the drawing area for such modes.
fixes #9073

### CODE REVIEW

File: src/develop/imageop.c [hunk 1]
```diff
@@ -2341,6 +2341,22 @@ void add_remove_mask_indicator(dt_iop_module_t *module, gboolean add)
...
     gtk_box_pack_end(GTK_BOX(module->header), module->mask_indicator, FALSE, FALSE, 0);
+
+    // in dynamic modes, we need to put the mask indicator after the drawing area
+    GList *children = gtk_container_get_children(GTK_CONTAINER(module->header));
+    GList *child = g_list_last(children);
+
+    for(child = g_list_last(children); child && GTK_IS_BUTTON(child->data); child = g_list_previous(child));
+
+    if(GTK_IS_DRAWING_AREA(child->data))
+      {
```
Comment (TurboGit) [inline src/develop/imageop.c:2352]: indentation is not dt style.

Can you also explain more what this does? Maybe a screenshot ?

Comment (elstoc) [reply src/develop/imageop.c:2352]: It should basically fix the bug listed in #9073. The module-header mask indicator is not currently appearing for some of the modes where the right-hand-side module-header icons are auto-hidden.

Comment (TurboGit) [reply src/develop/imageop.c:2352]: @elstoc : Yes, but my question is more how was this fixed, the changelog  says "by placing the mask indicator to the right of the drawing area for such modes" ... And I'm wondering where exactly the mask is now drawn as this is not clear to me, and difficult to see from just reading code.

Comment (elstoc) [reply src/develop/imageop.c:2352]: There's some explanation [here](https://github.com/darktable-org/darktable/issues/9073#issuecomment-849100989)

**Comment by elstoc** [comment]
Works for me. Thanks @Mark-64

**Comment by Mark-64** [comment]
#9073 was caused by adding the mask indicator unconditionally to the module header with `gtk_box_pack_end`. In dynamic header button visibility modes, there is a drawing area that must be placed to the left of the buttons instead, as explained by @dterrahe in the issue.
The PR checks for the drawing area and, if found, moves the mask indicator to its right with `gtk_box_reorder_child`.
I will fix the indentation

**Review by TurboGit — APPROVED** [review]
Thanks !

File: src/develop/imageop.c [hunk 2]
```diff
@@ -2341,6 +2341,22 @@ void add_remove_mask_indicator(dt_iop_module_t *module, gboolean add)
...
+    GList *child = g_list_last(children);
+
+    for(child = g_list_last(children); child && GTK_IS_BUTTON(child->data); child = g_list_previous(child));
+
+    if(GTK_IS_DRAWING_AREA(child->data))
+    {
+      GValue position = G_VALUE_INIT;
+      g_value_init (&position, G_TYPE_INT);
+      gtk_container_child_get_property(GTK_CONTAINER(module->header), child->data ,"position", &position);
+      gtk_box_reorder_child(GTK_BOX(module->header), module->mask_indicator, g_value_get_int(&position));
```
Comment (dterrahe) [inline src/develop/imageop.c:2356]: Just FYI I find this slightly more compact and readable, but of course does exactly the same thing, so no need to change here:
```
      int position = 0;
      gtk_container_child_get(GTK_CONTAINER(module->header), child->data ,"position", &position, NULL);
      gtk_box_reorder_child(GTK_BOX(module->header), module->mask_indicator, position);
```

**Review by dterrahe — APPROVED** [review]

File: src/develop/imageop.c (hunk 2 above)
Comment (dterrahe) [reply src/develop/imageop.c:2356]: No need to change _especially_ because Pascal the speed daemon already merged ;-)
