### PR TITLE
images to act on : refactor + fix

### LINKED ISSUE #10592: Can't copy history when image grouping is enabled
**Describe the bug/issue**

Copy history is greyed out when image grouping is enabled.

**To Reproduce**
1. enable image grouping
2. make edit to RAW file with JPEG pair
3. try to copy history but button is greyed out
4. disable image grouping
5. note that raw + jpeg are selected
6. select just raw
7. copy history is no longer greyed out

**Expected behavior**
Able to copy history of RAW file while image grouping is enabled. Similar to how double-clicking a grouped image opens the RAW file or mousing over a grouped image shows the RAW info, I would expect history copy to copy the history of that RAW file.

**Screenshots**
Grouping enabled:
image

Grouping disabled, both images selected:
image

Grouping disabled, one image selected:
image

**Platform**

* darktable version : 3.6.1-1.fc35.1 and master
* OS                :  Linux - kernel 5.15.6-200.fc35.x86_64
* Linux - Distro    : Fedora 35
* Memory            :  8GB
* Graphics card     :  GTX 970 4GB
* Graphics driver   : NVidia Proprietary
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              :  Wayland
* Desktop           :  Gnome
* gcc               :  11.2.1-7.fc35

**Additional context**
See #5931, specifically https://github.com/darktable-org/darktable/issues/5931#issuecomment-988288778 and newer

### PR DESCRIPTION
**Pull request by AlicVB**
this fix #10592 

this PR contains the following : 
1. move all act_on codes to its own files and renames the functions accordingly. This lower the view.c file and prepare things for the "yet-to-be-done" work on a different act_on algorithm.
2. store 2 caches in parallel : one for all images and one only for visible images. see #10592 
3. `dt_act_on_get_images` now always return a copy of the list of images (instead of the cached list) which will need to be freed by the caller. This is safer because the cached list may change at any moment, which can provoke weird bug if some action is done on the list at that moment. Currently, most of the code already do the copy manually, so it simplify the code for them.
4. propose a direct access to the nb of image in the list. This avoid to copy the list.

In my tests, I've not found any drawback, but better test carefully as my last fix was the cause of some issues I was not able to reproduce !

@ianhattendorf : can you confirm it fix your issue ? Thanks !
@elstoc @ClaesGitHub : can you test and verify that you can reproduce your previous issues ? Thanks

### CODE REVIEW

**Comment by ianhattendorf** [comment]
Selection works fine for me :+1: 

> now always return a copy of the list of images (instead of the cached list) which will need to be freed by the caller. This is safer because the cached list may change at any moment, which can provoke weird bug if some action is done on the list at that moment

This piqued my interest: not knowing anything about the darktable architecture, is `darktable.view_manager->act_on_cache_{visible,all}.images` being modified by multiple threads? Should it be protected by a mutex?

**Comment by AlicVB** [comment]
I was also also wondering the same thing...
Currently, I've followed the simplest way : limiting at the maximum the parts that can cause issues...
Any opinions of other devs are welcome here...

File: src/common/act_on.h [hunk 1]
```diff
@@ -0,0 +1,48 @@
+/*
+    This file is part of darktable,
+    Copyright (C) 2009-2021 darktable developers.
```
Comment (TurboGit) [inline src/common/act_on.h:3]: 2021 only here.

File: src/libs/image.c [hunk 2]
```diff
@@ -190,14 +190,14 @@ static void _update(dt_lib_module_t *self)
 {
   dt_lib_cancel_postponed_update(self);
   dt_lib_image_t *d = (dt_lib_image_t *)self->data;
-  const GList *imgs = dt_view_get_images_to_act_on(FALSE, FALSE, FALSE);
+  const int nbimgs = dt_act_on_get_images_nb(FALSE, FALSE);
 
-  const int act_on_any = imgs != NULL;              // list length > 0 ?
-  const int act_on_one = g_list_is_singleton(imgs); // list length == 1 ?
-  const int act_on_mult = act_on_any && !act_on_one;// list length > 1 ?
+  const int act_on_any = (nbimgs > 0);
```
Comment (TurboGit) [inline src/libs/image.c:195]: since you have this here...

File: src/libs/styles.c [hunk 3]
```diff
@@ -743,8 +747,7 @@ static void _update(dt_lib_module_t *self)
   dt_lib_cancel_postponed_update(self);
   dt_lib_styles_t *d = (dt_lib_styles_t *)self->data;
 
-  const GList *imgs = dt_view_get_images_to_act_on(TRUE, FALSE, FALSE);
-  const gboolean has_act_on = imgs != NULL;
+  const gboolean has_act_on = (dt_act_on_get_images_nb(TRUE, FALSE) > 0);
```
Comment (TurboGit) [inline src/libs/styles.c:750]: ... and this here.

And you have a nice refactoring of the act-on in a separate unit I would go even forward and introduce an enum

ACT_ON_ANY
ACT_ON_ONE
ACT_ONE_MULT

And have this returned by a new function (`dt_act_on_get_mode()` or systematically return this value in `dt_act_on_get_images()` by using an access to this enum as parameter).

File: src/common/act_on.c [hunk 4]
```diff
@@ -0,0 +1,411 @@
+/*
+    This file is part of darktable,
+    Copyright (C) 2009-2021 darktable developers.
```
Comment (TurboGit) [inline src/common/act_on.c:3]: 2021 only here

**Review by TurboGit — CHANGES_REQUESTED** [review]
A first review.

**Comment by TurboGit** [comment]
To me there is no need to have a mutex has this is used only by the GUI thread IIMM.

**Comment by ClaesGitHub** [comment]
Negative. Issue 10639 **not** solved by fix 10649.

One change, though: using fix 10649, setting *legacy* versus *modern*
now yield the same result (i.e. 2 ctrl-z undos needed).

Messages about missing mandatory modules still appear:
```
[_dev_auto_apply_presets] missing mandatory module rawprepare for image 4
[_dev_auto_apply_presets] missing mandatory module temperature for image 4
[_dev_auto_apply_presets] missing mandatory module highlights for image 4
[_dev_auto_apply_presets] missing mandatory module demosaic for image 4
[_dev_auto_apply_presets] missing mandatory module flip for image 4
[_dev_auto_apply_presets] missing mandatory module colorin for image 4
[_dev_auto_apply_presets] missing mandatory module colorout for image 4
[_dev_auto_apply_presets] missing mandatory module gamma for image 4

```

**Comment by elstoc** [comment]
I no longer get seg faults when editing metadata with this fix.

**Comment by TurboGit** [comment]
@ClaesGitHub : I don't think this PR was supposed to fix #10639.

**Comment by ClaesGitHub** [comment]
@TurboGit 
Pardon --- I thought so, because @AlicVB asked me
>can you test and verify that you can reproduce your previous issues ? Thanks

**Comment by elstoc** [comment]
@ClaesGitHub I think @AlicVB was referring to #10625

File: src/libs/styles.c (hunk 3 above)
Comment (AlicVB) [reply src/libs/styles.c:750]: well, in fact, that's not the same : the second one only use "nb of images > 0" so the enum and refactoring would only concern image.c... not sure it's worth the pain... and in fact I thing the current implementation is more clear to read.
That said, I can do the refactoring if you insist, that's not a problem ;)

**Comment by AlicVB** [comment]
@ClaesGitHub : @elstoc is right, sorry to have not been clear !

Last commit enhance the caching when we only need the number of images by not taking in account the ordering. This should avoid cache recompute in a few cases...
@TurboGit : this also fix the header as mentioned in your review...

File: src/common/selection.c [hunk 5]
```diff
@@ -42,7 +42,8 @@ const dt_collection_t *dt_selection_get_collection(struct dt_selection_t *select
 static void _selection_raise_signal()
 {
   // discard cached images_to_act_on list
-  darktable.view_manager->act_on.ok = FALSE;
+  dt_act_on_reset_cache(TRUE);
```
Comment (TurboGit) [inline src/common/selection.c:45]: Isn't this first call with TRUE superfluous since you call the same with FALSE below (only_visible = FALSE, means everything?).

File: src/libs/styles.c (hunk 3 above)
Comment (TurboGit) [reply src/libs/styles.c:750]: In tagging you also have `dt_act_on_get_images_nb(FALSE, FALSE) > 0` and I'm sure at some point some other checks will be added in many places, so I still think a nice API to get those state would be nice.

**Review by TurboGit — CHANGES_REQUESTED** [review]

File: src/common/selection.c (hunk 5 above)
Comment (AlicVB) [reply src/common/selection.c:45]: nope, as with this PR, we store one cache for "all images" and another one for "only visible images" so we need to reset both...
As dt_act_on_reset_cache is only called here, we could have remove the argument and always reset both caches together, but I've done it like that so we can eventually do a specific reset in some cases in the future (like a click on "group-degroup" icon for example...

File: src/libs/styles.c (hunk 3 above)
Comment (AlicVB) [reply src/libs/styles.c:750]: Fair enough... I'll do that :)

**Comment by AlicVB** [comment]
@TurboGit : I've done the refactoring. Can you have a separate look at the latest commit ? I'm still not convinced it's better (but it's not worth either), so I'm wonder if I have understand what you wanted...

**Comment by TurboGit** [comment]
> @TurboGit : I've done the refactoring. Can you have a separate look at the latest commit ? I'm still not convinced it's better (but it's not worth either), so I'm wonder if I have understand what you wanted...

Indeed, I was more thinking about this:

```
GList *dt_act_on_get_images(const gboolean only_visible, const gboolean force, const gboolean ordered, dt_act_on_mode_t *act_on)
{
  ... compute the list as before

  if(act_on)
  {
     const int nb_image = ...;
      *act_on = (nb_image == 0) ? DT_ACT_ON_NONE : (nb_image == 1) ? DT_ACT_ON_ONE : DT_ACT_ON_MULT;
  }

  return images;
}
```

And then in the code maybe just use directly :  

```
if(act_on == DT_ACT_ON_ONE)
{
}
```

And maybe no need to declare all the constants act_on_any, act_one_one...

How does that sound?

**Comment by TurboGit** [comment]
And then you can remove the : `dt_act_on_get_mode` & `dt_act_on_get_images_nb`.

**Comment by AlicVB** [comment]
hmm... I fear we still need 2 different functions, as `dt_act_on_get_images` always do a copy of the list, which is unneeded (and slow) for most call of `dt_act_on_get_images_nb` / `dt_act_on_get_mode`...

**Comment by TurboGit** [comment]
> 

I see, so my refactoring does not seems a good idea indeed. Sorry for that, I was missing some crucial parts!

**Comment by AlicVB** [comment]
> Sorry for that, I was missing some crucial parts!

no problem, I'm certainly guilty too due to my confusing explanations... Do you want me to remove the last commit, or do you handle it by yourself ?

**Comment by TurboGit** [comment]
Yes, please remove last commit. Thanks

**Comment by AlicVB** [comment]
@TurboGit : done

**Review by TurboGit — APPROVED** [review]
Works for me. I'll merge on master now and will merge on 3.8.1 after some more field testing.
