### PR TITLE
Fix processing of shorter date-time strings with TZ info

### LINKED ISSUE #12137: darktable cannot see the correct dateTimeOriginal in a DNG file
I have some dng files I received whose dataTime isn't recognized by darktable, it sees 1/1/1 0:00, while ghtumb correctly see it:

darktable

I cannot upload the dng file, github tells me that is exceeds the 25MB allowed, where can I upload it?

### PR DESCRIPTION
**Pull request by victoryforce**
This fixes processing of shorter (not highest precision) date-time strings with TZ info. The problem was that the processing code expected the timezone data to only be in strings with maximum precision. But this is not always the case. When the TZ tail started earlier, it damaged the parsing buffer.

Resolves #12137.

### CODE REVIEW

File: src/common/datetime.c [hunk 1]
```diff
@@ -66,7 +66,18 @@ gboolean dt_datetime_exif_to_numbers(dt_datetime_t *dt, const char *exif)
   if(exif && *exif && dt)
   {
     char sdt[DT_DATETIME_LENGTH] = DT_DATETIME_ORIGIN;
-    const int len = strlen(exif) > sizeof(sdt) - 1 ? sizeof(sdt) - 1 : strlen(exif);
+    int len = strlen(exif);
+    // If TZ data is found in the datetime string we should discard it.
+    // We will memcpy this string for parsing and we have to know where to stop so that
+    // the TZ tail after shorter XMP date-time string doesn't damage our parsing buffer.
+    // For possible formats see https://developer.adobe.com/xmp/docs/XMPNamespaces/XMPDataTypes/#date
+    if(exif[len-1] == 'Z')
```
Comment (TurboGit) [inline src/common/datetime.c:74]: Ok, if string terminates with Z we are UTC. Fine.

File: src/common/datetime.c [hunk 2]
```diff
@@ -66,7 +66,18 @@ gboolean dt_datetime_exif_to_numbers(dt_datetime_t *dt, const char *exif)
...
+      len--;
+    else if(exif[len-3] == '+' || exif[len-3] == '-')
```
Comment (TurboGit) [inline src/common/datetime.c:76]: But if we have an offset number `+/- nn` discarding it means that we are converting to a wrong UTC. No?

Comment (victoryforce) [reply src/common/datetime.c:76]: No, we are not _converting_ as darktable is TZ agnostic (this is a consequence of the fact that most cameras do not know anything about time zones). Most often darktable will deal with EXIF:DateTimeOriginal as the source of date-time information. According to the EXIF standard, the property is in ISO 8601 format but does not include the timezone suffix and should be treated as local time - that is, the time zone in which the photo was taken.

The code discarded TZ information before my fix (the parsing buffer was sized to just fit the date-time string with millisecond precision: "YYYY:mm:dd HH:MM:SS.sss"). Nothing changed here. I only adjusted the length for memcpy because it is possible that the date-time string will have less precision, fewer characters to record the time (for example, only 2 digits of subseconds, or no subseconds at all), but still the TZ tail. In this case, part of the TZ tail could get into the buffer and make it unparsable.

Comment (parafin) [reply src/common/datetime.c:76]: Not sure if it's relevant, but there's TimeZoneOffset TIFF (and probably EXIF) tag to specify timezone.

Comment (victoryforce) [reply src/common/datetime.c:76]: Yes, this tag exists. There are also other vendor specific tags for specifying the time zone. So a certain part (not all) of the images may have such information. And yes, it's not relevant.

**Comment by ptilopteri** [comment]
all of my Nikon DLSR exifs contain "Time Zone " and the correct offset,
but not updated if I travel to another time zone unless I manually 
change it.

**Comment by victoryforce** [comment]
> all of my Nikon DLSR exifs contain "Time Zone " and the correct offset, but not updated if I travel to another time zone unless I manually change it.

This is Exif.NikonWt.Timezone tag from Nikon's MakerNotes. As I said, such tags exist. But here we're discussing a fix to protect the parse buffer (which didn't support timezones from the beginning) from being corrupted under certain conditions.

**Comment by kmilos** [comment]
Yep, separate issues. We might want to open a new feature request to get to the time zone offset from known tags if available.

**Review by TurboGit — APPROVED** [review]
Ok, thanks for all info!

**Comment by paolobenve** [comment]
still to apply to 4.0.x branch
