### PR TITLE
Resets metadata_view (image information) to "-" when no selection is ongoing

### LINKED ISSUE #6482: Incorrect image information when mouse is not over image in lighttable mode
**Describe the bug**

- Open an image collection
- Enter culling mode (This seems to happen elsewhere in lighttable mode, but is most visible here)
- Navigate to an image towards the end of the collection
- Move the mouse over the image in the center
- observe that the image information on the left panel is correct
- Move the mouse over the image information panel (or anywhere but the center image)
- Observe that the image information is now from a different image

I would expect the image information to refer to the image on display

Notice the incorrect metadata displayed in the second image (when the mouse (invisible in the screenshot) is hovering over the "image information" panel):

image

image

**Platform (please complete the following information):**

darktable from `7631e70a8437f9e73f60b56f51801d0a36c1a076`

```
$ darktable --version
this is darktable unknown-version
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

- OS: NixOS
- OpenCL: enabled
- GPU: Nvidia 2080Ti
- Driver Version: 450.66

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both?
  - Have only tried RAW (Sony AWR format)
 - Are the steps above reproduce with a fresh edit (removing history)?
  - Yes
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
  - gcc 9.3.0 `    `-DBUILD_USERMANUAL=False`

### PR DESCRIPTION
**Pull request by vithom**
When no image is selected, when the cursor goes out of the image, the
metadata view (image information) keeps the last image information.
This change is about to reset information to "-" when mouse goes out of
an image (with no selection) and when an selection is canceled.
It works quite the same way than the buttons in the "selected image[s]"
module are activated.

Maybe fixes #6482 (not tried)

### CODE REVIEW

**Comment by AlicVB** [comment]
Great ! yes that partially fix #6482
(I've not tested yet, but just read the description)

The next step imho would be to handle more correctly the case where we have multiple selected images and no hovered images. This is the case for example when you select multiple image and go to the right panel to do things.
In that case, ideally, we should show either the value if it's the same for all images either something like "multiple values"
It's somewhere on my todo list, but I would be grateful if you want to take care ;)

Note that in any case this PR is needed so can be merged first...

**Comment by johnny-bit** [comment]
With multiple images selected and no hover for time being i'd say "no information is better than wrong information". Instead of "multiple values" I'd recommend going with standard "-".

So - if you can check all selected for infos - display identical and in multiple infos situation "-" is IMO fine (but that's just me, "multiple values" is fine too), if not - on multuiple images do "-" for all values and leave a "TODO" in comments ;)

**Comment by TurboGit** [comment]
> In that case, ideally, we should show either the value if it's the same for all images either something like "multiple values"

Right, for inspiration there is something similar done for the metadata editor module.

File: src/libs/metadata_view.c [hunk 1]
```diff
@@ -337,8 +337,14 @@ static void _metadata_view_update_values(dt_lib_module_t *self)
       sqlite3_stmt *stmt;
       DT_DEBUG_SQLITE3_PREPARE_V2(dt_database_get(darktable.db), "SELECT imgid FROM main.selected_images LIMIT 1",
                                   -1, &stmt, NULL);
-      if(sqlite3_step(stmt) == SQLITE_ROW) mouse_over_id = sqlite3_column_int(stmt, 0);
+      if(sqlite3_step(stmt) == SQLITE_ROW) { mouse_over_id = sqlite3_column_int(stmt, 0); }
```
Comment (AlicVB) [inline src/libs/metadata_view.c:340]: this doesn't follow the style in other dt parts...

File: src/libs/metadata_view.c [hunk 2]
```diff
@@ -907,7 +913,7 @@ static gboolean _jump_to_accel(GtkAccelGroup *accel_group, GObject *acceleratabl
 static void _mouse_over_image_callback(gpointer instance, gpointer user_data)
 {
   dt_lib_module_t *self = (dt_lib_module_t *)user_data;
-  if(dt_control_running()) _metadata_view_update_values(self);
+  if(dt_control_running()) { _metadata_view_update_values(self); }
```
Comment (AlicVB) [inline src/libs/metadata_view.c:916]: same

**Review by AlicVB — CHANGES_REQUESTED** [review]
Apart the 2 mentioned unwanted code change, I think everything is ok and works as expected.
Once fixed and merged, we can go further and take care of multiple images, but that's a different issue, so maybe it's better to separate the fix ! (I can take care of the second part if @vithom prefers)

File: src/libs/metadata_view.c (hunk 1 above)
Comment (vithom) [reply src/libs/metadata_view.c:340]: Maybe...but this is more secured if someone modify it later.
As you want, I will revert it.

**Comment by vithom** [comment]
> Apart the 2 mentioned unwanted code change, I think everything is ok and works as expected.
> Once fixed and merged, we can go further and take care of multiple images, but that's a different issue, so maybe it's better to separate the fix ! (I can take care of the second part if @vithom prefers)

For the second part, I'm working on it, so I can take care of it.

**Review by AlicVB — APPROVED** [review]
@vithom : great ! I let it to you then ;)
@TurboGit : I think this one is ready to review and merge...

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!
