### PR TITLE
metadata: control better the start of edition mode

### LINKED ISSUE #10925: lighttable: metadata editor fails to refresh
**Did you buy darktable from an application store ?**
no, self-compiled

**Describe the bug/issue**
When using keyboard shortcuts Alt-{arrow} to move to another image while one of the text fields in Metadata Editor has keyboard focus, the M.E. fails to update its display.  The display is correctly updated if the focus is elsewhere, e.g. in the text box for Tagging.

**To Reproduce**
1. Start dt with a fresh config dir and import a folder with enough images to show multiple rows of thumbnails in lighttable.
2. Click on an image to select, then open Metadata Editor and enter a unique value for "title"; press Enter or click Apply to store.
3. Click in the "title" text box to give it keyboard focus
4. Press Alt-Right or Alt-Down to move the "hovered" image
5. Observe that the display remains unchanged
6. Mouse over an image to move the "hover" indicator
7. Observe that the display updates
8. Click on the original image to re-select it
9. Press Alt-Right or Alt-Down and observe that Metadata Editor updates now that its text field no longer has keyboard focus
10. Click on the original image again
11. Open Tagging and click in its text box to give it focus
12. Add a unique tag to the image
13. Press Alt-Right or Alt-Down to move the "hovered" image
14. Observe that both Tagging and Metadata Editor update

**Expected behavior**
The fields in the metadata editor should refresh to show the values for the newly-activated image, just as they do when moving the mouse pointer to another image or when changing images with keyboard focus somewhere else.

**Which commit introduced the error**
This has been around at least since InputNG was merged last summer, although I don't think Alt-{arrow} was active by default at the time -- I remember specifically defining those shortcuts to test a mouse-free metadata editing workflow.

**Platform**
* darktable version : 3.9.0+4\~gc367c24b5 and current master (3.9.0+136\~g6e3023383)
* OS                : Linux - kernel 5.10.45
* Linux - Distro    : Mageia 8
* Memory            : 64GB
* Window Manager: KDE
* OpenCL installed  : no
* OpenCL activated  : no
* gcc               :  10.3.0
* CMAKE_BUILD_TYPE  : Release

**Additional context**
 - Do you use lua scripts?  no

### PR DESCRIPTION
**Pull request by phweyland**
attempt to fix #10925

### CODE REVIEW

**Comment by phweyland** [comment]
I've copied the content of the PR #10806 (I'll close it if this PR is merged).

@ralfbrown, I think you should have what you've described.
Return is now the shortcut of `apply` button, Tab or shift+Tab do the same plus move.

If the user starts with the first image of the collection that's fine.
But if the image hovered by key or the selected image is not the first one of the collection, the next click on a metadata field reset the hovered position to the first image. One starts to enter data on the wrong image...

It would be great that Alt-arrows key start at the first selected image. I have no idea how to do this. @dterrahe what do you think ? Any direction ?

Last detail, I think that, with Tab or shift-Tab, the content of the field which gets focus should be selected (as it works for tags entry). I'll try to do this.

**Comment by dterrahe** [comment]
I just proposed some simplifications in the metadata code by using gtk signals rather than duplicating their functionality in the key-press-event handler https://github.com/phweyland/darktable/pull/6

Specifically, I'm using the _focus_ signal to handle tab/shift-tab and the _changed_ signal on the textbuffer underlying the metadata textviews to detect if keypresses have changed the text. That saves you the trouble of creating a long list of all the characters (in all languages) that are valid input in a text view and will change the text.

Since you are still working on this particular part, I haven't attempted to correctly deal with all the places where d->editing needs to be reset (definitely after fresh data has been loaded).
 
I'm somewhat confused by the `_click_on_textview` handler. It looks like it should be trigger by a right-click, but that just shows me the edit popup menu (copy/paste etc). What is it supposed to do anyway?

**Comment by dterrahe** [comment]
> It would be great that Alt-arrows key start at the first selected image. I have no idea how to do this. @dterrahe what do you think ? Any direction ?

In general, I haven't really tried to mess will all the _logic_ when I was implementing input ng (because I would be introducing _tons_ of bugs/regressions). Instead I've just tied existing code to the new way of defining shortcuts.

Alt-arrow currently works like normal arrow except that it doesn't get intercepted by the textview (and then the Alt is silently dropped, unless a fallback or explicit shortcut is defined).

I must say I can't completely follow discussion above (and elsewhere) about what the goal is for alt-arrow to do when there is a hovered image. That's mainly because I (and others, from the many discussions) don't really understand how the whole thing is supposed to work anyway. But from a _shortcut_ perspective, if you want alt- to do something different than "normal" move and different from "select" move (which you get if fallbacks are enabled and you hold shift; it then selects all the imaged you move over), then you could define a third element in `_action_elements_move` in lighttable.c (which currently has normal "move" and "select" as elements) and then define a fallback in `_action_fallbacks_move` for `GDK_MOD1_MASK` that generates an action with element `altmove`. Completely parallel to what's done for shift. `_action_process_move` then needs to check against `DT_ACTION_ELEMENT_ALTMOVE` (?) and do whatever needs doing.

**Comment by phweyland** [comment]
> I just proposed some simplifications in the metadata code

Thanks a lot. I'll look at your proposal asap.

> I'm somewhat confused by the _click_on_textview handler. 

This the special case where several images are selected with different metadata. It should show the list of these metadata. The goal is to be able to select one of them and apply it to selected images.
The sizing of the drop list could be improved as well.
image

> for alt-arrow

With the last 2 commits, I can now navigate on lighttable images thanks to Alt+arrows keys, starting from the first selected image and exiting the hovering with Alt+Escape, to continue entering new data on the selected images. Of course this will need the @AlicVB attention as that are lighttable/thumbtable changes.

**Comment by ralfbrown** [comment]
Haven't had a chance to test the latest version yet, but from what I see in the code things are looking good.

@dterrahe - since arrows and shift-arrows are swallowed by the text box when it has focus, we need to use some other keystrokes to change the active image.  Alt-{arrow} just happens to do what is desired ootb, though I would have been happy to have defined them as alternates to the plain arrow keys on the thumbtable.

File: src/dtgtk/thumbtable.c [hunk 1]
```diff
@@ -2601,6 +2601,7 @@ static gboolean _filemanager_key_move(dt_thumbtable_t *table, dt_thumbtable_move
   int baseid = dt_control_get_mouse_over_id();
   // let's be sure that the current image is selected
   if(baseid > 0 && select) dt_selection_select(darktable.selection, baseid);
+  else if(baseid <= 0) baseid = dt_selection_get_first(darktable.selection);
```
Comment (AlicVB) [inline src/dtgtk/thumbtable.c:2604]: We may have unwanted effect in the case where the first selected image is not shown on screen. We may want to add something in order to ensure that we don't go outside the current table...
Note that this may interfere with @Solarer PR #10771

tbh I wasn't even aware of the alt-arrow feature...

**Comment by dterrahe** [comment]
> This the special case where several images are selected with different metadata. It should show the list of these metadata.

Could this possibly have been done with a popup menu rather than a dialog box? Maybe via the appealingly named "populate-popup"?

I guess if it works, it works. But if there are plans to undertake serious maintenance to the current approach, that alternative could be looked at.

**Review by AlicVB — CHANGES_REQUESTED** [review]
I'm not sure to follow all the discussion detailed here, but for the thumbtable part, we need to ensure that we stay inside the current view...

**Comment by phweyland** [comment]
> Note that this may interfere with @Solarer PR #10771

That will, but I agree with Solarer's statements. I can rebase if necessary.
Should not be in conflict if we assume that these changes make full sense when there is no image selected.
When at least one image is selected, it's logic to me (let's check if others agree) that the first selected image becomes the starting point.

> We may have unwanted effect in the case where the first selected image is not shown on screen.

If the selected image is not visible, the first Alt+arrow key press brings the image in the center view, which should be good to see on which image changes are made.

**Comment by AlicVB** [comment]
I agree with PR #10771 too, I just wanted to be sure that you were aware of it ;)



> I don't see the reason for that. Could you explain ?

The case we are speaking here is the one where for some reason there's no image hovered. In this case, when user start to play with arrow, the goal is not to loose all visible imho...

Imagine the case where all images from collection are selected. you scroll or use scrollbar to move forward. if you start to use right arrow, you don't want to be back to the start...
Even more problematic if you click (select) one image somewhere near the end of the collection, scroll back and start to use arrows...

**Comment by phweyland** [comment]
@dterrahe Great changes ! Integrated here with only small tweaks on change detection. Thanks again!

@AlicVB OK, I see that in both cases we can have some undesired behaviors. I have no strong opinion on this. Maybe @ralfbrown will have some preference for the use case he has presented (start with the first visible or the first selected ?).

Detail: dt_act_on_get_images() gives different results, when hovering with the mouse or hovering with keys, over a multiple images selection. Hovering with the mouse returns the list of selected while hovering with keys returns the hovered image. Not a big deal though.

File: src/libs/metadata.c [hunk 2]
```diff
@@ -107,6 +105,14 @@ static void _text_set_italic(GtkTextView *textview, const gboolean italic)
     gtk_text_buffer_remove_tag_by_name(buffer, "italic", &start, &end);
 }
 
+static void _set_text_buffer(GtkTextBuffer *buffer, const char *text)
+{
+  gulong handler = GPOINTER_TO_INT(g_object_get_data(G_OBJECT(buffer), "tv_handler"));
+  g_signal_handler_block(buffer, handler);
```
Comment (dterrahe) [inline src/libs/metadata.c:111]: Would something like `g_signal_handlers_block_matched(G_OBJECT(buffer), G_SIGNAL_MATCH_FUNC, 0, NULL, NULL, _textbuffer_changed, NULL);` not work here? (with matching `g_signal_handlers_unblock_matched` below)? No need to store and retrieve tv_handler. And somewhat easier to read (imvho). I haven't tried to compile, mind!

**Comment by Solarer** [comment]
I did not have a lot of time to read and understand the whole discussion but will do that tomorrow. I saw my name linked and wanted to share 2 thoughts

> When at least one image is selected, it's logic to me (let's check if others agree) that the first selected image becomes the starting point.

I tested that because I thought it would be a good idea but it felt very bad. @AlicVB mentioned some problematic cases and there are some more.
My idea was to always start on the first visible image when pressing arrow key but have a different shortcut (e. g. Alt-Arrow) to navigate through all selected images. That way a user can control where to start. I am not sure if that is what you are proposing here right now for Alt-arrow or not

File: src/dtgtk/thumbtable.c (hunk 1 above)
Comment (phweyland) [reply src/dtgtk/thumbtable.c]: reverted.

File: src/libs/metadata.c (hunk 2 above)
Comment (phweyland) [reply src/libs/metadata.c]: Works as well. Done.

**Comment by phweyland** [comment]
> My idea was to always start on the first visible image when pressing arrow key but have a different shortcut (e. g. Alt-Arrow) to navigate through all selected images. That way a user can control where to start. I am not sure if that is what you are proposing here right now for Alt-arrow or not

The intention was this one but the normal arrow had the same behavior. I've reverted this. We can come back on this if necessary later on. Thanks

**Comment by ralfbrown** [comment]
I seem to have opened a big can of worms :).

Having Alt-arrow start at the first visible image when multiple are selected seems more intuitive than jumping somewhere completely different in the collection.  But which image(s) does the metadata editor act on before we start navigating with Alt-arrow?  We should be consistent with that as well if possible.

Or, could we take the easy way out and simply disable Alt-arrow hovering if multiple images are selected?

**Comment by phweyland** [comment]
Hovering with mouse, there are two possibilities:
- when over an image outside the selection, any metadata change applies to the hovered image
- when over the selection, any change applies to the selection.

Hovering with keys, that's always the hovered image which takes the change. 
If you kick Alt+Escape, the hovering by keys ends and the selection, if any, is back the target.

> We should be consistent with that as well if possible.

I agree. I'll try to find my way ... Which of the above behaviors would be the best ?

EDIT
> But which image(s) does the metadata editor act on before we start navigating with Alt-arrow? 

On selected images, if any.

**Comment by phweyland** [comment]
> which image(s) does the metadata editor act on before we start navigating with Alt-arrow?

If no hovering (whatever), selected image(s).

> Detail: dt_act_on_get_images() gives different results, when hovering with the mouse or hovering with keys, over a multiple images selection. Hovering with the mouse returns the list of selected while hovering with keys returns the hovered image. Not a big deal though.

But when I let the mouse the over the thumbtable, key hovering behaves as mouse hovering ... :)

> We should be consistent with that as well if possible.

Agreed.

**Comment by phweyland** [comment]
Both key and mouse hovering are consistent for over selection now.

**Comment by dterrahe** [comment]
> we have lost some `entry` features.

Not sure what you mean here, but I meant #10992

**Comment by phweyland** [comment]
> The only missing point is that we should exit the key_inside mode automatically too each time the user use the mouse again in the thumbtable part... I would add this in thumbtable.c _event_motion_notify

Done

**Comment by TurboGit** [comment]
There is still something that we may try to improve. Today:
- select an image in lightable
- go to title in metadata editor
- enter xyz and press <TAB>
- cursor move to description, all good
- enter xyz and press <TAB>

Good, the widget shows xys ad title and description. Fly over another image and go back to the one just edited, the metadata are lost.

I really think we should handle <TAB> as <ENTER>, that is <TAB> will save/commit the edited field.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Make <TAB> key a way to save the edits in metadata editor.

**Comment by phweyland** [comment]
> enter xyz and press [?]
> Fly over another image and go back to the one just edited, the metadata are lost.
I really think we should handle as , that is will save/commit the edited field.

As described his is a bug, but which key do you use ?

`Enter` still saves the metadata but, unlike before, stays on the field instead of moving to next field.

When I fly over others images the metadata of these images are shown. When I move the mouse outside the center, the selected images metadata are back.

`Tab` has changed as well. It moves to the next field but doesn't save anymore. Coupled to the fact we cannot see the difference between a saved and a not saved field this is misleading. We could:
- make `Tab` save back
- draw some text difference (lightness, color, symbol,...) to inform this is not saved.

Does that answer the issue you describe ?
What do you think ?

**Comment by TurboGit** [comment]
The key pressed is **TAB** (I had put in inside sup & inf characters).



> * make `Tab` save back

Yes, I think that is a sensible choice, at least that what I expect.

**Comment by phweyland** [comment]
> * make `Tab` save back

Thanks, the simplest ! :). Done.

**Review by TurboGit — APPROVED** [review]
All good, ready for 4.0!

**Review by TurboGit — APPROVED** [review]
Thanks!
