### PR TITLE
fix for windows copy and import

### LINKED ISSUE #9707: Copy & Import: file paths non correctly managed under Windows
I can't make the new function Copy & Import work correctly in DT 3.6 under Windows.

In the dialog, under "base directory naming pattern", if I put a variable, for example

immagine

then the pictures are copied and imported in the database correctly, but the film roll name is including the picture folder name and a slash, which is incorrect

immagine

If instead, I put the absolute path

immagine

the the pictures are copied correctly, but not imported in the database

immagine

See in the error message that the backslash in E:\Immagini is removed.

I guess Windows file paths need some sanification.

### PR DESCRIPTION
**Pull request by Mark-64**
In Copy & Import, for Windows, using two escaped backslashes between base directory and subdirectory seems to be needed to make it work correctly.
Using a single forward slash as previously, also works for file copy, but create issues in the database.
This is a simple fix, I hope could be included in 3.6.1
Fixes #9707

### CODE REVIEW

**Comment by TurboGit** [comment]
> Using a single forward slash as previously, also works for file copy, but create issues in the database.

Can you comment on that? What issue does it creates? To me, as Windows supports both \ and / on path it seems safer to use the same separator as on Linux on the database.

**Comment by Profoktor** [comment]
#9630 ist _not_ fixed by this PR

**Comment by Mark-64** [comment]
@TurboGit Starting with a clean database, let's say I import in place and then copy/import the same image

with the patch
immagine
everything looks fine

Looking inside the database
immagine
is ok too

without the patch
immagine
This is incorrect, the main image folder is also part of the film roll name

Looking inside the database
immagine
there is anyway a mix of forward and backward slashes, wich might ok for the Windows file system, but is interpreted incorrectly in the film roll name (and maybe somewhere else)

**Comment by Mark-64** [comment]
An alternative is the following
In image.c

```
const char *dt_image_film_roll_name(const char *path)
{
  const char *folder = path + strlen(path);
  const int numparts = CLAMPS(dt_conf_get_int("show_folder_levels"), 1, 5);
  int count = 0;
  while(folder > path)
  {
    if(*folder == G_DIR_SEPARATOR)
      if(++count >= numparts)
      {
        ++folder;
        break;
      }
    --folder;
  }
  return folder;
}
```

the line `if(*folder == G_DIR_SEPARATOR)` expects a backslash, because `G_DIR_SEPARATOR` is equal to `'\\'` on Windows. That's why it doesn't work with forward slash.
So modifying it 

```
#ifdef _WIN32
    if(*folder == G_DIR_SEPARATOR || *folder == '/')
#else
    if(*folder == G_DIR_SEPARATOR)
#endif
```

also works. I am not sure this is better, though.

**Comment by Mark-64** [comment]
A third, perhaps more resilient approach is to just use the utility function dt_util_normalize_path(), which is not used in copy & import currently. That would keep all the shit inside that function.
So:
immagine
and therefore:
immagine

However, this piece of code commented out interferes with path detection in Windows and need to be eliminated.
immagine
Does anyone know its purpose?

**Comment by johnny-bit** [comment]
I'd preffer using `dt_util_normalize_path` wherever path manipulations like that are done, just have to solve the remaining TODO in that function :)

as for code elem - i think it's for checking escape and one needs to consider whole range of implications for it but i guess it'll be fine...
Side note - I think instead of screenshots you can link to code segments in github, which would be a bit more readable and provide a bit more context.

**Comment by Mark-64** [comment]
Ok, then perhaps it's better to avoid any risk of side effect and just use `dt_util_normalize_path()` , without touching the rest. 
See the new commit

File: src/common/import_session.c [hunk 1]
```diff
@@ -322,7 +322,7 @@ static const char *_import_session_path(struct dt_import_session_t *self, gboole
     return NULL;
   }
 
-  new_path = dt_variables_expand(self->vp, pattern, FALSE);
+  new_path = dt_util_normalize_path(dt_variables_expand(self->vp, pattern, FALSE));
```
Comment (TurboGit) [inline src/common/import_session.c:325]: This leaks memory and you do not free the now inaccessible char* returned by dt_variables_expand.

**Review by TurboGit — CHANGES_REQUESTED** [review]

**Comment by wpferguson** [comment]
@Mark-64 as I was testing last night I ran into another problem with paths which might be the same problem or something different.

I have a mapped drive, X:, and there are images in the root directory of the drive, i.e. X:\\myimage.cr2.  When I choose the X: drive in the copy and import dialog, the filename shows up as ylink.cr2 so I'm guessing that the \\m is getting interpreted as an escape and thus the image isn't shown.  Images in subdirectories of the X: drive show up fine.  If you select yimage.cr2 it doesn't import, since there is no image by that name.  Anyway, could you check and see if you can recreate and if you can does your fix take care of it?  Thanks

**Comment by Mark-64** [comment]
@TurboGit You're right, I will fix that
@wpferguson Yes, confimed. It is not the same bug, but related. I will look into this one as well

**Comment by Mark-64** [comment]
@wpferguson I found the issue.
The case when images are in the root is not managed correctly
In `import.c`
```
        gtk_list_store_set(d->from.store, &iter,
                           DT_IMPORT_UI_EXISTS, already_imported ? "âœ”" : " ",
                           DT_IMPORT_UI_FILENAME, &uifullname[folder_lgth + 1],
                           DT_IMPORT_FILENAME, &fullname[folder_lgth + 1],
                           DT_IMPORT_UI_DATETIME, dt_txt,
                           DT_IMPORT_DATETIME, datetime,
                           DT_IMPORT_THUMB, d->from.eye, -1);
```
the index `[folder_lgth + 1]` assumes that the path is `<drive_letter>:\\<folder>\\<filename>`
but if the file is in the root, then the path is `<drive_letter>:\\<filename>` and there one separator less
I believe the problem is in Linux too, but in Linux nobody puts image files in the root.

Tomorrow I will work on a fix, plus on other gui glitches in copy & import in Windows

**Comment by wpferguson** [comment]
> I believe the problem is in Linux too, but in Linux nobody puts image files in the root.

I just tried it, you are correct

**Comment by Mark-64** [comment]
Ok rebased, squashed in one commit and ready for review.
With this PR we fix three issues for Copy & Import in Windows

1) Incorrect film roll name after import (#9707 )

immagine

2) Image files in root folders displayed with truncated name as per @wpferguson  comment above (this affects Linux too)

3) Windows root folders displayed without the drive letter

before
immagine


after
immagine


Comments:
1) I had to revert using `dt_util_normalize_path()`, which doesn't work well for Windows. Infact it uses `GetLongPathNameW()` from Win32 api, which requires that the filepath being checked exists and it is writable.
Maybe this is on purpose, but the result is that the function cannot be used to sanitize a folder path before its creation.

2) The whole Windows file system support is messy and full of ad hoc solutions. Network paths are not supported (#9630, #9407). 
I have some ideas but that will take time and other PRs.

**Comment by johnny-bit** [comment]
Awesome!

> The whole Windows file system support is messy and full of ad hoc solutions

That's the tradeoff unfortunately.

> Maybe this is on purpose, but the result is that the function cannot be used to sanitize a folder path before its creation.

Generally we ought to strive towards unified path handling solutions. IMO `dt_util_normalize_path` should be "taught" to handle windows network shares (addressed it's TODO) and used everywhere where path normalization to existing file/dir be used. And another similar function could be created and used everywhere where we deal with path normalization to stuff that does not yet exist?

> I have some ideas but that will take time and other PRs.

Great :+1: more better win support :)

**Comment by wpferguson** [comment]
Pulling and checking...

**Review by wpferguson — APPROVED** [review]
Looks good to me

File: src/common/import_session.c (hunk 1 above)
Comment (Mark-64) [reply src/common/import_session.c]: PR no longer uses `dt_util_normalize_path()` now

File: src/libs/import.c [hunk 2]
```diff
@@ -678,6 +678,9 @@ static guint _import_set_file_list(const gchar *folder, const int folder_lgth,
   GError *error = NULL;
   GFile *gfolder = g_file_parse_name(folder);
 
+  // if folder is root, consider one folder separator less
+  int offset = (g_path_skip_root(folder)[0] ? folder_lgth + 1 : folder_lgth);
```
Comment (TurboGit) [inline src/libs/import.c:682]: a const here and we can merge.

**Review by TurboGit — CHANGES_REQUESTED** [review]
A minor comment. TIA.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by TurboGit** [comment]
Only merged on master as there is conflicts for the darktable-3.6.x branch. @Mark-64 : The merging is not straight so I have not done so, feel free to open a separate PR for 3.6.1. TIA.
