### PR TITLE
[masks/imageio] track module name changes in mask manager

### LINKED ISSUE #7640: Drawn mask group names in mask manager not in sync with module names
**Describe the bug**
Let's say you create a new duplicate of the `Exposure` module and add a drawn mask to it, now the mask group would be referred to as "grp exposure 1". If you would later decide to give the module a more specific name, e.g. "burn sky" the group name wouldn't be updated in the mask manager, however it is updated if you would want to re-add the mask as raster mask for a different module.

**Expected behavior**
I'd expect that the mask group would be always in sync with the module name which it is (firstly) associated to, such as it works for raster masks.

### PR DESCRIPTION
**Pull request by da-phil**
Fixes https://github.com/darktable-org/darktable/issues/7640

Track module name changes in mask manager.
Currently shapes in the mask manager get the name of module which created it, however once the module name is changed the change it not propagated to the mask manger, the old module name still is associated with the shape in the mask manager.

Additionally some refactoring in `masks.c` was done to reduce code duplication.

### CODE REVIEW

**Comment by da-phil** [comment]
Maybe @johnny-bit could have a look, according to the git history I see that you were dealing with the mask manager :smile:

**Comment by johnny-bit** [comment]
cursory glance looks ok. Try to make it go boom - if it doesn't crash and burn (make sure to test with spots & retouch modules) then it'll be fine IMO :stuck_out_tongue_winking_eye:

**Comment by da-phil** [comment]
> cursory glance looks ok. Try to make it go boom - if it doesn't crash and burn (make sure to test with spots & retouch modules) then it'll be fine IMO stuck_out_tongue_winking_eye

Actually I was able to make it go boom, but then discovered that this also happens on master and in release 3.4.0 :sweat_smile: 
See new isssue: https://github.com/darktable-org/darktable/issues/7673

Before merging I'd like to understand why the CI is reporting errors and try to address them if they are related to my changes.
Can somebody tell me how to re-trigger the CI without additional git interactions such as pushing new commits or force-pushing the same commit again and again?

**Comment by johnny-bit** [comment]
Doin't worry about windows and mac ci problems. i'm fixing those currently.

File: src/develop/masks/masks.c [hunk 1]
```diff
@@ -2137,6 +2147,17 @@ static void _menu_add_exist(dt_iop_module_t *module, int formid)
...
 
+void dt_masks_group_update_name(dt_iop_module_t *module)
+{
+  dt_masks_form_t *grp = dt_masks_group_from_module(module);
+  if (!grp)
+    return;
+
+  _dt_masks_group_set_name_from_module(module, grp);
+  dt_dev_add_masks_history_item(darktable.develop, module, TRUE);
+  dt_masks_iop_update(module);
```
Comment (da-phil) [inline src/develop/masks/masks.c:2158]: I'm not completely sure whether this is correct after renaming a form/group.
Do I need to also call `_check_id(grp);` like in the function which creates a new group (`dt_masks_group_create()`)?

**Review by da-phil — COMMENTED** [review]
I added only one concern of my current fix, maybe @johnny-bit  or @TurboGit  you can comment on that. 
Other than that I think it's ready.

Moreover I'd like to discuss with you guys about the general design concerns I raised in https://github.com/darktable-org/darktable/issues/7640#issuecomment-753635658

File: src/develop/masks/masks.c (hunk 1 above)
Comment (TurboGit) [reply src/develop/masks/masks.c:2158]: I don't think so, but hard to tell as there is missing comments on _check_id() but it seems only to ensure that we have no duplicate id. Since here you just change the name it seems ok.

File: src/develop/masks/masks.c [hunk 2]
```diff
@@ -2147,18 +2168,9 @@ void dt_masks_iop_use_same_as(dt_iop_module_t *module, dt_iop_module_t *src)
...
-    // we create a new group
-    grp = dt_masks_create(DT_MASKS_GROUP);
-    gchar *module_label = dt_history_item_get_name(module);
-    snprintf(grp->name, sizeof(grp->name), "grp %s", module_label);
-    g_free(module_label);
-    _check_id(grp);
-    darktable.develop->forms = g_list_append(darktable.develop->forms, grp);
-    module->blend_params->mask_id = grpid = grp->formid;
+  dt_masks_form_t *grp = dt_masks_group_from_module(module);
+  if(!grp) {
```
Comment (TurboGit) [inline src/develop/masks/masks.c:2172]: style : `{` should be on next line.

File: src/develop/masks/masks.c [hunk 3]
```diff
@@ -2108,25 +2122,21 @@ static void _menu_add_brush(struct dt_iop_module_t *module)
...
```
Comment (TurboGit) [inline src/develop/masks/masks.c:2138]: style : `{` should be on next line.

**Review by TurboGit — CHANGES_REQUESTED** [review]
minor style change

File: src/develop/masks/masks.c (hunk 1 above)
Comment (da-phil) [reply src/develop/masks/masks.c:2158]: I agree, that's what my thought was too :+1:

**Comment by da-phil** [comment]
> minor style change

Thanks for the feedback, I wasn't sure about the style as it is not consistent across the codebase anyway.

I even found a `.clang-format` in the code main folder, but apparently not many people apply clang-format before committing their changes :smile: 
Do you think it would be worthwhile to create a seperate PR to apply clang-format to the whole code-base to have a consistent code style? 

At work we have a CI job which checks whether new commits have clang-format applied, before those changes are merged to master.  Do you think it would be worthwhile to have something like that too in the future?

**Comment by TurboGit** [comment]
> Thanks for the feedback, I wasn't sure about the style as it is not consistent across the codebase anyway.

Right, but the far more common style is the one I quoted :)

> Do you think it would be worthwhile to create a seperate PR to apply clang-format to the whole code-base to have a consistent code style?

No, I have deactivated the script as it messes all the SQL statements that I have been formatting to make them readable.

>  Do you think it would be worthwhile to have something like that too in the future?

Yes, would be really nice indeed to have this for all PR. I don't think we want this for master as sometime style is violated for good reasons. Again readability is one very important aspect, remember that a line is written once but read many many times by different people. But anything that can improve the overall quality of the codebase is very important to me.

**Comment by TurboGit** [comment]
Another point, I do not care really about the final style, what is very important to me is the uniformity of the style across the code base. Every developer should feel comfortable with any source file and no source file should be identified by a specific style.

**Comment by da-phil** [comment]
> No, I have deactivated the script as it messes all the SQL statements that I have been formatting to make them readable.

> Yes, would be really nice indeed to have this for all PR. I don't think we want this for master as sometime style is violated for good reasons. Again readability is one very important aspect, remember that a line is written once but read many many times by different people. But anything that can improve the overall quality of the codebase is very important to me.

Yes, that's completely understandable, and therefore clang-format offers hints which will disable the code formatter for some lines of code, see https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code

If you want I can set-up a PR in which we re-activate clang-format'ing the codebase and disable it at the delicate sections of the code such as the SQL statements?

**Comment by johnny-bit** [comment]
you'd have to sprinkle code with loads of "clang format off" ;)

**Comment by da-phil** [comment]
> you'd have to sprinkle code with loads of "clang format off" ;)

Do you think it would be so much affected code? :smile: 
According to @TurboGit  mainly the SQL expressions would be affected.
Let's just try and see if we like it? ;)

**Comment by da-phil** [comment]
I'll create a new PR with a proposal on how we can deal with the automatic code formatting to achieve a uniform code style sometime.

As for the PR: I addressed @TurboGit points, for me it would be ready to go, if you don't object this behavior of tracking the module name within respective mask in the mask manager. However now renaming the shape does not make so much sense anymore, as the name will be overwritten once a module name is changed. This brings me back to the point of having read-only mask group names for masks which were created in a module. And then maybe we can enhance the mask manager by a button to create new mask groups in the manager.

File: src/develop/masks.h [hunk 4]
```diff
@@ -327,7 +328,9 @@ void dt_masks_gui_form_remove(dt_masks_form_t *form, dt_masks_form_gui_t *gui, i
 void dt_masks_gui_form_test_create(dt_masks_form_t *form, dt_masks_form_gui_t *gui);
 void dt_masks_gui_form_save_creation(dt_develop_t *dev, struct dt_iop_module_t *module, dt_masks_form_t *form,
                                      dt_masks_form_gui_t *gui);
+dt_masks_form_t *dt_masks_group_create(dt_iop_module_t *module, dt_masks_type_t type);
```
Comment (TurboGit) [inline src/develop/masks.h:331]: As this one is only used in body it should be removed from there as not a routine useful outside. And...

File: src/develop/masks/masks.c [hunk 5]
```diff
@@ -609,6 +603,23 @@ void dt_masks_gui_form_save_creation(dt_develop_t *dev, dt_iop_module_t *module,
...
 }
 
+static void _dt_masks_group_set_name_from_module(dt_iop_module_t *module, dt_masks_form_t *grp)
+{
+  gchar *module_label = dt_history_item_get_name(module);
+  snprintf(grp->name, sizeof(grp->name), "grp %s", module_label);
+  g_free(module_label);
+}
+
+dt_masks_form_t *dt_masks_group_create(dt_iop_module_t *module, dt_masks_type_t type)
```
Comment (TurboGit) [inline src/develop/masks/masks.c:613]: set this one static and remove leading `dt_masks_` from name to just have `_group_create`

**Review by TurboGit — CHANGES_REQUESTED** [review]
another minor change

**Comment by TurboGit** [comment]
Thanks ! I'll do a final review soon.

**Comment by TurboGit** [comment]
Works for me, thanks !

**Comment by TurboGit** [comment]
@da-phil : BTW, if you have some spare cycle as you are working on the mask manager I found while testing this PR that when you select a form from the mask manager and you move it the mask manager is redraw and the group is collapsed. Would be nice to avoid the collapse of the group to let user continue editing other forms in the same group.

**Comment by da-phil** [comment]
@TurboGit oh, I didn't even notice this behaviour, but  now it bothers me :stuck_out_tongue: 
I'll create another issue and have a look at it.

We should also talk about the general design of the mask manager, a question I raised again here: https://github.com/darktable-org/darktable/issues/7640#issuecomment-753635658
