### PR TITLE
utility: fix for librsvg 2.52

### LINKED ISSUE #10685: macOS 12.1: Watermark placed in 3.6 moved in 3.8.0
**Introduction**

**Did you buy darktable from an application store ?**

Downloaded today from darktable.org

**Describe the bug/issue**

Photos I had previously watermarked in darktable 3.6, when opened in 3.8.0, now show the watermark displaced from its previous location. I use an SVG file as a watermark and usually locate it in the lower right corner of the image.

The attached screenshots show a representative thumbnail generated by 3.6 in the lighttable view in 3.8.0, the darkroom view in 3.8.0 of that same image, and the thumbnail when I return to the lighttable view.

I have confirmed to my satisfaction that the SVG file has exactly the width and height of the graphical content of the watermark.

**To Reproduce**

1. Place watermark in darktable 3.6 and save.
2. Open image in 3.8.0.
3. Observe location of watermark has changed.

**Expected behavior**

I expect the watermark to not move between releases.

**Screenshots**

[Before](https://www.dropbox.com/s/xaf8nb58ifq45q6/Screen%20Shot%202021-12-24%20at%205.38.34%20PM.png?dl=0)

[darkroom view](https://www.dropbox.com/s/cygnn2i8s14sagk/Screen%20Shot%202021-12-24%20at%205.40.58%20PM.png?dl=0)

[After](https://www.dropbox.com/s/0xgfu7r8sdir1e9/Screen%20Shot%202021-12-24%20at%205.41.34%20PM.png?dl=0)

**Screencast**

**Which commit introduced the error**

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0 (release)
* OS                : macOS 12.1
* Memory            : 64GiB
* Graphics card     : 2x AMD FirePro D500, 3GB each
* Graphics driver   : Apple
* OpenCL installed  : Apple OpenCL 1.2
* OpenCL activated  : Yes

**Additional context**

I will attempt to reproduce this on my Linux machine (Ubuntu Studio 20.04).

### PR DESCRIPTION
**Pull request by parafin**
dimensions weren't computed correctly when there was no intrinsic size:
1). offset shouldn't be added to size
2). returned value could have been small (<1) which rounds to zero

Fixes #10685

### CODE REVIEW

File: src/common/utility.c [hunk 1]
```diff
@@ -911,10 +911,18 @@ RsvgDimensionData dt_get_svg_dimension(RsvgHandle *svg)
     }
     else
     {
+#define VIEWPORT_SIZE 10000 //some random big value to have enough precision when size is converted to int
```
Comment (ralfbrown) [inline src/common/utility.c:914]: I would recommend 32767, as that is the largest image size supported by Cairo.  (Watermarks are currently broken anyway for full-size exports of images with dimensions greater than that, such as stitched panoramas.)

Comment (parafin) [reply src/common/utility.c:914]: I'm not completely sure what consequences this number has (e.g. on performance and render quality). Probably not a very good idea to actually go to the limit, given that watermark can be rotated... How about 16384?

Comment (ralfbrown) [reply src/common/utility.c:914]: I suppose it depends on how the 'get geometry' function is implemented.  But if the resulting dimensions generate an upscaled image that later needs to be downscaled before adding to the image, then the best viewport size to use is probably the actual image size rather than some fixed value (with the caveat that it needs to be clamped to 32767).

Comment (parafin) [reply src/common/utility.c:914]: I've looked at watermark iop code - cairo surface size is calculated based on processing image size, not watermark dimensions. Returned watermark dimensions are used as is for viewport when rendering to that cairo surface prepended by cairo_scale call, so that watermark would fit. Seems that changing the ratio between scale factor and dimensions (viewport size) doesn't affect the quality (and therefore probably speed too). I think because this is vector graphics, these numbers are only used for calculation of coordinates and doesn't affect how graphics are drawn. No downscaling/upscaling of actual image data is happening because of viewport size. E.g. viewport 1x1 produced visually good result except for positioning (that's what happened in #10685). So the only thing that VIEWPORT_SIZE constant affects is precision of watermark aspect ratio due to conversion between float and int. Given that maximum image size is 32767, the extreme case would be aspect ratio of 1/32767 (though 1 pixel line is probably not very useful as a watermark). So OK, let's go with VIEWPORT_SIZE == 32767, at least it's not a random number.

**Comment by parafin** [comment]
I think this is ready, but let's hear from @ralfbrown.

**Review by TurboGit — APPROVED** [review]
Looks good to me and the regression test is OK:

```
Test 0032-watermark
      Image mire1.cr2
      CPU & GPU version differ by 8230 pixels
      CPU vs. GPU report :
      ----------------------------------
      Max dE                   : 2.76747
      Avg dE                   : 0.00154
      Std dE                   : 0.03072
      ----------------------------------
      Pixels below avg + 0 std : 99.71 %
      Pixels below avg + 1 std : 99.71 %
      Pixels below avg + 3 std : 99.71 %
      Pixels below avg + 6 std : 99.72 %
      Pixels below avg + 9 std : 99.75 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 0.54489
      Avg dE                   : 0.00000
      Std dE                   : 0.00033
      ----------------------------------
      Pixels below avg + 0 std : 100.00 %
      Pixels below avg + 1 std : 100.00 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 0.00 %
 
  OK

Total test 1
Errors     0
see test-20211229-110931.log
```

@ralfbrown : Ok to go?

**Comment by ralfbrown** [comment]
Looks fine to me.

**Comment by TurboGit** [comment]
Merging then, thanks!
