### PR TITLE
Fixing Y0-mask calculations (#13271)

### LINKED ISSUE #13271: Turning off white balance gives black image when demosaicing is RCD+VNG4
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
When turning off white balance module, the image turns black. But only if RCD+VNG4 is active.
Skärmbild från 2023-01-03 23-22-34

CC0 raw file with xmp from Canon EOS R6 [20230103_R6_9123.zip](https://github.com/darktable-org/darktable/files/10340203/20230103_R6_9123.zip)

**Platform**
Ubuntu 22.04

* darktable version : 4.2

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
The reported issue was about instability while dual-demosaicing if white-balance module was switched off.

This is due to undefined wb coeffs (zero) possibly calculating NaNs while calculating the Y0 mask which is used for the scharr operator.

This pr makes sure the the taken coeffs are at least 1.0 for each channel, this affects dual demosaicers and the details mask (there was a workaround for that).

Fixes #13271

Safe bugfix for 4.2.1

### CODE REVIEW

File: src/develop/pixelpipe_hb.c [hunk 1]
```diff
@@ -2517,13 +2517,9 @@ gboolean dt_dev_write_rawdetail_mask(dt_dev_pixelpipe_iop_t *piece, float *const
   p->rawdetail_mask_data = mask;
   memcpy(&p->rawdetail_mask_roi, roi_in, sizeof(dt_iop_roi_t));
 
-  dt_aligned_pixel_t wb = { piece->pipe->dsc.temperature.coeffs[0],
-                            piece->pipe->dsc.temperature.coeffs[1],
-                            piece->pipe->dsc.temperature.coeffs[2] };
-  if((p->want_detail_mask & ~DT_DEV_DETAIL_MASK_REQUIRED) == DT_DEV_DETAIL_MASK_RAWPREPARE)
```
Comment (TurboGit) [inline src/develop/pixelpipe_hb.c:2523]: Why removing this? It seems related to masking... Or maybe it was some kind of workaround for the issue you've properly fixed here?

Comment (jenshannoschwalm) [reply src/develop/pixelpipe_hb.c:2523]: Yes. It was a workaround.

Comment (TurboGit) [reply src/develop/pixelpipe_hb.c:2523]: Noted, thanks!

**Comment by ralfbrown** [comment]
I'm pretty sure I've seen some (extreme) instances where the R or B coefficient was legitimately less than 1.0.  Would it be better to use a smaller but nonzero bound like 0.1?

**Comment by jenshannoschwalm** [comment]
> I'm pretty sure I've seen some (extreme) instances where the R or B coefficient was legitimately less than 1.0. Would it be better to use a smaller but nonzero bound like 0.1?

I would have never imagined such images exist :-) (Can't think of a reason to be so too). Will think about it ...

**Comment by parafin** [comment]
At the very least it’s possible to set such values manually.

**Comment by jenshannoschwalm** [comment]
Right you are. Making use of the temperature->enabled flag as set by that module instead ...

**Comment by TurboGit** [comment]
Merged in master & 4.2 branch.
