### PR TITLE
Bugfix: Opposed chroma correction OpenCL update

### LINKED ISSUE #13362: Inpaint opposed highlight reconstruction OpenCL code 5x slower than CPU code
**Describe the bug/issue**

After the change in the following PR, I see a significant slow-down in the "inpaint opposed" OpenCL code: https://github.com/darktable-org/darktable/pull/13254

OpenCL turned off:
`[dev_process_image] pixel pipeline processing took 0,164 secs (1,021 CPU)`
see log [without_open_cl.txt](https://github.com/darktable-org/darktable/files/10439761/without_open_cl.txt)

With OpenCL:
`[dev_process_image] pixel pipeline processing took 0,953 secs (0,382 CPU)`
see log [with_open_cl.txt](https://github.com/darktable-org/darktable/files/10439760/with_open_cl.txt)

According to this log the culprit seems to be the function ``highlights_chroma``.

Can you maybe have a look @jenshannoschwalm?
At the same time I want to thank you for all your valuable contributions to the hlr code, this made DT so much better for dealing with blown highlights!

**To Reproduce**

* Make sure OpenCL is activated and used.
* Load random RAW image and turn on "inpaint opposed" method in the highlight reconstruction module.
* Zoom in and out to enforce pixel pipe to recompute image very often

Compare with darktable running with OpenCL turned off (add `` --disable-opencl`` to darktable command)

**Expected behavior**

Runtime equal or shorter as before change, as code changes were supposed to increase performance.

**Which commit introduced the error**

This PR introduced the change: https://github.com/darktable-org/darktable/pull/13254

**Platform**

* darktable version : latest master (4.3.0+244~g2131b15f6-dirty)
* OS                : Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 32 GB
* Graphics card     : AMD Radeon rx 5700 xt 
* Graphics driver : amdgpu 5.4
* OpenCL installed  : yes
* OpenCL activated  : yes

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As reported the current OpenCL code for chroma correction is **very** slow at least on AMD cards, in fact it only works fine on nvidia cards as they support an atomic float add (the other cards use a simulated instruction involving a poll).

The new code doen't use any atomic instructions at all, as the algorithm doesn't allow a simple reduction based on 2d data a bunch of new functions for 1d kernels was introduced.

On my machine the new code has no penalty (in fact seems to be a bit faster) and should also work fine on non-nvidia devices.  

Fixes #13362
Replaces #13372

### CODE REVIEW

**Comment by MStraeten** [comment]
looks fine on mac with amd gpu

**Comment by piratenpanda** [comment]
here as well on my RX580 on arch

File: src/common/opencl.c [hunk 1]
```diff
@@ -2363,6 +2363,45 @@ int dt_opencl_enqueue_kernel_2d_args_internal(const int dev, const int kernel, c
...
 
+int dt_opencl_enqueue_kernel_1d_with_local(const int dev, const int kernel, const size_t *sizes,
+                                           const size_t *local)
+{
+  dt_opencl_t *cl = darktable.opencl;
+  if(!cl->inited || dev < 0) return -1;
+  if(kernel < 0 || kernel >= DT_OPENCL_MAX_KERNELS) return CL_INVALID_KERNEL;
+
+  char buf[256];
+  buf[0] = '\0';
```
Comment (TurboGit) [inline src/common/opencl.c:2374]: Is equivalent to:

`char buf[256] = { 0 };`

**Review by TurboGit — CHANGES_REQUESTED** [review]
Apart the minor style comment, looks good to me.

**Comment by dterrahe** [comment]
I have to say, I don't understand the technical issue here on the driver side _at all_, so I have no idea if this is going to be used much/the majority of cases?

But assuming not, do we really need duplicates for `dt_opencl_enqueue_kernel_1d_with_local`, `dt_opencl_enqueue_kernel_1d` _and_ `dt_opencl_enqueue_kernel_1d_args_internal`?

My approach when I refactored this was to _only_ in the bog standard case use `dt_opencl_enqueue_kernel_2d_args` and otherwise just call `dt_opencl_set_kernel_args` and set up `sizes` first (in `_process_opposed`) and then directly call `dt_opencl_enqueue_kernel_2d_with_local` (you can find many examples in the codebase).

The latter you'll have to create a duplicate `dt_opencl_enqueue_kernel_1d_with_local` for, but they could both simply call a refactored `dt_opencl_enqueue_kernel_nd_with_local` which would have an additional parameter 1 or 2. Rather then lazily (sorry) copying _all_ the code. I may have missed some subtle differences. But that is really the point; two almost identical functions hide what are the essential differences. And that means in future people will always resort to just adding one more special case function because they can't really understand anymore what is reusable.

**Comment by da-phil** [comment]
Also works fine on my Radeon RX 5700 XT :+1:

**Comment by jenshannoschwalm** [comment]
> But assuming not, do we really need duplicates for ...

I fully accept your critics ! (should have done better ...)

**Comment by dterrahe** [comment]
It must have been a really nasty problem to track down, so I can understand the joy of finally finding _something_ that fixes it. You can count on me to spoil part of that joy!

**Comment by jenshannoschwalm** [comment]
@dterrahe should be good now (except the va issue discussed elsewhere ...)
No maths changed, housekeeping in the commits ...

**Comment by dterrahe** [comment]
All looking good! Thank you!

TBH I'm not sure why originally `sizes` was always loaded with n+1 values with the last one always set to 1. https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html says they only expect 1 or 2 values in the array. So this may be cargo cult _or_ it could be hard earned wisdom, so not really worth messing with imho.

**Comment by jenshannoschwalm** [comment]
> TBH I'm not sure why originally `sizes` was always loaded with n+1 values with the last one always set to 1. https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html says they only expect 1 or 2 values in the array. So this may be cargo cult _or_ it could be hard earned wisdom, so not really worth messing with imho.

Don't know either, we can have up to three sizes for 3 dimensions. From my knowing the dt code we always do 2d kernels except the latest one introduced here. Maybe there were early issues long gone ...

**Comment by dterrahe** [comment]
It may be that some flaky drivers always read 3 values, even when work_dim is set to 1 or 2. So if you want to be extra careful (and perpetuate the myth) you _could_ set
`size_t sizes[] = { iheight, 1, 1};`
like is done elsewhere (when dim = 2) but it _shouldn't_ lead to fewer crashes....

**Comment by jenshannoschwalm** [comment]
> So if you want to be extra careful (and perpetuate the myth) you _could_ set

:-) Let's wait for report about out-of-resources error or "perpetuate"?

**Comment by jenshannoschwalm** [comment]
Maybe we should always define with a specified array size like `size_t sizes[3] = { a, b, c};`?

**Comment by dterrahe** [comment]
This is done in many places, but the [3] is inferred by the compiler anyway. I am not here to say that 3 elements _should_ always be enforced (rather the opposite) but only that they _have_ been and I've been too often guilty of breaking stuff because I assumed (or found "evidence") that parts could be removed because they looked to be the result of aggressive copy/pasting.

If you were to "fix" this across the whole codebase, then you maybe should have some indication that it _actually_ adds benefit, because you'll be setting a practice in stone. Otherwise, it seems that it is "working" so why not leave it alone :-)

**Comment by jenshannoschwalm** [comment]
> then you maybe should have some indication that it _actually_ adds benefit,

Don't have that right now.

**Comment by jenshannoschwalm** [comment]
Ready to go

**Review by TurboGit — APPROVED** [review]
Thanks!
