### PR TITLE
edited fields focus fix

### LINKED ISSUE #5460: Issue on entering metadata or tag info.
**Describe the bug**
Mouse hovering on images makes lose the focus on metadata and tag entries. The result is always unexpected when one is writing ...

**To Reproduce**
Select an entry in metadata, start writing something.
If the mouse moves and hovers an image the written text disappears and is lost.
Worse, if the mouse move happens unexpectedly and one continues to write, dt executes the action corresponding to the entered shortcuts (instead of writing the text).

**Expected behavior**
As long as another image (EDIT or another field) is not selected (clicked on), there is no reason for losing the current text, and to have the risk to break something.

**Additional context**
darktable 3.1.0+2137~g3b19bdfa2
OS debian 10

### PR DESCRIPTION
**Pull request by phweyland**
edited fields focus fix
- don't grab focus on hovering thumbnails
- ~~metadata clear entry when focus is lost~~
- metadata remove redraw widget callback (cairo not involved here)
- ~~tag clear entry when focus is lost~~
- treat tag entry escape

Fixes #5460 

Pinging @AlicVB for potential side effect on thumbtable. On my side I haven't seen any, but your vision on this is surely better than mine.

### CODE REVIEW

**Comment by AlicVB** [comment]
I've not found any drawback either. I admit that I don't exactly remember why the focus in the inside view was required. It was for accels, but they seems to work well like that...

So that seems fine for me !

**Comment by phweyland** [comment]
> So that seems fine for me !

Thanks a lot for checking this.

**Comment by TurboGit** [comment]
IIRC @elstoc changed for focus request to fix key shortcut in some cases. So I'd like his view on this change if possible before merging. @elstoc is that ok with you ?

**Comment by elstoc** [comment]
I haven't tested but I don't think this should be a big issue. The only fixes I have added were:

- give focus to centre screen when clicking on an iop module header (so darkroom only) in order to take focus away from the search box
- pass keyboard shortcuts to key_pressed view handler if not already handled by a bauhaus widget (slider/combobox) that currently has keyboard focus

This change will have the impact that it stops the lighttable keyboard shortcuts (moving image, viewing the preview) from working (unless you click on a thumbnail in the centre view to reassign focus), but that seems reasonable if you've chosen to edit a metadata field. Gtk entry fields seem to stubbornly keep keyboard focus unless you explicitly assign it to something else.

Perhaps we could add something to this so that when you expand/collapse lib views this also delivers focus back to the centre view (dt_ui_center(darktable.gui->uk)) - similar to my first fix above.

Longer term, we really should get rid of the key_pressed handlers in the views (at least for the preview window) and replace them with standard keyboard shortcuts, since they currently require a few hacks to ensure they keep working reliably.

File: src/libs/metadata.c [hunk 1]
```diff
@@ -214,35 +210,30 @@ static void _update(dt_lib_module_t *self, gboolean early_bark_out)
...
 
 static void _collection_updated_callback(gpointer instance, dt_collection_change_t query_change, gpointer imgs,
                                         int next, dt_lib_module_t *self)
 {
-  _update(self, FALSE);
-}
-
-static gboolean _draw(GtkWidget *widget, cairo_t *cr, dt_lib_module_t *self)
-{
-  if(!dt_control_running()) return FALSE;
```
Comment (johnny-bit) [inline src/libs/metadata.c:235]: this still should IMO have this bit. it's basically saying "if darktable is closing, do nothing on this event"

**Comment by johnny-bit** [comment]
For some of the stuff @elstoc's saying #5063 would be optimal "solution"...

I've tested this PR and it seems like it doesn't affect anything negatively. so it's all good for me except that small dt_running conditional.

File: src/libs/metadata.c (hunk 1 above)
Comment (phweyland) [reply src/libs/metadata.c:235]: Good to do nothing if exiting dt !
But _draw() is called thousands of times and I haven't still figured out what it does in metadata on normal time...
The "draw" event is related to cairo stuff. In metadata module I don't see anything related to that. It's possible to have had some role in the past. But currently I don't see what it does. Do you have any idea ?

**Comment by phweyland** [comment]
>  but that seems reasonable if you've chosen to edit a metadata field. Gtk entry fields seem to stubbornly keep keyboard focus unless you explicitly assign it to something else.

To edit any field grab focus is required otherwise shortcut are captured and one cannot even write "bloody hell". So when a field is edited it seems normal that shortcuts are disabled (except the edition ones). But the focus is released all shortcuts should work properly.

Hoovering is handy to get on the fly information (about image, tooltips, ...) but should NEVER steal the focus (even in darkroom).

> This change will have the impact that it stops the lighttable keyboard shortcuts (moving image, viewing the preview) from working

Could you pinpoint the code which could fail without having the focus (I don't know these features moving image, viewing the preview ...) ?
I'll check they still work.
dt_view_get_image_to_act_on() is always aware of the hoovered image even while editing (to check that start edit a metadata field (with that PR), hover other images, you can see image information and tagging updated correctly). 
When focus is released, shortcuts are enabled again and the cases you mention should still work.

File: src/libs/metadata.c (hunk 1 above)
Comment (johnny-bit) [reply src/libs/metadata.c:235]: Since it simply called _update with early `bark_out` (lol) then it's most likelly that it was just overzealous update mechanism. i _think_ for metadata it would be enough to just use collection/selection/mouse_over signals and it would be "enough".

if i remember correctly dt_signal_raise doesn't even raise signals if closing darktable so it avoids unnecessary handling.

**Comment by phweyland** [comment]
> (dt_ui_center(darktable.gui->uk))

For my understanding, do you know what is the difference with (dt_ui_main_window(darktable.gui->ui)), which is commonly used inside modules, in term of focus behavior ?

**Comment by phweyland** [comment]
> For some of the stuff @elstoc's saying #5063 would be optimal "solution"...

Ooops, this one is a big stuff !
However, the discussion here is only about focus, and I'm sure that with any other input system, focus still must be handled properly.

File: src/libs/metadata.c (hunk 1 above)
Comment (phweyland) [reply src/libs/metadata.c:235]: I agree with what was executed :) but I just don't figure out why the "draw" event was triggered ...

**Comment by elstoc** [comment]
> Could you pinpoint the code which could fail without having the focus

In my experience if any other widget has keyboard focus, the key_pressed function in the darkroom/lighttable view code does not get run. But with a gtkentry widget I think that grabs all of the keyboard input anyway. There was an issue with the module search in the darkroom that, because it never gave up keyboard focus, none of the keyboard shortcuts worked unless you first clicked on the centre image (hence my fix was to give keyboard focus to the centre image). I agree that hovering should never grab the keyboard focus, my issue was that something at some point needs to make the metadata module _lose_ focus in order for the shortcuts to start working again. If you've done this then I'm sure it will work fine, or clicking in the lighttable centre panel will also work.

> For my understanding, do you know what is the difference with (dt_ui_main_window(darktable.gui->ui)), which is commonly used inside modules, in term of focus behavior ?

I assume that the above gives focus to the entire window, which then probably passes that focus down to the first one of its children that can accept keyboard focus, whereas gtk_widget_grab_focus(dt_ui_center(darktable.gui->uk)) specifically hands the focus to the centre panel. I think the gtk documentation suggests its preferable to assign focus to a specific widget as it won't be entirely predictable where the focus will get assigned if you give it to the whole window.

**Comment by phweyland** [comment]
>  There was an issue with the module search in the darkroom that, because it never gave up keyboard focus, none of the keyboard shortcuts worked unless you first clicked on the centre image

I see, that is what one has always done, not very handy, agreed. But that's the role of the escape key, isn't it ? While escape key was already implemented on metadata, I've just added it on tagging where it was missing. Maybe it is also missing in this darkroom search field. I think that escape key is handier than clicking anywhere on the centre image.

> gtk_widget_grab_focus(dt_ui_center(darktable.gui->uk)) specifically hands the focus to the centre panel. I think the gtk documentation suggests its preferable to assign focus to a specific widget as it won't be entirely predictable where the focus will get assigned if you give it to the whole window

It's important to note that `grab focus` is more than `set focus` to a widget. It gives the ability to that widget to get all the entered keys (as we need for editing).

**Comment by elstoc** [comment]
> Maybe it is also missing in this darkroom search field

I think the difference is that with the darkroom search field, once your search is successful the next thing you will do is click on a module header or adjust a bauhaus widget, which is how you indicate you're done with the search box. Hard to see why you'd want to search and then not follow it up with another module action (for which the tab key is fine, if you know to use it).

**Comment by phweyland** [comment]
> > Maybe it is also missing in this darkroom search field
> 
> I think the difference is that with the darkroom search field, once your search is successful the next thing you will do is click on a module header or adjust a bauhaus widget, which is how you indicate you're done with the search box. Hard to see why you'd want to search and then not follow it up with another module action (for which the tab key is fine, if you know to use it).

... when I search a module, I end up clicking on the one I want. This makes the search field lose the focus, before adjusting whatever slider, right ? Then shortcuts should work properly for the slider. Is that still correct ? (Note I do not see any slider before selecting and opening a module).

TAB does make the search field lose the focus, but not escape key. This one is really missing.

File: src/libs/metadata.c (hunk 1 above)
Comment (johnny-bit) [reply src/libs/metadata.c:235]: the _draw is triggered every time widget for full iop has to be redrawn (so quite often). you could try and comment out
```c
g_signal_connect(self->widget, "draw", G_CALLBACK(_draw), self);
```
in `gui_init` and thus avoid unnecessary calls. then see what (if anything) changes, making sure that the other signals I've mentioned are handled.

**Comment by elstoc** [comment]
> ... when I search a module, I end up clicking on the one I want. This makes the search field lose the focus, before adjusting whatever slider, right ? Then shortcuts should work properly for the slider. Is that still correct ?

So yes it does that, but it didn't used to if you just expanded the module (to look at the parameters maybe) without adjusting a bauhaus widget. It works like that now because I changed so that when you click on the module header the callback function causes the centre panel to grab focus. Prior to that fix the search box retained focus until you clicked or adjusted a bauhaus widget. 

> (Note I do not see any slider before selecting and opening a module)

You might see a slider without opening a module if that module was already open (in another module group).

I agree with you that escape to clear the box and lose focus would be useful.

File: src/libs/metadata.c (hunk 1 above)
Comment (phweyland) [reply src/libs/metadata.c:235]: >  you could try and comment out

This is already done, isn't it ? :)

**Comment by phweyland** [comment]
>  It works like that now because I changed so that when you click on the module header the callback function causes the centre panel to grab focus.

Why not to give the focus the module on which the user has clicked on ? (that would remove the focus from search field as well). But if that works, that's already good.

I think we are all aligned, aren't we ?

**Comment by elstoc** [comment]
> Why not to give the focus the module on which the user has clicked on ?

That was my first attempt but because the header can't do anything with the keyboard focus it handed it down to the first available (random) bauhaus widget meaning that scroll then changed random sliders/comboboxes depending on the module.

> I think we are all aligned, aren't we ?

Yes we got off on a tangent there didn't we. I'm fine with this change. We can always tweak later if there are any minor issues.

**Comment by phweyland** [comment]
Pascal, is ready for your review when you can.

**Comment by TurboGit** [comment]
I was not sure this was ready for review and was sidetracked by many other things. I should be able to come back to this tomorrow.

**Comment by TurboGit** [comment]
I found a quite big issue.

- select a picture
- enter "toto" into title metadata field
- click on [apply]

The metadata is lost from the field and not applied to the picture.

**Comment by phweyland** [comment]
>     * click on [apply]
> 
> 
> The metadata is lost from the field and not applied to the picture.

Arghhh! Quite possible. I look at it.

**Comment by phweyland** [comment]
I've removed the field clearing on lost of focus. Should work better now. Sorry for that.

I'm not completely satisfied with ergonomics but that's anterior to this fix and can be done in another PR: there is no visual difference between fields already saved and fields newly entered and not yet saved (those which will be cleared if one presses escape).
