### PR TITLE
grouping fix

### LINKED ISSUE #4840: Group indicator "G" is not reset when current group is diminished to a single image
openSUSE Tumbleweed 20200425
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable 3.1.0~git1346.532efbf17-2885.1.x86_64
OpenCL on 
i7 12-core 36GB

Select an image in lightroom
duplicate the image, now a group exists and the original image is marked "G"
delete the original image in light table, the "G" indicator moves to the duplicate image, only remaining image, but there is no longer a group.

The "G" indicator should disappear.

### PR DESCRIPTION
**Pull request by phweyland**
grouping fix
- duplicate selected
- remove/delete selected (duplicate or real image)

cleanup unused code in control_jobs.c

fixes #4840

### CODE REVIEW

File: src/common/grouping.c [hunk 1]
```diff
@@ -82,6 +82,7 @@ int dt_grouping_remove_from_group(const int image_id)
     wimg->group_id = image_id;
     dt_image_cache_write_release(darktable.image_cache, wimg, DT_IMAGE_CACHE_SAFE);
     imgs = g_list_prepend(imgs, GINT_TO_POINTER(image_id));
+    imgs = g_list_prepend(imgs, GINT_TO_POINTER(img_group_id));
```
Comment (TurboGit) [inline src/common/grouping.c:85]: Can you explain this one ? I don't understand the use!

Especially since the signal is only caught in thumtable and calls `_dt_image_info_changed_callback` where we iterate over all values comparing to the imgid.

Comment (phweyland) [reply src/common/grouping.c:85]: One part of the bug is when one removes the second image image of a group of two. The main image remains with the group symbol. 
Then this line forces the refresh of thumbnail info for the remaining image.

> specially since the signal is only caught in thumtable and calls `_dt_image_info_changed_callback` where we iterate over all values comparing to the imgid.

yes, but only on the provided list (and not all the displayed images in lt).

Comment (TurboGit) [reply src/common/grouping.c:85]: Ok, maybe a small comment to clarify this in the code ?

Comment (TurboGit) [reply src/common/grouping.c:85]: And maybe while we are at it only register the img_group_id if different than the image_id:

`if(image_id != img_group_id) imgs = g_list_prepend(...);`

**Comment by Nilvus** [comment]
@phweyland: group icons on thumbnails are now ok and all seems to work for what I test on my side. Thanks.

File: src/common/grouping.c (hunk 1 above)
Comment (phweyland) [reply src/common/grouping.c:85]: > And maybe while we are at it only register the img_group_id if different than the image_id:
> 
> `if(image_id != img_group_id) imgs = g_list_prepend(...);`

That's already the case, line 50...  :)


> Ok, maybe a small comment to clarify this in the code ?

I'll do it.

Comment (phweyland) [reply src/common/grouping.c:86]: Done

**Comment by TurboGit** [comment]
All good then. Thanks.
