### PR TITLE
presets menu: add preferences entry. applied to metadata_view and metadata plugins

### LINKED ISSUE #5609: Image Information Display
**Describe the bug**
When the import, change, export, and print timestamps got added to the database they were inserted into the metadata.c code where it seemed to make the most sense, according to the code comments.  However, the data displays in the order that it's declared, so the timestamp information is displayed while image information such as exposure, ISO, timestamp, height, width... are pushed out of the viewport.

image_info

**To Reproduce**
1. Open darktable
2. Hover over an image

**Platform (please complete the following information):**
 - Darktable Version: git master
 

**Additional context**
This is simple enough to fix, but I thought that I would open an issue in case anyone else had ideas about the information displayed and the order.

My plan is to move the timestamps to the bottom, unless someone has a better idea of where to place them.

### PR DESCRIPTION
**Pull request by phweyland**
Do not solve #7050 but could contribute as suggested [here](https://github.com/darktable-org/darktable/issues/7050#issuecomment-743407679)

Fixes #5609

Introduce the set_preferences() routine for plugin. When exists add an entry at the bottom of the presets menu.
Apply this to metadata editor.
image

Use it to select and hide the metadata_view information one is not interested in.
image

@Nilvus. You may want to give advices / instructions to ensure a consistent look / behavior for these popups.

### CODE REVIEW

File: src/libs/metadata.c [hunk 1]
```diff
@@ -726,12 +726,6 @@ void gui_init(dt_lib_module_t *self)
   gtk_box_pack_start(hbox, d->apply_button, TRUE, TRUE, 0);
   g_signal_connect(G_OBJECT(d->apply_button), "clicked", G_CALLBACK(_apply_button_clicked), self);
 
-  d->config_button = dtgtk_button_new(dtgtk_cairo_paint_preferences, CPF_STYLE_BOX, NULL);
```
Comment (dterrahe) [inline src/libs/metadata.c:729]: Also remove https://github.com/darktable-org/darktable/blob/599679fe93b7fbefe4ffa8ec5ec8011a51bccf3b/src/libs/metadata.c#L49

File: src/libs/metadata_view.c [hunk 2]
```diff
@@ -93,66 +96,73 @@ enum
...
-  _md_labels[md_internal_groupid] = _("group id");
-  _md_labels[md_internal_filename] = _("filename");
-  _md_labels[md_internal_version] = _("version");
-  _md_labels[md_internal_fullpath] = _("full path");
-  _md_labels[md_internal_local_copy] = _("local copy");
-  _md_labels[md_internal_import_timestamp] = _("import timestamp");
-  _md_labels[md_internal_change_timestamp] = _("change timestamp");
-  _md_labels[md_internal_export_timestamp] = _("export timestamp");
-  _md_labels[md_internal_print_timestamp] = _("print timestamp");
+  _labels[md_internal_filmroll] = "filmroll";
```
Comment (dterrahe) [inline src/libs/metadata_view.c:106]: You'll want to mark all of these strings for translation using for example `N_("filmroll")`, otherwise the call to `_(_labels[i])` below won't be able to find any translations.

File: src/libs/metadata_view.c [hunk 3]
```diff
@@ -791,6 +807,115 @@ void connect_key_accels(dt_lib_module_t *self)
...
+            _("tick if the corresponding metadata is of no interest for you"));
+
+  char *pref = dt_conf_get_string("plugins/lighttable/metadata_view/pref_hidden");
+  GList *prefs = dt_util_str_to_glist(",", pref);
+  g_free(pref);
+  GtkWidget *hidden[md_size];
+  gboolean hide[md_size];
+  for(int i = 0; i < md_size; i++)
+  {
+    label = gtk_label_new(_md_labels[i]);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:860]: could you use dt_ui_label_new? it is missing `gtk_label_set_xalign (label, 0.0f);`  which should be added there.

File: src/libs/metadata_view.c [hunk 4]
```diff
@@ -791,6 +807,115 @@ void connect_key_accels(dt_lib_module_t *self)
...
+  char *pref = dt_conf_get_string("plugins/lighttable/metadata_view/pref_hidden");
+  GList *prefs = dt_util_str_to_glist(",", pref);
+  g_free(pref);
+  for(int i = 0; i < md_size; i++)
+  {
+    const gboolean hidden = g_list_find_custom(prefs, _labels[i], (GCompareFunc)g_strcmp0) != NULL;
+    for(int j = 0; j < 2; j++)
+    {
+      GtkWidget *w = gtk_grid_get_child_at(GTK_GRID(d->grid), j, i);
+      gtk_widget_show_all(w);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:822]: this show_all is probably not needed as you are dealing with single widgets (not containers) here?

File: src/libs/metadata_view.c [hunk 5]
```diff
@@ -791,6 +807,115 @@ void connect_key_accels(dt_lib_module_t *self)
...
+    gtk_label_set_xalign (GTK_LABEL(label), 0.0f);
+    gtk_label_set_ellipsize(GTK_LABEL(label), PANGO_ELLIPSIZE_END);
+    gtk_grid_attach(GTK_GRID(grid), label, 0, i+1, 1, 1);
+
+    hidden[i] = gtk_check_button_new();
+    gtk_widget_set_halign(hidden[i], GTK_ALIGN_CENTER);
+    hide[i] = g_list_find_custom(prefs, _labels[i], (GCompareFunc)g_strcmp0) != NULL;
+    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(hidden[i]), hide[i]);
+    gtk_grid_attach(GTK_GRID(grid), hidden[i], 1, i+1, 1, 1);
+    if(i >= md_xmp_metadata && i < md_xmp_metadata + DT_METADATA_NUMBER)
```
Comment (dterrahe) [inline src/libs/metadata_view.c:871]: If you moved `gtk_widget_show_all(dialog);` _before_ the loop, you could simplify this to
```
    // metadata plugin preferences have precedence
    gboolean hide_line = i >= md_xmp_metadata &&
                         i < md_xmp_metadata + DT_METADATA_NUMBER &&
                         !gtk_widget_is_visible(GTK_WIDGET(d->name[i]));
    gtk_widget_set_visible(label, !hide_line);
    gtk_widget_set_visible(hidden[i], !hide_line);

```
but I'm not sure about the logic and it also doesn't seem to work:
- even if I myself am not normally using particular metadata fields (so I don't want them in the editor) I might still want to see what somebody else put in there or if the field contains rubbish. However at the moment I cannot select them in the info module if I don't have it in the metadata module.
- when a metadata field _is_ visible in the metadata module, I can chose to hide it in the info module (which makes sense; I can already see it on the right side after all). However it will reappear as soon as I mouseover a different image.

**Comment by dterrahe** [comment]
BTW nice PR. The next thing people are going to ask for is to be able to reorder the image information and to be able to store different field selections (as presets). :-)

File: src/libs/metadata_view.c [hunk 6]
```diff
@@ -791,6 +807,115 @@ void connect_key_accels(dt_lib_module_t *self)
...
+
+  GtkWidget *win = dt_ui_main_window(darktable.gui->ui);
+  GtkWidget *dialog = gtk_dialog_new_with_buttons(_("metadata settings"), GTK_WINDOW(win), GTK_DIALOG_DESTROY_WITH_PARENT,
+                                       _("cancel"), GTK_RESPONSE_NONE, _("save"), GTK_RESPONSE_YES, NULL);
+  GtkWidget *area = gtk_dialog_get_content_area(GTK_DIALOG(dialog));
+
+  GtkWidget *w = gtk_scrolled_window_new(NULL, NULL);
+  gtk_widget_set_size_request(w, -1, DT_PIXEL_APPLY_DPI(300));
+  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(w), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
+  gtk_container_add(GTK_CONTAINER(area), w);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:842]: `gtk_box_pack_start(GTK_BOX(area), w, TRUE, TRUE, 0);`

File: src/libs/metadata_view.c [hunk 7]
```diff
@@ -791,6 +807,115 @@ void connect_key_accels(dt_lib_module_t *self)
...
+  g_free(pref);
+  GtkWidget *hidden[md_size];
+  gboolean hide[md_size];
+  for(int i = 0; i < md_size; i++)
+  {
+    label = gtk_label_new(_md_labels[i]);
+    gtk_widget_set_halign(label, GTK_ALIGN_START);
+    gtk_label_set_xalign (GTK_LABEL(label), 0.0f);
+    gtk_label_set_ellipsize(GTK_LABEL(label), PANGO_ELLIPSIZE_END);
+    gtk_grid_attach(GTK_GRID(grid), label, 0, i+1, 1, 1);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:864]: `gtk_widget_set_hexpand(label, TRUE);`

File: src/libs/metadata_view.c [hunk 8]
```diff
@@ -791,6 +807,115 @@ void connect_key_accels(dt_lib_module_t *self)
...
+        gtk_widget_show_all(label);
+        gtk_widget_set_no_show_all(label, TRUE);
+        gtk_widget_set_visible(label, FALSE);
+        gtk_widget_show_all(hidden[i]);
+        gtk_widget_set_no_show_all(hidden[i], TRUE);
+        gtk_widget_set_visible(hidden[i], FALSE);
+      }
+    }
+  }
+  gtk_window_set_resizable(GTK_WINDOW(dialog), FALSE);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:885]: With the gtk_box_pack_start and gtk_widget_set_hexpand changes above, the dialog can be safely resized. Which is useful to be able to read the title and longer field names without ellipsizing.

File: src/libs/metadata.c (hunk 1 above)
Comment (phweyland) [reply src/libs/metadata.c:729]: Yes!

File: src/libs/metadata_view.c (hunk 2 above)
Comment (phweyland) [reply src/libs/metadata_view.c:106]: I' think I've already experienced the issue you talk about. But as the screenshots show the translation in French is done. I'm a bit lost here ...

Comment (dterrahe) [reply src/libs/metadata_view.c:106]: Ah, but that's because the translations haven't been updated yet. But when this gets merged and the new list of translatable strings gets generated, all the existing translations for these strings will get purged, because it will look like they are no longer needed.

Translations are tricky :-)

File: src/libs/metadata_view.c (hunk 3 above)
Comment (phweyland) [reply src/libs/metadata_view.c:860]: Yes for the first. Already there for the second.
Removed what is already in dt_ui_label_new.

Comment (dterrahe) [reply src/libs/metadata_view.c:860]: I meant you could probably add gtk_label_set_xalign to dt_ui_label_new, because generally halign and xalign go hand in hand. But you can also leave it here.

File: src/libs/metadata_view.c (hunk 5 above)
Comment (phweyland) [reply src/libs/metadata_view.c:871]: >     * I might still want to see what somebody else put in there or if the field contains rubbish. However at the moment I cannot select them in the info module if I don't have it in the metadata module.

I've made that on purpose, but I understand your point. I'll remove the precedence.

>     * when a metadata field _is_ visible in the metadata module, I can chose to hide it in the info module (which makes sense; I can already see it on the right side after all). However it will reappear as soon as I mouseover a different image.

Good catch. I'll fix that.

> If you moved `gtk_widget_show_all(dialog);`

I've been lasy here and copied the piece of code you gave me for metadata. I'd already tried to to put that on the grid but it did not work. Am I wrong on this ? Is there any reason ? In such case I'll do it also in metadata.

File: src/libs/metadata_view.c (hunk 8 above)
Comment (phweyland) [reply src/libs/metadata_view.c:885]: I wanted to do that, but haven't take the time to find out how. I'll do it.

**Comment by AlicVB** [comment]
Great work, that was on my todo (always great to see it decreasing without work !) !
Just some points I would have done differently (not to criticize, but just for information, in case you can include some ideas here) :
1. As @dterrahe said, for metadata view specific case, I would have used the presets using the `manage_presets` function (see in `modulegroups.c` for example) That would the benefit to save different presets, to propose different layout too...
2. For lot of other cases, I'm not sure that using an external window is worth the pain (most module prefs will consist in 1 or 2 checkbox) : What if `set_preference` fct directly return the menuitem to be added. That way, for simple prefs, you can return a menuitem which contain submenuitems with checkbox (or other things)

**Comment by Nilvus** [comment]
Thanks for that proposal. Du to some personal event, I will have really few time these days, so I will see and test that later. It's seems great. As soon I can test that, I will put here my feedback and on #7050. We will need to be sure the good way to set preferences and that is ok for most of us.

File: src/libs/metadata_view.c (hunk 2 above)
Comment (phweyland) [reply src/libs/metadata_view.c:106]: So, I should use _label[i] = N_() to set the untranslated strings, and then _md_label[i] = get_text(_label[i]) to get the translated one. Is that correct ?

Comment (dterrahe) [reply src/libs/metadata_view.c:106]: `_labels[md_internal_filmroll] = N_("filmroll");`

you can use 
`_md_label[i] = _(_label[i]);` 
instead of 
`_md_label[i] = gettext(_label[i]);` 
it is the same.

File: src/libs/metadata_view.c (hunk 5 above)
Comment (phweyland) [reply src/libs/metadata_view.c:871]: Precedence removed and reported issue solved.

File: src/libs/metadata_view.c (hunk 8 above)
Comment (phweyland) [reply src/libs/metadata_view.c:885]: Works indeed !

File: src/libs/metadata_view.c (hunk 3 above)
Comment (phweyland) [reply src/libs/metadata_view.c:860]: > you could probably add gtk_label_set_xalign to dt_ui_label_new

done. I hope that won't create issue elsewhere...

File: src/libs/metadata_view.c (hunk 4 above)
Comment (phweyland) [reply src/libs/metadata_view.c:822]: Yes, you're right.

**Comment by phweyland** [comment]
I've udpated as suggested by @dterrahe. Great review ! Thanks.

> The next thing people are going to ask for is ~~to be able to reorder the image information and~~ to be able to store different field selections (as presets). 

> I would have used the presets using the manage_presets function 

I'll try to understand this and give a try. For metadata_view, where there are a lot of selections, that makes sense indeed. But for the others ?... 
Not sure, but doing so, don't we add (not desired) dependencies on module version and params update ?

> For lot of other cases, I'm not sure that using an external window is worth the pain (most module prefs will consist in 1 or 2 checkbox) : What if set_preference fct directly return the menuitem to be added.

Great idea. I'll look at it.

Related to that we could add a preference button on plugin headline (beside reset and presets) instead of invading the presets menu. Any pros or cons ? Maybe not compatible with the idea of including the prefs into presets however...

**Comment by AlicVB** [comment]
> I'll try to understand this and give a try.

Not really hard : you add the fct to the module and what you want inside. If this fct is present in a module, it add a "manage presets" items at the bottom of the preset menu...
The part which is a little more complex is that you have to define how presets are stored in the database. The simplest is to use strings. Here, I think something like : "info1|info2|..." should be good...
If you want some help, just ask ;)

> For metadata_view, where there are a lot of selections, that makes sense indeed. But for the others ?...

Yes, this won't be good for most of the other modules. That's why I think your work here is really needed !



> Related to that we could add a preference button on plugin headline (beside reset and presets) instead of invading the presets menu. Any pros or cons ?

imho there's already lot of things inside module headers, so I would prefer the prefs at the bottom of the preset menu (but I may be alone)

**Comment by dterrahe** [comment]
> > Related to that we could add a preference button on plugin headline (beside reset and presets) instead of invading the presets menu. Any pros or cons ?
> 
> imho there's already lot of things inside module headers, so I would prefer the prefs at the bottom of the preset menu (but I may be alone)

Agreed. Let's not add a button that is _always_ taking up prime space and that the user might only use once.

**Comment by phweyland** [comment]
> The part which is a little more complex is

... I've looked at the code of "manage presets" and also in `modulegroups.c`. I've started to copy & paste something like 1500 lines of code to get the preset manager (display the list, add, modify, delete, ...). 
But unlike the module groups which is a critical function, I don't think that metadata_view deserves this duplication, unless we could factorize the "preset manager" code in some way. This said, the feature makes sense and the current solution doesn't prevent this upgrade. Maybe another PR...

Now I'm looking at your second suggestion...

**Comment by TurboGit** [comment]
Agreed, really nice !

**Comment by TurboGit** [comment]
Is the setup saved as preset? It would be nice to let user create multiple preset for the "image information" view for example.

File: src/libs/metadata_view.c [hunk 9]
```diff
@@ -791,6 +798,112 @@ void connect_key_accels(dt_lib_module_t *self)
...
+    _update_layout(self);
+  }
+  g_list_free_full(prefs, g_free);
+  gtk_widget_destroy(dialog);
+}
+
+void set_preferences(void *menu, dt_lib_module_t *self)
+{
+  GtkWidget *mi = gtk_menu_item_new_with_label(_("preferences..."));
+  g_signal_connect(G_OBJECT(mi), "activate", G_CALLBACK(_menuitem_preferences), self);
```
Comment (phweyland) [inline src/libs/metadata_view.c:903]: The value of self received in _menuitem_preferences doesn't match the sent value ...

**Comment by phweyland** [comment]
>     What if `set_preference` fct directly return the menuitem to be added.

Should be straight forward. It works for metadata editor where the module ref is not necessary.
But nor for metadata_view.  I'm stuck with the pb above line 903. 
Could somebody help me to open the right eye ?

**Comment by phweyland** [comment]
> Is the setup saved as preset? It would be nice to let user create multiple preset for the "image information" view for example.

Not yet. As commented above, "preset manager" is something like 1500 lines to be duplicated from modulegroups.c. Should be better to set "preset manager" as a service somehow first ... What do you think ?

**Comment by TurboGit** [comment]
> Not yet. As commented above, "preset manager" is something like 1500 lines to be duplicated from modulegroups.c. Should be better to set "preset manager" as a service somehow first ... What do you think ?

Why not but you seem to have a more sofisticated proposal in mind. I'm just thinking to record into the preset (for module information) the list of selected entry to display. I'm just thinking of enabling the _hamburger button_ in "image information" module.

**Comment by phweyland** [comment]
>  I'm just thinking of enabling the _hamburger button_ in "image information" module.

OK, this one should be simpler. Let me check.

File: src/libs/metadata_view.c (hunk 9 above)
Comment (AlicVB) [reply src/libs/metadata_view.c:903]: this is because you don't have the right args in _menuitem_preferences I don't recall the exact signature of the activate callback for menuitems, but first arg is always the widget... (I've faced same problem in modulegroups because I've forgot the event at the second place :))

Comment (phweyland) [reply src/libs/metadata_view.c:903]: Thanks ! my _menuitem_preferences is incorrect indeed !

**Comment by phweyland** [comment]
This is now a working version with set_preference setting up the needed menu items. In case of metadata (and metadata_view for the time being) that's just an entry for the popup, but could be any number of menu items...

Now I'll look at the hamburger button.

**Comment by phweyland** [comment]
I've made progress to drag & drop metadata order in the preferences window.

Now I've to apply the order to the plugin. 
It seems that grid is not very useful to manage order, unless removing all records and adding all fields again.
I'm starting to try to move from grid to a listview. I may have some difficulty to translate some functions: field layout, click on folder line, ... I'll see.

If anyone has some advice or good idea to make a displayed list respond to order changes, he/she is very welcome.

**Comment by phweyland** [comment]
image

**Comment by phweyland** [comment]
grid changed for a sortable treeview.
Remain some tooltips to implement and reparation of lua access.
Hoping we can replace the widget reference by metadata index (like md_internal_filmroll for example).
If I cannot solve this I'll ask for some help from @wpferguson.

image

**Comment by phweyland** [comment]
> Hoping we can replace the widget reference by metadata index (like md_internal_filmroll for example).

I've had a better look to the lua code (which is difficult to follow for me) and it is fully based on the usage of grid + embedded widgets. 
I'm afraid I'll have to revert the sorting stuff... :( unless @wpferguson had a brillant idea ...

**Comment by wpferguson** [comment]
I'll look at it and see what I can figure out

**Comment by wpferguson** [comment]
I took a quick look.  Right now, AFAIK, there is nothing using those functions.  I'll have to code up something that uses them then see how it breaks with the new stuff.  By the way, I love the new stuff.  I really wanted those timestamps gone :).

**Comment by phweyland** [comment]
Thanks for looking at this @wpferguson. 
For metadata_view there are basically 2 new features. The selection (the one you may like) and the ordering.
Only the implementation of the second one breaks the lua interface.
So if we cannot decide/find a solution for lua, we still have the option to keep the selection and revert the ordering.

**Comment by wpferguson** [comment]
@phweyland I wrote a quick script and tested against current git before trying your PR.  It seems that it was already broken.  When the grid got wrapped in the scrolled window, the lua code didn't get updated.  I fixed that by taking the child of the child and passing that to GTK_GRID so not it works in current git. @TurboGit do you want a PR for this or do we let it slide until 3.4.1.  No one has complained about it, so it looks like it's not used much.  Your call.

**Comment by wpferguson** [comment]
@phweyland I played some, but I didn't have enough brain cells left to figure out trees.  Here's what I think needs done..

```
    GtkLabel *name = GTK_LABEL(gtk_label_new(key));  // format these the same as your other labels
    GtkLabel *value = GTK_LABEL(gtk_label_new("-"));   // same for values
    gtk_widget_set_name(GTK_WIDGET(value), "brightbg");  // add to the fixme list :)
    gtk_label_set_selectable(value, TRUE);  // same with the following, set them up the same way you set up the other labels and values
    gtk_widget_set_halign(GTK_WIDGET(name), GTK_ALIGN_START);
    gtk_widget_set_halign(GTK_WIDGET(value), GTK_ALIGN_FILL);
    gtk_label_set_xalign (value, 0.0f);
    GList *tree; // In order to get the tree I had to take the child of the scrolled window
    tree = gtk_container_get_children(GTK_CONTAINER(self->widget));
    gtk_grid_attach_next_to(GTK_GRID(tree->data), GTK_WIDGET(name), NULL, GTK_POS_BOTTOM, 1, 1);  // can you just add this to the store?
    gtk_grid_attach_next_to(GTK_GRID(tree->data), GTK_WIDGET(value), GTK_WIDGET(name), GTK_POS_RIGHT, 1, 1); // same
    gtk_widget_show_all(tree->data);  // just a redraw
    { // this can stay the same
      lua_getfield(L,-1,"widgets");
      lua_pushstring(L,key);
      lua_pushlightuserdata(L,value);
      lua_settable(L,5);
      lua_pop(L,1);
    }
    g_free(tree);

```

Here's a quick script to test with

```
local dt = require "darktable"

local function say(image)
  return "something"
end

dt.gui.libs.metadata_view.register_info(
  "crap", 
  say
)
```

**Comment by phweyland** [comment]
Not sure to understand this.Your suggested code should work with the current master. Is that correct ? 

On the other hand, with the current PR, the gtk_grid doesn't exist anymore and the gtk_label(s) are not used neither.
Instead of a grid of widgets, there is a gtk_liststore (of data). Currently it is not possible to connect any interface because the plugin uses also data from outside of this gtk_liststore. But I can fix that and make sure everything works on top of the gtk_liststore only. Then we can think about an interface able to add some rows at the bottom of this gtk_liststore.
This gkt_liststore helds these info: name, value, visibility and display order. Name, visibility and display order are saved in darktablerc and possibly in presets.
Would that make sense ?

**Comment by phweyland** [comment]
Now the gtk_liststore holds all the necessary information (no static data anymore).
Normally, rows can be added to it. However, visibility and order can be changed only for the native data.
Assuming lua interface works, added information will be displayed at the end of the list and will remain visible. I think this could be improved, but at least that would ensure the backward compatibility.

**Comment by phweyland** [comment]
@wpferguson , not to far now thanks to test script and the code entry point your gave me :
image

I've just difficulty to get back the index (I get whatever value) when update.

My code is now,
for lua_register:

```
    GtkTreeIter iter;
    dt_lib_metadata_view_t *d = (dt_lib_metadata_view_t *)self->data;
    gtk_list_store_append(GTK_LIST_STORE(d->model), &iter);
    GtkTreePath *path = gtk_tree_model_get_path(d->model, &iter);
    // get the row index
    gint *i = gtk_tree_path_get_indices(path);
    gtk_tree_path_free(path);
    gtk_list_store_set(GTK_LIST_STORE(d->model), &iter,
                       DT_METADATA_COL_NAME, key,
                       DT_METADATA_COL_NAME_L, key,
                       DT_METADATA_COL_VALUE, "-",
                       DT_METADATA_COL_VISIBLE, TRUE,
                       DT_METADATA_COL_ORDER, i[0],
                       -1);
    {
      lua_getfield(L,-1,"indexes");
      lua_pushstring(L,key);
      lua_pushinteger(L,i[0]);
      lua_settable(L,5);
      lua_pop(L,1);
    }
```

and for lua_update:

```
   while(lua_next(L, 4) != 0)
  {
     lua_getfield(L,5,lua_tostring(L,-2));
     int index = lua_tointeger(L,-1);
     _metadata_update_value(index,luaL_checkstring(L,7), d->model);
     lua_pop(L,2);
  }
```

But in lua_update the index is (really :)) crap.

I've changed lua_pushlightuserdata to lua_pushinteger, and lua_touserdata to lua_tointeger
but I miss certainly something ...

**Comment by wpferguson** [comment]
> Not sure to understand this.

Told you I was out of brain cells :)

I've had a good night's sleep now so I'll pull the latest from your branch and start playing with it

**Comment by wpferguson** [comment]
@phweyland can you commit your latest so that I can pull it and play?  Thanks

**Comment by phweyland** [comment]
> can you commit your latest so that I can pull it and play? Thanks

sure

**Comment by wpferguson** [comment]
checked the value that was getting pushed on the stack and it wasn't what i[0] originally was.  I was getting 38, for the original value,  but when I checked what was getting pushed it was something like -1052938547, so I saved the value returned from gtk_tree_path_get_indices(path) as a const gint and used that.  It appears to fix the "random" index.  
 ```
 gint *i = gtk_tree_path_get_indices(path);
    const gint index = i[0];
    fprintf(stderr, "index is %d\n", index);
    printf("lua_register_info %s %d\n", key, index);
    gtk_tree_path_free(path);
    gtk_list_store_set(GTK_LIST_STORE(d->model), &iter,
                       DT_METADATA_COL_NAME, key,
                       DT_METADATA_COL_NAME_L, key,
                       DT_METADATA_COL_VALUE, "-",
                       DT_METADATA_COL_VISIBLE, TRUE,
                       DT_METADATA_COL_ORDER, index,
                       -1);
    {
      lua_getfield(L,-1,"indexes");
      lua_pushstring(L,key);
      lua_pushinteger(L,index);
      fprintf(stderr, "pushed index %d on the stack\n", index);
      lua_settable(L,5);
      lua_pop(L,1);
    }
  }

```

**Comment by phweyland** [comment]
Brilliant ! I was reading the lua doc to get an idea about how the stack works, but I was very far from finding that!
Thanks so much @wpferguson

**Comment by phweyland** [comment]
A question, maybe not the last. In the liststore there is room for the translated name (to be displayed) ?
Do we care with lua ?
If yes, how do I get it ?

**Comment by wpferguson** [comment]
The translation should take place in the script and translated string passed to lua_register_info

**Comment by phweyland** [comment]
> The translation should take place in the script and translated string passed to lua_register_info

OK, thanks! So that's ok for the time being.

**Comment by phweyland** [comment]
Tooltip works again now.

For me that works. The behavior of the 2 columns is not exactly the same as with grid. I've tried a lot of things without success. I've left some `FIXME` inside the code to mark what I've failed to solved, but nothing serious I hope.

**Comment by wpferguson** [comment]
Now that the lua script can insert a field, is there anything keeping it from being treated like the rest of the items in the store, such as selecting it and reordering it?

**Comment by phweyland** [comment]
> Now that the lua script can insert a field, is there anything keeping it from being treated like the rest of the items in the store, such as selecting it and reordering it?

In theory, not. The main concerned is to treat properly the discrepancies between the preferences (presets as well) and the presence or absence of the lua metadata. Then if you start dt without the lua script, the corresponding preferences are lost.

I've understood that was not (yet) widely used.
Do you see any strong use case for that ?

**Comment by wpferguson** [comment]
I couldn't find any instance of it being used, so I had to figure it out for myself from the API manual.  If it is being used it's in somebody's private script.  The question was more of a is it possible, and what would we need to do to make it happen if we wanted to from the lua side.  I thought we would need some way to manipulate the index, but that was about it.

I'm fine with the state you currently have it in.  If someone starts using the function and raises an issue we can always address it then.

"If it's not broke, don't fix it"

I'm fine with the state it's currently in

**Comment by phweyland** [comment]
>  I thought we would need some way to manipulate the index, but that was about it.

Index manipulation is coded, but limited to the size of static data. It is easy to remove this limit to consider the new rows (added by lua).
It's also easy to remove the limit on preferences read/write. 
As said before, what is not coded is what to do when the content of preferences (or preset) record does not match with the current content of the liststore. But should not be so difficult.

>  If someone starts using the function and raises an issue we can always address it then.

:+1: 

As a possible use case: to display the different variables and/or combination of variables.

**Comment by phweyland** [comment]
added gui_reset + prefs for lua info.

image

**Comment by wpferguson** [comment]
Nice!

File: src/libs/metadata_view.c [hunk 10]
```diff
@@ -927,30 +1325,39 @@ static int lua_register_info(lua_State *L)
...
     {
-      lua_getfield(L,-1,"widgets");
+      lua_getfield(L,-1,"indexes");
       lua_pushstring(L,key);
-      lua_pushlightuserdata(L,value);
+      lua_pushinteger(L,index);
       lua_settable(L,5);
       lua_pop(L,1);
     }
+    // apply again preferences because it's already done
```
Comment (phweyland) [inline src/libs/metadata_view.c:1351]: @wpferguson
Here preferences are called from lua_register_info(). I would fine more correct to call lua_register_info() from gui_init() at the right time (after or at the end of _lib_metadata_view_init_labels()).
Would that be correct ?
Should have to remove:

  lua_pushlightuserdata(L, self);
  lua_pushcclosure(L, lua_register_info,1);

from init() ?

Comment (wpferguson) [reply src/libs/metadata_view.c:1351]: I'll look at it and see...

Comment (wpferguson) [reply src/libs/metadata_view.c:1351]: lua_register_info() is a callback that runs when called from a script.  The scripts run long after gui_init() is done.  While I see the logic, I don't think it will work.  You could always try it and see what happens :smiley:

Comment (phweyland) [reply src/libs/metadata_view.c:1351]: >  While I see the logic, I don't think it will work

Thanks a lot for the advice ! :smiley:

**Comment by Nilvus** [comment]
I will not have time to test that and so related #7050 until some days. This month is more busy than expected. So, I hope this could wait a little more before being merged as it is quite a lot related to #7050.

**Comment by TurboGit** [comment]
@Nilvus : This can wait a bit, no problem.

**Comment by Nilvus** [comment]
> added gui_reset + prefs for lua info.
> 
> image

I began to test that PR and it's really good. Simple and efficient, I like that. What you show there is the good way to display this type of preferences for me. So, it would be good to display them the same way for metadata preferences. Actually, those last preferences are like your screenshot in initial post of this PR.

I will test ASAP more that PR. Thanks for the good work here!

**Comment by phweyland** [comment]
Solved conflicts

**Comment by phweyland** [comment]
Opening the metadata_view preferences window I get this:

image

Is there a way to avoid the vertical scrollbar eats the content ?

File: src/libs/metadata_view.c [hunk 11]
```diff
@@ -791,46 +910,306 @@ void connect_key_accels(dt_lib_module_t *self)
...
+      g_free(name);
+      valid = gtk_tree_model_iter_next(d->sort_model, &sort_iter);
     }
+  }
+
+  GtkWidget *view = gtk_tree_view_new_with_model(model);
+  g_object_unref(model);
+  GtkCellRenderer *renderer = gtk_cell_renderer_text_new();
+  GtkTreeViewColumn *column = gtk_tree_view_column_new_with_attributes(_("metadata"), renderer,
+                                                    "text", DT_METADATA_PREF_COL_NAME_L, NULL);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:1062]:
```
  g_object_set(renderer, "ellipsize", PANGO_ELLIPSIZE_END, NULL);
  gtk_tree_view_column_set_expand(column, TRUE);
```

File: src/libs/metadata_view.c [hunk 12]
```diff
@@ -791,46 +910,306 @@ void connect_key_accels(dt_lib_module_t *self)
...
+
+  // metadata column
+  GtkCellRenderer *renderer = gtk_cell_renderer_text_new();
+  g_object_set(renderer, "xalign", 0.0,
+  // FIXME                         "ellipsize", PANGO_ELLIPSIZE_END,
+                         NULL);
+  // FIXME
+  //  gtk_widget_set_halign(label, GTK_ALIGN_FILL); // make it span the whole available width
+  GtkTreeViewColumn *column = gtk_tree_view_column_new_with_attributes(_("name"), renderer,
+                                        "text", DT_METADATA_COL_NAME_L, NULL);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:1185]:
```
  g_object_set(renderer, "ellipsize", PANGO_ELLIPSIZE_END, NULL);
  gtk_tree_view_column_set_expand(column, TRUE);
```

File: src/libs/metadata_view.c [hunk 13]
```diff
@@ -791,46 +910,306 @@ void connect_key_accels(dt_lib_module_t *self)
...
+                                           DT_METADATA_COL_VISIBLE);
+
+  GtkWidget *view = gtk_tree_view_new_with_model(GTK_TREE_MODEL(filter_model));
+  d->view = view;
+  gtk_tree_view_set_headers_visible(GTK_TREE_VIEW(view), FALSE);
+  g_object_unref(filter_model);
+
+  // metadata column
+  GtkCellRenderer *renderer = gtk_cell_renderer_text_new();
+  g_object_set(renderer, "xalign", 0.0,
```
Comment (dterrahe) [inline src/libs/metadata_view.c:1179]: Not needed

File: src/libs/metadata_view.c [hunk 14]
```diff
@@ -791,46 +910,306 @@ void connect_key_accels(dt_lib_module_t *self)
...
+  // value column
+  renderer = gtk_cell_renderer_text_new();
+  g_object_set(renderer, "xalign", 0.0,
+                         "ellipsize", PANGO_ELLIPSIZE_MIDDLE,
+                         NULL);
+  // FIXME
+  //  gtk_widget_set_name(GTK_WIDGET(d->metadata[k]), "brightbg");
+  //  gtk_widget_set_halign(GTK_WIDGET(d->metadata[k]), GTK_ALIGN_FILL);
+  column = gtk_tree_view_column_new_with_attributes(_("value"), renderer,
+                                        "text", DT_METADATA_COL_VALUE, NULL);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:1197]: `   gtk_tree_view_column_set_expand(column, TRUE);`

File: src/libs/metadata_view.c [hunk 15]
```diff
@@ -791,46 +910,306 @@ void connect_key_accels(dt_lib_module_t *self)
...
+  //  gtk_widget_set_halign(label, GTK_ALIGN_FILL); // make it span the whole available width
+  GtkTreeViewColumn *column = gtk_tree_view_column_new_with_attributes(_("name"), renderer,
+                                        "text", DT_METADATA_COL_NAME_L, NULL);
+  gtk_tree_view_append_column(GTK_TREE_VIEW(view), column);
+
+  // value column
+  renderer = gtk_cell_renderer_text_new();
+  g_object_set(renderer, "xalign", 0.0,
+                         "ellipsize", PANGO_ELLIPSIZE_MIDDLE,
+                         NULL);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:1192]: This used to have
```
k == md_exif_model || k == md_exif_lens || k == md_exif_maker	
? PANGO_ELLIPSIZE_END 
: PANGO_ELLIPSIZE_MIDDLE
```
as I think for those fields middle ellipsizing doesn't work very well, but I wouldn't immediately know how to apply row specific formatting in a tree view.

**Review by dterrahe — COMMENTED** [review]
> Is there a way to avoid the vertical scrollbar eats the content ?

I've added some suggestions.

**Comment by dterrahe** [comment]
The tooltip used to be column specific, so you could read the whole name of the metadata field name ("change timestamp") by hovering, even when it got ellipsized. That's no longer the case.

**Comment by phweyland** [comment]
@dterrahe , Thanks for your comments. I'll look at all this.

File: src/libs/metadata_view.c (hunk 11 above)
Comment (phweyland) [reply src/libs/metadata_view.c:1062]: Great. This works.
I had already try gtk_tree_view_column_set_expand() alone but this did not work.

File: src/libs/metadata_view.c (hunk 12 above)
Comment (phweyland) [reply src/libs/metadata_view.c:1185]: Done.
Remains that the first column used to be narrower than the second one. Now the columns are kept equal.

File: src/libs/metadata_view.c (hunk 15 above)
Comment (phweyland) [reply src/libs/metadata_view.c:1192]: Good reminder. Done.

File: src/libs/metadata_view.c (hunk 13 above)
Comment (phweyland) [reply src/libs/metadata_view.c:1179]: OK. done

**Comment by phweyland** [comment]
> The tooltip used to be column specific, so you could read the whole name of the metadata field name ("change timestamp") by hovering, even when it got ellipsized. That's no longer the case.

This one and all your other comments are treated.
Thanks for the review.

**Comment by dterrahe** [comment]
All looking good, thanks, except I no longer have an active presets button, so can't go into the configuration options...

**Comment by dterrahe** [comment]
Unfortunately because you've force-pushed everything into one commit, I can't tell which one of your latest changes might have caused the problem.

**Comment by phweyland** [comment]
> I no longer have an active presets button

Well, no change on this area ...
image

**Comment by phweyland** [comment]
> Unfortunately because you've force-pushed everything into one commit, I can't tell which one of your latest changes might have caused the problem.

image

When I click on `force-pushed ` I get the specific changes of the push. Do you this link too ?

**Comment by dterrahe** [comment]
> When I click on `force-pushed ` I get the specific changes of the push. Do you have this link too ?

!!! I did not know that was a link and that it worked like that. Brilliant and thank you for showing me!

**Comment by dterrahe** [comment]
> > I no longer have an active presets button
> 
> Well, no change on this area ...
> image

Strange; I deleted my build and .config/darktable directories and still get this (inactive buttons):
image

**Comment by dterrahe** [comment]
All working now; sorry, I must have messed something up on my side. Started from a clean pull and now all is perfect!

**Comment by phweyland** [comment]
> All working now; sorry, I must have messed something up on my side. Started from a clean pull and now all is perfect!

Don't worry. Thanks again.

**Comment by phweyland** [comment]
Rebased to solve conflicts.

**Comment by Nilvus** [comment]
@phweyland: With your last push (ac24e48 commit), I can't compile your branch here. I have that compiled error:

```
[ 46%] Building C object bin/CMakeFiles/lib_darktable.dir/common/camera_control.c.o
/home/nilvus/Projets/dtph/src/libs/lib.c: In function ‘popup_callback’:
/home/nilvus/Projets/dtph/src/libs/lib.c:994:1: error: version control conflict marker in file
  994 | <<<<<<< HEAD
      | ^~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1733 : bin/CMakeFiles/lib_darktable.dir/libs/lib.c.o] Erreur 1
gmake[2]: *** Attente des tâches non terminées....
gmake[2] : on quitte le répertoire « /home/nilvus/Projets/dtph/build »
gmake[1]: *** [CMakeFiles/Makefile2:2302 : bin/CMakeFiles/lib_darktable.dir/all] Erreur 2
gmake[1] : on quitte le répertoire « /home/nilvus/Projets/dtph/build »
gmake: *** [Makefile:152 : all] Erreur 2
```

And quite strange, I made a second try (by being sure to remove build and destination install folders), and now, the compile error is a little bit different:

```
[ 45%] Building C object bin/CMakeFiles/lib_darktable.dir/common/pwstorage/backend_libsecret.c.o
/home/nilvus/Projets/dtph/src/libs/lib.c: In function ‘popup_callback’:
/home/nilvus/Projets/dtph/src/libs/lib.c:994:1: error: version control conflict marker in file
  994 | <<<<<<< HEAD
      | ^~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1733 : bin/CMakeFiles/lib_darktable.dir/libs/lib.c.o] Erreur 1
gmake[2]: *** Attente des tâches non terminées....
gmake[2] : on quitte le répertoire « /home/nilvus/Projets/dtph/build »
gmake[1]: *** [CMakeFiles/Makefile2:2302 : bin/CMakeFiles/lib_darktable.dir/all] Erreur 2
gmake[1] : on quitte le répertoire « /home/nilvus/Projets/dtph/build »
gmake: *** [Makefile:152 : all] Erreur 2

```

**Comment by phweyland** [comment]
If I look at the code for commit  ac24e48 in libs/lib.c, there is not this line:

 
image

More strange. @turbogit had also this line in #7523 : https://github.com/darktable-org/darktable/pull/7523#discussion_r550426142.
I've checked on my repository and I have not this line neither...

**Comment by Nilvus** [comment]
> More strange. @TurboGit had also this line in #7523 : [#7523 (comment)](https://github.com/darktable-org/darktable/pull/7523#discussion_r550426142).
> I've checked on my repository and I have not this line neither...

It seems I've had some strange update issues on my local folder of your github. Even a clean build with a clean pull doesn't solve that but downloading again your repository in a fresh folder, fix that build error.

**Comment by Nilvus** [comment]
@phweyland: on that PR, 2 things to improve in preferences.

- On image infos preferences, just increase a little window width to better show all text (at least in english). I would add 10 to 20% more
- On metadata editor preferences, could you change the way options are shown and change the view to be the same as in image infos modules? So use a treeview instead of a grid. I know it's some work but those preferences are quite near and that would be more consistent and UI is better in image infos preferences than in metadata editor ones.

**Comment by phweyland** [comment]
>     * On image infos preferences, just increase a little window width to better show all text (at least in english). I would add 10 to 20% more

This should this be done through css, right ? padding or margin on columns ?

>     * So use a treeview instead of a grid.

I can do that. Would I take his opportunity to show "visible" instead of "hidden" to be consistent with metadata info ?

**Comment by Nilvus** [comment]
> > ```
> > * On image infos preferences, just increase a little window width to better show all text (at least in english). I would add 10 to 20% more
> > ```
> 
> This should this be done through css, right ? padding or margin on columns ?

What was I thinking? Of course, I can do that myself that way. Forget that one, I've already began some CSS improvements so I will add that to my to-do list!

> > * So use a treeview instead of a grid.
> > ```
> 
> I can do that. Would I take his opportunity to show "visible" instead of "hidden" to be consistent with metadata info ?

Yes, it would be more consistent too.

**Comment by phweyland** [comment]
Metadata info. Workaround for vertical scrollbar not to eat view content (without ellipsizing)
image  

Same layout for metadata editor (hidden -> visible)
image

Export, remove config button and move to preferences in presets menu. No change for presets as these data are already in there.
image

**Comment by phweyland** [comment]
Le commit 0292177 seems very strange ...
image

I've squashed all this. If there is mistake somewhere it will hopefully go ...

**Comment by phweyland** [comment]
@Turbogit, if @Nilvus is OK with the changes above, this PR is ready for your review.

File: src/libs/metadata_view.c [hunk 16]
```diff
@@ -791,46 +921,319 @@ void connect_key_accels(dt_lib_module_t *self)
...
+  // drag & drop
+  gtk_tree_view_set_reorderable(GTK_TREE_VIEW(view), TRUE);
+  g_signal_connect(G_OBJECT(model), "row-inserted", G_CALLBACK(_drag_data_inserted), NULL);
+
+  // workaround to avoid verticall scrollbar to cover view content
+  GtkWidget *grid = gtk_grid_new();
+  gtk_grid_attach(GTK_GRID(grid), view, 0, 0, 1, 1);
+  GtkWidget *scroll = gtk_label_new("  ");
+  gtk_grid_attach(GTK_GRID(grid), scroll, 1, 0, 1, 1);
+  gtk_container_add(GTK_CONTAINER(w), grid);
```
Comment (dterrahe) [inline src/libs/metadata_view.c:1091]: This isn't pretty and when you increase the size of the window vertically, the first column no longer expands if you also increase the horizontal size. I know it doesn't need to, because it has allocated enough space, but it is still somewhat ugly and not standard behavior.

I would suggest above using 
```
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(w), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_overlay_scrolling(GTK_SCROLLED_WINDOW(w), FALSE);
```
and here simply
`  gtk_container_add(GTK_CONTAINER(w), view);
`
It is not _perfect_, because the scrollbar stays, even if it isn't needed. But most of the time it is needed anyway...

Comment (phweyland) [reply src/libs/metadata_view.c]: That's better indeed. I take it!
Thanks for your help (as usual :smiley: )

**Comment by TurboGit** [comment]
@phweyland : I'll wait for final ok from @Nilvus. I haven't tested this yet myself.

**Comment by Nilvus** [comment]
It's all ok for me. Thanks for that great work @phweyland

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!

**Comment by TurboGit** [comment]
One thing I found but could be reworked in another PR as not related directly to this. The spaces between each line in the image information lib is now bigger and so takes more places. The spaces is not the same as for other libs, I suppose we had a specific CSS rule for the image information ? But not working now that the widget has changed name/layout ? @Nilvus maybe an idea ? I'll try to look at this tomorrow.

**Comment by TurboGit** [comment]
Ok, after restarting I see that the preference of what is displayed is not kept and always go back to the full list!

**Comment by TurboGit** [comment]
@phweyland : can you double check the lost of setting when restarting ? TIA.

**Comment by phweyland** [comment]
>  can you double check the lost of setting when restarting ? TIA.

I'll do.

**Comment by Nilvus** [comment]
I haven't seen that image infos was in treeview widget now. Bad idea, it was better before. About treeview, I have asked for preferences only in that module. Preferences are good and that what I check but I think image infos module could be done as it was before. @phweyland: why do you changed that?

**Comment by phweyland** [comment]
> why do you changed that?

You cannot manage order in a grid... ( at least it is not done for that )

**Comment by Nilvus** [comment]
> > why do you changed that?
> 
> You cannot manage order in a grid... ( at least it is not done for that )

Oh, ok, I didn't understood that we can change the order. Really great. But so, could you add a specific CSS tag (like "image-infos" in treeview of image infos module, to allow specific margin/padding in it? I will manage margin/padding after that. Thanks.

**Comment by phweyland** [comment]
>  But so, could you add a specific CSS tag (like "image-infos" in treeview of image infos module, to allow specific margin/padding in it?

Yes. I'll do it

**Comment by phweyland** [comment]
>  can you double check the lost of setting when restarting ?

I cannot reproduce this neither with an existing db not with a new one.
And presets work correctly too. 

> after restarting I see that the preference of what is displayed is not kept and always go back to the full list!

Can you find in darktablerc the record `plugins/lighttable/metadata_view/visible` with the ordered list of metadata ?

**Comment by TurboGit** [comment]
`plugins/lighttable/metadata_view/visible=pellicule,numéro,|numéro groupe,nom de fichier,|version,chemin complet,copie locale,date importation,date changement,date exportation,date impression,|états,modèle,fabricant,objectif,ouverture,exposition,biais d'exposition,focale,mise au point,ISO,date/heure,largeur,hauteur,largeur exporté,hauteur exporté,titre,|description,auteur,diffuseur,droits,|notes,|nom de version,latitude,longitude,élévation,|mots-clés,|catégories
`

Value are translated, maybe the issue ?

**Comment by TurboGit** [comment]
That's it, if I use dt in English no more issue.

**Comment by TurboGit** [comment]
@phweyland : I have fixed this, it was trivial.

**Comment by phweyland** [comment]
> I have fixed this

Thanks !

**Comment by phweyland** [comment]
Just to get your view. 
The widths of the 2 columns of image information are now equal. This wastes a bit of space for the second column.
I prefer the way it was before but I haven't succeeded in replicating it.
What I can do is to set the first column fixed and adjusted (without ellipsizing) and let the available space for the second column. The drawback is that it won't adapt itself anymore when the user resizes the left plugins column.
@dterrahe may have a better idea to improve that.

What do you think ?

**Comment by quovadit** [comment]
I love the preferences, but I agree that it wastes space (mostly the datetime is cropped):



If the first column is fixed and adjusted, maybe you could also shorten some titles (e.g. 'import timestamp') so that more space is available for the second column

**Comment by TurboGit** [comment]
> The widths of the 2 columns of image information are now equal. This wastes a bit of space for the second column.

Fully agree, we can certainly do something about this.

**Comment by TurboGit** [comment]
> If the first column is fixed and adjusted, maybe you could also shorten some titles

We don't have control on this, think about all the translations.

**Comment by dterrahe** [comment]
> What do you think ?

This is not easy.

Basically, there are seemingly arbitrary differences between how gtk widgets with similar functionality behave, so if you switch one widget (grid) for another (treeview) you get all the advantages and all the drawbacks of the differences.

Here, what you want is the proportional column spacing that grid does. There's no reason treeview could not have that built-in. And even if for some reason it was a good idea to not have it as the default, it could have been an option. Instead, you'd have to rebuild all the resizing functionality (calculating natural sizes of all the complete columns) just because at the last step you want to do something different.

I did this for notebook tabs, which suffers from the same issue. There it was possible and doesn't seem to impact performance much, but it was relatively simple because there's only one row. For TreeView...

For me, setting an absolute size on the first column is worse than what you have now, because it means if you reduce the width of the panel, at some point you won't see any actual data, making the module useless.

To be honest, I haven't tried to understand the rationale for the switch to a treeview, which seems to have made everything much more complex. I assumed it was necessary to support lua? For the reordering, just a row number lookup before putting data in the grid would have worked, I think. Grids don't show empty rows, so invisible items should not be a problem. And you'd simply refill the grid after a configuration change.

**Comment by phweyland** [comment]
I may have found a solution, see #7677.

> just a row number lookup before putting data in the grid would have worked, I think. Grids don't show empty rows, so invisible items should not be a problem. And you'd simply refill the grid after a configuration change.

I haven't tried. The "refill" discouraged me.

**Comment by quovadit** [comment]
@phweyland : your solution works perfectly for me :+1:

**Comment by dterrahe** [comment]
> I haven't tried. The "refill" discouraged me.

Why? You would have moved the _initialize the metadata name/value labels_ section that was previously in `gui_init `to `_mouse_over_image_callback ` and you'd have added two calls to `gtk_grid_remove_column` to start with a clean grid each time first. Obviously that meant more work for gtk at each update, but I assume that dealing with a sortable treeview with additional columns is more expensive too.

**Comment by phweyland** [comment]
> > I haven't tried. The "refill" discouraged me.
> 
> Why?

I have no good reason to give you. I was just more comfortable this way.

**Comment by phweyland** [comment]
I'll make a try to see if I can do it easily with a grid.

**Comment by phweyland** [comment]
The main advantage of the treeview is to be the central dynamic repository of all metadata and related information (name, translated name, value, index, order, visibility). Then all connected services can add, update, reorder with all things in hand.
The drawback is the display. Some jitter when resizing the plugins column and the height of the lines which is a bit bigger than with grid.

On the other hand the grid offers some advantages display wise but doesn't provide a good support for storing data (doesn't even provide the number of rows) and must be reset in case of reordering.
So to mimic the current behavior we need to build an ordered queue with the above information as main repository, connect the services on it, and rebuild the grid each time the order is changed.

Not really a big deal, but still some work :)
