### PR TITLE
ensure dt window icon is used on Plasma/Wayland

### LINKED ISSUE #19946: darktable windows have generic icon
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

darktable windows don't use the darktable icon in window manager's app switcher

### Steps to reproduce

1. Start darktable
2. Open desktop environments window switcher (via `alt`-`tab`)
3. Window switcher appears
4. Note that the darktable icon is a generic Wayland icon

### Expected behavior

darktable should use the darktable-specific icon

### Logfile | Screenshot | Screencast

Image

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

5.1.0+1989~gebb7ef77f3

### What OS are you using?

Linux

### What is the version of your OS?

Debian forky/sid

### Describe your system

KDE Plasma 6.5.4 on Wayland, GTK 2.24.33, 32GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA RTX 3080 laptop, 8GB, nvidia driver 550.163.01

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This looks to be a result of the switch to Wayland, and is KDE specific. See https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/ and https://honk.sigxcpu.org/con/GTK__and_the_application_id.html for background.

### PR DESCRIPTION
**Pull request by dtorop**
Setting the program name to match our desktop file allows for the icon to come from that file.

Fixes #19946.

Note that this fixes a Wayland/Plasma interaction under GTK 3. A different solution will be necessary for GTK 4 (see #19448), apparently via setting the desktop file basename via `gtk_application_new()`.

### CODE REVIEW

File: src/common/darktable.c [hunk 1]
```diff
@@ -1473,6 +1473,10 @@ int dt_init(int argc,
     g_free(new_xdg_data_dirs);
   }
 
+  // desktop entry name required for mapping application icon to
+  // window for KDE/Plasma on Wayland under GTK 3
```
Comment (TurboGit) [inline src/common/darktable.c:1477]: Why having KDE/Plasma mentioned here? Is that not needed on GNOME?

Comment (dtorop) [reply src/common/darktable.c:1477]: > Why having KDE/Plasma mentioned here? Is that not needed on GNOME?

Apparently Gnome doesn't require finding the application icon in the desktop file, so therefore doesn't need to know where the desktop file is to display the icon! KDE is either more pedantic, or lacks some other private protocol, so this PR matters for KDE (and shouldn't alter Gnome behavior).
