### PR TITLE
lighttable : speedup scrolling

### LINKED ISSUE #15421: lighttable sluggish when scrolling down/up
Since some time I have found that the lighttable is sluggish and mostly when many images are displayed in a single row.

To reproduce:
1. Select a collection with lot of images, say more that 500
2. Set the lighttable with 20 pcitures in a raw
3. Set display to top of collection, that is first image in the collection being displayed on top-left corner of lighttable
4. Do a single long/big scroll

See that there is some delay ~2 seconds on my computer before the lighttable refresh.

Note that the same sluggishness happens if one try to drag the scrollbar. 

We have been discussing this with @AlicVB and we found out that this is because the `_event_scroll()` routine is receiving lot of events (1 per row to move) and so that many call to `_move` is done.

I'm almost sure this was not the case some time ago, at least just after the full reimplementation of lighttable by @AlicVB .

This may be due to smooth scrolling or missing event compression.

@AlicVB : Am I missing something in this summary?

@dterrahe : As our Gtk+ expert, any idea?

### PR DESCRIPTION
**Pull request by AlicVB**
This fixes #15421

### CODE REVIEW

**Comment by AlicVB** [comment]
This is a first attempt to enhance lighttable speed when scrolling.
Currently, this "only" implement the reuse of "invalidated" widget, instead of deleting/recreating them on each scroll. This has NOT been tested in details for instance (just for "standard" filemanager and zooming mode).
In my tests (with 20 image per raw), the speedup for a "single" scroll is ~x8 :)

Next step will be to try to handled big scroll in one time...

File: src/dtgtk/thumbtable.c [hunk 1]
```diff
@@ -475,44 +475,97 @@ static gboolean _thumbtable_update_scrollbars(dt_thumbtable_t *table)
...
+  else
+  {
+    // let's reuse a now unaffected widget
+    dt_thumbnail_t *thumb = (dt_thumbnail_t *)(*th_invalid)->data;
+    thumb->imgid = imgid;
+    thumb->rowid = rowid;
+    thumb->x = posx;
+    thumb->y = posy;
+    dt_thumbnail_reload_infos(thumb);
+    if(thumb->img_surf && cairo_surface_get_reference_count(thumb->img_surf) > 0)
```
Comment (dterrahe) [inline src/dtgtk/thumbtable.c:543]: I'm not going to review all this code because it requires auditing the rest of thumbtable. This is not a new pattern (it occurs a few times in `thumbnail.c` (where it probably belongs; exposing and using those internals elsewhere is not great; publish functions if need be) but could you please explain why this reference count check is needed? Supposedly if somehow the surface has no references it may have been destroyed/cleaned up completely already anyway and if we still have a pointer, this could be dangling and we shouldn't use it to check a phantom object. If we took a reference before storing the pointer, then we can just safely destroy it here.

What I'm saying is `destroy` already decreases and checks outstanding references
https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-destroy

Comment (AlicVB) [reply src/dtgtk/thumbtable.c:543]: this comes from the fact that *sometimes* the surface is in an indeterminate state. certainly because of a race condition... After *lot* of try and guess, we have only found this check to avoid crash... But I admit that this is quite dirty...
My understanding is that when destroying a surface, the reference count is decreased at the far end of the process. Before the surface is in a inderminated state... `cairo_surface_status` doesn't help in this case...

Comment (AlicVB) [reply src/dtgtk/thumbtable.c:543]: And yes, I agree with you and I'll add a specific fct for all this, with some comments...

Comment (dterrahe) [reply src/dtgtk/thumbtable.c:543]: > My understanding is that when destroying a surface, the reference count is decreased at the far end of the process.

If that's the case, how would testing for the reference count help?

I understand these kind of issues can be really aggravating and bugs in gtk _do_ exist.

Comment (dterrahe) [reply src/dtgtk/thumbtable.c:543]: > certainly because of a race condition

All of the accesses to gtk objects are only from the ui thread, correct?

Comment (AlicVB) [reply src/dtgtk/thumbtable.c:543]: I've read again the code (because tbh, I don't remember exactly all the story)
What I would say : sometimes (always ?) when the surface is destroyed by gtk directly for whatever reason, the pointer is not set to NULL *but* not valid either (calling `cairo_surface_destroy` raise an error/crash) and `cairo_surface_status` doesn't help either...
So the only reliable way we have found is to get the reference counting...

Now as you say, this *may* be a gtk bug... don't know...

Comment (dterrahe) [reply src/dtgtk/thumbtable.c:543]: > when the surface is destroyed by gtk directly for whatever reason

What? Gtk (or I guess you mean cairo) goes about randomly destroying surfaces behind our backs? That should cause problems all over the place. But it seems only here...

My worry is that maybe at some point there was a bug where a surface got unintentionally destroyed somewhere without clearing the pointer and the bug was "fixed" by adding checks everywhere. And then eventually the bug was really fixed but the checks stayed and are now still being copied all over the place "just to be safe". This doesn't make sense and really complicates code maintenance and maybe even hides real new bugs somewhere (or makes them much harder to spot).

Every time I'm trying to change things in convoluted code I end up having to clean up all kinds of unnecessary crap before the wood can be seen for the trees again. So this is a real serious worry for me. Althoug of course this isn't at all the worst instance.

I see that these checks were introduced originally as part of your massive (130 commit) rewrite. Could you at all remember if crashes could be triggered reliably before these checks? Could we just try removing them and seeing if that works OK, as expected? And if not, I could help track down and solve the real causes of the problem?

Comment (AlicVB) [reply src/dtgtk/thumbtable.c:543]: tbh, that was a long time ago...
You're right, maybe the best is to remove all that checks and see if we manage to reproduce the crash... I'll try to do that asap...

**Comment by AlicVB** [comment]
last commit enhance greatly scrolling with the scrollbars (by dragging them or clicking somewhere)
this also solve an issue where the last row was sometimes unreachable using the scrollbars exclusively

File: src/dtgtk/thumbtable.c [hunk 2]
```diff
@@ -542,25 +593,12 @@ static int _thumbs_load_needed(dt_thumbtable_t *table)
...
-          thumb->single_click = TRUE;
-          thumb->sel_mode = DT_THUMBNAIL_SEL_MODE_MOD_ONLY;
-        }
-        thumb->x = posx;
-        thumb->y = posy;
-        table->list = g_list_prepend(table->list, thumb);
-        gtk_widget_set_margin_start(thumb->w_image_box, old_margin_start);
-        gtk_widget_set_margin_top(thumb->w_image_box, old_margin_top);
-        gtk_layout_put(GTK_LAYOUT(table->widget), thumb->w_main, posx, posy);
+        _thumb_move_or_create(table,
```
Comment (TurboGit) [inline src/dtgtk/thumbtable.c:596]: For clarity please use intermediate variable to name the parameter:

```
const dt_imgid_timgid = sqlite3_column_int(stmt, 1);
const int rowid =  sqlite3_column_int(stmt, 0);
```

And use them below.

File: src/dtgtk/thumbtable.c [hunk 3]
```diff
@@ -601,23 +639,14 @@ static int _thumbs_load_needed(dt_thumbtable_t *table)
...
-          thumb->single_click = TRUE;
-          thumb->sel_mode = DT_THUMBNAIL_SEL_MODE_MOD_ONLY;
-        }
-        thumb->x = posx;
-        thumb->y = posy;
-        table->list = g_list_append(table->list, thumb);
-        gtk_widget_set_margin_start(thumb->w_image_box, old_margin_start);
-        gtk_widget_set_margin_top(thumb->w_image_box, old_margin_top);
-        gtk_layout_put(GTK_LAYOUT(table->widget), thumb->w_main, posx, posy);
+        _thumb_move_or_create(table,
```
Comment (TurboGit) [inline src/dtgtk/thumbtable.c:644]: likewise

**Review by TurboGit — CHANGES_REQUESTED** [review]
Minor change after review. I'll test now.

**Comment by TurboGit** [comment]
The performance improvement is huge! Up to 15 per row it is very fast and 20 you have clearly good performance and a usable UI. Great work! Is that still draft? Do you plan on handling the issues I raised here as part of this PR https://github.com/darktable-org/darktable/issues/15421#issuecomment-1763349995 ?

**Comment by AlicVB** [comment]
Thanks for the tests and review.

The last things I want to handle before exiting draft mode : 
- try to handle big scroll in 1 time (I currently test it and it seems doable)
- fix some issues in move bounds, due to recent changes
- see what I can do for what you mention in #15421 
- test "special" cases more deeply

@dterrahe : I propose to test the "reference counting" thing apart from that PR, in order to not mix everything...

**Comment by TurboGit** [comment]
@AlicVB : Understood!

**Comment by AlicVB** [comment]
last commits "group" together "big" scrolls so the move is done in one time.
This is done with a timeout set to 10ms.
Here, this is quite effective and I don't feel any lag during "normal" scroll. But I'd like to get other people opinion on this...

Also I've removed a leftover from the first times of my rewrite, 3 years ago...

**Comment by AlicVB** [comment]
Thanks for your comments

> I'd be somewhat surprised if gtk didn't already compress mouse moves if they're not handled fast enough, so does this do anything more than just (very slightly) delay the initial response? Then it just changes the balance between responsiveness to small moves vs large moves. And large lists/many icons vs small zoomed in lists. If it feels better to you, it could be worth it.

I've done quite some tests with the different devices I have at home and in all cases, a simple scroll produce many small events (up to 6). For big scroll this is the same (although delta values are bigger)
Currently `t_gui_get_scroll_unit_delta` already ensure that nothing is done until the sum of all the "small" events deltas reach the unit.
Sadly this is not enough for "big" scroll, where you want to be able to handle all events in one time, with for example a delta value of 6. Hence the proposal to delay a very little the scroll in order to be able to handle all those "small" scroll in one time.

for your concern about `g_timeout`, I *think* I understand what you mean. I'll try to handle them...

**Comment by TurboGit** [comment]
@dterrahe : This is maybe because we don't set the Gtk event compression?

https://docs.gtk.org/gdk3/method.Window.set_event_compression.html

**Comment by AlicVB** [comment]
> @dterrahe : This is maybe because we don't set the Gtk event compression?

I've just checked, and the `event_compression` is TRUE. I've tried to set it to FALSE, with no change...

**Comment by dterrahe** [comment]
> a simple scrol

what do you mean by this? When smooth scrolling is disabled (i.e. `gtk_widget_set_events` hasn't requested `GDK_SMOOTH_SCROLL_MASK` and you scroll one "click" with the mousewheel)?

> although delta values are bigger

So that suggests aggregation is happening.

Gdk will send a scroll event up to once every 1/60th of a second. Your big scroll probably lasts longer than that, so will be split up. But if your event handler is too slow to keep up, the next time you'll get the aggregated moves that happened in the mean time.

So I'm not saying putting a delay before reacting to the first move is a bad thing; it just reduces responsiveness. I'm suggesting something similar in #15450; there's no point immediately reacting when the user pans the image by a few pixels, because likely they'll move it much further and you'll be calculating the useless update while they wait for the final picture. Similar with scrolling or dragging a slider. But again, when you wait too long, the user will feel a lag in responsiveness.

Once the move has started and you've responded to the first bit of it, if there are more scrolls incoming (maybe even aggregated if they had to wait for your event handler to finish) then there is no point inserting additional delays for the 2nd, 3rd etc scroll event; either you can keep up or you should try as fast as possible; otherwise the scrolling will become a little jerky. But on the other hand, it is also going to be even less noticeable if there's an unnecessary 10ms delay when there is a much larger visible delay already.

It would, again :-), have been nice if gtk had some way to reduce responsiveness of mouse messages so we didn't have to build in these delays ourselves. It might be possible to intercept scroll events in `dt_shortcut_dispatcher` and only send them on, aggregated if needed, after some delay. Then it would apply to everything (sliders, scroll bars, zooming etc). And we wouldn't have to worry about switching views etc. But we _would_ have to be careful about accidentally changing the order of, say, a scroll and a key press. Although with only a 10ms delay the user might not really be physically able to tell which one happened first anyway...

**Comment by AlicVB** [comment]
in order to have some data, I've put a simple printf to get the event time and delta_y of all scroll event (and disable the rest of the function to be sure we don't mix anything.
For the record, I have a Logitech mouse with 2 modes : ratchet mode (use for "simple" scroll : on step at a time) and free-spin mode (used for "big" scroll) But I also reproduce "big" scroll with "classical" mouse by scrolling very fast a lot of "steps"...

Here is the result for a "simple" (1 step) scroll : 
13709218 delta:0,000000
```
time:13709250 delta:0,125000
time:13709290 delta:0,125000
time:13709316 delta:0,125000
time:13709348 delta:0,125000
```
now with a "big" scroll : 
```
time:13897831 delta:0,000000
time:13897839 delta:0,500000
time:13897847 delta:1,000000
time:13897855 delta:1,625000
time:13897863 delta:2,000000
time:13897871 delta:2,375000
time:13897879 delta:2,125000
time:13897887 delta:2,125000
time:13897895 delta:2,250000
time:13897903 delta:2,250000
time:13897911 delta:2,250000
time:13897919 delta:2,125000
time:13897927 delta:2,125000
time:13897935 delta:2,250000
time:13897943 delta:2,125000
time:13897951 delta:2,125000
time:13897959 delta:2,250000
time:13897967 delta:2,125000
time:13897975 delta:2,375000
time:13897983 delta:2,000000
time:13897991 delta:2,125000
time:13897999 delta:2,250000
time:13898007 delta:2,125000
.... (until I stop the wheel)
```
Hope that this explain more clearly what happen...

Now if I put a loop after the printf that in the event function, which do some time consuming task (actually traversing 10000 times the table->list with some computations inside),
I get similar results... except that it takes lot of time between the printf... so iiuc gtk doesn't "aggregate" the pending events...

**Comment by dterrahe** [comment]
That is pretty convincing evidence that you need the extra delay!

Mouse behavior across machines is pretty diverse. There were lots of issues with macs, but your case looks interesting too! (With one scroll "tick" bring spread across 4 events that add up to a Delta of 0.5...)

**Comment by AlicVB** [comment]
@dterrahe : to try to mitigate your concerns with the `g_timeout` : 
I think I've avoided the case where we have multiple pending scroll event, by using `table->scroll_timeout_id` and `table->scroll_value` like that : 
```
static gboolean _event_scroll_compressed(gpointer user_data)
{
  dt_thumbtable_t *table = (dt_thumbtable_t *)user_data;
  if (table->scroll_value == 0) return FALSE;
  float delta = table->scroll_value;
  // starting from here, all further scroll event will count for the next round
  table->scroll_value = 0;
[........]
  // we reset the id value at the end, to ensure we don't get more than 1 pending scroll
  table->scroll_timeout_id = 0;
  return FALSE;
}
```
and
```
if(table->scroll_timeout_id == 0)
{
  table->scroll_timeout_id = g_timeout_add(10, _event_scroll_compressed, table);
}
table->scroll_value += delta;
```
in the scroll event
So imho the worst case here would be that we somehow "loose" some scroll events at the end, that would have happen during the last scroll function...

Another point is that `table` is always defined during dt "life"...

What do you think ?

@TurboGit : last commit implement the hashtable discussed earlier.

As I've done all the pending thing from my todo, I remove the draft flag now (this doesn't mean we can't discuss further, esp. @dterrahe concerns)

**Comment by AlicVB** [comment]
> Mouse behavior across machines is pretty diverse. There were lots of issues with macs, but your case looks interesting too! (With one scroll "tick" bring spread across 4 events that add up to a Delta of 0.5...)

yep... and my devices / availabel OS  are not so diverse ;)

**Comment by dterrahe** [comment]
> Another point is that table is always defined during dt \"life\"...

Then that should be safe. I have no issues (but also not helped testing, sorry 😔) so am ok with this pr. Sounds like a great improvement; thank you!

**Review by TurboGit — APPROVED** [review]
A huge improvement! I did a last check on a collection with more than 64k images. Even with 25 images per row I can scroll and have the GUI react quite fast. Thanks for the hard work @AlicVB.
