### PR TITLE
colorchecker: unstick slider when using saved colors

### LINKED ISSUE #4820: [module color LUT] slider stuck when using saved colours
**Describe the bug**

When using custom colour tile (colour picker & shift+click to a tile), dragging  of lightness or saturation slider is delayed, actually stuck in original position and  get updated upon release of the mouse button

Attached ZIP contains a screencast. The moment my mouse moves to the left, I hold the mousebutton (so you see, I move gently). @~15s of the vid, I releas the button and the screenupdate appears.

Using mouse-wheel is without this error

**To Reproduce**
1. Go to 'darkroom/color look up table'
2. Click on 'color picker in color LUT'
3. mark any color in your picture and shift+click on one tile in color lut to save it there
4. with that saved box activated, grab the slider of lightness or saturation and try to drag it for some distance (e.g. 15-20nm). (too see better, hold the mous for a moment or slide a bit left & right)
5. keep observing pic and slider prior releasing the mouse button now
6. see error

**Expected behavior**

immediate update of screen

**Screenshots**

[Color-LUT-BUG.zip](https://github.com/darktable-org/darktable/files/4535360/Color-LUT-BUG.zip)

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: **Gentoo Linux**
 - OpenCL: **on and off, both show error**
 - GPU 0 Nvidia GTX1060 OC 
 - GPU 1 Nvidia RTX2070 Super
 - nvidia-drivers-440.82

**Additional context**
 - Are the steps above reproduce with a fresh edit (removing history)? **yes**
 - Did you compile Darktable yourself? If so which compiler was used, with what options? 
**gcc 9.3.0 | -march=native -O3 -mtune=native -pipe**
 - Is the issue still present using an empty/new config-dir **yes**

### PR DESCRIPTION
**Pull request by dtorop**
Straighten out freeze when dragging slider after creating a new color swatch. Do this by not calling `gui_update()` when a control is updated. Separate out draw logic from color picking logic.

Fixes #4820.

### CODE REVIEW

File: src/iop/colorchecker.c [hunk 1]
```diff
@@ -109,6 +109,8 @@ typedef struct dt_iop_colorchecker_global_data_t
   int kernel_colorchecker;
 } dt_iop_colorchecker_global_data_t;
 
+#define SQR(x) ((x) * (x))
```
Comment (flannelhead) [inline src/iop/colorchecker.c:111]: (just a minor note as I happened to stumble upon this): there is a widely used `static inline float sqf(const float x)` function in `src/develop/openmp_maths.h` – could that one be used here?

Comment (dtorop) [reply src/iop/colorchecker.c]: Thank you, yes!

Comment (TurboGit) [reply src/iop/colorchecker.c]: Not sure maybe a commit is missing. This is marked as resolved, you agreed to use sqf() already defined but I still see SQR() macco used.

Comment (dtorop) [reply src/iop/colorchecker.c]: It should be there in 57d8efd, following this conversation? It seems to have integrated, in https://github.com/darktable-org/darktable/pull/9892/files I see only `sqf()`, not `SQR()`.

**Comment by TurboGit** [comment]
I see, not sure what I did wrong, sorry for the noise.

**Review by TurboGit — APPROVED** [review]
Thanks !

**Comment by dtorop** [comment]
Thank you! It looks like there could still be more to be done on the module, but hope it's good for now...
