### PR TITLE
Fix images added to group when grouping not active

### LINKED ISSUE #19693: Grouping images sometimes joins the grouped images into the previously edited image group
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

Sometimes, when creating several image groups one after another, the last created group is joined into the previously created group.

### Steps to reproduce

1. Open a collection of ungrouped images in lighttable.
1. Disable image grouping in the top panel.
1. Select some images.
1. Group the selected images by clicking the “group” button in the [actions on selection](https://docs.darktable.org/usermanual/development/en/module-reference/utility-modules/lighttable/selected-image/) module, or by pressing Ctrl+G (see [image grouping](https://docs.darktable.org/usermanual/development/en/lighttable/digital-asset-management/grouping/)).
1. Change the group leader to edit the newly created group.
1. Select some other ungrouped images.
1. Group the selected images in the same way as in step 4.

Now the images selected in step 3 and the images selected in step 6 are all joined into the same image group.

This bug does not occur if step 5 is omitted.

### Expected behavior

The images selected in step 6 should be in a different group than the images selected in step 3.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

distro packaging

### darktable version

5.0.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 25.04

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by wpferguson**
Added check to see if grouping is active before using expanded group id when creating a group.

@TurboGit it turns out the easy fix with an added test is the correct fix :smile:

Tested creating a 2nd group with an expanded group with a changed group leader and the groups remained separate

Tested grouping active, expand a group, select more images and hit group button and they are added to the expanded group.

Fixes #19693.

### CODE REVIEW

File: src/libs/image.c [hunk 1]
```diff
@@ -85,11 +85,14 @@ uint32_t container(dt_lib_module_t *self)
 }
 
 /** merges all the selected images into a single group.  if there is
- * an expanded group, then they will be joined there, otherwise a new
+ * an expanded group and grouping is on, then they will be joined there, otherwise a new
  * one will be created. */
 static void _group_helper_function(void)
 {
-  dt_imgid_t new_group_id = darktable.gui->expanded_group_id;
+  dt_imgid_t new_group_id = NO_IMGID;
```
Comment (TurboGit) [inline src/libs/image.c]: Maybe rewrite as:

```
const dt_imgid_t new_group_id = darktable.gui->grouping
   ? darktable.gui->expanded_group_id;
   : NO_IMGID;
```

Comment (wpferguson) [reply src/libs/image.c]: Can't be a `const` as new_group_id gets used to create a new group a few lines later.  When it's set to NO_IMGID it takes the first selected image id and assigns it to new_image_id for use in building the group.

**Review by TurboGit — APPROVED** [review]
Works on my side, thanks!
