### PR TITLE
Don't crash when applying style from Lua in darkroom mode

### LINKED ISSUE #13985: crash when applying style from lua in darkroom view
I have a lua script that adds buttons to the lighttable and darkroom for applying styles.

The lua script essentially runs `darktable.styles.apply(style, image)` on the current `image`, for a number of predefined `style`s. Code and styles are here: https://github.com/bastibe/Darktable-Film-Simulation-Panel/blob/master/lua/contrib/FilmSimPanel.lua#L15.

If I click these buttons in the lighttable, it works as expected and applies the style. In the darkroom, it works sometimes, but very often crashes darktable with a SIGSEGV. Applying the same styles through the style menu does not produce a crash. Some of the styles were created with `darktable-chart`, others were built by hand in darktable. All styles were built in the current version of darktable (4.2.1), and any of them can crash darktable.

In most cases, darktable claims, e.g. `backtrace written to /tmp/darktable_bt_LJ9611.txt`. However, there is no such file in `/tmp`, nor does `find / -name "darktable_bt_LJ9611.txt"` find it anywhere else. I expected `/tmp` to be remapped somewhere since I'm using the flatpak darktable, but setting `--tmpdir` does not change the logged backtrace location, nor produce the backtrace file.

The issue happens with images from all my cameras, and regardless of whether OpenCL is turned on or off.

I do not see any pattern in the last few lines of output with `-d all`, although sometimes (rarely) it ends with

```
malloc(): unaligned tcache chunk detected
```

or says

```
validation check failed in _iop_validate_params for type "float", field: aspect
validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
```

**Platform**

* darktable version :  4.2.1 Flatpak
* OS                : Linux - kernel 5.19.0-35
* Linux - Distro    : KUbuntu 20.10
* Memory            : 32 Gb
* Graphics card     : Nvidia 3060
* Graphics driver   : nvidia-driver-515
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 1:7.7+23ubuntu2
* Desktop           : KDE
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

### PR DESCRIPTION
**Pull request by wpferguson**
Lua isn't supposed to be used to process images in darkroom mode.  Using the function `darktable.styles.apply()` in darkroom mode causes darktable to crash.  

Added a test to determine if the function is being called from darkroom mode, and return an error message if that's the case.

`darktable.gui.action()` can be used to apply a style in darkroom mode since it's actually using the GUI to apply the style rather than trying to do it internally.

Fixes #13985

### CODE REVIEW

File: src/lua/styles.c [hunk 1]
```diff
@@ -259,8 +259,14 @@ int dt_lua_style_apply(lua_State *L)
     luaA_to(L, dt_style_t, &style, 1);
     luaA_to(L, dt_lua_image_t, &imgid, 2);
   }
-  dt_styles_apply_to_image(style.name, FALSE, FALSE, imgid);
-  DT_DEBUG_CONTROL_SIGNAL_RAISE(darktable.signals, DT_SIGNAL_TAG_CHANGED);
+
+  if(darktable.develop && darktable.develop->image_storage.id == imgid)
+    dt_print(DT_DEBUG_LUA, "LUA ERROR : %s can't called from darkroom view.  Use darktable.gui.action() instead\n", __FUNCTION__);
```
Comment (TurboGit) [inline src/lua/styles.c:264]: Have you tried calling:

`    dt_styles_apply_to_dev(style.name, darktable.develop->image_storage.id);`

When in darkroom?

Comment (wpferguson) [reply src/lua/styles.c:264]: Repeatedly with lots of crashes as the result.  The crashes are segfaults, usually updating module instance names, but sometimes updating the history, and sometimes other places.  I couldn't get anything that repeated consistently.

Comment (wpferguson) [reply src/lua/styles.c:264]: I also tried using dt_action_process(), since darktable.gui.action() works fine from Lua,  but didn't have any better luck.

Comment (wpferguson) [reply src/lua/styles.c:264]: Here's the test script and styles I used if you'd like to try it
[styles_apply.zip](https://github.com/darktable-org/darktable/files/11240419/styles_apply.zip)

Comment (TurboGit) [reply src/lua/styles.c:264]: Where should I put all those files and what's the procedure to trigger the issue? I'm not using Lua :)

Also, just to be clear I meant to call the `dt_styles_apply_to_dev() `only in the conditional that you have added:
`
if(darktable.develop && darktable.develop->image_storage.id == imgid)`

**Comment by wpferguson** [comment]
If you don't have the scripts installed, use the script installer and install them.  Take the script and put it under ~/.config/<darktableconfigdir>/lua/contrib.  Start it from script_manager.  Assign a shortcut to it under the lua section of shortcuts.  The only style you need to import is testStyle3.dtstyle.  The number after testStyle is the number of modules the style invokes.  You can import the other styles, then just change the name of the style in the script.

For my testing I imported a fresh set of images.  I would open an image in darkroom, the use the shortcut to apply the style.  Then, if it didn't crash,  I would go to the next image and apply the style with the shortcut. Sometimes it will work for several images but sooner or later it will start crashing.

**Comment by wpferguson** [comment]
One more note, for me the crash was always in the pool-darktable thread

**Comment by TurboGit** [comment]
Ok, reproduced with the Lua script. The crash happens in `imageop.c:dt_iop_show_hide_header_buttons()` on the `gtk_widget_set_visible` call below:

```
  GList *button;
  for(button = g_list_last(children);
      button && GTK_IS_BUTTON(button->data);
      button = g_list_previous(button))
  {
    gtk_widget_set_no_show_all(GTK_WIDGET(button->data), TRUE);
    gtk_widget_set_visible(GTK_WIDGET(button->data), show_buttons && !always_hide && !disabled);
    gtk_widget_set_opacity(GTK_WIDGET(button->data), opacity);
  }
```

The strange thing is that if you add a shortcut for the same style in global actions under Styles section there is no problem.So looks like some bad interaction with Lua... Really no idea why :( 

So I'll merge this which at least avoid the crash.

**Comment by dterrahe** [comment]
Is this code being called in a non-gui thread?

**Comment by TurboGit** [comment]
> Is this code being called in a non-gui thread?

Should not be the case as we are speaking of a shortcut, right?

**Comment by dterrahe** [comment]
> Should not be the case as we are speaking of a shortcut, right?

When a lua routine is triggered from a normal shortcut, it is run in the lua thread (in order for long routines to keep running in the background). Only dt.gui.mimic routines are run in the gui thread because they are solely intended to quickly call back into the gui and would lock it up if they took too long anyway.

I pushed the correct fix in #14238
