### PR TITLE
dt_imageio_export_with_flags should keep history for append style

### LINKED ISSUE #9191: export with style: "replace history" adds history and "append history" does nothing
**Introduction**
I have a style to export in scene liner space from dt. 
When selecting "append history" for the style in the export panel the style is not appended. the export is the same as exporting without a style.  
when selecting "replace history" the history gets appended (the expected behavior for "append history")

**Describe the bug/issue**
with a style selected
"append history" in the export panel does nothing
"replace history" in the export panel appends the history

[the style i used](https://drive.google.com/file/d/1JgYQ1Ag6nzNB-mLybrfkvLcszNYJbeuz/view?usp=sharing)

**To Reproduce**
1. import the style
2. select an image with filmic enabled
3. go to the export panel
3. select my style as the export style to use
4. select mode "append history"
4. observe that the exported image does not look like it has filmic disabled.

**Expected behavior**
"append history" actually appends the history
"replace history" replaces history

also another minor issue: 
the naming between the export panel and the styles panel isn't consistent
overwrite in styles panel is replace history in export panel

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #9191

I am not sure how to deal with the text difference mentioned. I would prefer to use "replace" for both cases but i really dont care.

### CODE REVIEW

**Comment by TurboGit** [comment]
This is not working on my side, and when I use append to history I get on the console:

```
[dt_ioppr_check_iop_order] module bilat (0)(60) and bilat (0)(60) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_duplicate_iop_order] modules bilat (60) and bilat (60) have the same iop_order
[dt_ioppr_check_iop_order] module bilat (0)(60) and bilat (0)(60) have the same order image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] module filmicrgb (0)(52) and filmicrgb (0)(52) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] module bilat (0)(60) and bilat (0)(60) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_duplicate_iop_order] modules filmicrgb (52) and filmicrgb (52) have the same iop_order
[dt_ioppr_check_duplicate_iop_order] modules bilat (60) and bilat (60) have the same iop_order
[dt_ioppr_check_iop_order] module filmicrgb (0)(52) and filmicrgb (0)(52) have the same order image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] module bilat (0)(60) and bilat (0)(60) have the same order image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] module filmicrgb (0)(52) and filmicrgb (0)(52) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] module bilat (0)(60) and bilat (0)(60) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_duplicate_iop_order] modules filmicrgb (52) and filmicrgb (52) have the same iop_order
[dt_ioppr_check_duplicate_iop_order] modules bilat (60) and bilat (60) have the same iop_order
[dt_ioppr_check_iop_order] module filmicrgb (0)(52) and filmicrgb (0)(52) have the same order image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] module bilat (0)(60) and bilat (0)(60) have the same order image 0 (dt_dev_pop_history_items_ext end)
```

File: src/common/imageio.c [hunk 1]
```diff
@@ -708,8 +708,10 @@ int dt_imageio_export_with_flags(const int32_t imgid, const char *filename,
 
     GList *modules_used = NULL;
 
-    dt_dev_pop_history_items_ext(&dev, dev.history_end);
-
+    // if we export with history overwrite we clear the complete stack
+    if(format_params->style_append  == FALSE)
+      dt_dev_pop_history_items_ext(&dev, dev.history_end);
```
Comment (paul-pw) [inline src/common/imageio.c:713]: I don't think this will fix my issue. I've added a few test images in the issue #9191  to show the behavior I'm experiencing.

**Comment by jenshannoschwalm** [comment]
I will find a correct way tonight :-)

**Comment by jenshannoschwalm** [comment]
Hi Pascal @TurboGit i looked this up more thoroughly and for me it touches delicate code handling iop order. Please have a closer look to review. I tested and it works here but i am not completely sure about it. To make testing a bit easier the relevant code gives more output with -d imageio

**Comment by TurboGit** [comment]
@jenshannoschwalm : @johnny-bit will have a look today and I should be able to test this over the week-end.

For the record, this is the last PR currently opened for 3.6.

**Comment by johnny-bit** [comment]
Yep, I think this fixes #9191 properly :) tested! results are now (i think) identical with overwrite/append on paste when exporting with style and when applying style via styles module

File: src/common/imageio.c [hunk 2]
```diff
@@ -708,14 +710,13 @@ int dt_imageio_export_with_flags(const int32_t imgid, const char *filename,
 
     GList *modules_used = NULL;
 
-    dt_dev_pop_history_items_ext(&dev, dev.history_end);
-
-    dt_ioppr_update_for_style_items(&dev, style_items, format_params->style_append);
+    dt_dev_pop_history_items_ext(&dev, appending ? dev.history_end : 0);
```
Comment (TurboGit) [inline src/common/imageio.c:713]: At the end the fix was on a single line if we do not take into account cosmetic (but important for clarity) changes !

**Review by TurboGit — APPROVED** [review]
Perfect to me, working as expected and fixes a long standing issue. Thanks a lot !

File: src/common/imageio.c (hunk 2 above)
Comment (jenshannoschwalm) [reply src/common/imageio.c:713]: yeah, i was also surprised how simple this turned out :-)
