### PR TITLE
altered fix - in mipmap consider auto apply as altered

### LINKED ISSUE #5295: Auto applied WB preset is not used for thumbnail
**Describe the bug**
I use WB preset with "Auto apply" checkbox "on".  It successfully applied to the image, but ignored in thumbnails of DR and LT.

**To Reproduce**
1. Create WB preset with "Auto apply" checkbox "on".
2. Open test image in DR. WB automatically apply to it.
3. Switch back on LT.
4. See thumbnail of test image w/o WB applied.
5. Open another image in DR. See thumbnail of test image w/o WB applied.

**Platform:**
Darktable Version: master
OS: Debian 10

**Additional context**
To bypass issue it is necessary to manually turn off/on WB module.

### PR DESCRIPTION
**Pull request by phweyland**
fixes #5295 

I am not completely happy with this, mainly because the "altered" concept is bit weak and we have to live with it.
However this fixes the related issue: when embedded thumbnail is to be used, the image enters in darkroom not developed (even auto applied stuff). Leaving darkroom didn't triggers mipmap because auto applied stuff was not considered as altered.

I've also renamed dt_history_hash_get_mipmap_sync() to dt_history_hash_is_mipmap_synced() for more clarity.

### CODE REVIEW

File: src/common/history.c [hunk 1]
```diff
@@ -1427,7 +1427,7 @@ void dt_history_hash_read(const int32_t imgid, dt_history_hash_values_t *hash)
   sqlite3_finalize(stmt);
 }
 
-const gboolean dt_history_hash_get_mipmap_sync(const int32_t imgid)
+const gboolean dt_history_hash_is_mipmap_synched(const int32_t imgid)
```
Comment (johnny-bit) [inline src/common/history.c:1430]: change `synched` to `synced`?

File: src/common/history.h [hunk 2]
```diff
@@ -120,7 +120,7 @@ void dt_history_hash_write_from_history(const int32_t imgid, const dt_history_ha
 const dt_history_hash_t dt_history_hash_get_status(const int32_t imgid);
 
 /** return true if mipmap_hash = current_hash */
-const gboolean dt_history_hash_get_mipmap_sync(const int32_t imgid);
+const gboolean dt_history_hash_is_mipmap_synched(const int32_t imgid);
```
Comment (johnny-bit) [inline src/common/history.h:123]: change `synched` to `synced`?

File: src/views/darkroom.c [hunk 3]
```diff
@@ -817,7 +817,7 @@ static void dt_dev_change_image(dt_develop_t *dev, const uint32_t imgid)
   dt_dev_write_history(dev);
 
   // be sure light table will update the thumbnail
-  if (!dt_history_hash_get_mipmap_sync(dev->image_storage.id))
+  if (!dt_history_hash_is_mipmap_synched(dev->image_storage.id))
```
Comment (johnny-bit) [inline src/views/darkroom.c:820]: just a spellcheck

File: src/views/darkroom.c [hunk 4]
```diff
@@ -2879,7 +2879,7 @@ void leave(dt_view_t *self)
   }
 
   // be sure light table will regenerate the thumbnail:
-  if (!dt_history_hash_get_mipmap_sync(dev->image_storage.id))
+  if (!dt_history_hash_is_mipmap_synched(dev->image_storage.id))
```
Comment (johnny-bit) [inline src/views/darkroom.c:2882]: just a spellcheck :)

Comment (phweyland) [reply src/views/darkroom.c:2882]: Right !

**Comment by TurboGit** [comment]
Looks good to me. Thanks!
