### PR TITLE
[masks] use query tooltip to have always up to date mask indicatr tooltip

### LINKED ISSUE #9685: [dt 3.7.0] adding raster mask crashes darktable
**Describe the bug/issue**
Adding raster mask to module crashes darktable

**To Reproduce**

1. make some parametric mask on one module
2. open another module and add raster mask
3. darktable crashes 

See [darktable_bt_H3GA70.txt](https://github.com/darktable-org/darktable/files/6909975/darktable_bt_H3GA70.txt)

* darktable version : 3.7.0~git579.5c3444e43e-1
* Linux - Distro    : Kubuntu 20.04
* Graphics card     : GeForce GTX 1070
* Graphics driver   : 460.91.03
* OpenCL installed  : yes
* OpenCL activated  : yes
* Desktop           : KDE

### PR DESCRIPTION
**Pull request by johnny-bit**
Fixes #9685

Creating tooltip at the moment of creating mask indicator button causes either a crash (if raster mask has no source yet) or stale tooltip (eg when changing raster mask source or actually setting it)

This instead uses query-tooltip signal to get the freshest tooltip.

Also - avoids memory leak :D

### CODE REVIEW

**Comment by johnny-bit** [comment]
Hey @TurboGit - I've started working on the issue yesterday but only today assigned to myself... and didn't notice you've committed a closing commit to it.

I think this PR handles it a bit better. Please review.

File: src/develop/imageop.c [hunk 1]
```diff
@@ -2282,6 +2282,45 @@ static void _display_mask_indicator_callback(GtkToggleButton *bt, dt_iop_module_
...
+      type=_("drawn + parametric mask");
+    else if(mm & DEVELOP_MASK_MASK)
+      type=_("drawn mask");
+    else if(mm & DEVELOP_MASK_CONDITIONAL)
+      type=_("parametric mask");
+    else if(mm & DEVELOP_MASK_RASTER)
+      type=_("raster mask");
+    else
+      fprintf(stderr, "unknown mask mode '%d' in module '%s'\n", mm, module->op);
+    if(raster && module->raster_mask.sink.source)
```
Comment (TurboGit) [inline src/develop/imageop.c:2305]: not correct as we don't want to display the else part when raster is activated. If there is not yet a raster mask selected we should just not display the second line. That's what I did.

Comment (johnny-bit) [reply src/develop/imageop.c:2307]: Right you are.

Done :) a bit cleaner imo and no mem leak :)

**Comment by johnny-bit** [comment]
Rebased :)

**Review by TurboGit — APPROVED** [review]
Thanks a lot, looking perfect now!
