### PR TITLE
Fixing Ashift black edges

### LINKED ISSUE #15785: Rotation leaves parts of pictures blank
### Describe the bug

When adjusting the Rotate and Perspective Rotation module, If adjusted to quickly, the program leaves this triangle of black at the edge of the picture, and it does not fix itself without setting the rotation back to zero again.

As you can see in the top right edge of this photo, it leaves just enough space to be noticeable, sometimes more.
Screenshot 2023-11-29 205427

### Steps to reproduce

1. Open Darkroom
2. Go to the rotate and perspective module and adjust the rotation

### Expected behavior

crop as it is rotating to eliminate blank space.

### Logfile | Screenshot | Screencast

Screenshot 2023-11-29 205427

### Commit

_No response_

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Describe your system?

**Processer**    __Intel(R) Xeon(R) CPU E31225 @ 3.10GHz   3.10 GHz__
**Installed RAM** 20.0 GB
**System Type**    64-bit operating system, x64-based processor

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
While allocating and handling the buffer in g() we should always use the data available in struct piece->buf_in
as that is used for calculating the transformations.

This seems to be a residual from times we used this module only in expanded state, as we now have shortcuts
and the straightening line tool we can run into trouble in do_crop() in ASHIFT_CROP_ASPECT automatic cropmode.

The reproducer for the on master would be:
1. fresh history
2. select "original format" in ashift module and close module header again.
3. use some strong "straightening line" angle and quite often you will see black borders at 2 of the edges in canvas & preview.
4. Possibly inspect what's happening by activating ashift module - you will see "wrong corners", these can be corrected by changing the rotation.

Please note:
1. this always worked correctly for other modes than ASHIFT_CROP_ASPECT or while in ashift-module-expanded state.
2. there have been a number of issues about this since some time

Fixes #15785 

@elstoc and @kofa73 you both have commented on issues with this module so it seems to me you might be good testers?

### CODE REVIEW

File: src/iop/ashift.c [hunk 1]
```diff
@@ -1285,18 +1285,17 @@ void modify_roi_in(struct dt_iop_module_t *self,
...
-  roi_in->y = fmaxf(0.0f, ym - interpolation->width);
-  roi_in->width = fminf(ceilf(orig_w) - roi_in->x,
-                        xM - roi_in->x + 1 + interpolation->width);
-  roi_in->height = fminf(ceilf(orig_h) - roi_in->y,
-                         yM - roi_in->y + 1 + interpolation->width);
+
+  roi_in->x       = xm - interpolation->width;
+  roi_in->y       = ym - interpolation->width;
+  roi_in->width   = xM + interpolation->width - xm + 1;
+  roi_in->height  = yM + interpolation->width - ym + 1;
```
Comment (ralfbrown) [inline src/iop/ashift.c:1292]: The old code, expanded out, does `+ 2 * interpolation->width`.  So this is not computing exactly the same size even without the clamping, and my immediate reaction is that we need the doubling since the interpolation will access beyond the edge on both sides.

**Review by ralfbrown — COMMENTED** [review]
Looks reasonable, other than the change in computed roi_in size.

File: src/iop/ashift.c (hunk 1 above)
Comment (jenshannoschwalm) [reply src/iop/ashift.c]: Your immediate reaction is absolutely correct!

Comment (jenshannoschwalm) [reply src/iop/ashift.c]: fixed.

**Comment by jenshannoschwalm** [comment]
fixed as c ommented by ralf, squashed and force-pushed

**Comment by jenshannoschwalm** [comment]
> Looks reasonable, other than the change in computed roi_in size.

"reasonable" sounds nice, understanding this took me two f. days :-)

**Comment by ralfbrown** [comment]
I hear you.  I've often told the story of the Monday I spent trying to squash a bug and didn't go to bed until 4 o'clock Tuesday afternoon....  But at least the bug was finally fixed.

**Comment by kofa73** [comment]
So far, I have been unable to reproduce this on master (I used images from 2 cameras, both quite old, 10 and 20 MPx).

**Comment by jenshannoschwalm** [comment]
It's easier to reproduce with 3:2 raws and angles above 10°

**Comment by kofa73** [comment]
I've tried pretty wild angles (around 45 degrees) with 3:2 images, but I very rarely get the issue. I'll try some more, and if I can get a feel for the frequency of reproducibility, I'll try your branch.

**Comment by jenshannoschwalm** [comment]
Also can only be reproduced with the ashift module **not** expanded by using keyboard shortcuts or midi interface.

**Comment by kofa73** [comment]
This is what I tried:
- open the darkroom
- click _original_ in _duplicate manager_
- activate _rotate and perspective_
- open the module -> at this point, _original format_ is selected
- collapse the module
- right-click and drag on the image to draw an adjustment line
- if failed to reproduce the issue, delete the duplicate and click _original_ again.

**Comment by jenshannoschwalm** [comment]
The reproducer is more easy to do and i have 100% here. (All steps required)

1. make sure you have automatic cropping with "original format" set in ashift module, also make sure that ashift module won't be expanded while entering darkroom, so close all modules.
2. Use a raw file with a width/height ratio of 3:2 (others work also but are less likely)
3. Force fresh history on that file
4. Open it in darkroom
5. Now either rotate via the quick access panel (if you have that available) or via keyboard shortcuts until you see black corners top left or right likely at an angle of maybe 10. But **strictly avoid** entering the ashift module gui stuff until you  see the issue as in this screenshot. 
 
Bildschirmfoto vom 2024-06-30 15-02-23

6. **now** you can open the ashift module and will notice the wrong "frame"
