### PR TITLE
ashift: check for pathological parameters to avoid crash.

### LINKED ISSUE #14241: XMP file crashes darktable, segmentation fault
### Describe the bug

I imported a collection of about 400 Fuji X-E4 RAW images (.RAF). I was able to go through all images for a first cull. Then I wanted to edit the remaining images. When I reached about half of the remaining collection darktable crashed each time while generating previews in the lightroom view. On the command line, I get “Speicherzugriffsfehler darktable” (memory access error/segmentation fault).

I tried running darktable with the -d cache and -d all arguments without clear results. Then I tried to rebuild the cache with darktable-generate-cache. It crashed as well, the last line in the -d all output was:

image 7311/7818 (93,51%) (id:7312, file=DSCF8970.RAF)

Removing the RAF file and the
corresponding XMP has fixed my problem. I am able to re-import the RAF
file into a separate collection and use it without issues. But when I
import the RAF file with the XMP file into another separate collection
darktable crashes again.

Darktable should take more care in handling its input data. If data (in
the XMP file?) is broken, darktable should discard the invalid input
data. Anyhow, no kind of input data should lead darktable to a
segmentation fault  ("Speicherzugriffsfehler").

### Steps to reproduce

1. Open darktable
2. Import RAF file from a directory containing also the XMP

### Expected behavior

Darktable should handle errors in input data robustly, without crashing. Bad data should be discarded. At no time should bad input data lead to a segmentation fault. 

### Logfile | Screenshot | Screencast

```
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2023:04:09 07:44:01.000"
   xmp:Rating="1"
   xmpMM:DerivedFrom="DSCF8970.RAF"
   darktable:import_timestamp="63817353117472532"
   darktable:xmp_version="5"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="10"
   darktable:iop_order_version="2"
   darktable:history_auto_hash="02daaf1ff566f0d9ce34201c86c8ce7d"
   darktable:history_current_hash="02daaf1ff566f0d9ce34201c86c8ce7d">
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="000000000c0000008400000006000000ff03ff03ff03ff03ff3f000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="1"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="0000000000000000000000000104000001000000cdcc4c3e"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="2"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="7"
      darktable:params="gz48eJzjZhgFowABWAbaAaNgwAEAOQAAEA=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="3"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="gz35eJxjZBgFo4CBAQAEEAAC"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="4"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="5"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="fb74fd3f0000803f757dfa3f0000c07f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="6"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="050000000000803f00000000000000000000803f000000000100000005000000cdcccc3e000000400000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz13eJxjYGBgYARiCQYYOOHEgAZY0QVwggZ7CB6pfNoAAFDAGQk="/>
     <rdf:li
      darktable:num="7"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz02eJybNXOyo3zr+wOmcbMcGMDAAUifcIJgCJgFVKO/rMIGJNZXHOnAdV0ZyG6wh8mfPeNjxwykQZgRKsaIxIYBJigNABTUEr0="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz10eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi08IAAB/xiOk"/>
     <rdf:li
      darktable:num="8"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="00000000000080b93333333f00004842000080c001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz10eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi08IAAB/xiOk"/>
     <rdf:li
      darktable:num="9"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
    </rdf:Seq>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
```

### Commit

_No response_

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian testing

### Describe your system?

Lenovo Thinkpad L13, 16 GB RAM, i7-10510U CPU, CometLake-U GT2 graphics

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The relevant picture is a family picture (egg hunt), so I don't want to put it into the bug tracker, If necessary I can send it to individual developers upon request.

### PR DESCRIPTION
**Pull request by TurboGit**
Fixes #14241.

### CODE REVIEW

File: src/iop/ashift.c [hunk 1]
```diff
@@ -5754,7 +5754,11 @@ void commit_params(struct dt_iop_module_t *self,
   d->orthocorr = (p->mode == ASHIFT_MODE_GENERIC) ? 0.0f : p->orthocorr;
   d->aspect = (p->mode == ASHIFT_MODE_GENERIC) ? 1.0f : p->aspect;
 
-  if(gui_has_focus(self))
+  if(gui_has_focus(self)
+     || isnan(p->cl)
+     || isnan(p->cr)
+     || isnan(p->ct)
+     || isnan(p->cb))
```
Comment (kmilos) [inline src/iop/ashift.c:5761]: Isn't @ralfbrown eliminating `isnan()` everywhere?

Comment (TurboGit) [reply src/iop/ashift.c:5761]: Yes, but this is to recover from a bad XMP with NAN. The $MIN & $MAX also added to the introspection circuitry for those 4 fields should avoid new NAN but at least we can recover from broken XMP already created.

Comment (parafin) [reply src/iop/ashift.c:5761]: isnan() might break after @ralfbrown introduces compiler flags for non-NAN maths

Comment (parafin) [reply src/iop/ashift.c:5761]: It's a question for @ralfbrown I think

Comment (dterrahe) [reply src/iop/ashift.c:5761]: > The $MIN & $MAX also added to the introspection circuitry for those 4 fields should avoid new NAN

No they won't. They are used to set the range for a slider, if one is connected to these param fields (which they aren't), and in the _optional_ call to `_iop_validate_params`, which needs to be enabled by `DT_DEBUG_PARAMS/-d params` but even then only does diagnostic checking and no _fixing_.

> isnan() might break after @ralfbrown introduces compiler flags for non-NAN maths

InputNG extensively uses `NAN/isnan()` for signalling purposes. I.e. if you _explicitly_ send a move size of `NAN ` if will only do a read and if an option is not available, a `NAN` is returned. So these NANs are _not_ the result of a calculation, just the defined value. Will that still break when the compiler flag is set?

Comment (parafin) [reply src/iop/ashift.c:5761]: AFAIK yes

Comment (dterrahe) [reply src/iop/ashift.c:5761]: Because `isnan` gets optimised away even when not looking at the result of a calc? Seems weird but ohkay.

Would it then be possible to have our own implementation that simply does `(int)x == (int)NAN` or something like that? Or is even NAN not defined anymore? I guess we could use G_MAXFLOAT or something if needed... Not sure how to test for that in lua.

**Review by dterrahe — APPROVED** [review]

File: src/iop/ashift.c (hunk 1 above)
Comment (ralfbrown) [reply src/iop/ashift.c:5761]: I plan to add a `dt_isnan(x) { return isnan(x); }` for those cases we can't eliminate.  It turns out that a function compiled with different optimization flags won't get inlined (even if declared "inline"), so it should be safe to set the finite-math-only flag globally if all the NAN checks are inside code compiled without it.

@dterrahe: I had noticed that lots of action callbacks check for NAN.  Since these checks are not done per pixel, an extra function call would be negligible.  But we could also switch the "read-only" signal to -FLT_MAX.

Comment (dterrahe) [reply src/iop/ashift.c:5761]: > But we could also switch the "read-only" signal to -FLT_MAX.

Working on it. Only snag is that this also gets passed back to/through LUA, so LUA will need to have a way to check for -FLT_MAX. Haven't looked into that yet. A Q&D < 1e6 will work too, so not a show stopper. Checking for NAN in LUA goes like `value ~= value` :-)

Comment (dterrahe) [reply src/iop/ashift.c:5761]: Should have @wpferguson; checking the return of `dt.gui.action` would need to change and requesting a read-only action by passing a NAN (0/0) as the last parameter will no longer be supported. However, since recently the last parameter can simply be dropped (or, in the rare case it is followed by a multiinstance number, set as "")

**Comment by wpferguson** [comment]
> Not sure how to test for that in lua.

In Lua NaN is 0/0, so you could do `x == 0/0`

NaN is also used in image GPS information.  `https://github.com/darktable-org/lua-scripts/blob/master/contrib/clear_GPS.lua` sets elevation, longitude, and latitude to NaN to clear them.  Other pieces of Lua code may test against NaN to see if they are set.

**Comment by dterrahe** [comment]
Are you sure that works for you? I believe in lua comparing anything again nan returns false, so even 0/0 == 0/0 is false. But since that makes it the only value that compares false to itself, you can use x ~= x.

Anyway, the point is, in c we'll now be using -FLT_MAX, so either we'll have to test against that in lua or, maybe easier, keep using nan and I'll convert back and forth in the calls to dt.gui.action/mimic (using the dt_is_nan variant @ralfbrown is proposing).

**Comment by ralfbrown** [comment]
> NaN is also used in image GPS information. `https://github.com/darktable-org/lua-scripts/blob/master/contrib/clear_GPS.lua` sets elevation, longitude, and latitude to NaN to clear them. Other pieces of Lua code may test against NaN to see if they are set.

I already started work on a PR to change those to -FLT_MAX as well.  Noticed that there will probably have to be a check for NaN when retrieving from the database due to existing entries.

**Comment by wpferguson** [comment]
> I believe in lua comparing anything again nan returns false

You're right.  Not enough coffee yet.

The only place we use NaN in the scripts is clear_GPS.lua and that just gets passed through to the database.

**Comment by TurboGit** [comment]
@ralfbrown : Thanks I'm using `dt_isnan()` here now.
