### PR TITLE
let users choose the cairo filter in pref

### LINKED ISSUE #4152: Slow and sluggish preview panning in dt 3.1 git
**Describe the bug**
Panning a zoomed image is slow and unresponsive. Clear stutter in preview image and "rubberbanding" between the mouse cursor and preview image. Seems to be worst when around 50% zoom. 100% zoom performs okay. Zooming in and out (with mouse wheel) also feels less responsive than with 3.0.

**To Reproduce**

Zoom preview to ~50% and try panning. Compare with 3.0 release -> big difference.

**Expected behavior**
Responsive and stutter-free panning and zooming

**Screenshots**
Screen recording comparison of both 3.0 and 3.1, not sure how well the difference comes across in this (OpenCL off in both cases):
https://streamable.com/uv48s

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.1.0~git414
 - OS: Fedora Workstation 31 GNOME DE
 - OpenCL on could be slightly better, hard to say really. OpenCL on produces more single core spiking in 3.1 than 3.0 when panning.
 - NVIDIA Quadro w/ NVIDIA 440.44 driver

**Additional context**
 - Can you reproduce with another Darktable version?

No, 3.0 is smooth as butter. I'm referencing [this fix](https://github.com/darktable-org/darktable/pull/3957) for previously reported performance regression (maybe the panning regression is caused by something similar).

### PR DESCRIPTION
**Pull request by aurelienpierre**
Fix #4152
Set default cairo filter to fast (== nearest). Keep the nearest setting in parts of the code where exact buffer/display pixel sizes is ensured.
Default can be changed in darktablerc: "ui/cairo_filter = fast, good, best"

### CODE REVIEW

File: src/gui/gtk.c [hunk 1]
```diff
@@ -1486,6 +1486,19 @@ static void init_widgets(dt_gui_gtk_t *gui)
 
   gtk_widget_set_visible(gui->scrollbars.hscrollbar, FALSE);
   gtk_widget_set_visible(gui->scrollbars.vscrollbar, FALSE);
+
+  // Fetch the cairo filter to draw scaled surfaces where exact 1:1 buffer/viewport size is not guaranteed
+  gui->filter_image = CAIRO_FILTER_FAST;
+
+  if(dt_conf_key_exists("ui/cairo_filter"))
+  {
+    if(strcmp(dt_conf_get_string("ui/cairo_filter"), "best"))
```
Comment (TurboGit) [inline src/gui/gtk.c]: This should be !strcmp

File: src/gui/gtk.c [hunk 2]
```diff
@@ -1486,6 +1486,19 @@ static void init_widgets(dt_gui_gtk_t *gui)
...
+      gui->filter_image = CAIRO_FILTER_BEST;
+    else if (strcmp(dt_conf_get_string("ui/cairo_filter"), "good"))
```
Comment (TurboGit) [inline src/gui/gtk.c]: likewise

**Comment by aurelienpierre** [comment]
I have put `fast` as a default because it was the default mode for the longest time, and nobody seemed to complain. I changed that in the UI revamping last April out of precaution for the edge cases, but since it's now configurable, I think we can default to the fastest and then point out other options if users complain.

File: src/gui/gtk.c (hunk 1 above)
Comment (aurelienpierre) [reply src/gui/gtk.c]: strcmp can output 1, -1, or 0, so I have put == 0 instead (I have no idea what `!(-1)` is)

**Comment by TurboGit** [comment]
Perfect ! That's merged in master and 3.0.1. Thanks.
