### PR TITLE
Correcting history compression in lighttable mode.

### LINKED ISSUE #2780: Compress history in lighttable does not retain disabled modules
**Describe the bug**

When a module is disabled, compressing its history stack from lighttable will remove that module from the stack.

**To Reproduce**

Open image in darkroom.  Change exposure.  Then disable the "exposure" module by clicking on its ⏻ symbol.  The history stack will contain "exposure (off)" as topmost entry.  Go to lightroom.  Make sure the same image is selected.  Choose "history stack/compress hist...".  Open the same image in darkroom again.  The exposure module has vanished from the history stack.

If you cannot reproduce this, it may be an effect of #2774.  Make sure you have a consistent history stack to start with.

**Expected behavior**

According to [this](https://github.com/darktable-org/darktable/issues/2775#issuecomment-509542189), compressing history should retain disabled modules.

**Platform (please complete the following information):**
  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * $ git describe: release-2.7.0-1514-g122cca227

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Fixes #2780 

The underlying reason for this bug is in src/common/history.c

In `void dt_history_compress_on_image(int32_t imgid)` we should **not** look for enabled modules but keep the summary status for **all** modules that have be enabled or disabled while developing as in `static void _lib_history_compress_clicked_callback` found in src/libs/history.c

Also the masks should be preserved as in darktable mode.

### CODE REVIEW

**Comment by TurboGit** [comment]
I've not looked at the code, but I suppose we should have a single compress routine in common/history and call it also in libs/history with possibly some more calls here to satisfy the lib requirement (update gui or whatever....).

Do you think this is possible? At least sharing code for this seems a nice goal.

**Comment by jenshannoschwalm** [comment]
@TurboGit I will give you a hint to merge after refactoring

**Comment by TurboGit** [comment]
Perfect, thanks!

**Comment by aurelienpierre** [comment]
> Do you think this is possible? At least sharing code for this seems a nice goal.

The lighttable code needs to iterate over all the selected pictures. Thinking about it, the darkroom path could be a special case of the more general lighttable case with only one selected image.

**Comment by aurelienpierre** [comment]
> In void dt_history_compress_on_image(int32_t imgid) we should not look for enabled modules but keep the summary status for all modules that have be enabled or disabled while developing as in static void _lib_history_compress_clicked_callback found in src/libs/history.c

The problem, then, is every module that has been activated then disactivated will be kept in history. The real, underlying, reason, is some module are applied in dt by default (base curve, white balance, sharpening), and are force-applied ON if no evidence is found that they have been force-disabled by user. That needs to be addressed too (and I don't know how).

**Comment by jenshannoschwalm** [comment]
@aurelienpierre 

> The problem, then, is every module that has been activated then disactivated will be kept in history.
Indeed.

> The real, underlying, reason, is some module are applied in dt by default (base curve, white balance, sharpening), and are force-applied ON if no evidence is found that they have been force-disabled by user.

Right again. I agree that this is a design decision. **But** we should have an identical behaviour for both use cases. 
You seem to think it's wrong to do it this way. I think it's just right. If you **actively** disable a module it should be saved in history as _disabled_, it does not matter whether you enabled it before or it was enanbled by default settings.

@TurboGit From your comments on #2780, do we want disabled modules marked as disabled in history or not?

**Comment by TurboGit** [comment]
To me we want disabled module to be marked as disabled in the history. It is not an option to remove them as they may have settings ready to be re-enabled at any time. So we want to keep them in the history even when disabled.

**Comment by aurelienpierre** [comment]
When things go bad, for example while applying styles or copy-pasting history, sometimes you end up with bugged history stacks of more than 50 entries, mostly duplicates instances. In some cases, I ever had images I could not even open, with hundreds of entries in history (and that was back when I used stable dt from repository).

I'm not opposed to both compression buttons having the same behaviour. I'm saying the default state of darktable is buggy, and users should have a way to manually flatten the history without opening the image, in cases it has gone south. Otherwise, the only other option is to discard the history entirely.

**Comment by TurboGit** [comment]
> When things go bad, for example while applying styles or copy-pasting history, sometimes you end up with bugged history stacks of more than 50 entries

In that case we need to fix this and not hide it by adapting the history compression here I would say.

**Comment by jenshannoschwalm** [comment]
> In that case we need to fix this and not hide it by adapting the history compression here I would say.

I sort of disagree here.

Both ways offer a compression of the history, we must define the way we want it to behave, either include **only enabled** modules or all modules that have been used.

The point of a buggy history is a different point in my opinion so it should be addressed in another PR, i would certainly also do that.
What is wrong with the history?

1. Scrolling a slider for example _pollutes_ the history, is this really necessary? Difficult to fix?
2. Can we overflow the history? Is this the problem aurelianpierre ran into?
3. Can we clearly define situations when we can **always** assume it's safe to compress history automatically?
4. Whatever way for history compression we agree on can be done via the lighttable button!, thats what aurelianpierre wanted i guess.

**Comment by TurboGit** [comment]
> What is wrong with the history?

Nothing. My thinking is that the compression algorithm on the darkroom has always been working properly. We need to have the same code used in lighttable.

> Can we overflow the history? Is this the problem aurelianpierre ran into?

No we can't.

> Can we clearly define situations when we can always assume it's safe to compress history automatically?

It is always safe as long as you keep disabled modules (last history of it only). There is always a loss when compression of course. That's why it is not automatic but done when user ask for it.

**Comment by jenshannoschwalm** [comment]
@TurboGit done the refactoring. I think this also fixes #2774

**Comment by aurelienpierre** [comment]
> It is always safe as long as you keep disabled modules (last history of it only). There is always a loss when compression of course. That's why it is not automatic but done when user ask for it.

The only modules that **need** to be kept in history when disabled are the ones that will be re-applied automatically if we ditch them (AFAIK, only white balance is affected, and base curve/sharpen if they are to be applied by default). Most modules can be safely removed if disabled. I think someone on the mailing list had a PR coming to handle white balance and others specifically.

**Comment by TurboGit** [comment]
>  Most modules can be safely removed if disabled.

I don't agree. All disabled modules have been used and have a set of settings that may be reused  later by just enabling back the module. That's the behavior since dt inception I don't think we want to change that by default.

If we want to change this behavior we need a preference if people want to really use a dangerous semantic.

File: src/common/history.c [hunk 1]
```diff
@@ -870,66 +870,76 @@ int dt_history_copy_and_paste_on_selection(int32_t imgid, gboolean merge, GList
   return res;
 }
 
-void dt_history_compress_on_image(int32_t imgid)
+void basic_dt_history_compress_on_image(int32_t imgid)
 {
   // make sure the right history is in there:
   dt_dev_write_history(darktable.develop);
```
Comment (TurboGit) [inline src/common/history.c]: this should probably be in dt_history_compress_on_image() only as this can be called from lighttable nothing to do.

File: src/common/history.h [hunk 2]
```diff
@@ -55,6 +55,7 @@ void dt_history_delete_on_selection();
 /** compress history stack */
 void dt_history_compress_on_selection();
 void dt_history_compress_on_image(int32_t imgid);
```
Comment (TurboGit) [inline src/common/history.h]: I would rename this one:
dt_history_compress_on_image_and_reload() // intended to be used in the darkroom

File: src/common/history.h [hunk 3]
```diff
@@ -55,6 +55,7 @@ void dt_history_delete_on_selection();
...
+void basic_dt_history_compress_on_image(int32_t imgid);
```
Comment (TurboGit) [inline src/common/history.h]: And this one renamed to just:
dt_history_compress_on_image()

File: src/common/history.c (hunk 1 above)
Comment (TurboGit) [reply src/common/history.c]: Well, maybe safe to keep it there after all. If a style is applied and the history not properly written after... Probably safer to ensure that history is properly written before dealing with it. So I withdraw my comment. Do you agree with the analysis?

Comment (jenshannoschwalm) [reply src/common/history.c]: Yes i do. Would keep it

File: src/common/history.h (hunk 2 above)
Comment (jenshannoschwalm) [reply src/common/history.h]: Sure

File: src/common/history.h (hunk 3 above)
Comment (jenshannoschwalm) [reply src/common/history.h]: Sure

**Comment by TurboGit** [comment]
Thanks !
