### PR TITLE
Redraw atrous area fixes

### LINKED ISSUE #19886: Contrast equalizer issues with redrawing alternating light and dark stripes after zoom scale change.
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

I am using DT5.3 +975 Windows 11 build. the manual states “In the background of the curve you can see a number of alternating light and dark stripes. These represent the levels of detail that are visible at your current zoom scale – any details without these stripes are too small to be seen your current view.”

However, when the zoom scale is changed the stripes only change when the mouse is hovered over CE graph. If the scale is changed to small then the stripes only change if the spline itself is engaged. I am unsure if this is intended or unintended behaviour. I feel either a note should be made in the documentation or the behaviour adjusted. 

### Steps to reproduce

1) set scale to something large like 100%
2) set scale to small
3) hover mouse over the CE graph (Does it redraw the stripes? Not on my machine)
4) engage the spline and shift it (the stripes redraw now on my machine)

### Expected behavior

Darktable should automatically redraw the stripes. 

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.3+ 975 Windows 11 weekly build

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Ncvidia Geforce GTX

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
The area should also be redrawn if
- the UI pipe has finished while atrous is in focus
- when the module gets focus

Fixes #19886

### CODE REVIEW

File: src/iop/atrous.c [hunk 1]
```diff
@@ -1766,6 +1766,23 @@ const dt_action_def_t _action_def_equalizer
       _action_elements_equalizer,
       _action_fallbacks_equalizer };
 
+
+static void _ui_pipe_done(gpointer instance, dt_iop_module_t *self)
+{
+  dt_iop_atrous_gui_data_t *g = self->gui_data;
+  if(!g || darktable.gui->reset) return;
+
+  if(dt_dev_gui_module() == self)
```
Comment (TurboGit) [inline src/iop/atrous.c]: Maybe we want to refresh if the module is expanded and enabled? Because if you open a another IOP and still see the contrast equalizer UI it seems better to also refresh it?

**Comment by jenshannoschwalm** [comment]
force-pushed changes drawing the area when enabled&expanded instead of being the gui_module

**Review by TurboGit — APPROVED** [review]
Looks good to me, thanks!

**Comment by TurboGit** [comment]
@jenshannoschwalm : Worth a release note entry I think.
