### PR TITLE
nlmeans_core.c: avoid out-of-bounds references

### LINKED ISSUE #9290: segfault in denoise (profiled) / nlmeans
**Describe the bug/issue**
segfault (backtrace at https://pastebin.com/skhGKeh4) while editing raw from https://discuss.pixls.us/t/hockey-game-under-lights-20k-iso-on-m4-3/25502. 
Analysis on IRC:
```
[10:10] <@johnny_bit> darktable/src/common/nlmeans_core.c:694 caused the app to go into sigsegv
...
[10:12] <@johnny_bit> it looks like the index i might go out of range for col_sums array
...
[10:42] <@johnny_bit> You can raise an issue with that stacktrace and ping ralfbrown on it because it's part of the code he's now most "accustomed" with, adding the info we've managed to "guess" here :)
```

**To Reproduce**
Edit settings of _denoise (profiled)_ in NL-means mode (does not happen immediately, probably hard to reproduce)

**Expected behavior**
No crash

**Which commit introduced the error**
I don't know, I hardly ever use NL-means.

**Platform**
* darktable version : 864e22daf
* OS                : Linux - kernel 5.11.0-18
* Linux - Distro    : KUbuntu 21.04
* Memory            : 64 GM
* Graphics card     : Nvidia 1060/6GB
* Graphics driver   : 460.80-0ubuntu0.21.04.2
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : xserver-xorg 1:7.7+22ubuntu1; xserver-xorg-core 2:1.20.11-1ubuntu1
* Desktop           : KDE
* GTK+              : 3.24.25-1ubuntu4.1
* gcc               : 10.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  : RelWithDebInfo

### PR DESCRIPTION
**Pull request by ralfbrown**
With very large values of both 'search radius' and 'scattering', it becomes possible for the left bound of some loops to lie to the right of the supposed right bound (and similarly for top/bottom), which results in an access outside of the input array.  This patch fixes that by clamping the bounds.

Fixes #9290.

### CODE REVIEW

File: src/common/nlmeans_core.c [hunk 1]
```diff
@@ -510,7 +510,7 @@ void nlmeans_denoise(const float *const inbuf, float *const outbuf,
           }
           const int pcol_min = chunk_left - MIN(radius,MIN(chunk_left,chunk_left+scol));
           const int pcol_max = chunk_right + MIN(radius,MIN(width-chunk_right,width-(chunk_right+scol)));
-          if (row < row_top)
+          if (row < MIN(row_top, row_bot))
```
Comment (TurboGit) [inline src/common/nlmeans_core.c:513]: I don't understand the semantic here. Don't you meant:

`if(row < row_top || row > row_bot)`

File: src/common/nlmeans_core.c [hunk 2]
```diff
@@ -728,7 +728,7 @@ void nlmeans_denoise_sse2(const float *const inbuf, float *const outbuf,
...
```
Comment (TurboGit) [inline src/common/nlmeans_core.c:731]: same here

**Review by TurboGit — COMMENTED** [review]
A question.

File: src/common/nlmeans_core.c (hunk 1 above)
Comment (johnny-bit) [reply src/common/nlmeans_core.c:513]: I think it's correct that the check is for `MIN(row_top, row_bot)` because it might be possible that bottom bound lies above top bound and we do not want to exceed either...

Comment (TurboGit) [reply src/common/nlmeans_core.c:513]: Maybe, but I'll wait for confirmation from @ralfbrown to be sure.

Comment (ralfbrown) [reply src/common/nlmeans_core.c:513]: Johnny-bit is correct, the cause of the crash was that row_top was greater than row_bot.

File: src/common/nlmeans_core.c (hunk 2 above)
Comment (ralfbrown) [reply src/common/nlmeans_core.c:731]: Same reason, just on the SSE code path.

File: src/common/nlmeans_core.c (hunk 1 above)
Comment (TurboGit) [reply src/common/nlmeans_core.c:513]: Probably an artifact of the algorithm as in all the code I went through the top was always smaller than the bottom as origin is on top-left. Anyway, merging then. Thanks!

Comment (ralfbrown) [reply src/common/nlmeans_core.c:513]: In the particular instance I managed to catch a segfault, the patch was at a vertical offset of 896 on a 900px high image, with a patch radius of 2.  After constraining things to stay within the input image, that resulted in row_top of 898 and row_bot of 897....
