### PR TITLE
retouch: fix for crash with large number of wavelet scales

### LINKED ISSUE #7929: Darktable crashes when Wavelet scales slider in retouch module is adjusted above a certain value
**Describe the bug**

When adjusting the wavelet scale above a certain value (8 for me) in the retouch module, Darktable crashes and produces a back trace. 

**To Reproduce**

1. Enable the retouch module
2. Adjust the lower slider for wavelet scales
3. Raise by one until crashing value is encountered. 

**Expected behavior**

That Darktable not crash and inform the user if there is an upper bound to wavelet scales.

**Screenshots**

image
image

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10
 - OpenCL activated
 -  Nvidia 1080Ti / 441.87

**Additional context**

Backtraces attachedL
[darktable_bt_5DQEX0.txt](https://github.com/darktable-org/darktable/files/5836169/darktable_bt_5DQEX0.txt)
[darktable_bt_9LLGX0.txt](https://github.com/darktable-org/darktable/files/5836175/darktable_bt_9LLGX0.txt)
[darktable_bt_AMLGX0.txt](https://github.com/darktable-org/darktable/files/5836176/darktable_bt_AMLGX0.txt)
[darktable_bt_HS0BX0.txt](https://github.com/darktable-org/darktable/files/5836177/darktable_bt_HS0BX0.txt)

### PR DESCRIPTION
**Pull request by ralfbrown**
First row could access locations before the start of the buffer when (1<<scalenumber) > width/2, where `width` is the size of the center image or the preview image when in the darkroom.  Fix is the addition of abs() to ensure reflection at left edge.

Also do a bit of code cleanup by introducing use of for_each_channel and converting indices and buffer offsets from int to size_t.

Fixes #7929.

### CODE REVIEW

**Comment by johnny-bit** [comment]
Interesting problem reported by CI on LLVM :) it seems like LLVM thinks ` (unsigned) - (signed) = (unsigned)` because error is "fatal error: taking the absolute value of unsigned type 'unsigned long' has no effect" on line 136:
`const float* const restrict above = in + 4 * abs(row - vscale) * width;`

**Comment by parafin** [comment]
LLVM thinks correct: https://en.cppreference.com/w/c/language/conversion

> If the unsigned type has conversion rank greater than or equal to the rank of the signed type, then the operand with the signed type is implicitly converted to the unsigned type.

unsigned type here is size_t which is >= int in size.

**Comment by johnny-bit** [comment]
so... the `row` here should be cast to `ptrdiff_t`?

**Comment by parafin** [comment]
I see several options:

1. dwt_interleave_rows returns int, so row can be int also, but it will require upcasting it when doing calculations - so probably not ideal; alternatively use ptrdiff_t for row type, but it's IMHO confusing;
2. cast row to ptrdiff_t in abs call;
3. don't do any signed math here at all, but implement the same logic as with below_row:
```
const size_t vscale = MIN(1 << lev, height-1);
...
const size_t above_row = row > vscale ? row - vscale : vscale - row;
const float* const restrict above = in + 4 * above_row * width;
```

I think staying away from signed stuff and sticking with unsigned is the least confusing or error-prone option, but I have no idea about its effects on performance.

File: src/common/dwt.c [hunk 1]
```diff
@@ -106,37 +106,16 @@ int dt_dwt_first_scale_visible(dwt_params_t *p)
...
   if(p->image != layer) memcpy(p->image, layer, sizeof(float) * p->width * p->height * p->ch);
 }
 
 // first, "vertical" pass of wavelet decomposition
 static void dwt_decompose_vert(float *const restrict out, const float *const restrict in,
-                               const int height, const int width, const int lev)
+                               const size_t height, const size_t width, const size_t lev)
 {
-  const int vscale = MIN(1 << lev, height);
+  const int vscale = MIN(1 << lev, height-1);  //(int because we need a signed difference below)
```
Comment (parafin) [inline src/common/dwt.c:118]: I suggest to change int to size_t here and remove now obsolete comment.

**Review by TurboGit — APPROVED** [review]
All good on my side. Thanks for the hard work!
