### PR TITLE
Only remove trailing carriage return/linefeed from preferences on loading

### LINKED ISSUE #14906: Regression: Space-suffixed preference values are being loaded inaccurately in Darktable 4.4.1.
### Describe the bug

In Darktable 4.2.0 and earlier, if one set a string preference to a value ending in a space (*e.g.*, `String `), it was read accurately out of `darktablerc`  upon restart. Darktable 4.4.1 still writes such a value correctly to `darktablerc`, but on restart reads it incorrectly, without the space (as `String`), and subsequently updates `darktablerc` to remove the space.

This is interfering with a Lua script I use to add a prefix to image metadata strings, storing the default prefix in a Lua preference. Such a prefix often ends in a space and is thus getting mangled on restart.

### Steps to reproduce

1. Add a space to the end of any string preference in the preferences dialog.
2. Restart Darktable two times, observing the changes to the preference's value in the preferences dialog and in `darktablerc`.

### Expected behavior

String preferences should be read exactly as written to `darktablerc`, as in Darktable 4.2.0 and earlier.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

_No response_

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

_No response_

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by wpferguson**
Fixes #14906

### CODE REVIEW

**Comment by wpferguson** [comment]
I've attached a simple Lua script that creates a string preference.  Start it then go to settings->lua options.  Enter a string with some trailing spaces.  Restart darktable then check the string preference by clicking in the field and observe the spaces are still there.
[test_string_pref.zip](https://github.com/darktable-org/darktable/files/12115545/test_string_pref.zip)

File: src/control/conf.c [hunk 1]
```diff
@@ -439,7 +439,8 @@ gchar *dt_conf_read_values(const char *filename,
       const char* ret = fgets(line, LINE_SIZE, f);
       if(ret != NULL)
       {
-        g_strchomp(line);
+        // only remove trailing carriage return, newline but leave whitespace #14906
```
Comment (TurboGit) [inline src/control/conf.c:442]: Please no #ref in the code. The commit message is sufficient in this case. TIA.

Comment (wpferguson) [reply src/control/conf.c]: Done
