### PR TITLE
Guided filter OpenCL fixes

### LINKED ISSUE #15621: Blocky mask artefacts when feathering (only with OpenCL)
### Describe the bug

A follow-up to https://github.com/darktable-org/darktable/issues/14215 after https://github.com/darktable-org/darktable/pull/15612.

Import the following into darktable, open the images in the darkroom.

### Steps to reproduce

Import the following into darktable, open the images in the darkroom.

black-dot2
[black-dot2.png.xmp.txt](https://github.com/darktable-org/darktable/files/13325579/black-dot2.png.xmp.txt)

dot2
[dot2.png.xmp.txt](https://github.com/darktable-org/darktable/files/13325620/dot2.png.xmp.txt)

### Expected behavior

_No response_

### Logfile | Screenshot | Screencast

With OpenCL:

image

image

Without:
image

image

### Commit

_No response_

### Where did you install darktable from?

self-compiled from git master branch

### darktable version

`4.5.0+1137~gd72544e3fc` (and many others, the initial report used `3.7.0+1111~g2a83a6389`)

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Ryzen 5, 64 GB, NVidia 1060 / 6 GB, driver 525.147.05

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 / 6 GB, driver 525.147.05

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Occurs with clean config as well.

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. Cleaned up filter kernels, using float4 simplifications, some perf improvements due to using samplerA if coordinates are known for sure
2. The big bug was the boxing kernels assumed aligned mask dimensions but they were not. So functioning was just good luck.

Fixes #15621

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Overall for me this seems to be the first time the guided filters work as they should (both for cpu and gpu) :-)

**Review by TurboGit — APPROVED** [review]
Works for me, thanks for the hard work!

**Comment by kofa73** [comment]
You are going to ban me from this repo, I think...
Deleted ~/.cache/darktable and moved ~/.config/darktable out of the way. 4.5.0+1167~g6f45d4bc0e
image

**Comment by s7habo** [comment]
Same here:

image

dt 4.5.0+1167~g6f45d4bc0

**Comment by jenshannoschwalm** [comment]
Right, with exactly your setting there is still something wrong. Seems to strongly depend on input data of that module. Will see,

**Comment by kofa73** [comment]
Reproducible with Intel UHD Graphics on Windows, as well.

**Comment by jenshannoschwalm** [comment]
Yes. Give me another day or two :-)

**Comment by kofa73** [comment]
Sorry, I didn't mean that to urge you, I'm grateful for what you have done already. I rarely encounter the issue in real photos anyway; just hoped to provide additional info (and rule out NVidia OpenCL bugs).

**Comment by jenshannoschwalm** [comment]
I'm perfectly fine with you "insisting" on the problem. And, quite a number of things already fixed. I definitely want this to be fixed in 4.6

File: src/common/guided_filter.c [hunk 1]
```diff
@@ -323,8 +323,10 @@ static int _cl_split_rgb(const int devid,
                           cl_mem imgg_b,
                           const float guide_weight)
 {
+  const int clwidth = ROUNDUPDWD(width, devid);
+  const int clheight = ROUNDUPDHT(height, devid);
   const int kernel = darktable.opencl->guided_filter->kernel_guided_filter_split_rgb;
-  return dt_opencl_enqueue_kernel_2d_args(devid, kernel, width, height,
+  return dt_opencl_enqueue_kernel_2d_args(devid, kernel, clwidth, clheight,
```
Comment (dterrahe) [inline src/common/guided_filter.c:329]: I'm a bit confused by this as  `dt_opencl_enqueue_kernel_2d_args` / `dt_opencl_enqueue_kernel_2d_args_internal` already contains (since a large deduplication effort a while back)
```
  const size_t sizes[] = { ROUNDUPDWD(w, dev), ROUNDUPDHT(h, dev), 1 };
```
Presumably rounding up twice should not change anything? This looks like a dededup to me :-)

Comment (jenshannoschwalm) [reply src/common/guided_filter.c:329]: It is and i already spotted that too.
