### PR TITLE
reset window placement if last position is out of available display space

### LINKED ISSUE #18986: Multiple displays
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

Hi,

I use Darktable on a laptop.
Sometimes I use it with one small display and sometimes with the docking with multiple large diplays (4k).
Bug: 
I use Darktable on a large external display and then close the program and shut down the computer,
Then I boot the laptop with the single, small internal display, Darktable opens in a space not available on the display. I have to move the Darktable window manually with the cursor-keys to make it reapear in the visible area. Darktable should appear in a visible area (many Windows don't know how to move hidden windows).

Thanks a lot for this great soft!

KR,

Patrik

### Steps to reproduce

Open Darktable on a laptop docked with multiple displays (4k)
Move Darktable-window to an external display (which is not the main Windows-display)
Close Darktable
Optional: shutdown Windows
Undock laptop, so it has only its main display (no more external displays)
Optional: start Windows
Launch Darktable
Darktable opens in a non accessible area which is virtually on a non connected external display.

### Expected behavior

darktable should not open in a non visible area when I switch between one and multiple displays (laptop with docking station)

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro 24H2

### Describe your system

I7-1195G7, 32 GB RAM, Iris Xe Graphics, SSD 1TB, Laptop

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel Iris Xe Graphics, driver: Intel 10.06.2024

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by MStraeten**
on initialisation the darktable window is moved to the last position even thats outside of available displays e.g. after undocking a laptop from external displays.
`_valid_window_placement checks` for an overlay with an existing display
`dt_gui_gtk_load_config()` is enhanced to reset the position to default if there's no overlap

fixes #18986

### CODE REVIEW

File: src/gui/gtk.c [hunk 1]
```diff
@@ -773,6 +773,30 @@ static gboolean _scrollbar_changed(GtkWidget *widget,
...
+
+  // check each monitor
+  for(gint i = 0; i < n_monitors; i++)
+  {
+    GdkMonitor *monitor = gdk_display_get_monitor(display, i);
+    GdkRectangle geometry;
+    gdk_monitor_get_geometry(monitor, &geometry);
+
+    // Check if window overlaps with this monitor
+    gboolean x_overlap = (saved_x < geometry.x + geometry.width) && (saved_x + window_width > geometry.x);
```
Comment (dterrahe) [inline src/gui/gtk.c]: Could you maybe be a little more picky and require that at least part of the header/top-left of the window is on the monitor? Otherwise you could still end up with just the bottom-right corner of the window being on the top-left of the monitor and that is a little hard to interact with (or even notice). I guess you'll have to allow for the border of the window to be outside of the monitor, since that is likely how full-screen is implemented.

File: src/gui/gtk.c [hunk 2]
```diff
@@ -773,6 +773,38 @@ static gboolean _scrollbar_changed(GtkWidget *widget,
   return TRUE;
 }
 
+gboolean _valid_window_placement(gint saved_x, gint saved_y, gint window_width, gint window_height, gint border)
```
Comment (TurboGit) [inline src/gui/gtk.c]: all parameters are `const`

File: src/gui/gtk.c [hunk 3]
```diff
@@ -773,6 +773,38 @@ static gboolean _scrollbar_changed(GtkWidget *widget,
...
+{
+  GdkDisplay *display = gdk_display_get_default();
+  gint n_monitors = gdk_display_get_n_monitors(display);
```
Comment (TurboGit) [inline src/gui/gtk.c]: const

File: src/gui/gtk.c [hunk 4]
```diff
@@ -773,6 +773,38 @@ static gboolean _scrollbar_changed(GtkWidget *widget,
...
+
+  // check each monitor
+  for(gint i = 0; i < n_monitors; i++)
+  {
+    GdkMonitor *monitor = gdk_display_get_monitor(display, i);
+    GdkRectangle geometry;
+    gdk_monitor_get_geometry(monitor, &geometry);
+
+    // Calculate effective area excluding border
+    gint eff_x = geometry.x + border;
```
Comment (TurboGit) [inline src/gui/gtk.c]: all consts

File: src/gui/gtk.c [hunk 5]
```diff
@@ -773,6 +773,38 @@ static gboolean _scrollbar_changed(GtkWidget *widget,
...
+    gint eff_y = geometry.y + border;
+    gint eff_width = geometry.width - (2 * border);
+    gint eff_height = geometry.height - (2 * border);
+
+    if(eff_width <= 0 || eff_height <= 0) continue;
+
+    // Check overlap
+    gboolean x_overlap = (saved_x < eff_x + eff_width) && (saved_x + window_width > eff_x);
```
Comment (TurboGit) [inline src/gui/gtk.c]: 2 consts

File: src/gui/gtk.c (hunk 2 above)
Comment (TurboGit) [reply src/gui/gtk.c]: And please one parameter per line.

Comment (MStraeten) [reply src/gui/gtk.c]: done

File: src/gui/gtk.c (hunk 4 above)
Comment (MStraeten) [reply src/gui/gtk.c]: done

File: src/gui/gtk.c (hunk 5 above)
Comment (MStraeten) [reply src/gui/gtk.c]: done

**Comment by TurboGit** [comment]
@MStraeten : Can you draft an entry for the release notes? TIA.

**Comment by TurboGit** [comment]
@MStraeten : Gentle reminder for the release note. TIA.

**Comment by MStraeten** [comment]
already merged:  https://github.com/darktable-org/darktable/commit/9815f1dec4781e81fbd5fea75527aac455bc2366

**Comment by TurboGit** [comment]
@MStraeten : Indeed, in the UI/UX section, didn't look in there :) Sorry for the noise, and thanks again for the contribution.
