### PR TITLE
highlights: Makes DT_IOP_HIGHLIGHTS_OPPOSED the default method.

### LINKED ISSUE #14050: Applying a style to images changes the HR module to clip
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
I nearly always apply a style just after importing. I have found that it changes the highlight reconstruction module to "clip highlights" (it used the default "inpaint opposed" before this change). Note that this style does not use the highlight reconstruction module. 
I think it happen only when the image was not opened in the darkroom before applying the style. 

**To Reproduce**
Not totally sure, but I think I found a way to reproduce: 
1. Create a style (I tested by creating a style with just a "local constrast" instance on)
2. Import some raw files (or discard the history from lighttable). Stay in the lighttable and do not go to the darkroom. 
3. Apply the style on _several_ files (the results is not systematic, see below) 
4. Go to darkroom and check the HR module: most of the images have "clip highlights" instead of "inpaint opposed". 

If I only apply the style to one image, it sometimes work correctly (it stays "inpaint opposed"). 
If I apply the style to several images, it sometimes works correctly for the first image only; but the other images are changed. 

**Expected behavior**
HR should keep the "inpaint opposed" reconstruction method. 

**Which commit introduced the error**
I do not know, but it is probably related to inpaint opposed being the new default since 4.2, I suppose. 

**Platform**
* darktable version : both 4.2.1 and master d96c6c5 
* OS                : Linux - kernel 5.15.0-48-generic
* Linux - Distro    : Linux Mint 21.1
* Memory            : 23.3 GB
* Graphics card     : NVIDIA Corporation TU116 [GeForce GTX 1660]
* Graphics driver   : nvidia-driver-510
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : unknown
* Desktop           : Cinnamon
* GTK+              : unknown
* gcc               : gcc12
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes** (4.2.1 and master d96c6c5)
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

### PR DESCRIPTION
**Pull request by TurboGit**
This part in the introspection circuitry was missing.

This second version keep compatibility with old edits by adding an highlights module with CLIP method when no highlights module found in the XMP.

Fixes #14050.

### CODE REVIEW

File: src/common/exif.cc
Comment (ralfbrown) [inline src/common/exif.cc:1]: Looks good, as far as I can see.  Did you intentionally omit the removal of the overrides in `gui_reset`?

Comment (TurboGit) [reply src/common/exif.cc:1]: The `gui_reset()` function is now removed.

File: src/common/exif.cc [hunk 1]
```diff
@@ -3568,6 +3570,54 @@ gboolean dt_exif_xmp_read(dt_image_t *img,
...
+      entry->blendop_version = 13;
+      entry->blendop_params = dt_exif_xmp_decode(no_blend,
+                                                 strlen(no_blend),
+                                                 &entry->blendop_params_len);
+      // we insert the module in second position, just after
+      // rawprepare. This is to ensure that history_end do include
+      // this module. Just adding one to history_end won't work if the
+      // history_end is not pointing to the last history item.
+      entry->num = 1;
+      entry->iop_order = -1;
```
Comment (jenshannoschwalm) [inline src/common/exif.cc:3615]: I have no image with an xmp version < 2 for "real testing" but could you explain the '-1' for iop_order here?

Comment (TurboGit) [reply src/common/exif.cc:3615]: Because we don't care about the value here. Remember the iop_order is not part of the module data. So in the XMP we either are using one of the default iop order (tag `darktable:iop_order_version` - `DT_IOP_ORDER_LEGACY`,  `DT_IOP_ORDER_V30`, `DT_IOP_ORDER_V30_JPG` and highlights is listed in there) or we have a custom iop_order and so a list into the xmp (`darktable:iop_order_list`) and again highlights is listed in there. This is true for xmp_version >= 4. For older version the iop order list is reconstructed as it was not yet implemented and follows in this case the order of the module back then.

Hope this clarifies the situation. Do you think I may still have a missing code path?

Comment (jenshannoschwalm) [reply src/common/exif.cc:3615]: Thanks, it does clear my mind. And - no ideas about any missing path.

**Comment by jenshannoschwalm** [comment]
congrats and thanks for fixing this.
