### PR TITLE
sharpen: fix memory overrun

### LINKED ISSUE #12198: use after poison in sharpen
commit a3245360c8ed700fa579414153bc242b9f112297

`AddressSanitizer: use-after-poison /home/martin/c/darktable/src/iop/sharpen.c:347`

it seems to be overflow in input buffer.

probably caused at 036f710fcbf2516e858404edfdc07414092acb40 by @ralfbrown 

`k <= end_row` is suspicious to me

**To Reproduce**

regenerate thumbnail in lighttable

### PR DESCRIPTION
**Pull request by ralfbrown**
Fix #12198 by eliminating the "use after poison".

Running all four integration tests involving the sharpen module gives same results (0035 fails, but so does master, with the same dE).

### CODE REVIEW

File: src/iop/sharpen.c [hunk 1]
```diff
@@ -337,7 +337,7 @@ void process(struct dt_iop_module_t *self, dt_dev_pixelpipe_iop_t *piece, const
     const size_t start_row = j-rad;
     const size_t end_row = j+rad;
     // do the bulk of the row four at a time
-    for(int i = 0; i < width; i += 4)
+    for(int i = 0; i < (width & ~3); i += 4)
```
Comment (rabauke) [inline src/iop/sharpen.c:340]: This is a rather problematic kind of integer operations mixing signed and unsigned arithmetic of integer types with different width. Imho, the loop and the loops that follow should be refactored to use loop variables of type `size_t`. E.g.,:
```
for(size_t i = 0; i < (width & ~3u); i += 4u)
```
or even
```
for(size_t i = 0; i < (width & ~(size)3); i += (size)4)
```
when one wants to be very verbose. Note that `width` is of type `size_t`.

**Review by TurboGit — APPROVED** [review]
Thanks!
