### PR TITLE
eliminate discrepancy in definition of DT_IOP_COLOR_ICC_LEN

### LINKED ISSUE #7368: discrepancy in definition of DT_IOP_COLOR_ICC_LEN
**Describe the bug**
The source contains multiple definitions of the symbol DT_IOP_COLOR_ICC_LEN, but they do not all have the same value.
colorin.c, colorout.c, and rgbcurve.c use a value of 512, while lightroom.c uses 100.  The latter matches the value used by legacy parameters in colorin and colorout, so it is likely that lightroom.c was never updated.

**To Reproduce**
See src/iop/colorin.c at line 60, src/iop/colorout.c at line 46, src/iop/rgbcurve.c at line 41, and src/develop/lightroom.c at line 196 (line numbers current as of Dec 19th).

### PR DESCRIPTION
**Pull request by johnny-bit**
fixes #7368

> The source contains multiple definitions of the symbol DT_IOP_COLOR_ICC_LEN, but they do not all have the same value.
colorin.c, colorout.c, and rgbcurve.c use a value of 512, while lightroom.c uses 100. The latter matches the value used by legacy parameters in colorin and colorout, so it is likely that lightroom.c was never updated.

This PR addresses the issue by ensuring single definition is in place

### CODE REVIEW

File: src/iop/colorin.c [hunk 1]
```diff
@@ -56,10 +56,6 @@
 
 #include <lcms2.h>
 
-// max iccprofile file name length
-// must be in synch with dt_colorspaces_color_profile_t
-#define DT_IOP_COLOR_ICC_LEN 512
```
Comment (TurboGit) [inline src/iop/colorin.c:61]: No please, not in any of the iop because they must be self sufficient and the value should not be changed without updating the legacy_params() routine. So changing it globally would break IOP having it recorded into their params.

**Review by TurboGit — CHANGES_REQUESTED** [review]
IOP should not depend on any global values.

File: src/iop/colorin.c (hunk 1 above)
Comment (johnny-bit) [reply src/iop/colorin.c:61]: OK... then it seems like "dedup" isn't really an option, just a bit of cleaning needed.

**Review by TurboGit — APPROVED** [review]
Looks good, thanks !
