### PR TITLE
try to cleanup import_session created dirs

### LINKED ISSUE #2584: Import parameter
**Describe the bug**
When importing photos create an empty folder on the date of import in addition to the import folder request.

**To Reproduce**
See the screenshots.

**Expected behavior**
For my session options I have the expected result except for this unnecessary and undesired empty folder.

**Screenshots**
dartable preferences
test import 1
test import 2
test import 3

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version darktable 2.6.2

**Additional context**
After several attempts I realized that what creates this empty folder and using the parameter $(EXIF_DAY) in "base directory naming pattern" or in "sub directory pattern" it does not create an empty folder however if you use it in "file naming pattern".

### PR DESCRIPTION
**Pull request by johnny-bit**
Honestly whole clean up dirs was supposed to be easy... It wasn't... This is the iteration I came up with and it didn't break anything for me and it didn't create changes across several files and probably didn't introduce any performance issues and doesn't leak memory all over the place...

Anyway possibly fixes #2584

### CODE REVIEW

File: src/common/import_session.c [hunk 1]
```diff
@@ -44,11 +44,17 @@ typedef struct dt_import_session_t
 static void _import_session_cleanup_filmroll(dt_import_session_t *self)
 {
   if(self->film == NULL) return;
-
   /* if current filmroll for session is empty, remove it */
-  /* TODO: check if dt_film_remove actual removes directories */
-  if(dt_film_is_empty(self->film->id)) dt_film_remove(self->film->id);
-
+  if(dt_film_is_empty(self->film->id)){
```
Comment (TurboGit) [inline src/common/import_session.c:48]: { should be on its own line below.

**Comment by TurboGit** [comment]
All good to me. Thanks.
