### PR TITLE
Expose tca_overwrite to gui, fixes #8039

### LINKED ISSUE #8039: Lens correction introduces chromatic aberration, resetting to the already set defaults removes them
**Describe the bug**
If I enable lens correction it adds chromatic abberations to the image. This obviously could be the fault of the profile, but it gets a little bit weirder: If I reset the TCA sliders with a double click the abbereations are gone. The sliders don't change from their default (1.00000), but the image changes.

**To Reproduce**
1. Open darktable, load image into darkroom
image
2. Enable lens correction (chromatic abberations appear)
image
3. Double click on the TCA red slider (chromatic abberations disappear, but the settings are still the same)
image

**Expected behavior**
No changes of of the image if the TCA red slider is reset to the already set default.

**Screenshots**
see above

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10
 - OpenCL enabled
 - NVidia 660Ti

**Additional context**
Example image to reproduce:
[image.zip](https://github.com/darktable-org/darktable/files/5898470/image.zip)

### PR DESCRIPTION
**Pull request by fvollmer**
As discussed in #8039 

Should be backward compatible, because `gboolean` is essentially an `int` (see `gtypes.h`)
```
typedef int    gint;
typedef gint   gboolean;
```

### CODE REVIEW

File: src/iop/lens.cc [hunk 1]
```diff
@@ -2098,8 +2098,14 @@ static void modflags_changed(GtkWidget *widget, gpointer user_data)
 void gui_changed(dt_iop_module_t *self, GtkWidget *w, void *previous)
 {
   dt_iop_lensfun_params_t *p = (dt_iop_lensfun_params_t *)self->params;
+  dt_iop_lensfun_gui_data_t *g = (dt_iop_lensfun_gui_data_t *)self->gui_data;
 
-  if(p->tca_r != 1.0 || p->tca_b != 1.0) p->tca_override = 1;
+  // enable tca override toggle if tca_b or tca_r is changed
+  if(w == g->tca_b || w == g->tca_r)
+  {
+    p->tca_override = 1;
```
Comment (TurboGit) [inline src/iop/lens.cc:2106]: As this is now a boolean we also want to clean the setting : 1 -> TRUE

Also please double check any other setting in the code as I suppose we have 0 or 1 instead of TRUE or FALSE.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Some minor changes.

**Review by TurboGit — CHANGES_REQUESTED** [review]
BTW, in #8039 we have:

`When the checkbox is unchecked, the sliders would be hidden and the settings from the lens profile would be used.`

This is not done there. You want to hide the proper tca setting in gui_update() I suppose. TIA.

File: src/iop/lens.cc (hunk 1 above)
Comment (fvollmer) [reply src/iop/lens.cc]: I think there aren't any other places where 0 or 1 was used. The latest commit removes this lines.

**Comment by fvollmer** [comment]
@TurboGit The sliders are now hidden if tca_overwrite isn't set.

**Comment by fvollmer** [comment]
I've seen that you assigned the milestone 3.6. I'm not sure how exactly your policy regarding minor releases looks like, but I would imagine that this could qualify as a bug fix and be a useful addition to the 3.4.1 release, because

 * the flag tca_overwrite was set by moving the tca sliders (kind of unexpected)
 * the user had no indicator to see whether tca_overwrite was set (the gui could look the same with two different outcomes)
 * the only way to reset tca_overwrite it was to reset the hole lens corrections module

**Comment by elstoc** [comment]
This seems like something that might be worth doing with other parameters in lens correction as well, allowing it to be better utilised with presets while still including lens- and camera-specific behaviour. 

For example, it should be possible to set the 'corrections' drop-down only and save, say, a "TCA only" preset. This isn't currently possible because as soon as you override any parameter in the module all others become hard-coded.

File: src/iop/lens.cc [hunk 2]
```diff
@@ -2098,8 +2098,13 @@ static void modflags_changed(GtkWidget *widget, gpointer user_data)
 void gui_changed(dt_iop_module_t *self, GtkWidget *w, void *previous)
 {
   dt_iop_lensfun_params_t *p = (dt_iop_lensfun_params_t *)self->params;
+  dt_iop_lensfun_gui_data_t *g = (dt_iop_lensfun_gui_data_t *)self->gui_data;
 
-  if(p->tca_r != 1.0 || p->tca_b != 1.0) p->tca_override = 1;
+  // update gui to show/hide tca sliders if tca_override was changed
+  if(w == g->tca_override)
+  {
+    gui_update(self);
```
Comment (dterrahe) [inline src/iop/lens.cc:2106]: The preferred pattern is to call gui_changed from gui_update (with NULL widget) if any gui elements need to be adjusted (made invisible etc) after a value change and make the adjustments here. For a simple example see globaltonemap (or others).

Comment (fvollmer) [reply src/iop/lens.cc]: Makes sense. I modified the code. It got slightly more complex, but should be fine now.

**Comment by fvollmer** [comment]
Thanks for the feedback so far. I adjusted the code :)

@elstoc In my opionion this is outside the scope of this PR. My primary goal is to fix #8039.

**Comment by elstoc** [comment]
> In my opionion this is outside the scope of this PR

Agreed. Actually this is already covered by #7017. I just mentioned it because it was delivering something similar.

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!
