### PR TITLE
collect + tagging: fix tags case issues + uncategorized entry

### LINKED ISSUE #7155: Tags with difference in case (upper and lower) are treated as the same when displaying images but show up differently in the collection filtered by tag
Current master 3.3.0+1942~g67e9d442b

While tagging, I incorrectly created a tag name with different case (**i**nspired... vs **I**nspired...).

So, images+xmp with the uppercase **I**nspired were imported into DT which already had a tag with lowercase **i**nspired

While tagging I cannot select the uppercase **I**nspired (not that I want to select it but it's not available for selection when I do a ctrl+t)

image

I see that the collect images with a tag filter shows both (**i**nspired and **I**nspired) of them , but the images being displayed by selecting each of those tags are the sum of both the tags (65 images with tag **i**nspired and 3 images with tag **I**nspired, displays 68 images).

image

The images displayed should be consistent with what was clicked in the collection->tag
If DT needs to be case insensitive then tags should be normalized to being case insensitive and imports should detect changed case and fix it to be alike.
Ctrl+T currently does not display the 2 cases for a tag present, if it needs to be case insensitive then both all should be displayed.

I also don't understand when tags show up under uncategorized as well as a separate node.
image
 

Not here to force a design decision, just stating observations, but whatever design decision is taken, do it consistently.

### PR DESCRIPTION
**Pull request by phweyland**
Fixes #7155

- does~~n't~~ consider different case strings as different tags (display)
- fixes the uncategorized tags issue (regression because the code was assuming a reverse order for tags). ~~However I guess the fix will not work if the user select reverse order.~~

~~BTW, where does the user set reverse order ? ~~

~~Another weakness of this fix: usage of deprecated g_strcasecmp().~~ Nope, g_ascii_strcasecmp is used, sorry.

@chill could you check if that fixes your issues ?
note: completion will show you the first option (in case of multiple cases). If you want to cleanup the case, you can easily see the differences in tag listview and then fix them with rename path in treeview (or edit tag if it's a leave).

~~If that works I can pursue with g_strcasecmp() replacement.~~
Thanks in advance

### CODE REVIEW

**Comment by TurboGit** [comment]
> BTW, where does the user set reverse order ?

Top bar filter in lighttable.

File: src/libs/collect.c [hunk 1]
```diff
@@ -1193,6 +1196,8 @@ static void tree_view(dt_lib_collect_rule_t *dr)
                                 "   ON tagid = tag_id"
                                 " WHERE %s"
                                 " GROUP BY name,tag_id", where_ext);
+        // case insensitive for tags
+        string_compare = g_ascii_strcasecmp;
```
Comment (TurboGit) [inline src/libs/collect.c:1200]: what about multi-bytes utf8 characters ?

File: src/libs/tagging.c [hunk 2]
```diff
@@ -363,7 +363,7 @@ static void _init_treeview(dt_lib_module_t *self, const int which)
           if(last_tokens)
           {
             while(tokens[common_length] && last_tokens[common_length] &&
-                  !g_strcmp0(tokens[common_length], last_tokens[common_length]))
+                  !g_ascii_strcasecmp(tokens[common_length], last_tokens[common_length]))
```
Comment (TurboGit) [inline src/libs/tagging.c:366]: likewise

**Review by TurboGit — COMMENTED** [review]
This will probably fail for languages using many multi-bytes characters (Russian, Chinese, ...).

**Comment by phweyland** [comment]
> > BTW, where does the user set reverse order ?
> 
> Top bar filter in lighttable.

Humm, this one is ok. That's the order of displayed images. 
I was confused about "sort collection recent to older" which has no effect on tags. Sorry for the noise.

File: src/libs/collect.c (hunk 1 above)
Comment (phweyland) [reply src/libs/collect.c:1200]: > what about multi-bytes utf8 character

I'll look at this. This is new for me, if you have any tip or reference, this is welcome.

Comment (TurboGit) [reply src/libs/collect.c:1200]: I don't have solution but the documentation here make this clear I think:
https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-strcasecmp

Comment (phweyland) [reply src/libs/collect.c:1200]: Thanks. I've made sure that the comparison is made on utf8.

**Comment by phweyland** [comment]
That's still work for me, even selecting russian language but I've no russian tags to better test...

**Comment by chhil** [comment]
@phweyland , is this in master or I need to bring specific files over to test this?

**Comment by phweyland** [comment]
> @phweyland , is this in master or I need to bring specific files over to test this?

It is not in master. In that situation I clone the personal repository origin of the PR. But @TurboGit may have a better method. Would be great if I can learn something...

**Comment by phweyland** [comment]
> > @phweyland , is this in master or I need to bring specific files over to test this?
> 
> It is not in master. In that situation I clone the personal repository origin of the PR. But @TurboGit may have a better method. Would be great if I can learn something...

This seems to be a better way:
https://medium.com/google-cloud/pull-push-to-someone-elses-upstream-github-pr-6073ae5005e7

**Comment by phweyland** [comment]
> > > @phweyland , is this in master or I need to bring specific files over to test this?
> > 
> > 
> > It is not in master. In that situation I clone the personal repository origin of the PR. But @TurboGit may have a better method. Would be great if I can learn something...
> 
> This seems to be a better way:
> https://medium.com/google-cloud/pull-push-to-someone-elses-upstream-github-pr-6073ae5005e7

The command:
`git fetch https://github.com/darktable-org/darktable pull/7201/head:tag_fix2`
creates a branch called tag_fix2 with the related changes.

**Comment by chhil** [comment]
I did 

```git fetch https://github.com/darktable-org/darktable pull/7201/head:tag-fix2```

Then did dit branch to see all the branches available, saw the branches ->  master and tag-fix2.

Did a git switch to tag-fix2 and am building it now. I am hoping I am building the correct branch ;)

**Comment by chhil** [comment]
image


I no longer see the upper case Inspired (top riht collections).
I see upper case Inspired in the tagging panel on the right with count of 3 images.

The numbers still don't add up.

The ctrl+t , and then typing upper case **I** does show the all cases of inspired..

**Comment by phweyland** [comment]
Could you make a snapshot of tagging module in listview showing `inspiredstreerphoto` tags ?

**Comment by phweyland** [comment]
> The ctrl+t , and then typing upper case **I** does show the all cases of inspired..

OK, that's fine. Normally for leave you should have only one case. For the path, you can have several cases.

**Comment by chhil** [comment]
image


As a reminder, the 3 upper case Inspired were from importing folders that were previously edited in older versions of DT (older in the sense still 3.3-xxx versions of master builds that I do daily).

**Comment by phweyland** [comment]
I would need the full beginning of the listview ordered by name.

Could also help if you can share the data.db file (if you can).

**Comment by chhil** [comment]
Remove the txt extension...
[data.db.txt](https://github.com/darktable-org/darktable/files/5648839/data.db.txt)

**Comment by chhil** [comment]
image
image

**Comment by phweyland** [comment]
OK. Thanks for your answers. I think I have a lead. I'll look at it.

**Comment by TurboGit** [comment]
> The command:
> `git fetch https://github.com/darktable-org/darktable pull/7201/head:tag-fix2`
> creates a branch called tag-fix2 with the related changes.

I'm a bit late, that's one of the way to do so. You can either move to this branch indeed or:

```
$ git checkout master
$ git merge head:tag-fix2
```

So that you can have multiple PR merged into your master for testing purpose. When done you can revert your master to the current state in upstream:

`$ git reset --hard upstream/master `

**Comment by phweyland** [comment]
I'm back on the first logic (I've abandoned on wrong assumption).
So now every different case should be visible everywhere.
@chhil, please could check again ? Thanks in advance.

**Comment by chhil** [comment]
Thanks for working on this.

Tested your branch.
Views show correct number of tag names/counts.

However, I don't understand why the uncategorized exists and has leaves in that tree?
image

Maybe its related to tags that are used while importing images and selecting import option->check apply metadata on import->specify tag

**Comment by phweyland** [comment]
> However, I don't understand why the uncategorized exists and has leaves in that tree?

This one (with I, in your listview) has no child. So it is seen as uncategorized. So that's correct.

**Comment by chhil** [comment]
From the documentation https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/tagging/

"Tags provide a means of adding information to images using a keyword dictionary. You can also manage tags as a hierarchical tree, which can be useful when their number becomes large. Only tags at the leaves of the tree add information to an image – parent tags simply serve as categories and are used to organise the leaf tags. For example, in the “color|white” tag, “color” is a category for the “white” tag."

I am fine with the explanation 
> This one (with I, in your listview) has no child. So it is seen as uncategorized. So that's correct.

A category without a tag is put under uncategorized just seems a bit off.

**Comment by phweyland** [comment]
> > 
> 
> A category without a tag is put under uncategorized just seems a bit off.

I agree that "uncategorized" is not a great feature, especially when I have catergories on several level. I agree also that a single level tag is also a leave and may not be a category. But this feature has been there before I've entered into this. And as you know it is easier to add a new feature than changing an old one...

On the other hand this feature doesn't hurt too much (I know where to find my one level tags). 
I can suggest to add a configuration point on this to not have this uncategorized entry. For 3.4.1 ?

**Comment by phweyland** [comment]
@TurboGit , If @chhil is ok, it's good for me too.

These fixes do not modify the way to create/modify tags. Just changes the display. So it should not be risky.

On the other hand, I would have preferred to have case insensitive tags, because far more meaning oriented.
But for that I would need to change the behavior of the data.tags table to not accept different cases for the same string. That's where my previous fix failed, as shown by Chhil. I don't know if would really succeed but in any case that can be for a future version too.

**Comment by phweyland** [comment]
And... Thanks again to you @chhil for testing !

**Comment by chhil** [comment]
I am good with the changes and can be merged into master. 

As a future enhancement maybe change uncategorised to category and dispoaying  all first level/root of tags.

**Review by TurboGit — APPROVED** [review]
Works for me! Thanks.

**Comment by phweyland** [comment]
> what about multi-bytes utf8 characters ?

I've made some positive tests adding collate=NOCASE for names in tags table. Unfortunately, unlike g_utf8 routines, SQLITE NOCASE works only with the 26 English letters, ignoring other utf8 letters, like é and É.
To make it work, we would need to add ICU (International Components for Unicode) to SQLite. Maybe not so simple...
