### PR TITLE
mipmap_cache: respect conf request to always use embedded thumbnail

### LINKED ISSUE #19944: lighttable: preview of unedited image processes raw file on 4K display with fractional scaling
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

In lighttable view, when displaying a fullscreen "preview" of a raw file, darktable will default to using the embedded JPEG rather than the full pixelpipe processed output. But in the case of a 4K display with fraction scaling of 1.5, this goes awry. The embedded JPEG is initially displayed, as usual. But then the "working..." overlay appears, and the image changes to the file as processed by the default pixelpipe.

It is the default and a helpful behavior to use the embedded JPEG rather than the default pixelpipe. This allows for rapidly looking through multiple images. The CPU/GPU doesn't max out, switching images is fast. The images does not change its appearance in the shift from embedded JPEG to processed raw. The embedded JPEG is often more legible than the image as processed by the default pixelpipe. 

### Steps to reproduce

1. Use a computer with a 4K display. Configure display scaling to 150%.
2. Start darktable with a fresh config
3. Maximize the window to fill the display.
4. Import images into a darktable with no edits. For best results use large (e.g. 100 MP) images, so that pixelpipe lag is apparent.
5. In lighttable view, mouse over the first image
6. Type `F`
7. You should see the embedded JPEG, then "working...", then a few moments later the images as processed by the pixelpipe.

### Expected behavior

darktable should just simply show the embedded JPEG so long as config `plugins/lighttable/thumbnail_raw_min_level` has default value of `never`

### Logfile | Screenshot | Screencast

Log excerpt with `-d lighttable -d control -d cache -d dev -d imageio -d pipe`

Note that system ppd is read as 2.0, mip is 999999999x999999999, `dt_image_get_final_size` is called, and full pixelpipe runs.
```
     5.8250 [dt_get_system_gui_ppd] system ppd is 2.000000
     5.8250 [screen resolution] setting the screen resolution to 96.000000 dpi 
     5.8585 [add_job]	00  load image 2 mip 6 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     5.8585 [run_job+]	05  load image 2 mip 6 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     5.8585 [mipmap_cache] thumbs fill 57.16/3981.00 MB (1.44%)
     5.8585 [mipmap_cache] float fill 0/16 slots (0.00%)
     5.8585 [mipmap_cache] full  fill 0/16 slots (0.00%)
     5.8585 [mipmap_cache] level | near match | miss | stand-in | fetches | total rq
     5.8586 [mipmap_cache] thumb |  70.83% |  35.42% | 100.00%  | 100.00% | 100.00%
     5.8586 [mipmap_cache] float |   -nan% |   -nan% |   0.00%  |   0.00% |   0.00%
     5.8586 [mipmap_cache] full  |   -nan% |   -nan% |   0.00%  |   0.00% |   0.00%


     5.9159 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     5.9159 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     5.9159 [run_job+]	07  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     5.9159 [dt_image_get_final_size] calculate it for ID=1
     5.9162 [rawspeed_open] extensions list to ignore: `cr3'
     5.9292 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     5.9476 [mipmap_cache] generate mip 6 for ID=2 from embedded jpeg
     6.1366 get dimensions                [thumbnail]                                        (0/0)  6384x4182 sc=1.000; ID=1
     6.1367 modified roi OUT              [thumbnail]      rawprepare              100       (0/0)  6384x4182 sc=1.000 -->       (0/0)  6240x4160 sc=1.000; 
     6.1377 [image_cache_write_release] from `get final size', imgid=1 took 0.000s
     6.1377 wait time 0.221800s
     6.1378 [run_job-]	05  load image 2 mip 6 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.1379 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.1379 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.1379 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.1489 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.2069 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.2069 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.2069 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.2171 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.2522 [dt_imageio_export_with_flags]  modules: rawprepare temperature highlights demosaic exposure colorin channelmixerrgb sigmoid colorout gamma
     6.2522 get dimensions                [thumbnail]                                        (0/0)  6384x4182 sc=1.000; ID=1
     6.2522 modified roi OUT              [thumbnail]      rawprepare              100       (0/0)  6384x4182 sc=1.000 -->       (0/0)  6240x4160 sc=1.000; 
     6.2523 [dt_imageio_export] thumbnail imgid 1, 6240x4160 --> 6240x4160 (scale=1.0000, maxscale=1.0000). upscale=no, hq=no
     6.2523 pipe starting             CL0 [thumbnail]                                        (0/0)  6240x4160 sc=1.000; '_DSF5237.RAF' ID=1, nvidiacudanvidiageforcertx3080laptopgpu 0MB
     6.2523 modified roi IN               [thumbnail]      rawprepare              100       (0/0)  6240x4160 sc=1.000 -->       (0/0)  6384x4182 sc=1.000; ID=1
     6.2523 pipe data: full               [thumbnail]                                        (0/0)  6384x4182 sc=1.000; 
     6.2616 process                   CL0 [thumbnail]      rawprepare              100       (0/0)  6384x4182 sc=1.000 -->       (0/0)  6240x4160 sc=1.000; IOP_CS_RAW 210.6MB
     6.2629 process                   CL0 [thumbnail]      temperature             300       (0/0)  6240x4160 sc=1.000; IOP_CS_RAW 207.7MB
     6.2659 process                   CL0 [thumbnail]      highlights              500       (0/0)  6240x4160 sc=1.000; IOP_CS_RAW 259.6MB
     6.2718 opposed chroma            CL0 [thumbnail]      highlights              500       (0/0)  6240x4160 sc=1.000; RGB 0.0000 0.0260 0.0000
     6.2740 process                   CL0 [thumbnail]      demosaic                900       (0/0)  6240x4160 sc=1.000; IOP_CS_RAW -> IOP_CS_RGB 830.7MB
     6.2777 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.2777 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.2777 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.2875 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.3454 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.3454 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.3454 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.3551 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.4107 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.4108 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.4108 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.4212 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.4774 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.4774 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.4774 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.4855 process                   CL0 [thumbnail]      exposure               2500       (0/0)  6240x4160 sc=1.000; IOP_CS_RGB 830.7MB
     6.4877 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.4921 process                   CL0 [thumbnail]      colorin                3300       (0/0)  6240x4160 sc=1.000; IOP_CS_RGB -> IOP_CS_LAB 830.7MB
     6.4921 coeff correction          CL0 [thumbnail]      colorin                3300       (0/0)  6240x4160 sc=1.000; `standard color matrix' 2.076(*1.128) 1.000(*1.000) 1.471(*0.838)
     6.5062 transform colorspace      CL0 [thumbnail]      channelmixerrgb        3400       (0/0)  6240x4160 sc=1.000; IOP_CS_LAB -> IOP_CS_RGB `linear Rec2020 RGB'
     6.5178 process                   CL0 [thumbnail]      channelmixerrgb        3400       (0/0)  6240x4160 sc=1.000; IOP_CS_RGB 830.7MB
     6.5266 process                   CL0 [thumbnail]      sigmoid                5800       (0/0)  6240x4160 sc=1.000; IOP_CS_RGB 830.7MB
     6.5352 transform colorspace      CL0 [thumbnail]      colorout               8500       (0/0)  6240x4160 sc=1.000; IOP_CS_RGB -> IOP_CS_LAB `linear Rec2020 RGB'
     6.5469 process                   CL0 [thumbnail]      colorout               8500       (0/0)  6240x4160 sc=1.000; IOP_CS_LAB -> IOP_CS_RGB 830.7MB
     6.5502 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.5502 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.5502 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.5614 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.5654 exif_xmp_read_data: dt_exif_xmp_write. imgid=1, hist=11, took 0.001s
     6.6396 [add_job]	00  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 0
     6.6396 [add_job]	-1 found job already in scheduled: load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.6396 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 1350x900
     6.6443 process                   CPU [thumbnail]      gamma                  9200       (0/0)  6240x4160 sc=1.000; IOP_CS_RGB 831MB
     6.6617 dt_view_image_get_surface  ID=1 with surface problem DT_VIEW_SURFACE_SMALLER
     6.7061 cache report                  [thumbnail]                                   2 lines (important=0, used=0, invalid=0). Using 815MB, limit=0MB. Hits/run=0.00. Hits/test=0.000
     6.7062 pipe finished             CL0 [thumbnail]                                        (0/0)  6240x4160 sc=1.000; '_DSF5237.RAF' ID=1
     6.7333 [mipmap_cache] generate mip 8 for ID=1 from scratch
     6.7333 [mipmap init 8] export ID=1 finished (sizes 999999999 999999999 => 6240 4160)
     6.7333 [run_job-]	07  load image 1 mip 8 | queue: DT_JOB_QUEUE_SYSTEM_FG | priority: 4
     6.7429 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 6240x4160
     7.1114 dt_view_image_get_surface  id 1, dots 5354x2740 -> mip 999999999x999999999, found 6240x4160
```

### Commit

I could reproduce this as far back as 1bef706ac983865c6283adb1f80e6c18d850182c

### Where did you obtain darktable from?

self compiled

### darktable version

5.1.0+1989~gebb7ef77f3

### What OS are you using?

Linux

### What is the version of your OS?

Debian forky/sid

### Describe your system

Wayland, GTK 2.24.33, 32GB ram

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GeForce RTX 3080 Mobile, 8GB, nvidia driver 550.163.01

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

With GTK 3 and Wayland, `dt_get_system_gui_ppd()` uses `gtk_widget_get_scale_factor()` to return the scale factor. This rounds up to the nearest integer, hence for 1.5 scaling, we receive a scaling factor of 2.

If the window size is reported as, for example, 2677x1370, at 1.5 scaling on a 4K display, this might reference a pixel size of 4016x2055. But as GTK 3 reports x2 scaling, darktable things it needs to to retrieve a 5354x2740 mipmap.

Unfortunately, `dt_mipmap_caache_init()` sets the largest specific mipmap size to 5120x3200 (`DT_MIPMAP_7`). So we retrieve the special `DT_MIPMAP_8` which is full resolution of the image. This somehow triggers the full pixelpipe, maybe because of the call to `dt_image_get_final_size()` in `_mipmap_cache_allocate_dynamic()`.

One fix could be to create another mipmap level for 6K images, or change the dimensions of mip7 to 6K. Either of these would make the cache inconsistent (in a minor way) for existing users, unless there was an upgrade path.

Alternately, with GTK 4 (see #19448), we should be able to use `gtk_widget_get_scale_factor()`, which returns the actual fractional scaling. This could help this.

Also: When I was looking at the mipmap code, it's clear that `DT_MIPMAP_8` is "magic", in that some code tests specifically for that case. It might be helpful to give it an alias, e.g. `DT_MIPMAP_MAX`, to make code less brittle in the event that new mipmap levels are added.

### PR DESCRIPTION
**Pull request by dtorop**
When conf `plugins/lighttable/thumbnail_raw_min_level` is `never`, always use the thumbnail embedded in a raw, even when it is lower resolution the requested mipmap.

This fixes a problem particularly visible on high dpi screens with fractional scaling: Due to limitations of GTK3 (which always returns a whole-number from gtk_widget_get_scale_factor), we generate mipmaps larger than the physical display resolution. These can easily exceed the resolution of the embedded JPEG. This problem is more visible now that darktable can run on Wayland, which allows fractional scaling.

Fixes #19944.

### CODE REVIEW

**Comment by wpferguson** [comment]
Hi @dtorop, it's nice to see your around again :-)

I think this may mess up culling (at least for me).  I'll test and see what happens.

**Comment by dtorop** [comment]
@wpferguson: Thanks likewise!

RE culling: I'm testing now. I think there's a minor problem in `_thumbs_prefetch()` where it also doesn't take into account PPD, so it prefetches a lower-resolution mip, then on display fetches the correct resolution mip. It's quick to fix, I may add it to this PR as it is related. But please let me know if there's another problem which you are seeing.

**Comment by dtorop** [comment]
Added fix for respecting display scaling in thumbnail prefetch. This is another problem visible when using display scaling.

@wpferguson: Does this relate to the problem you are seeing in culling, though?

**Comment by wpferguson** [comment]
My situation

- I have `use raw instead of jpeg from size` set to never and it's been that way for years
- In Aug of 2021 I added a function to Lua to generate cache
- At that time I had a 1080p and a 2K screen
- When I generated cache, the thumbnail came from the embedded jpeg, but the full size preview was built from raw
- I now have an R7 and a 4K screen.  The largest embedded preview is cache size 3. 
- For the 4K screen I need size 3 for the thumbtable and size 6 for the full preview, so 3 is the embedded and 6 is built from raw

With this patch:

- the `use raw instead of jpeg from size` is actually respected
- now size 6 is scaled up from the jpeg preview
- size 8 is scaled up

My concern is that user's are used to this behavior, since it's been this way for years.  Using a scaled up JPG for culling is difficult since you can't tell if it's in focus or not and doing a full size preview to check focus is useless since again it's scaled way up.

I can solve my problem by setting `use raw instead of jpeg from size` to 1080p (size 4) and everything works like it currently works in master and before.

CAVEAT: If your embedded JPG is larger than 4K, I guess it's a moot point.

So `use raw instead of jpeg from size` works for maybe the first time ever, but we probably need to do a lot of advertising before we release it or deal with some issues that arise because of it.

**Comment by ralfbrown** [comment]
Should we tag this with `default-behavior-change`?

**Comment by dtorop** [comment]
> Should we tag this with `default-behavior-change`?

Probably. It makes the default behavior match the behavior as documented by the config option. But before dt would never upscale a thumb if it could downscale a raw instead, and I understand from @wpferguson that this is a behavior which some (many?) users would prefer.

I'm trying to see if dt is a bit more laggy with this PR, when on a 4K display and moving through image previews. I wonder if upscaling a mip6 via Cairo is faster than working with a mip8.

**Comment by dtorop** [comment]
Maybe good to think about ideal behavior rather than extant code vs. documentation. Some useful behaviors:

1. Small thumbs use JPEGs for speed, fullscreen previews generated from raw (or very hires embedded jpeg) to allow for checking focus.
2. All thumbs and fullscreen previews use embedded JPEG, for sake of speed and because SOC JPEG can be nicer than unmodified pixelpipe on some cameras.
3. All thumbs and fullscreen previews generated from pixelpipe, because user either has a nice Lua script to do this offline, or wants consistency between thumbs & previews and has a well set up default pixelpipe.

Are there other scenarios? The current `use raw instead of jpeg from size` config can accommodate all of these, but it's a bit fiddly. Would a simple config giving these three choices be more helpful, and dt behind the scenes would then, if necessary, determine the mipmap cutoff to handle thumbs vs previews? But what happens then when a user switches monitors? And are dt users so competent that the current system is fine? Regardless, this may be beyond scope of this PR.

**Comment by wpferguson** [comment]
> But what happens then when a user switches monitors?

I had this when my laptop was 1080p and my external monitor was 2k.  I ended up generating cache for both.

> 'm trying to see if dt is a bit more laggy with this PR

My script spits out timing so when set to never 1171 size 3 (pull the embedded jpeg) took 22 seconds, and it took 44 seconds to upscale the 1171 images to size 6.  I did cull with them and sometimes displayed full size (upscaled from size 6) and I didn't notice any lag, certainly nothing like building from raw.

For reference, building size 6 cache from raw took 470 seconds for 1171 images.

EDIT:

> that this is a behavior which some (many?) users would prefer

I'm not sure they prefer it, but I'm worried they might expect it and be surprised with the change.

EDIT 2:

> Lua script to do this offline

Actually it's online and runs from a post-import-film trigger so that every time I import the thumbtable cache gets built quickly so I can scroll through the thumbtable and get an idea of what I have while the culling cache is being built.  Once it's done I can cull at full speed.  I don't zoom to full size enough to make worthwhile to build cache for it.

**Comment by dtorop** [comment]
>  I didn't notice any lag, certainly nothing like building from raw

Good to know about timings. I just tried this PR on a 1920x1080 screen, and it's quite responsive -- but so was dt without this PR on that setup.

> I'm not sure they prefer it, but I'm worried they might expect it and be surprised with the change.

Yes, I'm not sure either. In my own case, I prefer using embedded JPEG when culling images, even at fullscreen. I can view images without waiting for pixelpipe, and the embedded JPEGs are decent quality. I believe that the switch to Wayland and its handling of fractional scaling caused a regression for me. On a 4K display, culling images became laggy, as dt was busily running the pixelpipe in the background.

It seems like there's a balance, where some users want low latency and some want highest resolution, and ideally dt could accommodate both (with a user-visible conf option).

I did notice that with this PR, using ctrl-scroll or ctrl-middle-click to zoom in an image has a change in behavior with default config. Before, dt would run the full pixelpipe at 100% and (after a lag) show 1:1 the detail in the raw file (albeit with the image looking different than a zoomed out view, due to running the pixelpipe). Now, dt will generate a mip8 from the embedded JPEG, and zoom in on that. For me, I can get decent sharpness information even from the embedded JPEG at 100% (or switch to darkroom and see the raw), and appreciate that it is faster not to run the pixelpipe. Others may have a different experience/preference!

**Comment by ralfbrown** [comment]
Yeah, the main divide is going to be whether the camera's largest embedded preview is anywhere near the monitor's resolution, e.g 4K monitor and a Sony camera from when they didn't embed anything bigger than 1920x1080 (some really old cameras from various manufacturers only had 640x480!)

Maybe we could add an "auto" option to "use raw from size", where Auto selects what amounts to the old behavior: a cutoff of the monitor's linear pixel size and no upscaling from mipmaps.

**Comment by dtorop** [comment]
To document the changed behavior for the conf setting `use raw instead of jpeg from size` aka `plugins/lighttable/thumbnail_raw_min_level`:

### Prior Behavior

| `thumbnail_raw_min_level` | requested thumbnail resolution | generate |
| --- | --- | --- |
| `never` | > embedded JPEG | default pixelpipe |
|  |  < embedded JPEG | embedded JPEG |
| `small`...`5K` | > `thumbnail_hq_min_level` or > embedded JPEG | default pixelpipe |
| | _otherwise_ | embedded JPEG |
| `always` | _any_ | default pixelpipe |

### Behavior with this PR

Changed behavior is **_emphasized_**.

| `thumbnail_raw_min_level` | requested thumbnail resolution | generate |
| --- | --- | --- |
|  `never` | > embedded JPEG | **_embedded JPEG, upscaled_** |
| |  < embedded JPEG | embedded JPEG |
| `small`...`5K` | > `thumbnail_hq_min_level` or > embedded JPEG | default pixelpipe |
| | _otherwise_ | embedded JPEG |
| `always` | _any_ | default pixelpipe |

### Recommendation

If you previously used the `never` setting and prefer its prior behavior:

- Set `use raw instead of jpeg from size` to just smaller than the resolution of your screen to always run the pixelpipe for fullscreen previews.
- Set `use raw instead of jpeg from size` to just smaller than the resolution of the embedded JPEG of your camera(s) (could range from `1080p` to `5K`) to run the pixelpipe rather than upscaling JPEGs.

If you previously used the `never` setting and never want to see processed raw files of unaltered images, leave the setting at `never`. In this case, when you zoom an image to 100%, you will now see the embedded JPEG at 100%, rather than the pixelpipe processed image.

### Query

Would it be helpful to add `> embedded thumb` to `thumbnail_hq_min_level`, and make this replicate the prior behavior of `never`?

**Comment by dtorop** [comment]
> Maybe we could add an "auto" option to "use raw from size", where Auto selects what amounts to the old behavior: a cutoff of the monitor's linear pixel size and no upscaling from mipmaps.

Overlapping comments! But yes, that is exactly it! And `auto` is better then `> embedded thumb`. I will put in a commit to this PR to do this.

**Comment by dtorop** [comment]
> Maybe we could add an "auto" option to "use raw from size", where Auto selects what amounts to the old behavior: a cutoff of the monitor's linear pixel size and no upscaling from mipmaps.

A place this gets a bit tricky is when the user changes the conf value from/to `auto`. In `thumtable.c:_thumbs_ask_for_discard()`, the code will need to throw away cached thumbnails based on the resolution of the embedded JPEG of the image. This seems finicky. A quick and ugly solution (assuming an `auto` setting to retain prior behavior is important) would be to throw away all cached thumbnails when switching to/from auto.

**Comment by jenshannoschwalm** [comment]
Just mentioning this, when using either the lua script or dt internal backgriund update thumbs we currently already have thumbs in requested size processed after a short while. If i add a day's shots i just have an espresso and all is good and fast for culling. 

But "never is never" :-) Dan, nice having you around again !

**Comment by dtorop** [comment]
@jenshannoschwalm Thank you!

For my workflow, I tend to ignore the small thumbs and go through each image via fullscreen preview, and give each image a second or two to rate it. So I'm sensitive to when those are slow to load, hence a true `never` mode sounds good to me.

I'm trying to wrap my head around how to discard thumbs in `auto` vs. `never` vs. particular mipmap modes. Once I do, one more commit on the way... Looking at the code I also notice that DT_MIPMIP_8 is used as a synonym for highest-resolution 8 bit mipmap. There probably should be a different constant (set to be DT_MIPMAP_8) to express that, in case there are more mipmaps eventually.

**Comment by TurboGit** [comment]
@dtorop : Nice to see you again :) I also voice my approval for "never is never". I've not looked at the actual rendering when upscaling, but if a user want this then the option is there.

**Comment by dtorop** [comment]
@TurboGit: Thank you!

Yes "never is never" seems like the right formulation.

I added a commit to support an `auto` option. As mentioned in the commit notes, the updated code to discard mipmaps on pref change uses a heuristic which errs on discarding too many mipmaps when switching between `auto`/`never`. I figure this is better than altering the mipmap code to tag mipmaps with metadata to identify which to discard. Switching between `auto`/`never` is an edge case of a conf which is probably rarely changed.

Also added a release note to document this. And a small bugfix where the code skipped discarding cached mip8 files during a conf switch.

File: src/dtgtk/thumbtable.c [hunk 1]
```diff
@@ -1717,12 +1721,21 @@ static void _thumbs_ask_for_discard(dt_thumbtable_t *table)
     if(dt_gui_show_yes_no_dialog(_("cached thumbnails invalidation"), "",
                                  "%s", txt))
     {
+      // switching between auto/never modes
+      if (max_level == DT_MIPMAP_NONE && min_level == DT_MIPMAP_8)
+      {
+        // err on side of discarding too many thumbnails: a quick
+        // survey of vintage raw files shows a lowest res embedded
+        // JPEG of 1616x1080 (found in 2011 & 2014 Sony)
```
Comment (ralfbrown) [inline src/dtgtk/thumbtable.c]: Some really old Canon PowerShot and Ricoh GR models in the RPU collection have 480p thumbnails.

**Comment by dtorop** [comment]
Updated this PR to make it merge cleanly and to simplify commit record.

**Comment by TurboGit** [comment]
This needs conflict resolution. TIA.

**Comment by dtorop** [comment]
> This needs conflict resolution. TIA.

Done! Thank you for looking at this!

**Comment by dtorop** [comment]
@TurboGit: This PR already has a release note, so it should be possible to remove the "release notes: pending" tag. I don't see a way to do from here...
