### PR TITLE
Fix demosaicer/temperature related glitches

### LINKED ISSUE #12474: Image is getting "greenish" when switching demosaic method
When switching the demosaic in this order:
1) to passthrough
2) to photosite
3) to VNG or PPG 
the main image is getting "greenish", preview is OK however.

darktable : 4.0.0 and 4.1.0+338
OS: Win 10
opencl: deactivated

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
There are currently two problems around related to the "passthru" demosaicers
1. Some people want to use the white balance temperature module to change the coeffs even using standard sensors in the passthru monochrome mode. This was not possible as it was automatically disabled for all monochromes. So temperature modules can be used again.
2. As described in #12474 the color coeffs were not reset correctly.

As we might use the white balance and color calibration also for monochromes we will at least disable the module error messages here.

While re-reading the demosaic source some code cleanups were done plus two minor bugs fixed

Fixes #12474

### CODE REVIEW

File: src/iop/demosaic.c [hunk 1]
```diff
@@ -5824,6 +5831,12 @@ void gui_init(struct dt_iop_module_t *self)
   gtk_stack_add_named(GTK_STACK(self->widget), box_raw, "raw");
 }
 
+#undef DT_DEMOSAIC_XTRANS
```
Comment (dterrahe) [inline src/iop/demosaic.c:5834]: Not really sure what's the rationale for #undefing any macros at the end of a source file, when there's no risk of accidental usage or clashes later on?

Comment (jenshannoschwalm) [reply src/iop/demosaic.c:5834]: I guess tha'ts a memory leftover from my work in FORTH preprocessor stuff. I guess i can remove the #undefs?

**Review by TurboGit — APPROVED** [review]
Works for me, thanks!
