### PR TITLE
request natural instead of fixed side panel width

### LINKED ISSUE #12855: default layout not very attractive
Now that the panels don't have a minimal size the default layout when dt starts from the first time is not really attractive. For the first contact with dt I don't think this is good... See what I get:

image

None of the module labels on the right are readable. I think we should ensure a minimal default when starting the first time.

@dterrahe : One for you :)

### PR DESCRIPTION
**Pull request by dterrahe**
fixes #12855, alternative to #12856

The side panels now request a customizable _natural_ size, rather than using `gtk_widget_set_size_request` to request a _fixed_ size. This means that if there is not enough space in the window, the panels will get scaled down to fit. This _should_ resolve any issues from opening on a lower res screen than where the panel widths were set or opening a side panel that was hidden when the opposite panels width was set to the maximum. In both those cases the size of the window would previously have been forced to increase, potentially pushing its borders off the screen.

If there is _no_ width set yet, this defaults to the _natural_ width of the panels contents, meaning no widgets would get ellipsized, even when changing font size for example, unless the window itself isn't large enough. This _does_ mean that if the contents of the panel changes (for example by switching module groups) it could resize itself. This behavior can be switched off by dragging the panel handle to "set" (advice, really) a specific size (which is still limited by the _minimum_ width of the panel contents).

If a specific size has been set but the user wants the automatic/default scaling back, they can simply drag the handle all the way "down" (make width "0") at which point it snaps back to natural size.

@TurboGit I haven't encountered any problems with this, but can't test the tethering view.

### CODE REVIEW

File: src/gui/gtk.c [hunk 1]
```diff
@@ -1670,40 +1669,18 @@ void dt_ui_notify_user()
...
-    s = DT_UI_PANEL_BOTTOM_DEFAULT_SIZE; // default panel size
-    if(key && dt_conf_key_exists(key))
-      s = CLAMP(dt_conf_get_int(key), dt_conf_get_int("min_panel_height"), dt_conf_get_int("max_panel_height"));
-    if(key) gtk_widget_set_size_request(widget, -1, s);
-  }
+  gchar *key = _panels_get_panel_path(DT_UI_PANEL_BOTTOM, "_size");
+  int s = DT_UI_PANEL_BOTTOM_DEFAULT_SIZE; // default panel size
+  if(key && dt_conf_key_exists(key))
+    s = CLAMP(dt_conf_get_int(key), dt_conf_get_int("min_panel_height"), dt_conf_get_int("max_panel_height"));
+  if(key) gtk_widget_set_size_request(widget, -1, s);
```
Comment (TurboGit) [inline src/gui/gtk.c:1676]: I had removed the if(key) as I don't see why it is needed at all. `s` is always initialized anyway.

File: src/gui/gtk.c [hunk 2]
```diff
@@ -1670,40 +1669,18 @@ void dt_ui_notify_user()
 
 static void _ui_init_panel_size(GtkWidget *widget)
```
Comment (TurboGit) [inline src/gui/gtk.c:1670]: this name is now misleading : `_ui_init_bottom_panel_size` ?

File: src/dtgtk/sidepanel.c [hunk 3]
```diff
@@ -30,9 +31,12 @@ static GtkSizeRequestMode dtgtk_side_panel_get_request_mode(GtkWidget *widget)
 
 static void dtgtk_side_panel_get_preferred_width(GtkWidget *widget, gint *minimum_size, gint *natural_size)
 {
-  GTK_WIDGET_CLASS(dtgtk_side_panel_parent_class)->get_preferred_width(widget, minimum_size, NULL);
+  GTK_WIDGET_CLASS(dtgtk_side_panel_parent_class)->get_preferred_width(widget, minimum_size, natural_size);
 
-  *natural_size = *minimum_size;
+  int width = dt_ui_panel_get_size(darktable.gui->ui, strcmp(gtk_widget_get_name(widget), "right") ? DT_UI_PANEL_LEFT : DT_UI_PANEL_RIGHT);
```
Comment (TurboGit) [inline src/dtgtk/sidepanel.c:36]: const

**Review by TurboGit — CHANGES_REQUESTED** [review]
Works for me, some changes proposed. TIA.

**Comment by dterrahe** [comment]
Thanks for the review; changes incorporated.

**Review by TurboGit — APPROVED** [review]
Thanks!
