### PR TITLE
Bugfix both overexposed indicators

### LINKED ISSUE #12359: After cropping, clipping indicators don't appear
**Describe the bug/issue**

After some image operations (crop is the one ive most noticed), the clipping indicators don't function.

**To Reproduce**

1. over or under expose an image
2. turn on clipping indicators
3. crop the image
4. clipping indicators are not redawn
5. clipping indicators need to be cycled, or another operation like exposure needs to be be performed before they are re-shown

**Platform**

* darktable version : official release 4.0.0
* OS                : Windows 10 x64
* Memory            :  40GB
* Graphics card     :  GTX1060

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
As reported in #12359 the overexposed visual is not always shown if activated.

This is due to improper testing for a full pixelpipe in both modules.

Fixes #12359

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
I think this could be also for 4.0.1

File: src/iop/overexposed.c [hunk 1]
```diff
@@ -460,8 +460,8 @@ void cleanup_global(dt_iop_module_so_t *module)
 void commit_params(struct dt_iop_module_t *self, dt_iop_params_t *p1, dt_dev_pixelpipe_t *pipe,
                    dt_dev_pixelpipe_iop_t *piece)
 {
-  if(pipe->type != DT_DEV_PIXELPIPE_FULL || !self->dev->overexposed.enabled || !self->dev->gui_attached)
-    piece->enabled = 0;
+  const gboolean fullpipe = (piece->pipe->type & DT_DEV_PIXELPIPE_FULL) == DT_DEV_PIXELPIPE_FULL;
```
Comment (dterrahe) [inline src/iop/overexposed.c:463]: Since all PIXELPIPE enums are single bits (except _ANY) this could just be
`const gboolean fullpipe = piece->pipe->type & DT_DEV_PIXELPIPE_FULL;` which is easier to read and less likely to be incorrectly partially adjusted.
I know this is spread everywhere and would not be a good search-and-replace for 4.0.1. but no need to keep spreading?

Comment (jenshannoschwalm) [reply src/iop/overexposed.c:463]: This is not correct. It used to be but we have `DT_DEV_PIXELPIPE_FAST` adding another mask bit.

It's the exact reason why the old code was broken.

Yes - it's spread all over the place and we would either like a macro or a refactored testing function

Comment (jenshannoschwalm) [reply src/iop/overexposed.c:463]: No - you are right :-)

Comment (jenshannoschwalm) [reply src/iop/overexposed.c]: done

**Review by TurboGit — APPROVED** [review]
